auth-web/src/App.vue
auth-web/src/assets/styl/layout.styl
auth-web/src/views/BusinessProfile.vue
auth-web/src/views/Home.vue

*Issue #:* No corresponding ticket. 
The following changes were made in order to ensure that shared style rules are not repeated in multiple places in the app:
- Moved style rules that were being repeated in BusinessProfile.vue and Home.vue to layout.styl
- Moved style rules that were only being used in App.vue out of layout.styl and directly into App.vue
- Removed a couple of style rules from layout.styl that were not being used anywhere in the app
- #### Common
- #### REST 
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license …

Clean up repeated and unused styling

---

auth-api/config.py
auth-api/src/auth_api/resources/invitation.py
auth-api/src/auth_api/resources/org.py
auth-api/src/auth_api/services/invitation.py

*Issue#* 1586
https://github.com/bcgov/entity/issues/1586
Change invitation endpoints to use request origin for email link.  Renamed config item.
*Checklist:*

AUTH-API: Change invitation endpoints to use request origin

---

auth-web/.env
auth-web/.env.production
auth-web/src/components/auth/AddBusinessForm.vue
auth-web/src/components/auth/AffiliatedEntityList.vue
auth-web/src/components/auth/BusinessContactForm.vue
auth-web/src/components/auth/PasscodeForm.vue
auth-web/src/components/auth/SearchBusinessForm.vue
auth-web/src/services/iframe.services.ts
auth-web/src/services/payment.services.ts
auth-web/src/util/config-helper.ts
auth-web/src/views/TokenValidator.vue

1. introduced two methods in confighelper class to read browser origin
2. removed the timeouts and some redundant if's
Havent fixed Tests yet
*Issue #:*
1. introduced two methods in confighelper class to read browser origin
2. removed the timeouts and some redundant if's
*Checklist:*

read urls from the browser instead of config maps

---

auth-web/package.json
auth-web/src/store/index.ts
auth-web/tests/unit/UserProfileForm.spec.ts
auth-web/tests/unit/affiliatedEntityList.spec.ts
auth-web/tests/unit/businessContactForm.spec.ts
auth-web/tests/unit/searchBusinessForm.spec.ts
auth-web/tests/unit/signIn.spec.ts
auth-web/tests/unit/signOut.spec.ts
auth-web/vue.config.js

*Issue #:* 1588
https://github.com/bcgov/entity/issues/1588
Remove module 'vuex-persist', which not adding any value and was breaking in IE11.
Related module error here: https://github.com/championswimmer/vuex-persist/pull/137
*Checklist:*

Fix blank page in IE11

---

auth-api/src/auth_api/schemas/entity.py
auth-api/src/auth_api/services/affiliation.py

*Issue #:* 1595
https://github.com/bcgov/entity/issues/1595
Fix a logic error when creating an affiliation that allows the same user to affiliate with the same business multiple times.  Also switch to use proper CamelCaseSchema.
*Checklist:*

AUTH-API: Fix logic error on create business affiliation

---

auth-web/src/App.vue
auth-web/src/assets/scss/base.scss
auth-web/src/assets/scss/overrides.scss
auth-web/src/plugins/vuetify.ts
auth-web/vue.config.js

*Issue #:* 1646
https://github.com/bcgov/entity/issues/1646
This change will force Vue/Webpack to load the SCSS stylesheets in a specific order regardless of whether it's running in dev or prod mode.
*Checklist:*

Force ordered load of bundled styles

---

auth-api/src/auth_api/schemas/user.py
auth-api/src/auth_api/services/user.py
auth-api/tests/unit/services/test_user.py

removed org from the user schema
*Issue #:*
https://github.com/bcgov/entity/issues/1932
*Checklist:*

removed org from the user schema 

---

auth-api/src/auth_api/resources/org.py
auth-web/src/components/auth/AffiliatedEntityList.vue
auth-web/src/components/auth/InvitationsDataTable.vue
auth-web/src/components/auth/MemberDataTable.vue
auth-web/src/components/auth/PendingMemberDataTable.vue
auth-web/src/components/auth/Signin.vue
auth-web/src/models/Organization.ts
auth-web/src/store/modules/business.ts
auth-web/src/store/modules/org.ts
auth-web/src/views/management/UserManagement.vue

*Issue #:* 1931
https://github.com/bcgov/entity/issues/1931
Only show 'Invite Users' button on Manage Teams view if current user has the ADMIN or OWNER role.  This change also included adding a store getter for the current users's membership and proper enum use for types/statuses on the front-end.
*Checklist:*

Hide invite button for users with MEMBER role

---

auth-web/src/components/auth/InviteUsersForm.vue
auth-web/src/store/modules/org.ts
auth-web/src/views/management/Dashboard.vue

*Issue #:* 1970
https://github.com/bcgov/entity/issues/1970
Added a redirect away from the Dashboard/Manage Businesses view if the current user is not an active member of a team.  If they are pending, they are redirected to the page informing them that their membership is pending approval.  Otherwise, they are directed towards the create team view.
*Checklist:*

Redirect unapproved or non-members away from Dashboard

---

auth-web/src/components/auth/MemberDataTable.vue
auth-web/src/router.ts
auth-web/src/util/constants.ts
auth-web/src/views/AcceptInvite.vue
auth-web/src/views/DuplicateTeamWarning.vue

*Issue #:* 2026
https://github.com/bcgov/entity/issues/2026
Intercept acceptance of an invitation by users who already a team member and route to a new view informing them that they can't accept the invite.
In addition, allow an Owner to dissolve their team if they are the only member and they have no affiliated businesses. 
*Checklist:*

#2026 - Prevent team members from accepting invites to other teams

---

auth-web/src/components/auth/InviteUsersForm.vue
auth-web/src/components/auth/NextPageMixin.vue
auth-web/src/components/auth/Signin.vue
auth-web/src/components/auth/UserProfileForm.vue
auth-web/src/views/AcceptInvite.vue

*Issue #:* 2016
https://github.com/bcgov/entity/issues/2016
Fix a bug where multiple invites could be generated for the same email address.  This was fixed through the following changes on the front-end:
a) Validation was added to the invite users form to prevent duplicate emails being specified simultaneously
b) The invite users form is reset whenever it is closed
c) Prior to creating an invitation, pending invitations are checked for the same email.  If found, the existing is just resent instead of creating a new one.
*Checklist:*
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of …

#2016 - Prevent duplicate invites from being generated

---

auth-api/src/auth_api/models/invite_status.py
auth-api/src/auth_api/models/membership.py
auth-api/src/auth_api/schemas/user.py
auth-api/src/auth_api/services/codes.py
auth-api/src/auth_api/services/membership.py
auth-api/src/auth_api/services/user.py
auth-api/tests/unit/api/test_user.py
auth-api/tests/unit/models/test_invitation.py
auth-api/tests/unit/services/test_user.py
auth-web/.eslintrc.js
auth-web/.prettierrc.json
auth-web/src/components/auth/TermsOfUseDialog.vue
auth-web/src/components/auth/UserProfileForm.vue
auth-web/src/models/user.ts
auth-web/src/services/user.services.ts
auth-web/src/store/modules/user.ts

*Issue #:* 2086
https://github.com/bcgov/entity/issues/2086
* Fix bug where closing Terms of Service dialog inadvertently accepted the terms
* Refactor/simplify the User Profile state with Terms of Service and usage of the store
* Camelcase conversion on API and improvements to schema export
* Change user deactivation to unaccept terms of service
* Add in a basic prettier config for formatting in vscode
*Checklist:*

Fixes to terms of service acceptance flow

---

auth-web/src/App.vue
auth-web/src/components/auth/Signin.vue
auth-web/src/main.ts
auth-web/src/services/keycloak.services.ts
auth-web/src/util/constants.ts
auth-web/src/util/interceptors.ts

Token service timer is initiated on app load and sign in
*Issue #:*
https://app.zenhub.com/workspaces/entity-5bf2f2164b5806bc2bf60531/issues/bcgov/entity/1773
The token service is invoked on app load and sign in as well.  Interceptor code also checked in ;but not used right now because of  https://github.com/bcgov/entity/issues/2076
Need more testing in DEV .
*Checklist:*

Keycloak refresh done using tokenservices

---

auth-web/src/views/management/UserManagement.vue

*Issue #:*
@mengdong19 reported an issue with confirmation to send mail is being asked in the approve button.
the modal is replaced with old code
*Checklist:*

notify option showing wrongly in the confirm dialog

---

auth-web/src/components/auth/InterimLanding.vue
auth-web/src/locales/en.json
auth-web/src/router.ts
auth-web/src/views/AcceptInvite.vue
auth-web/src/views/AcceptInviteLanding.vue
auth-web/src/views/LeaveTeamLanding.vue
auth-web/src/views/PendingApproval.vue
auth-web/src/views/ProfileDeactivated.vue
auth-web/src/views/management/UserManagement.vue

*Issue #:*
https://github.com/bcgov/entity/issues/2103
- Created new UI for leaveteam success 
- Created a new component which can be used for these kind of UIs
- Changed all the existing duplicate code to use the new component
*Checklist:*

2103 : Redirecting the user to leaveteam success page

---

auth-web/src/components/auth/InviteUsersForm.vue

*Issue #:*
https://github.com/bcgov/entity/issues/entity2030
Fixed an issue with the role menu display in the Invite Users interface (IE11)
*Checklist:*

[entity2030] Fix Role Menu Display in Invite Users Interface (IE11 issue)

---

auth-api/src/auth_api/services/invitation.py

Multiple email has to be separated by comma instead of spaces
*Issue #:*
https://github.com/bcgov/entity/issues/2260
*Checklist:*

Multiple email has to be separated by comma instead of spaces

---

notify-api/jenkins/dev.groovy
notify-api/src/notify_api/db/crud/notification.py
notify-api/tests/unit/crud/test_notification.py
notify-api/tests/unit/service/test_notify.py
notify-api/tests/utilities/factory_scenarios.py

*Issue #:*
https://github.com/bcgov/entity/issues/2253
- Fixed the time range issue when retrieve the failure status email.
- Disable the pytest stage temporary until the permission issue get fix.
*Checklist:*

Fixed the resending failure email during service restart or deployment and disable pytest in pipeline

---

auth-api/src/auth_api/models/views/authorization.py
auth-api/tests/unit/models/views/test_authorization.py

*Issue #:*
https://github.com/bcgov/entity/issues/2024
This change I missed to commit for service account story. Service accounts should be able to access the organisation without any affiliation.Some of the postman scripts need this.
*Checklist:*

serviceaccount accessing orgs without affiliation

---

auth-api/src/auth_api/__init__.py
auth-api/src/auth_api/models/base_model.py
auth-api/src/auth_api/models/contact.py
auth-api/src/auth_api/resources/__init__.py
auth-api/src/auth_api/resources/reset.py
auth-api/src/auth_api/services/__init__.py
auth-api/src/auth_api/services/reset.py
auth-api/src/auth_api/utils/roles.py
auth-api/tests/postman/auth-api.postman_collection.json
auth-api/tests/postman/auth-api.postman_environment.json
auth-api/tests/unit/api/test_reset.py
auth-api/tests/unit/services/test_reset.py
auth-api/tests/utilities/factory_scenarios.py
auth-api/tests/utilities/factory_utils.py

*Issue #:*
https://github.com/bcgov/entity/issues/2246
1. add a service to reset all the table records created by the token user;
2. add a endpoint that only allow  'potman' role access it;
3. add new restplus blueprint group 'postman' and not allow production environment to run the endpoint;
*Checklist:*

add a reset data endpoint and serivce.

---

auth-api/src/auth_api/__init__.py
auth-api/src/auth_api/models/contact.py
auth-api/src/auth_api/models/views/authorization.py
auth-api/src/auth_api/resources/org.py
auth-api/src/auth_api/services/invitation.py
auth-api/src/auth_api/services/membership.py
auth-api/tests/unit/models/views/test_authorization.py
auth-api/tests/unit/services/test_org.py
auth-web/package.json

*Issue #:* 2186
https://github.com/bcgov/entity/issues/2186
Change to exclude notifications on member role change when going to MEMBER from another role.
*Checklist:*

#2186 Restrict notifications to non-member role change

---

auth-api/src/auth_api/exceptions/__init__.py
auth-api/src/auth_api/models/__init__.py
auth-api/src/auth_api/resources/__init__.py
auth-api/src/auth_api/services/contact.py
auth-api/src/auth_api/services/documents.py

*Issue #:*
Adding flake8 overrides to satisfy flake8 on both mac and linux/unix.  There were some differences related to the use of common component modules that were preventing the GH action checks from working properly for mac users.
*Checklist:*

Adding overrides for flake8 errors

---

auth-web/src/components/auth/CreateAccountInfoForm.vue
auth-web/src/components/auth/NextPageMixin.vue
auth-web/src/router.ts
auth-web/src/store/modules/org.ts
auth-web/src/util/constants.ts
auth-web/src/views/auth/CreateAccountView.vue
auth-web/src/views/auth/DashboardView.vue
auth-web/src/views/auth/DuplicateTeamWarningView.vue
auth-web/tests/unit/components/CreateAccountInfoForm.spec.ts

*Issue #:*
https://github.com/bcgov/entity/issues/entity2402
Updating the language from 'Team' to 'Account' for both the 'Create Account' and 'Account Information' interfaces
- Renamed 'TeamForm.vue' to 'CreateAccountInfoForm.vue'
- Renamed 'CreateTeamView.vue' to 'CreateAccountView.vue'
- Updated constants.ts with new naming convention (CREATE_ACCOUNT, createaccount)
- Fixed router push in DashboardView.vue to the new URL path ('/createaccount')
- Updated DuplicateTeamWarningView.vue with new component name (TeamForm --> CreateAccountInfoForm). No additional work required here considering this page will be redundant once multiple accounts come into play.
- Renamed 'TeamForm.spec.ts' to 'CreateAccountInfoForm.spec.ts' and updated naming conventions within this file
*Checklist:*
I confirm …

[entity2402] Update Language from 'Team' to 'Account'

---

auth-api/src/auth_api/resources/user.py
auth-api/src/auth_api/services/reset.py
auth-api/tests/unit/api/test_user.py
auth-api/tests/unit/services/test_reset.py

*Issue #:*
https://github.com/bcgov/entity/issues/2455
Add reset test data to deactivate user endpoint for tester role.
*Checklist:*

Add reset test data to deactivate user endpoint for tester role.

---

auth-web/src/router.ts

*Issue #:*
https://github.com/bcgov/entity/issues/2209
- Changes to redirect to staff login if the page is secured for only staff roles
- Since client can have multiple login mechanisms, not changing it for client login now
*Checklist:*

2209: Adding redirect url to the signin url from router to fix staff bookmark

---

auth-web/src/router.ts

*Issue #:* 2655
https://github.com/bcgov/entity/issues/2655
This PR adds a fallback URL for Manage Businesses for when the account id cannot be expressed in the route parameter.
*Checklist:*

Add fallback URL for manage businesses

---

auth-api/src/auth_api/models/__init__.py
auth-api/src/auth_api/services/contact.py
auth-api/src/auth_api/services/invitation.py
auth-api/src/auth_api/services/org.py
auth-web/package-lock.json
auth-web/package.json
auth-web/public/config/configuration.json
auth-web/src/App.vue
auth-web/src/components/auth/AccountInfo.vue
auth-web/src/components/auth/CreateAccountInfoForm.vue
auth-web/src/components/auth/NextPageMixin.vue
auth-web/src/components/auth/UserProfileForm.vue
auth-web/src/router.ts
auth-web/src/store/modules/org.ts
auth-web/src/views/auth/AcceptInviteView.vue
auth-web/src/views/auth/UserProfileView.vue

*Issue #:*
- https://github.com/bcgov/entity/issues/2580
- handled the case of an account switch between an active account and a pending account :  When switching to a pending account , now user is always taken to pending_approval page
When switching to an active account from pending_Approval page , user is being taken to home page
*Checklist:*

Handled the case of pending approval and active account switching

---

auth-api/src/auth_api/models/affiliation.py
auth-api/src/auth_api/models/entity.py
auth-api/src/auth_api/resources/org.py
auth-api/src/auth_api/services/keycloak.py
auth-api/src/auth_api/services/org.py
auth-api/tests/unit/api/test_org.py

*Issue #:*
https://github.com/bcgov/entity/issues/2522
- Adding a new GET /orgs endpoint which can be a generic search orgs endpoint for future requirements. Currently supports only searching by affiliation
*Checklist:*

Adding search orgs endpoint

---

auth-api/config.py
auth-api/tests/utilities/factory_scenarios.py

*Issue #:*
- Fix pytest to run with Keycloak Test values
*Checklist:*

Fix pytest to run with Keycloak Test values

---

auth-api/src/auth_api/models/entity.py

*Issue #:*
https://github.com/bcgov/entity/issues/2828
The reset endpoint can not find the proper relationship between affiliation and entity table. Add the relationship into entity model class. 
*Checklist:*

Fixed reset endpoint 500 error issue.

---

auth-api/src/auth_api/models/membership.py
auth-api/src/auth_api/resources/__init__.py
auth-api/src/auth_api/resources/notifications.py
auth-api/src/auth_api/services/membership.py

*Issue #:*
https://github.com/bcgov/entity/issues/2841
Came up with an API to return the count.
This is just a first pass. Lot of TODO ; But before that I just want to make sure the approach is fast
*Checklist:*

API for notifications count - first pass

---

auth-api/config.py
auth-api/tests/conftest.py
auth-api/tests/docker/docker-compose.yml
auth-api/tests/docker/nginx.conf
docs/docs/api_contract/auth-api-1.0.0.yaml

*Issue #:*
https://github.com/bcgov/entity/issues/2951
- 2951: pytest changes to use prism mock
*Checklist:*

2951: pytest changes to use prism mock

---

auth-api/src/auth_api/services/org.py
auth-api/tests/unit/api/test_org.py

setting anonymous if not passed from UI

---

auth-api/src/auth_api/resources/bulk_user.py
auth-api/src/auth_api/resources/invitation.py
auth-api/src/auth_api/resources/org.py
auth-api/tests/unit/api/test_account.py
auth-api/tests/unit/api/test_bulk_user.py
auth-api/tests/unit/api/test_entity.py
auth-api/tests/unit/api/test_invitation.py
auth-api/tests/unit/api/test_org.py
auth-api/tests/unit/api/test_reset.py
auth-api/tests/unit/api/test_user.py
auth-api/tests/unit/services/test_entity.py
auth-api/tests/unit/services/test_invitation.py
auth-api/tests/unit/services/test_keycloak.py
auth-api/tests/unit/services/test_membership.py
auth-api/tests/unit/services/test_org.py
auth-api/tests/unit/services/test_reset.py
auth-api/tests/unit/services/test_user.py
auth-api/tests/unit/services/test_user_settings.py
auth-api/tests/utilities/factory_scenarios.py

*Issue #:*
https://github.com/bcgov/entity/issues/3050
Secured many of the endpoints using public role so that anonymous cant use them.
Keycloak tests using random user name and email.
*Checklist:*

Added role check for APIs and fixed all Tests

---

scripts/keycloak_user_cleanup/README.md
scripts/keycloak_user_cleanup/remove_users.py

*Issue #:*
https://github.com/bcgov/entity/issues/3098
- Script to delete users from the IDP and delete corresponding users from keycloak realm (sso)
*Checklist:*

Script for deleting users from upstream and keycloak realm

---

auth-api/src/auth_api/models/views/authorization.py
auth-api/src/auth_api/services/authorization.py
auth-api/tests/unit/api/test_entity.py
auth-api/tests/unit/models/views/test_authorization.py
auth-api/tests/utilities/factory_scenarios.py
docs/docs/api_contract/auth-api-1.0.0.yaml

*Issue #:*
https://github.com/bcgov/entity/issues/3088
-Adding staff user auth to return expanded details
*Checklist:*

Adding staff user auth to return expanded details

---

auth-web/src/components/auth/AccountInfo.vue
auth-web/src/router.ts

*Issue #:*
https://github.com/bcgov/entity/issues/2543
https://github.com/bcgov/entity/issues/3605
- Another fix for user profile being accessible before TOS
Added a reset button [was in UXPIN , i missed it]
added org sync to the mounted
*Checklist:*

Fix for missing reset button and blank org name

---

auth-web/src/components/auth/AddUsersForm.vue
auth-web/src/components/auth/BaseAddress.vue
auth-web/src/components/auth/PasswordReset.vue
auth-web/src/components/auth/TermsOfUse.vue

1) TOS console had an error when last accepted terms is null
2) baseaddress was not emitting event on keyenter..so save button is disabled till user clicks somewhere else in the form
3) Director search labels were wrong
4) password reset wrong style
*Issue #:*
*Checklist:*

misc bug fixes

---

auth-web/src/components/auth/OutOfProvinceDialog.vue
auth-web/src/router.ts
auth-web/src/views/auth/HomeView.vue
auth-web/src/views/auth/OutOfProvinceAccount.vue

*Issue #:* 3875
https://github.com/bcgov/entity/issues/3875
Add intercept to `Create Account` button on home page view.  Shows dialog that prompts for selection of out of province flow.
Includes route and stub view for Out of Province instructions view.
*Checklist:*

3875 out of province dialog

---

auth-api/config.py
auth-api/src/auth_api/models/org.py
auth-api/src/auth_api/services/affiliation.py
auth-api/src/auth_api/services/notification.py
auth-api/src/auth_api/services/org.py
auth-api/tests/unit/api/test_org.py
auth-api/tests/unit/services/test_affidavit.py
auth-api/tests/unit/services/test_affiliation.py
auth-api/tests/unit/services/test_org.py
auth-api/tests/utilities/factory_scenarios.py
auth-api/tests/utilities/factory_utils.py
keycloak/namex_config.json

*Issue #:*
https://github.com/bcgov/entity/issues/4176
- 4176: Changes to add org contact on search endpoint
- Changes to filter out the temporary affiliation if the entity is already incorporated
*Checklist:*

4176: Changes to add org contact on search endpoint

---

auth-api/src/auth_api/models/org.py
auth-api/src/auth_api/resources/org.py
auth-api/src/auth_api/services/org.py
auth-api/tests/unit/api/test_org.py

* Added bcolAccountId filter to the org search
https://github.com/bcgov/entity/issues/4187
*Checklist:*

Added bcolAccountId filter to the org search (#837)

---

auth-api/src/auth_api/services/affiliation.py

*Issue #:* https://github.com/bcgov/entity/issues/4160
The previous commit set the corp type to the actual type of the NR (eg CR), but the API code doesn't support it. It needs to be of type "NR". This caused a 500 error as the NR's actual type could not be inserted (as it is not a valid type in the code table).
*Checklist:*

set the corp type as NR

---

auth-api/src/auth_api/resources/bcol_profiles.py
auth-api/src/auth_api/services/user.py
auth-web/src/components/auth/MemberDataTable.vue
auth-web/src/components/auth/TeamManagement.vue
auth-web/src/routes/router.ts

*Issue #:*
https://github.com/bcgov/entity/issues/4454
- password reset was not working since wrong view was rendering.This happened because of a faulty check by which accounts are treated like normal accounts for staff.Fixed that check
- member adding by staff was failing bcoz of the permission issues.
*Checklist:*

Fixed Routes for old invitations ; fixed reset password and adding members in anonymous account by staff

---

auth-api/src/auth_api/resources/reset.py
auth-api/src/auth_api/services/keycloak.py
auth-api/src/auth_api/services/reset.py
auth-api/src/auth_api/utils/enums.py
auth-api/tests/docker/setup/demo-realm.json
auth-api/tests/unit/api/test_reset.py
auth-api/tests/unit/services/test_keycloak.py
auth-api/tests/unit/services/test_reset.py
auth-api/tests/utilities/factory_scenarios.py

*Issue #:*
The BCeID user has otp setting in the keycloak. Currently, there is no way to reset the otp setting through keycloak api. During teardown stage of integration testing, it will call reset api to delete the test user. And, it will add the tester role into test user during setup stage. 
*Checklist:*

Add delete user, assign role function in Keycloak service and add tester role endpoint in Reset api.

---

auth-api/src/auth_api/resources/reset.py
auth-api/src/auth_api/services/keycloak.py
auth-api/src/auth_api/services/reset.py
auth-api/tests/unit/api/test_reset.py
auth-api/tests/unit/services/test_keycloak.py
auth-api/tests/unit/services/test_reset.py

*Issue #:*
Found a issuer that delete user api will reset the roles of service account. 
*Checklist:*

Rollback the keycloak service delete user and assign role function.

---

auth-web/src/routes/index.ts
auth-web/src/routes/router.ts
auth-web/src/services/payment.services.ts
auth-web/src/views/pay/PaymentReturnView.vue
auth-web/tests/unit/views/PaymentReturnView.spec.ts

*Issue #:*
https://github.com/bcgov/entity/issues/4243
- Changing the web to send whole response string url from paybc to transactions patch call
*Checklist:*

Changes to support transaction update for direct pay

---

auth-web/src/components/auth/mixins/NextPageMixin.vue

*Issue #:*
https://github.com/bcgov/entity/issues/4535
- BC/Non-BC resident screen appears twice#4535
*Checklist:*

BC/Non-BC resident screen appears twice#4535

---

auth-web/src/util/constants.ts

*Issue #:* 4660
https://github.com/bcgov/entity/issues/4660
The bug in Issue 4660 is being caused by a mismatched session storage key (BUSINESS_ID in Entities, BUSINESS_IDENTIFIER in Relationships).  This PR renames the session storage key constant to BUSINESS_ID to be consistent with the convention used in Entities.  
This change should also correct a similar issue described in #4328, but will confirm once deployed to development.
*Checklist:*

4660 - align session storage constant w/ entities

---

auth-api/requirements.txt
auth-api/src/auth_api/models/org.py
auth-api/src/auth_api/resources/org.py
auth-api/src/auth_api/services/org.py

*Issue #:*
https://github.com/bcgov/entity/issues/4786
the requirement says VIEWER staff should not be able to see director search related accounts ;It should only be visible to ADMINS. The api has been changed to take care of this behaviour. 
- filtered director search if request comes from non-admin
- blocked accessing pending invitations if its non-admin
*Checklist:*

director search account should only be accessible to Admins

---

auth-api/src/auth_api/services/keycloak.py

*Issue #:*
https://github.com/bcgov/entity/issues/4313
*Checklist:*

removing the disable otp api call for lower kc version

---

auth-web/src/routes/router.ts
auth-web/src/util/constants.ts

*Issue #:*
https://github.com/bcgov/entity/issues/4626
/staff should automatically redirect to /staff/dashboard
*Checklist:*

adding the missed redirection for 'staff' route

---

auth-web/src/components/auth/UserProfileForm.vue

*Issue #:* 4238
https://github.com/bcgov/entity/issues/4238
This PR fixes an issue where the Cancel button on the Edit Profile form was not functioning.  Prior to the fix the cancel button would resolve to using `window.history.back()` to return to the previous page.  In a SPA, this won't always work if you are coming from a different application (in this case IA dashboard) or if there is a redirect on load of the view.  For now, I've changed it to behave the same as if the View level back arrow was pressed (returns to the Manage Business dashboard if an account is selected, or Home otherwise).  If the desired behaviour is to return to the IA dashboard then this will require additional changes on that application as well (a query parameter would need to be passed …

4238 fix cancel button

---

auth-api/migrations/versions/959d8ff75e82_payment_change.py

*Issue #:*
https://github.com/bcgov/entity/issues/5098
some of the org doesn't have payment accounts in  auth which fails migration.This fixes the migration.
*Checklist:*

fix for non existing account types

---

auth-web/src/components/auth/PAD/PADAgreementDialog.vue
auth-web/src/components/auth/PAD/PADTermsOfUse.vue

*Issue #:* 4772
https://github.com/bcgov/entity/issues/4772
Adds views for the PAD agreement TOS dialog.  Before this feature can be used, the Payment Selection feature must be completed.
NOTE: This also does not include the data model or API changes needed on the account model to determine if the TOS has already been accepted.  Placeholders have been put in where appropriate.
*Checklist:*

4772 add view for PAD tos + dialog

---

auth-web/src/components/auth/create-account/AccountTypeSelector.vue
auth-web/src/components/auth/create-account/UserProfileForm.vue

- Userprofile not retaining values when coming back to the step
- payment not listed when default account type is selected
*Issue #:*
*Checklist:*

Account creation bug fixes

---

auth-web/src/components/auth/create-account/AccountTypeSelector.vue
auth-web/src/components/auth/create-account/UserProfileForm.vue

- Userprofile not retaining values when coming back to the step
- payment not listed when default account type is selected
*Issue #:*
*Checklist:*

QA Deployment

---

auth-web/src/components/auth/common/PaymentMethods.vue
auth-web/src/components/auth/create-account/AccountTypeSelector.vue
auth-web/src/components/auth/create-account/PaymentMethodSelector.vue
auth-web/src/components/auth/create-account/PremiumChooser.vue
auth-web/src/store/modules/org.ts
auth-web/tests/unit/components/DateRangeFilter.spec.ts
auth-web/tests/unit/components/PaymentMethods.spec.ts

- Fix for retaining acc name if user switch between linked and unlinked premiums
- Fix for selection of premium account type card if user coming back from unliked premium account flow
*Issue #:*
*Checklist:*

Fix for retaining acc name if user switch between linked and unlinked premiums

---

queue_services/account-mailer/src/account_mailer/pdf_templates/pad_confirmation.html

show bank institution number instead of bank name in pad confirmation pdf

---

auth-web/src/components/auth/common/PADInfoForm.vue
queue_services/account-mailer/src/account_mailer/email_templates/refund_request_email.html

*Issue #:*
https://github.com/bcgov/entity/issues/5719
- Incorrect wording for PAD - Linked Premium account#5719
- minor spacing fix in the refund email template
*Checklist:*

Incorrect wording for PAD - Linked Premium account#5719

---

auth-api/src/auth_api/models/org.py
auth-api/src/auth_api/services/org.py
auth-api/tests/unit/models/test_org.py
auth-api/tests/unit/services/test_org.py

*Issue #:*
https://github.com/bcgov/entity/issues/5436
https://github.com/bcgov/entity/issues/5685
- change duplicate name validation rule from similar to equal 
- duplicated names are not allowed for premium account without BCOL. 
*Checklist:*

#5436 #5685 validate duplicate account names

---

auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
auth-web/src/components/auth/account-settings/account-info/OrgAdminContact.vue

*Issue #:*
- Fix for ui breaking due to navigation from account info page
*Checklist:*

Fix for ui breaking due to navigation from account info page

---

auth-api/migrations/versions/e38ad1ce6d21_added_bank_permissions.py

*Issue #:*
https://github.com/bcgov/entity/issues/5514
Added the missing permission.
NSF account can view the bank information.

Fixed the bank info not showing for NSF accounts

---

auth-web/src/views/pay/PaymentView.vue

payment to continue instead of failing incase if invoice is not fetchable. To handle NRO users who are logged in auth and not logged in NRO

payment to continue instead of failing

---

auth-api/migrations/versions/b72d4946fb3c_added_view_edit_for_nsf_account.py

*Issue #:*
view and edit was missing for admins for NSF account

added edit and view for nsf account for admins

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/components/auth/account-freeze/ReviewBankInformation.vue
auth-web/src/views/pay/PaymentView.vue
auth-web/tests/unit/components/AccountPaymentMethods.spec.ts

Fixing Bank validation shouldn't show error message if service is unable to validate cfs.
- Axios version updated .Looks ok so far
- bank validation skip corrected.
- some lints fixed

Bank validation fix in the UI

---

auth-web/src/components/auth/create-account/AccountTypeSelector.vue

*Issue #:*
https://github.com/bcgov/entity/issues/entity5722
Removing the reference to the 'Developer API' for premium account types.

[entity5722] Remove Reference to Developer API

---

auth-web/src/App.vue

*Issue #:*
https://github.com/bcgov/entity/issues/6180
It was a bit tricky to track this bug down. In case of pending account status , the call to the org is failing.I think that behaviour didn't change.But the code block is moved to an try catch and catch had a redirection.Because of that , the redirection kicks in and redirects the pending user from pending page to home page. 
I just moved the code out of the try catch ; the error happens ;logs in console;but no more redirection.

fix for invitation flow breaking

---

auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue

*Issue #:*
with the last fix , I introduced a bug. Without that flag , nobody was shown address. So fixed that.
The enable-mandatory-address is just used to show the error message , not to affect the address display

Fix for not showing address

---

auth-api/migrations/versions/dfd28e2b34a3_add_bcol_account_name_to_org.py
auth-api/src/auth_api/models/org.py
auth-api/src/auth_api/schemas/schemas/org_response.json
auth-api/src/auth_api/services/org.py
auth-api/tests/unit/api/test_org.py
auth-api/tests/unit/services/test_org.py
auth-api/tests/utilities/factory_scenarios.py

*Issue #:*
https://github.com/bcgov/entity/issues/5912
Add new column bcol_account_name to save original linked BCOL account name.
Remove checking BCOL account name and org name matching checking.
Check if name is duplicate when create and update org for all org types.
Inactive account excluded when find by bcol_account_id, so bcol account could be reuse for new org, because delete org doesn't remove bcol account info.

5912 account name should be unique - API

---

auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
auth-web/src/components/auth/common/PaymentMethods.vue
auth-web/src/components/auth/create-account/AccountCreatePremium.vue
auth-web/src/models/Organization.ts
auth-web/src/store/modules/org.ts

*Issue #:*
https://github.com/bcgov/entity/issues/5912
1) change for handling duplicate name check for bcol accounts
2) bcol banner changes everywhere to show bcol account name

duplicate name check added for bcol

---

auth-web/src/components/auth/common/AccountSuspendAlert.vue
auth-web/src/components/auth/staff/account-management/StaffSuspendedAccountsTable.vue
auth-web/src/views/auth/AccountSettings.vue

*Issue #:*
https://github.com/bcgov/entity/issues/entity4658
Cleaning up front-end. Removing redundant error chips in the suspended tab (no state differentiation between items in this list outside of the actual messaging).

[entity4658] Front-end Clean-up

---

auth-api/src/auth_api/services/invitation.py
auth-api/src/auth_api/services/membership.py
auth-web/src/components/auth/account-settings/team-management/MemberDataTable.vue

*Issue #: 4909
https://github.com/bcgov/entity/issues/4909
Enable admin and staff remove other admins by set them inactive or downgrade.
Send notification to the staff who sent invitation if no active admin in the org, so staff can approve the new member.

#4909-Provide administrators the ability to remove other admins.

---

auth-api/migrations/versions/8260fac9943d_suspended_status.py
auth-api/requirements.txt
auth-api/src/auth_api/resources/org.py
auth-api/src/auth_api/services/org.py
auth-api/src/auth_api/services/permissions.py
auth-api/src/auth_api/utils/enums.py
auth-api/src/auth_api/utils/roles.py
auth-api/tests/unit/api/test_org.py
auth-api/tests/unit/services/test_org.py
auth-api/tests/utilities/factory_scenarios.py

*Issue #:*
Added suspend/activate account patch end point. 
New role will be added in keycloak.

Added suspend/activate accounts

---

auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
auth-web/src/services/org.services.ts
auth-web/src/store/modules/org.ts
auth-web/src/views/auth/account-freeze/AccountFreezeUnlockView.vue
auth-web/src/views/auth/account-freeze/AccountFreezeView.vue
auth-web/src/views/auth/account-freeze/AccountSuspendedView.vue
auth-web/tests/unit/components/AccountInfo.spec.ts
auth-web/tests/unit/views/AccountFreezeUnlockView.spec.ts

*Issue #:*
- Added suspendaccount patch call to backend in org service file
- event handling of the suspend account dialog button in the account info page.
- fixed minor code smells

Implementing suspend account server call from org service

---

.github/workflows/account-mailer-ci.yml
.gitignore
queue_services/account-mailer/requirements.txt
queue_services/account-mailer/src/account_mailer/config.py
queue_services/account-mailer/src/account_mailer/email_processors/ejv_failures.py
queue_services/account-mailer/src/account_mailer/email_templates/ejv_failed_email.html
queue_services/account-mailer/src/account_mailer/enums.py
queue_services/account-mailer/src/account_mailer/services/minio_service.py
queue_services/account-mailer/src/account_mailer/worker.py
queue_services/account-mailer/tests/conftest.py
queue_services/account-mailer/tests/docker/docker-compose.yml
queue_services/account-mailer/tests/integration/test_worker_queue.py

*Issue #:*
https://github.com/bcgov/entity/issues/6350
- Changes for listening to JV failure message and send email to BCOL Admin

Changes for sending email for JV failures

---

auth-api/src/auth_api/resources/org.py
auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
auth-web/src/components/auth/staff/account-management/StaffAccountManagement.vue
auth-web/src/util/constants.ts
auth-web/tests/unit/components/AccountInfo.spec.ts

*Issue #:*
https://github.com/bcgov/entity/issues/6426
Allow users with view_accounts role to see suspend account tab.
Allow any users with suspend_accounts role to suspend\unsuspend accounts.
Hide suspend account button for users without suspend_accounts role.

6426 Give BC Registries and Online Services Staff the ability to support suspended accounts.

---

auth-api/src/auth_api/services/invitation.py
auth-api/tests/unit/services/test_invitation.py

*Issue #:*
https://github.com/bcgov/entity/issues/6598
This is to set the status of the invited GOVM user to ACTIVE than PENDING . 

changes for approved status for govm first user

---

auth-web/src/store/modules/org.ts

*Issue #:*
https://github.com/bcgov/entity/issues/6813
*if account status is not available take from accountsettings

Incorrect screen displayed for user/coordinator for suspended account

---

auth-api/src/auth_api/resources/org.py
auth-api/src/auth_api/services/affiliation.py
auth-api/src/auth_api/services/entity.py
auth-api/tests/unit/services/test_affiliation.py
auth-api/tests/unit/services/test_entity.py
auth-api/tests/unit/services/test_org.py

*Issue #:*
https://github.com/bcgov/entity/issues/6220
Add reset passcode function to affiliation removal. 

6220-reset passcode-backend.

---

auth-api/requirements.txt
auth-api/src/auth_api/models/user_settings.py
auth-api/src/auth_api/schemas/schemas/user_settings_response.json
auth-api/src/auth_api/schemas/user_settings.py
auth-api/src/auth_api/services/user_settings.py
auth-api/tests/unit/api/test_user_settings.py
queue_services/account-mailer/src/account_mailer/enums.py
queue_services/account-mailer/src/account_mailer/worker.py

*Issue #:*
https://github.com/bcgov/entity/issues/6723
- Adding productSettings URL as part of /users/settings endpoint
- Changes to email subject for passcode reset as per latest comments

Adding productSettings to user settings endpoint

---

auth-web/src/routes/router.ts

*Issue #:*
Login source in the confirm token was added last sprint and missed to add an optional param

made loginsource optional

---

auth-api/src/auth_api/services/org.py
auth-api/src/auth_api/services/products.py
auth-api/src/auth_api/services/task.py
auth-api/tests/unit/api/test_org_products.py
auth-api/tests/unit/api/test_task.py

*Issue #:*
1) handled transactions in tasks
2) dir search accounts doesn't need default subscriptions
3) tasks not needed for all products.only products which has default status as staff review needs it

Clean up for product subscriptions and tasks

---

auth-api/src/auth_api/services/invitation.py

*Issue #:*
https://github.com/bcgov/entity/issues/7180
Fixed roles getting displayed.

Fixed Roles not getting displayed for GOVM member invitations

---

auth-web/src/store/modules/staff.ts
auth-web/src/views/auth/staff/ReviewAccountView.vue

*Issue #:*
https://github.com/bcgov/entity/issues/7164
The url variables was read from a getter which was unnecessary.Can directly read from the object
Async I added since the editor was showing an error.

Fix for affidavit not refreshing issue

---

auth-web/src/assets/scss/base.scss
auth-web/src/components/auth/home/NameRequestButton.vue
auth-web/src/views/auth/home/RequestNameView.vue
auth-web/tests/unit/views/RequestNameView.spec.ts

*Issue #:* https://github.com/bcgov/entity/issues/7304
- open NR UI in current tab instead of in new (blank) tab (3 places)
- it is hoped this will retain all session/cookie data so that account + user are retained from sbc-auth to NR UI
- also fixed/updated unit tests

Open NR UI in same tab

---

auth-web/src/services/user.services.ts

*Issue #:*
https://github.com/bcgov/entity/issues/6895
While testing its found out that since idir has backslashes , the network call to user endpoint fails.Added a url encode for this.

added encoding since idir usernames has backslashes

---

auth-api/src/auth_api/models/task.py
auth-api/tests/unit/models/test_task.py

*Issue #:*
https://github.com/bcgov/entity/issues/7417
- Updated task model fetch_tasks logic to order pending tasks by ascending order
- Added a test case for that

7417 - pending tasks in asc order

---

auth-api/src/auth_api/services/org.py
auth-api/src/auth_api/services/task.py
auth-api/src/auth_api/utils/user_context.py

- PAD confirmation mail not working because of wrong case
Auth api was sending the user name is upper case.Which made the DB look up for user name to fail.Changed user context not to upper case the user name
- Fix for BCEID status not setting
Separated the mailing part so that mails are being sent after transaction is commited.
Moved bcied status change before org.commit so that it gets commited to DB.
*Issue #:*
https://github.com/bcgov/entity/issues/7533
https://github.com/bcgov/entity/issues/7393

PAD confirmation mail/BCEID flow fix

---

auth-web/src/store/modules/user.ts
auth-web/src/views/auth/create-account/DuplicateAccountWarningView.vue

*Issue #:*
https://github.com/bcgov/entity/issues/6921
- On page reload, load existing accounts in duplicate account screen

Feature/6921-duplicate accounts view-page reload

---

auth-api/src/auth_api/config.py
auth-api/src/auth_api/services/task.py

*Issue #:*
https://github.com/bcgov/entity/issues/7781
Need to make the url after signin route to be encoded

changes to url encode the account creation route

---

auth-api/migrations/versions/c44fff21c830_pending_approval_view_permission.py

added missing permission for pending orgs so that they can payment methods

pending orgs need to see payment methods

---

auth-api/src/auth_api/models/task.py
auth-api/src/auth_api/services/org.py
auth-api/tests/unit/models/test_task.py

*Issue #:*
- Staff accoutn mailer takes org_id rather than the related task id
- extract task id in current method and send to mailer.
- add find task by relationship id in task model

account staff review fix

---

auth-api/migrations/versions/3b485a23d057_deactivate_permissions.py
auth-api/migrations/versions/f55e4cc1aaaa_view_teammember_auth.py
auth-api/src/auth_api/models/product_code.py
auth-api/tests/unit/api/test_permissions.py

- some permissions were not loading because it was set to empty string instead of None.
- there was a console error. this was on products caching

fixed error with permissions

---

auth-web/src/views/auth/AccountDeactivate.vue

*Issue #:*
https://github.com/bcgov/entity/issues/6270
Fixed the cancel button urls to point to account info

Fix the urls in deactivate page

---

auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
auth-web/src/routes/index.ts

*Issue #:*
https://github.com/bcgov/entity/issues/8306
Earlier , every click on SAVE , address payload was going..I improved that login in previous ticket..But that didnt work.
So i capture the original first address in a variable and compare against the final address

address save not working - fixed

---

auth-web/src/assets/scss/theme.scss
auth-web/src/components/auth/manage-business/AddNameRequestForm.vue
auth-web/src/components/auth/manage-business/AffiliatedEntityList.vue
auth-web/src/components/auth/manage-business/EntityManagement.vue
auth-web/src/models/business.ts
auth-web/src/services/business.services.ts
auth-web/src/store/modules/business.ts
auth-web/src/util/config-helper.ts
auth-web/src/util/constants.ts

*Issue #:* /bcgov/entity#8572
- Open button redirects to the Name Request app and queries Name Request for Display.
- Adds a button called "Use this name request" in drop down for Incorporations and this will launch draft IA. This button is not shown for unsupported NRs and BEN change of name/alteration (ie, only show for BEN IAs). Set Using a FF.
- "Remove" button relocated into Drop down menu.
- We are using the combo button design. Open/drop down menu including remove and the 'Use this name Request' conditionally and "Remove"
- Makes request to retrieve and populate Name Request data for any affiliation of NR Type.
- Removes auto draft creation upon manually affiliating a name request and does so ONLY when selecting "Use this Name Request"
- Open action to …

8572 Old Manage business dashboard updates

---

auth-api/src/auth_api/resources/org_api_keys.py
auth-api/src/auth_api/services/api_gateway.py
auth-api/tests/unit/api/test_org_api_keys.py

*Issue #:*
https://github.com/bcgov/entity/issues/7071
Just added staff and user role to api key delete end point

changes for supporting user role for revocation of api key

---

auth-api/migrations/versions/be4475027882_rename_tables.py
auth-api/src/auth_api/services/api_gateway.py
auth-api/src/auth_api/services/keycloak.py
auth-api/src/auth_api/utils/api_gateway.py
auth-api/src/auth_api/utils/constants.py
auth-api/tests/docker/setup/demo-realm.json
auth-api/tests/unit/api/test_org_api_keys.py

*Issue #:*
https://github.com/bcgov/entity/issues/9799
- Create 2 consumers. 1 For PROD and 1 for Sandbox
- Add the sandbox consumer's keycloak client to a different group, to yield a different role for applications to distinguish

Changes for creating different keycloak clients for sandbox and prod consumers

---

auth-api/src/auth_api/exceptions/errors.py
auth-api/src/auth_api/resources/org.py
auth-api/src/auth_api/services/org.py
auth-api/src/auth_api/utils/enums.py
auth-api/tests/unit/api/test_org.py
auth-api/tests/unit/services/test_org.py

*Issue #:*
https://github.com/bcgov/entity/issues/10255
- Update Org endpoint to add patch that accept org status and access type
- Remove Org status patch
- unit test cases

10255 - Refactoring Orgs Patch to accept status and access types

---

auth-web/src/store/modules/staff.ts
auth-web/src/views/auth/staff/ReviewAccountView.vue

product approve call for gvn account

---

auth-web/src/components/auth/account-settings/account-info/AccountAccessType.vue
auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
auth-web/tests/unit/components/AccountAccessType.spec.ts

*Issue #:*
https://github.com/bcgov/entity/issues/10255
- Add conditions to display premium accounts

10255 - Bug fix for Account accessType change premium to GovN

---

auth-web/src/components/auth/common/AccountLoginOptionPicker.vue
auth-web/src/components/auth/home/BcscPanel.vue
auth-web/src/views/auth/ChooseAuthMethodView.vue

*Issue #:*
https://github.com/bcgov/entity/issues/10566
- Update references to Mobile Card to BC Services Card App & fix broken links

Bug/10566 Update references to Mobile Card to BC Services Card App & fix broken links

---

auth-api/migrations/versions/342ec8814181_update_verified_flag.py
auth-api/src/auth_api/services/task.py
auth-api/tests/unit/services/test_task.py

*Issue #:*
https://github.com/bcgov/entity/issues/10135
- Adding verified flag for BCeID affidavit approved users

10135 : Adding verified flag for BCeID affidavit approved users

---

auth-web/src/resources/BreadcrumbResources.ts
auth-web/src/util/config-helper.ts
auth-web/src/util/constants.ts

*Issue #:*
https://github.com/bcgov/entity/issues/10747
* Removed Config-Helper from Resource file
* Fixed Registry home session assignment

Removed Config-Helper from Resource

---

auth-web/nginx.conf

*Issue #:*
https://github.com/bcgov/entity/issues/10195
1. added application security header;
2. exclude the http 2xx and 3xx logging from console;

Added application security header.

---

auth-api/src/auth_api/resources/org_products.py

*Issue #:*
https://github.com/bcgov/entity/issues/6884
- Accept Staff View Account role for get orgproducts endpoints

6884 - Add get orgproducts permission for Staff View Account role

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/App.vue
auth-web/src/components/auth/home/NameRequestButton.vue
auth-web/src/components/auth/manage-business/AffiliatedEntityTable.vue
auth-web/src/components/auth/manage-business/EntityManagement.vue
auth-web/src/views/auth/home/RequestNameView.vue

*Issue #:*
https://github.com/bcgov/entity/issues/6151
* append URL accountid in external URLs

 Account may change when navigating between UIs#6151

---

auth-api/src/auth_api/services/affiliation.py
auth-api/src/auth_api/utils/enums.py

*Issue #:*
https://github.com/bcgov/entity/issues/10737

Fixing find visible affiliations logic

---

auth-api/migrations/versions/cd89e8e61dec_sp_gp_corp_types.py

*Issue #:*
https://github.com/bcgov/entity/issues/9251

added SP & GP

---

docs/docs/api_contract/auth-api-1.0.0.yaml

updated auth api schema to include missing bcol and a few other attrs

---

auth-api/src/auth_api/services/affiliation.py
auth-api/src/auth_api/version.py
auth-api/tests/unit/services/test_affiliation.py

*Issue #:*
https://github.com/bcgov/entity/issues/10012
add casefold function to both the applicants email and the verification email in business affiliation logic.

10012_nr_affliation_emailcase

---

queue_services/account-mailer/src/account_mailer/config.py
queue_services/account-mailer/src/account_mailer/email_processors/common_mailer.py
queue_services/account-mailer/src/account_mailer/utils.py
queue_services/account-mailer/tests/docker/docker-compose.yml

fix for UTC time being sent in invoice creation mail

---

auth-web/src/components/auth/staff/account-management/StaffActiveAccountsTable.vue

*Issue #:*
https://github.com/bcgov/entity/issues/11622
Added branch name and id to search results

Added branch name and id to the search results

---

auth-web/devops/vaults.json
auth-web/public/config/configuration.json

*Issue #:*
https://github.com/bcgov/entity/issues/11263
- Update local configuration to point at correct url.
- Update /devops/vaults.json to include 'api-document'.

11263 - API Documentation Link on Developer Access page not working

---

auth-api/src/auth_api/__init__.py
auth-api/src/auth_api/resources/documents_affidavit.py

*Issue #:*
https://github.com/bcgov/entity/issues/11855 
Skip camel case on swagger.json. 

11855 - Swagger not working correctly for pay-api / auth-api

---

auth-web/src/locales/en.json

*Issue #:*
https://github.com/bcgov/entity/issues/11896
REMOVE the text "Title search companies approved by Vital Statistics Agency may also be granted access to Wills Registry."

11896 - Update wording on Wills Product - Terms of Service

---

auth-web/vue.config.js

*Issue #:*
https://github.com/bcgov/entity/issues/10111
Auth home page doesn't show in IE11, change transpileDependencies so it works.

10111 - Auth home page doesn't show in IE11

---

auth-web/package-lock.json
auth-web/package.json

*Issue #:*
https://github.com/bcgov/fas-ui/pull/147
Color change

11966 - Add text to footer

---

auth-api/src/auth_api/utils/enums.py
auth-web/src/components/auth/manage-business/AffiliatedEntityTable.vue
auth-web/src/models/business.ts
auth-web/src/util/common-util.ts
auth-web/src/util/constants.ts
queue_services/business-events-listener/app.py
queue_services/business-events-listener/requirements.txt
queue_services/business-events-listener/src/business_events_listener/worker.py
queue_services/business-events-listener/tests/integration/test_worker_queue.py
queue_services/business-events-listener/tests/integration/utils.py

**Note: this is merging into test_queues branch, will create a PR into main when I've tested it on DEV.**
*Issue #:*
https://github.com/bcgov/entity/issues/10296
Add in EntityStatus from LEAR.
Add in case for entity.Status.
Update business_events_listener/worker.py to handle business events.

10296 - AUTH API: Handle new state property

---

auth-web/src/components/auth/account-settings/payment/AccountPaymentMethods.vue
auth-web/src/components/auth/common/LinkedBCOLBanner.vue
auth-web/src/components/auth/common/PaymentMethods.vue
auth-web/src/components/auth/create-account/BcolLogin.vue

*Issue #:*
https://github.com/bcgov/entity/issues/11741
- Remove this.currentOrgPaymentType from BCOL check.
- Add in watch for username.
- Implement a force edit mode, which will automatically go into edit mode when the organization's payment method changes.

11741 - Transition from BCOL to PAD - Changes based on feedback 

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/components/auth/staff/PPRLauncher.vue
auth-web/tests/unit/components/PPRLauncher.spec.ts

*Issue #:*
https://github.com/bcgov/entity/issues/12267
* In response to the removal of `mhr_staff` roles, adjusted to look at base `mhr` and `ppr` roles in jwt.

Updated PprLauncher roles

---

auth-api/src/auth_api/models/affidavit.py
auth-api/tests/unit/services/test_affidavit.py

*Issue #:*
https://github.com/bcgov/entity/issues/11656
Change query for affidavit code, so it filters correctly. 

11656 - Fix for duplicate affidavits.

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/components/auth/manage-business/AddBusinessForm.vue
auth-web/src/components/auth/manage-business/Certify.vue
auth-web/src/components/auth/manage-business/EntityManagement.vue
auth-web/tests/unit/components/AddBusinessForm.spec.ts
auth-web/tests/unit/components/Certify.spec.ts
package-lock.json

*Issue #:*
https://github.com/bcgov/entity/issues/12792
Click for the [UI Design link](https://projects.invisionapp.com/share/H612PJX3F2KJ#/screens/467047952?browse)

12792 Auth UI: Enhancements to Affiliate

---

auth-api/devops/vaults.json
auth-api/docs/dotenv_template
auth-api/src/auth_api/__init__.py
auth-api/src/auth_api/config.py
auth-web/src/main.ts
queue_services/account-mailer/devops/vaults.json
queue_services/account-mailer/src/account_mailer/config.py
queue_services/activity-log-listener/devops/vaults.json
queue_services/activity-log-listener/src/activity_log_listener/config.py
queue_services/business-events-listener/devops/vaults.json
queue_services/business-events-listener/src/business_events_listener/config.py
queue_services/events-listener/devops/vaults.json
queue_services/events-listener/src/events_listener/config.py
status-api/config.py
status-api/devops/vaults.json
status-api/docs/dotenv_template
status-api/requirements/prod.txt
status-api/setup.cfg
status-api/src/status_api/__init__.py
status-api/src/status_api/resources/whatsnew.py

Signed-off-by: Chen <Steven.Chen@gov.bc.ca>
*Issue #:*
https://github.com/bcgov/entity/issues/12422>
Turn Sentry Off by using SENTRY_ENABLE FLAG instead of SENTRY_DSN

Turn Sentry Off by using SENTRY_ENABLE FLAG instead of SENTRY_DSN#12422

---

auth-web/src/services/payment.services.ts
auth-web/src/store/modules/org.ts
auth-web/src/views/pay/PaymentView.vue

*Issue #:*
https://github.com/bcgov/entity/issues/12877
12877 - Add Account-Id to headers.
If `Account-Id` isn't added to headers, it takes the business identifier auth route. But the business doesn't have an affiliation so it fails. The business gets an affiliation after name request has been paid. 

12877 - Add Account-Id to headers.

---

.github/CODEOWNERS
queue_services/activity-log-listener/setup.cfg
queue_services/activity-log-listener/src/activity_log_listener/version.py
queue_services/activity-log-listener/src/activity_log_listener/worker.py

*Issue #:*
https://github.com/bcgov/entity/issues/13287
Exception wrapping, to avoid InvalidRequestError: Can't reconnect until invalid transaction is rolled back

13287 - ACTIVITY-LOG-LISTENER - InvalidRequestError: Can't reconnect until invalid transaction is rolled back

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/components/auth/manage-business/EntityManagement.vue
auth-web/src/locales/en.json
auth-web/tests/unit/components/EntityManagement.spec.ts

*Issue #:* /bcgov/entity#13251
- Move incorporate numbered company from business marketing page, btn from HomeView in [13253](https://github.com/bcgov/sbc-auth/pull/2056)
- Add tooltips for "incorporate numbered company" and "Add an Existing Business or NR" btns
- typo correction
- unit tests

13251 Auth Web - Move buttons

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/components/auth/manage-business/EntityManagement.vue
auth-web/src/views/auth/home/HomeView.vue

*Issue #:* /bcgov/entity#13370
- Deleted unused function which did the same thing as startNumberedCompany
- changed account id fetching so it works for staff and users
- Make text white for Home log in btn
- App version = 1.1.2

13370 Fix Incorporate a numbered ben company btn and wrong color for login btn text

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/components/auth/manage-business/AddBusinessDialog.vue

*Issue #:*
https://github.com/bcgov/entity/issues/13014
- updated rules validation on blur only

13014 Auth Web: Affiliation modal dialog should not validate incorporation/registration number until focus leaves the field

---

auth-web/src/components/auth/account-settings/product/ProductPackage.vue
auth-web/src/components/auth/common/Product.vue
auth-web/src/components/auth/common/ProductFeeViewEdit.vue

*Issue #:*
https://github.com/bcgov/entity/issues/13622

13622 - Ensure $1.05 is the only Service Fee selectable by BCOL Admin during account creation

---

auth-api/src/auth_api/services/affiliation.py

*Issue #:*
https://github.com/bcgov/entity/issues/13269
Part 1
GIVEN I am a BC registries staff user (IDIR) completing an SP/GP reg
WHEN I look up the client’s NR in Name Request
THEN I am able to link into the registration flow
AND the NR is affiliated to my org behind the scenes

13269 - Allow staff the ability to create new business affiliation - Part 1

---

queue_services/account-mailer/devops/vaults.json
queue_services/account-mailer/requirements.txt
queue_services/account-mailer/requirements/prod.txt
queue_services/account-mailer/src/account_mailer/config.py
queue_services/account-mailer/src/account_mailer/worker.py
queue_services/activity-log-listener/devops/vaults.json
queue_services/activity-log-listener/requirements.txt
queue_services/activity-log-listener/requirements/prod.txt
queue_services/activity-log-listener/src/activity_log_listener/config.py
queue_services/activity-log-listener/src/activity_log_listener/worker.py
queue_services/business-events-listener/devops/vaults.json
queue_services/business-events-listener/requirements.txt
queue_services/business-events-listener/requirements/prod.txt
queue_services/business-events-listener/src/business_events_listener/config.py
queue_services/business-events-listener/src/business_events_listener/worker.py
queue_services/events-listener/devops/vaults.json
queue_services/events-listener/requirements.txt
queue_services/events-listener/requirements/prod.txt
queue_services/events-listener/src/events_listener/config.py
queue_services/events-listener/src/events_listener/worker.py

*Issue #: 13846*
https://github.com/bcgov/entity/issues/13846
- imported LD flag service from auth_api.services into account-mailer, activity-log-listener, business-events-listener, and 
events listener worker files in queue_services
- updated requirements, configs, and vaults for each respective queue service

imported LD flag service into queue_services

---

auth-api/src/auth_api/services/affiliation.py
auth-api/tests/unit/services/test_affiliation.py

*Issue #:*
https://github.com/bcgov/entity/issues/14427

14427 remove duplicated spaces from party name before comparing

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/components/auth/manage-business/AddBusinessDialog.vue
auth-web/src/components/auth/manage-business/Certify.vue
auth-web/src/components/auth/manage-business/EntityManagement.vue
auth-web/src/models/affiliation.ts
auth-web/src/models/business.ts
auth-web/src/store/modules/business.ts
auth-web/tests/unit/components/AddBusinessDialog.spec.ts
auth-web/tests/unit/components/Certify.spec.ts
auth-web/tests/unit/components/EntityManagement.spec.ts
auth-web/vue.config.js

*Issue #:*
https://github.com/bcgov/entity/issues/14066
- updated UI to allow text entry of certifier (when staff only)
- updated UI to save certifier in call to API
- updated unit tests

14066 Auth Web: Affiliation certifier should be editable by SBC Staff and Registries Staff

---

docs/docs/database/bca_users_accounts.sql

*Issue #:*
https://github.com/bcgov/entity/issues/14507
added column of BCOL USER ID and word 'FIRST' to Admin Email&Phone column

14507 add column of BCOL USER ID and 'FIRST' to Admin Email&Phone

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue

*Issue #:*
https://github.com/bcgov/entity/issues/12753
Read from route instead of session storage.

12753 - Navigating by URL on staff account causes the wrong org to be loaded 

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/components/auth/create-account/UserProfileForm.vue

Make admin phone number manditory. `Business-create-ui` looks in contacts for a phone number. 
https://github.com/bcgov/business-create-ui/blob/565d9b1bce6bc83f9f326f19e1e93b20253b31ae/src/App.vue#L942

Required phone for account admin

---

auth-web/src/components/auth/account-settings/transaction/Transactions.vue
auth-web/src/components/auth/account-settings/transaction/TransactionsDataTable.vue
auth-web/src/components/datatable/BaseVDataTable.vue
auth-web/src/models/transaction.ts
auth-web/src/resources/table-headers/transactions-table-headers.ts
auth-web/src/util/common-util.ts
auth-web/tests/unit/components/BaseVDatatable.spec.ts
auth-web/tests/unit/components/TransactionsDataTable.spec.ts
auth-web/tests/unit/test-utils/test-data/transaction.ts

*Issue #:*
https://github.com/bcgov/entity/issues/14376

14376 transaction table ux 1

---

auth-web/src/components/auth/mixins/NextPageMixin.vue
auth-web/src/views/pay/CcPaymentView.vue
auth-web/src/views/pay/PaymentView.vue

This was working on localhost, but not deployed. 
These changes are needed, because the url that is provided on DEV and TEST are different than the url provided in PROD. 
Keycloak gold vs keycloak silver I believe.

15245 - Changes for redirectTo.

---

auth-web/src/util/common-util.ts
auth-web/tests/unit/util/common-util.spec.ts

Failing on the string:
EG.
/confirmtoken/eyJpZCI6MTc1MSwidHlwZSI6IlNUQU5EQVJEIn0.Y-qrVg.jqfdfdfdfd

isUrl fix.

---

auth-api/src/auth_api/services/affidavit.py

Sometimes an affidavit will already be approved and not PENDING. 
If it's already approved, continue forward without throwing a 404. 

Small fix for affidavit

---

auth-api/src/auth_api/utils/util.py

This prevents double requests (calling options each time before making a request)

OPTIONS not caching - Add access control max age

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/util/http-util.ts

*Issue #:*
https://github.com/bcgov/entity/issues/15241
auth-web defaults to sending an `Authorization` header for any request it makes - newer version of Minio does not like this header, and throws 400 errors. This change will not auto-add the header for urls with `minio` in them.

15241 minio upgrade fix

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/models/affiliation.ts
auth-web/src/store/modules/business.ts
auth-web/tests/unit/components/AffiliatedEntityTable.spec.ts
auth-web/tests/unit/test-utils/test-data/affiliations.ts

*Issue #:*
https://github.com/bcgov/entity/issues/16333
added "state" to affiliation response, it's status before, so it didn't grab "historical" status

16333 - show historical entities

---

auth-api/migrations/versions/2023_07_24_b20a33cb84f2_mhr_qualified_supplier.py
auth-api/src/auth_api/models/dataclass.py
auth-api/src/auth_api/models/product_code.py
auth-api/src/auth_api/models/task.py
auth-api/src/auth_api/resources/task.py
auth-api/src/auth_api/schemas/product_code.py
auth-api/src/auth_api/schemas/schemas/org_product_subscription.json
auth-api/src/auth_api/schemas/schemas/product.json
auth-api/src/auth_api/schemas/schemas/task_request.json
auth-api/src/auth_api/schemas/schemas/task_response.json
auth-api/src/auth_api/services/products.py
auth-api/src/auth_api/utils/enums.py
auth-api/tests/docker/setup/demo-realm.json
auth-api/tests/unit/api/test_org_products.py
auth-api/tests/unit/api/test_product.py
auth-api/tests/unit/services/test_org.py
auth-api/tests/unit/services/test_product.py
auth-api/tests/utilities/factory_scenarios.py

*Issue #:*
https://github.com/bcgov/entity/issues/17097
https://github.com/bcgov/entity/issues/17098
- Add MHR qualified supplier sub product codes for (Lawyers and Notaries, Home Manufacturers, Home Dealers)
- Extend Product Subscriptions POST to allow an external_source_id to be persisted to a created staff review task
- Update task to include the external source identifier
- Add parent product code to product codes to track hierarchy
- When activating a sub product subscription, the parent product is also evaluated and activated as needed
- update keycloak demo realm to include new groups for unit tests
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the sbc-auth license (Apache …

17097, 17098 - qualified supplier sub project subscriptions

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/components/auth/account-settings/product/ProductPackage.vue
auth-web/src/models/Organization.ts

*Issue #:*
https://github.com/bcgov/entity/issues/17098
- As part of implementing #17098 sub products now appear in the account products and services list. 
- Update to not display any products with a parentCode (MHR - Qualified supplier will have this on their own forms in the near future)

hide new sub products (has parentCode)

---

.github/CODEOWNERS
auth-api/src/auth_api/resources/entity.py
auth-api/src/auth_api/schemas/__init__.py
auth-api/src/auth_api/schemas/contact.py
auth-api/src/auth_api/services/contact.py
auth-api/src/auth_api/services/entity.py
auth-api/tests/unit/api/test_affiliation_invitation.py
auth-api/tests/unit/api/test_entity.py

*Issue #:*
https://github.com/bcgov/entity/issues/15769

15769 - Backend changes - for masked email for contacts.

---

auth-api/migrations/versions/2023_08_08_628b52a95bad_affiliation_invitations_to_org_nullable.py
auth-api/src/auth_api/exceptions/errors.py
auth-api/src/auth_api/models/affiliation_invitation.py
auth-api/src/auth_api/resources/affiliation_invitation.py
auth-api/src/auth_api/schemas/affiliation_invitation.py
auth-api/src/auth_api/schemas/contact.py
auth-api/src/auth_api/schemas/schemas/affiliation_invitation.json
auth-api/src/auth_api/schemas/schemas/affiliation_invitation_response.json
auth-api/src/auth_api/services/affiliation_invitation.py
auth-api/src/auth_api/utils/util.py
auth-api/tests/unit/api/test_affiliation_invitation.py
auth-api/tests/unit/services/test_affiliation_invitation.py
auth-api/tests/utilities/factory_utils.py

https://github.com/bcgov/entity/issues/15769
- update affiliation_invitations table: to_org_id and recipient_email is nullable (email is not required for passcode flow)
- update affiliation to be created for the from_org
- update to_org to be an optional parameter
- update auth check to not include business_identifier as there is no affiliation to the from_org when creating an invite
- update auth check to not include business_identifier when working with an affiliation invitation
- removed sent date parameter for creation (was already being set as part of create date, sent date updates when an email it resent)
- removed recipient email parameter for creation (this is fetched via the entity contacts), if there is no email a validation error is thrown
- …

15769 - Affiliation Invitations - updates and fixes

---

auth-api/src/auth_api/models/product_subscription.py
auth-api/src/auth_api/services/products.py
auth-api/tests/unit/api/test_org_products.py
auth-api/tests/utilities/factory_scenarios.py

- update parent product handling for sub products - checks additional checks for parent product and the current status
- additional test cases to test different approval and rejection situations

fix sub product handling of parent product subscriptions

---

auth-api/src/auth_api/version.py

auth-api version increment to 2.8.0

---

auth-api/src/auth_api/services/affiliation_invitation.py

Fix missing to_org_id when creating affiliation invitation with toOrgUuid.

Fix missing to_org_id when creating affiliation invitation with toOrgUuid.

---

auth-api/src/auth_api/resources/v1/documents.py
auth-api/tests/unit/api/test_documents.py
auth-api/tests/utilities/factory_utils.py

*Issue #:*
https://github.com/bcgov/entity/issues/15686
- fix 500 error returning specifically for TOS PAD

fix 500 error fetching on documents endpoint for tos pad

---

auth-api/src/auth_api/resources/v1/entity.py
auth-api/src/auth_api/services/entity.py
auth-api/tests/unit/api/test_entity.py

*Issue #:17057*
https://github.com/bcgov/entity/issues/17057

17057 - Checking for Authentication Endpoint for Entities

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/composables/affiliations-factory.ts
auth-web/src/models/affiliation.ts
auth-web/src/models/business.ts
auth-web/src/stores/business.ts
auth-web/src/util/common-util.ts
auth-web/src/util/constants.ts

*Issue #:*
https://github.com/bcgov/entity/issues/17385
- Use the action code for amalgamation to display Name Request type.
*Notes:*
While the `requestTypeCd` returned from LEAR can be used for the NR type in most cases, in this situation we have to use the `requestActionCd`. This is because for _Incorporation_ and _Amalgamation_ NR types for a BC Limited Company, the `requestTypeCode` will be "CR" in both cases (so we can't differentiate using this), however the `requestActionCd`s will be "NEW" and "AML" respectively. I couldn't find a general solution using just `requestActionCd`s as many of the codes have dual uses.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the sbc-auth …

17385 - Fix amalgamation NR display in MBR

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/components/auth/manage-business/AuthorizationEmailSentDialog.vue
auth-web/src/components/auth/manage-business/BusinessLookup.vue
auth-web/src/components/auth/manage-business/EntityManagement.vue
auth-web/src/components/auth/manage-business/SearchBusinessNameRequest.vue
auth-web/src/components/auth/manage-business/manage-business-dialog/AuthorizationRequestSentDialog.vue
auth-web/src/components/auth/manage-business/manage-business-dialog/ManageBusinessDialog.vue

1. Name request cancel button clear the input box
2. Fix help dialog section
3. Display loading when it re-fetch affiliations

Auth-web: Magic link bug fixing

---

auth-api/src/auth_api/services/products.py
auth-api/src/auth_api/services/task.py
auth-api/src/auth_api/utils/enums.py
auth-api/src/auth_api/utils/notifications.py
auth-api/tests/unit/services/test_product.py
auth-api/tests/unit/services/test_product_notifications.py
queue_services/account-mailer/src/account_mailer/email_templates/product_approved_notification_detailed.html
queue_services/account-mailer/src/account_mailer/email_templates/product_rejected_notification_detailed.html
queue_services/account-mailer/src/account_mailer/enums.py
queue_services/account-mailer/src/account_mailer/worker.py

*Issue #:*
https://github.com/bcgov/entity/issues/17525
https://github.com/bcgov/entity/issues/17526
https://github.com/bcgov/entity/issues/17527
- Product subscription qualified supplier emails - approved / rejected / re-approved
- refactor to fall back on default notifications used by other product codes
- refactor adding data classes for some methods that have a large amount of params
- fix an existing issue where putting a task on hold would send a rejection email
- tests specifically to test messages for mailer

17525, 17526, 17527 - Qualified Supplier Emails

---

auth-api/src/auth_api/services/products.py
auth-api/src/auth_api/utils/enums.py
auth-api/src/auth_api/utils/notifications.py
auth-api/tests/unit/services/test_product_notifications.py
queue_services/account-mailer/src/account_mailer/config.py
queue_services/account-mailer/src/account_mailer/email_processors/product_confirmation.py
queue_services/account-mailer/src/account_mailer/email_templates/product_confirmation_notification.html
queue_services/account-mailer/src/account_mailer/enums.py
queue_services/account-mailer/src/account_mailer/worker.py

*Issue #:*
https://github.com/bcgov/entity/issues/17528
- qualified supplier agreement added to account mailer minio bucket as part of this update
- implement confirmation email for MHR qualified supplier product subscriptions

17528 - Qualified supplier confirmation email

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/components/auth/manage-business/AffiliatedEntityTable.vue
auth-web/src/util/constants.ts

We'll still need this feature flag in LD until this code reaches PROD.

Remove unused feature flag - enable-name-request-type - this will be on permanently.

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/components/auth/manage-business/AffiliationAction.vue

*Issue #:17777 *
https://github.com/bcgov/entity/issues/17777 
- Remove 'business authorized' message after first access to Manage Business page.

17777 - Remove 'business authorized' message

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/components/auth/manage-business/BusinessLookup.vue
auth-web/src/components/auth/manage-business/SearchBusinessNameRequest.vue

*Issue #:*
https://github.com/bcgov/entity/issues/17519
on My Business Registry Dashboard
- Included the word 'active' in initial text
- Changed no matches state text for NR search
- app version = 2.4.26

17519 - Indicate to user that cancelled/expired NRs will not be returned by NR search

---

auth-api/src/auth_api/resources/v1/affiliation_invitation.py
auth-api/src/auth_api/services/affiliation_invitation.py
auth-api/src/auth_api/services/user.py
auth-api/tests/unit/services/test_affiliation_invitation.py

*Issue #:17778 & 17788*
https://github.com/bcgov/entity/issues/17778
https://github.com/bcgov/entity/issues/17788
- updating how emails are fetched for affiliation invitation of type REQUEST (going to all admins/coordinators)
- updating who can see affiliation invitations of type REQUEST (only admin/coordinators now)
- updating who can accept affiliation invitations of type REQUEST (only admin/coordinators now)

17778 & 17788 - Org Admin/Coordinator for affiliation invitation updates

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/stores/staff.ts

*Issue #:*
https://github.com/bcgov-registries/ops-support/issues/3093
Allow failure of affidavit GET to still allow code to set value

OPS#3093 - Fix for affidavit error

---

queue_services/account-mailer/src/account_mailer/email_templates/payment_due_notification.html
queue_services/account-mailer/src/account_mailer/email_templates/payment_reminder_notification.html
queue_services/account-mailer/src/account_mailer/enums.py
queue_services/account-mailer/src/account_mailer/version.py
queue_services/account-mailer/src/account_mailer/worker.py
queue_services/account-mailer/tests/integration/test_worker_queue.py

*Issue #:*
https://github.com/bcgov/entity/issues/17224
- added email templates for statement payment notifications (reminder and due)

17224 - Payment reminder notifications for EFT

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/components/auth/common/PaymentMethods.vue
auth-web/src/models/Organization.ts
auth-web/src/util/config-helper.ts

*Issue #:*
https://github.com/bcgov/entity/issues/16904
1. Add EFT Payment Option to Payment methods
2. Add enable_eft flag to store
3. convert PaymentMethod.vue to composition-api

16904 - Add EFT Payment Option

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/components/auth/account-settings/account-info/AccountAccessType.vue
auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
auth-web/src/components/auth/manage-business/manage-business-dialog/ManageBusinessDialog.vue
auth-web/src/locales/en.json
auth-web/src/services/payment.services.ts
auth-web/src/stores/org.ts
auth-web/src/views/auth/staff/ReviewAccountView.vue
auth-web/tests/unit/components/AccountAccessType.spec.ts

*Issue #:*
https://github.com/bcgov/entity/issues/10680
Initial commit for changing from GOVN -> PREMIUM

10680 - Allow changing from GOVN -> PREMIUM

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/components/auth/manage-business/manage-business-dialog/ManageBusinessDialog.vue

Typos, small UX improvements.

---

auth-web/package-lock.json
auth-web/package.json
auth-web/tests/unit/components/AccountInformation.spec.ts
auth-web/vite.config.ts

*Issue #:*
https://github.com/bcgov/entity/issues/18487

18487 - Fix for the issue of multiple Vue instances detected in fas-ui with Vite.

---

auth-api/src/auth_api/services/membership.py
auth-api/src/auth_api/version.py

*Issue #:*
https://github.com/bcgov/entity/issues/16627
- fix ADMIN check for membership deactivation

16627 - fix check for team membership deactivation

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/components/auth/account-settings/statement/Statements.vue
auth-web/src/components/auth/account-settings/statement/StatementsSettings.vue

*Issue #:*
https://github.com/bcgov/entity/issues/18761
https://github.com/bcgov/entity/issues/18763
- Fix issue where statement settings are always hidden when the feature flag for eft payment method is enabled. Statements settings are now always shown, but the statement frequency will be locked if the feature flag is enabled and payment method is EFT
- Fix some styling issues as per UXPIN

18761, 18763 - EFT statement settings updates

---

auth-api/src/auth_api/services/api_gateway.py

Add in regex to filter out bad characters for API key generation.

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/util/constants.ts

*Issue #:*
https://github.com/bcgov/entity/issues/19143
Allow signout for pending orgs.
https://github.com/bcgov/sbc-common-components/pull/345

19143 - Allow signout for pending orgs.

---

auth-api/requirements.txt
auth-api/requirements/dev.txt
auth-api/requirements/prod.txt
auth-api/src/auth_api/config.py
auth-api/src/auth_api/services/rest_service.py
auth-api/src/auth_api/utils/cache.py
auth-api/tests/conftest.py
auth-api/tests/unit/api/test_task.py
auth-api/tests/unit/api/test_user.py
auth-api/tests/unit/api/test_user_settings.py
auth-api/tests/unit/services/test_affidavit.py
auth-api/tests/unit/services/test_affiliation.py
auth-api/tests/unit/services/test_affiliation_invitation.py
auth-api/tests/unit/services/test_invitation.py
auth-api/tests/unit/services/test_invitation_auth.py
auth-api/tests/unit/services/test_membership.py
auth-api/tests/unit/services/test_org.py
auth-api/tests/unit/services/test_product.py
auth-api/tests/unit/services/test_product_notifications.py
auth-api/tests/unit/services/test_task.py
auth-api/tests/unit/services/test_user.py
auth-api/tests/unit/services/test_user_settings.py

*Issue #: https://github.com/bcgov/entity/issues/16527
*Description of changes: added a service account token caching service in gcp as a POC: https://github.com/bolyachevets/token_cache
Looking for some feedback.

16527 - check token cache endpoint before generating new service account token

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/components/auth/staff/review-task/QsApplication.vue
auth-web/src/models/external.ts
auth-web/src/resources/QualifiedSupplierAccessResource.ts
auth-web/src/services/task.services.ts
auth-web/tests/unit/components/QsApplication.spec.ts

*Issue #:*
https://github.com/bcgov/entity/issues/17573
https://github.com/bcgov/entity/issues/17467
Note: Hide White Space changes for easier reviewing 👍 
*Home Dealer Applicant Updates:*
- Support additional DBA Name Field
- Minor Requirements configuration updates
*Manufacturer Applicant Updates:*
- Fetch and parse data from dedicated Manufacturer endpoint via mhr api
- Support for dba name fields, as well as Home/lot location data
- Requirements configuration updates
- Updated unit tests to verify all types of Qualified Supplier applicants
Some screenshots attached for context:
Home Dealer Flow:
Manufacturer Flow:
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the sbc-auth …

17573/17467: Support for Manufacturer and HomeDealer QS Applicant Reviews

---

auth-api/src/auth_api/__init__.py
auth-api/src/auth_api/config.py
auth-api/src/auth_api/models/affiliation.py
auth-api/src/auth_api/services/__init__.py
auth-api/src/auth_api/services/affiliation.py
auth-api/src/auth_api/services/flags.py
auth-api/tests/unit/services/test_flags.py
auth-web/package-lock.json
auth-web/package.json
auth-web/src/models/affiliation.ts
auth-web/src/stores/business.ts
auth-web/src/util/constants.ts

*Issue #:*
https://github.com/bcgov/entity/issues/15603

15603 - Initial changes for adding in displayName for legalName changes (SP/GP).

---

queue_services/account-mailer/src/account_mailer/worker.py
queue_services/activity-log-listener/src/activity_log_listener/worker.py
queue_services/events-listener/src/events_listener/worker.py
queue_services/names-events-listener/src/names_events_listener/worker.py

add in cache.init_app

---

auth-web/package-lock.json
auth-web/package.json

revert mdi/fonts version - caused regression issues

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/components/pay/eft/ShortNameAccountLink.vue
auth-web/src/components/pay/eft/ShortNameTransactions.vue

*Issue #:*
https://github.com/bcgov/entity/issues/19333

19333 UX tweaks part 2

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/components/pay/LinkedShortNameTable.vue
auth-web/src/components/pay/eft/ShortNameAccountLink.vue
auth-web/src/components/pay/eft/ShortNameTransactions.vue
auth-web/src/views/pay/ShortNameMappingView.vue

Add in some small tweaks

---

jobs/notebook-report/Makefile
jobs/notebook-report/vaults.json

*Issue #:*
https://github.com/bcgov/entity/issues/3596
Amend weekly Auth Stats reports to include new accounts setup - counting accounts using BCeID or BCSC

Auth Stats reports to include new accounts setup - counting accounts using BCeID or BCSC 3596

---

auth-api/src/auth_api/resources/v1/org.py
auth-api/src/auth_api/services/org.py
auth-api/src/auth_api/utils/enums.py
auth-api/tests/unit/api/test_org.py

*Issue #:*
To refactor '_src/auth_api/resources/v1/org_api_keys.py_' to a separate service, we have to support updating the 'has_api_access' property of the org via an API call.

Code to update the api access property of the org via API call

---

auth-api/migrations/versions/2024_04_19_824f5ef280c6_add_ca_search_product_code.py

*Issue #:*
https://github.com/bcgov/entity/issues/19991
New product for competent authority search. It is supposed to be mirroring the same sort of setup as NDS

Added new product migration for comp auth search

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/assets/scss/theme.scss
auth-web/src/components/CardHeader.vue
auth-web/src/components/auth/staff/DissolutionSchedule.vue
auth-web/src/components/index.ts
auth-web/src/models/Staff.ts
auth-web/src/stores/staff.ts
auth-web/src/views/auth/staff/InvoluntaryDissolution.vue
auth-web/tests/unit/views/InvoluntaryDissolution.spec.ts

*Issue #:*
https://github.com/bcgov/entity/issues/19024
- Implemented the Involuntary Dissolution Screen
- Implemented all phases (pause, resume, edit)
- Implemented the badge
- Implemented validation
- Lots of misc. stuff

19024 - Implemented the Involuntary Dissolution Screen

---

queue_services/events-listener/src/events_listener/worker.py
queue_services/events-listener/tests/integration/utils.py

https://github.com/bcgov/entity/issues/20087

20087 - Add suspension reason from queue payload

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/components/pay/eft/ShortNameAccountLink.vue
auth-web/src/components/pay/eft/ShortNameTransactions.vue
auth-web/tests/unit/components/ShortNameTransactions.spec.ts

*Issue #:*
https://github.com/bcgov/entity/issues/20417
- align statement and amount columns on link and transaction tables
- Fix text padding when there is no links
- update transaction amount formatting to be negative for paid statement rows

20417-UXA-Fixes

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
auth-web/src/components/pay/LinkedShortNameTable.vue
auth-web/src/util/constants.ts

*Issue #:*
https://github.com/bcgov/entity/issues/20421

20421 - UXA for displaying suspension status next to eft overdue payment accounts

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/components/auth/account-settings/payment/AccountPaymentMethods.vue
auth-web/src/components/auth/common/PADInfoForm.vue
auth-web/src/components/auth/common/PaymentMethods.vue
auth-web/src/components/auth/common/TermsOfUseDialog.vue
auth-web/src/components/pay/LinkedShortNameTable.vue

*Issue #:*
https://github.com/bcgov/entity/issues/21107

21107 - Add T&C to Selecting EFT Payment

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/components/auth/staff/DissolutionSchedule.vue
auth-web/src/models/Staff.ts
auth-web/src/services/staff.services.ts
auth-web/src/stores/staff.ts
auth-web/src/views/auth/staff/InvoluntaryDissolution.vue

*Issue #:*
https://github.com/bcgov/entity/issues/20929
- Interface Changes for the dissolution
- Implemented the GET call of the configurations
- Misc. fixes

20929 - Implemented GET involuntary dissolution configurations endpoint

---

auth-api/migrations/versions/2024_05_29_41fa6588c76e_add_eft_pad_to_suspension_reason_code.py

*Issue #:*
https://github.com/bcgov/entity/issues/21204
*Description of changes:* Create migration that updates suspension_reason_code

21204 - Create migration that add EFT and PAD into suspension_reason_codes

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/components/auth/manage-business/AffiliatedEntityTable.vue
auth-web/src/models/affiliation.ts
auth-web/src/models/business.ts
auth-web/src/stores/business.ts

*Issue #:*
https://github.com/bcgov/entity/issues/21262
- Showing an alert when a business is in the process of being dissolved
Keep in mind, the alert existed in the code before but was never being used. Now, since I'm building the business object with the new flag, we can actually show it.

21262 - New dissolution alert

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/views/auth/staff/SafeEmailView.vue
auth-web/src/views/auth/staff/StaffDashboardView.vue

Fixes issues with safe email list not displaying after clicking dropdown and re-rendering of the list on addition and removal. Done testing on local env. 

20463 - Fix: Update Safe Email List on Button Click

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/components/auth/staff/DissolutionSchedule.vue
auth-web/src/services/staff.services.ts
auth-web/src/stores/staff.ts

*Issue #:*
https://github.com/bcgov/entity/issues/21445
Since we're only using the `NUM_DISSOLUTIONS_ALLOWED` in the UI, there are some changes being made to be more efficient.
1. The GET call will now support params to grab ONLY what we need.
2. I'm putting now ONLY the object that I need which is when the name is `NUM_DISSOLUTIONS_ALLOWED`
This is a Quality of Life fix to improve things here.

21445 - Updated the GET and PUT configuration calls

---

auth-api/src/auth_api/resources/v1/org.py
auth-api/src/auth_api/utils/util.py
auth-api/tests/unit/api/test_org.py

Fixes:
```
sqlalchemy.exc.DataError: (psycopg2.errors.InvalidTextRepresentation) invalid input syntax for type integer: "M"
LINE 5: ...ND orgs.access_type = 'GOVM')) ORDER BY orgs.id = 'M' DESC, ...
```

Add in handling for letters in ID

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/components/auth/common/StaffAccountsTable.vue
auth-web/src/components/auth/staff/account-management/StaffActiveAccountsTable.vue
auth-web/src/components/auth/staff/account-management/StaffInactiveAccountsTable.vue
auth-web/src/util/constants.ts

*Issue #:*
https://github.com/bcgov/entity/issues/19414
*Description of changes:* Clicking the "Inactive" tab does not display inactive accounts when applying a filter.

19414 - Fixed filter issue on Active and Inactive Tab

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
auth-web/src/components/auth/account-settings/account-info/AccountMailingAddress.vue
auth-web/src/components/auth/common/BaseAddressForm.vue

*Issue #:*
https://github.com/bcgov/entity/issues/21878
1. fix for: Mailing address not update when switch accounts
2. update relate components BaseAddressForm.vue and AccountMailingAddress.vue to composition-api

21878  - AUTH WEB - Mailing address not update when switch accounts

---

auth-api/migrations/versions/2024_06_24_acc7e2e2c2d7_remove_eft_nsf_from_suspension_reason_.py

*Issue #:*
https://github.com/bcgov/entity/issues/21984
*Description of changes:* AUTH-API - Create migration that remove EFT_NSF from suspension_reason_codes

21984 - Create migration that remove EFT_NSF from suspension_reason_codes

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/components/pay/ShortNameLookup.vue
auth-web/src/util/constants.ts

*Issue #:*
https://github.com/bcgov/entity/issues/20415
Short names in PENDING state will now show up as LINKED and un-selectable from ShortNameLookup

20415 - Supporting PENDING state for short names

---

auth-api/src/auth_api/services/api_gateway.py

*Issue #:*
https://github.com/bcgov/entity/issues/22442

API Key Generation - Consumer - Use length of 64, instead of 256

---

queue_services/auth-queue/src/auth_queue/resources/worker.py
queue_services/auth-queue/tests/unit/test_events_worker_queue.py
queue_services/auth-queue/tests/unit/utils.py

- allow skipping the default NSF lock / unlock emails

Add skip_notification flag to bypass NSF notifications

---

jobs/gcp-db-data-masking/Dockerfile
jobs/gcp-db-data-masking/cloudbuild.yaml
jobs/gcp-db-data-masking/db_mask.sh
jobs/gcp-db-data-masking/run.sh

*Issue #:*
[https://github.com/bcgov/entity/issues/<Put the github issue number here>](https://app.zenhub.com/workspaces/connect-6690070c1ee5ec09f20a0ec1/issues/zh/82)
Cloud run job that pulls auth-db prod data. Placeholder script for db masking needs updating - jobs/gcp-db-data-masking/db_mask.sh

sandbox db upload job

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/components/auth/manage-business/AffiliatedEntityTable.vue
auth-web/src/components/auth/manage-business/EntityDetails.vue

*Issue #:*
https://github.com/bcgov/entity/issues/22686
- Fix the bug in business type wording for expiration alert
- Add a tooltip for change requested
- Updated the FE and Change Requested icon style

22686 - MBR Fix Tooltip

---

.github/workflows/account-mailer-ci.yml
.github/workflows/auth-api-ci.yml
.github/workflows/auth-queue-ci.yml

adding the following to CI files:
```
- name: Install docker-compose
run: |
sudo curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
docker-compose version
```

add install docker-compose to auth-api-ci.yml, auth-queue-ci.yml, account-mailer-ci.yml

---

auth-api/src/auth_api/version.py

updating version number for release, going from 2.10.3 to 2.10.4

updating release version number to 2.10.4

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/components/auth/staff/continuation-application/ContinuationApplicationTable.vue
auth-web/src/models/continuation-review.ts

*Issue #:*
https://github.com/bcgov/entity/issues/22416
- Add a date picker to the Staff Reviews section (ie, the Continuation Review table) 
- Change the date filter URL parameters to "yyyy-mm-dd" format, and change the name to "startDate" and "endDate"
- Change status selection display when there are multiple selections (display "Multiple Selected")
-  Set the default state for the 'Status' column to the first 3 options (Awaiting Review, Change Requested, and Resubmitted) selected.

22416 - Update Staff Review Table (Staff Dashboard)

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/components/auth/account-settings/statement/Statements.vue
auth-web/src/models/statement.ts
auth-web/tests/unit/components/OutstandingBalance.spec.ts

relies on 
https://github.com/bcgov/sbc-pay/pull/1681
*Issue #:*
https://github.com/bcgov/entity/issues/22678

22678 - Rename field to oldestDueDate

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/components/pay/ShortNameLookup.vue

*Issue #:*
https://github.com/bcgov/entity/issues/20415
- update short name search page limit to be the account list size

20415 Linking modal fix, update page limit to match account list size

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/assets/scss/tooltip.scss
auth-web/src/components/auth/account-settings/payment/AccountPaymentMethods.vue
auth-web/src/components/auth/common/AccountBusinessType.vue
auth-web/src/components/auth/common/PaymentMethods.vue

*Issue #:*
https://github.com/bcgov/entity/issues/22841

22841 - Add tooltip and pop-up window reminder to EFT payment

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/components/auth/account-settings/account-info/AccountAccessType.vue
auth-web/src/views/pay/eft/ShortNameDetailsView.vue

*Issue #:*
https://github.com/bcgov/entity/issues/22716
https://github.com/bcgov/entity/issues/21964

22716 & 21964 - UX tweaks

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/components/pay/eft/ShortNamePaymentHistory.vue

*Issue #:*
https://github.com/bcgov/entity/issues/22776
- Fix reload should go back to page 1
- Fix issue where infinite scroll back is no longer triggering if it previously has reached an end state even after reload

22776 - Shortname History Table Fixes

---

auth-web/.env.example
auth-web/devops/vaults.env
auth-web/package-lock.json
auth-web/package.json
auth-web/src/components/auth/staff/continuation-application/ContinuationApplicationTable.vue
auth-web/src/components/auth/staff/continuation-application/ContinuationApplications.vue
auth-web/src/models/continuation-review.ts
auth-web/src/util/config-helper.ts
auth-web/src/util/navigation.ts

*Issue #:*
https://github.com/bcgov/entity/issues/22579
- Added Future Effective Date column to table
- Added red/orange tooltips to future effective date
- Added red/orange tooltips to NR number when it has expired /<14 days
- Added action for NR redirect to Namex UI
- Added hover text showing what statuses are selected
- For date pickers: show the date range truncated and the full text on hover
- Added close icon to all search fields
- Fixed the bug: calendar icon can't open the date picker

22579 - Add FED Column & Tooltips (continuation table)

---

queue_services/account-mailer/src/account_mailer/email_templates/payment_due_notification.html
queue_services/account-mailer/src/account_mailer/email_templates/payment_reminder_notification.html
queue_services/account-mailer/src/account_mailer/resources/worker.py
queue_services/account-mailer/tests/unit/test_worker_queue.py

*Issue #:*
https://github.com/bcgov/entity/issues/21560
- Update EFT payment reminder / due templates

21560 - EFT Payment reminder template updates

---

auth-web/package-lock.json
auth-web/package.json

Update sbc-common-components 3.0.15

Update sbc-common-components 3.0.15

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/components/auth/account-settings/payment/AccountPaymentMethods.vue

Added all admins as notification recipients when switching to EFT payment method
*Issue #:*
https://github.com/bcgov/entity/issues/18769

18769 - EFT switching logic fix

---

queue_services/account-mailer/src/account_mailer/email_templates/payment_due_notification.html
queue_services/account-mailer/src/account_mailer/email_templates/payment_reminder_notification.html

*Issue #:*
https://github.com/bcgov/entity/issues/21560
- clean up template spacing causing gc notify to not recognize line breaks
- fix multi vs single text

21560 - Payment Reminder Fixes

---

auth-api/src/auth_api/resources/v1/__init__.py
auth-api/src/auth_api/resources/v1/keycloak.py
auth-api/src/auth_api/services/keycloak.py

https://github.com/bcgov/entity/issues/21537

21537 - Add in keycloak user fetch for role

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/assets/scss/ShortnameTables.scss
auth-web/src/components/pay/LinkedShortNameTable.vue
auth-web/src/components/pay/ShortNameSummaryTable.vue
auth-web/src/components/pay/eft/ShortNameLinkingDialog.vue
auth-web/src/components/pay/eft/ShortNamePaymentHistory.vue
auth-web/src/components/pay/eft/ShortNameRefund.vue
auth-web/src/models/pay/short-name.ts
auth-web/src/routes/router.ts
auth-web/src/services/payment.services.ts
auth-web/src/util/common-util.ts
auth-web/src/util/constants.ts
auth-web/src/util/short-name-utils.ts
auth-web/src/views/pay/eft/ShortNameDetailsView.vue
auth-web/src/views/pay/eft/ShortNameRefundView.vue
auth-web/tests/unit/components/LinkedShortNameTable.spec.ts
auth-web/tests/unit/components/ShortNamePaymentHistory.spec.ts
auth-web/tests/unit/components/ShortNameSummaryTable.spec.ts
auth-web/tests/unit/views/ShortNameRefundView.spec.ts

*Issue #:*
https://github.com/bcgov/entity/issues/21539
https://github.com/bcgov/entity/issues/23102
- Payment history table to support short name refunds
- Add read only view for refund details
- Update screens to show short name type for WIRE implementation

21539/23102 - EFT Wire and EFT Refund updates

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/components/pay/eft/ShortNamePaymentHistory.vue
auth-web/src/util/constants.ts

*Issue #:*
https://github.com/bcgov/entity/issues/21539
- fix on short name history type rename

21539 - Update short name history type

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/components/pay/ShortNameSummaryTable.vue

*Issue #:*
https://github.com/bcgov/entity/issues/21594
- move refund label to unsettled amount due to limited room from adding short name type
- adjust column sizes
- update / clean up styling

21594 - UXA Refund label

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/components/pay/ShortNameSummaryTable.vue
auth-web/src/util/constants.ts

*Issue #:*
https://github.com/bcgov/entity/issues/21536
- sync refund label statuses with backend refund status changes

21536 - sync refund label statuses with backend changes

---

auth-api/migrations/versions/2024_09_20_aa74003de9d8_.py

change memberships_history pkey

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/services/payment.services.ts
auth-web/src/views/pay/PaymentView.vue

23942 - If transaction is already completed jump directly to redirect url

---

queue_services/account-mailer/src/account_mailer/email_templates/pad_invoice_email.html
queue_services/account-mailer/src/account_mailer/enums.py
queue_services/account-mailer/src/account_mailer/resources/worker.py
queue_services/account-mailer/tests/unit/test_worker_queue.py

*Issue #:*
https://github.com/bcgov/entity/issues/19182

19182 - Changes to pad invoice email to consider credits

---

auth-api/poetry.lock
auth-api/pyproject.toml
auth-api/src/auth_api/config.py
auth-api/src/auth_api/models/pubsub_message_processing.py

Use pg8000 consistently

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/components/auth/account-settings/transaction/Transactions.vue
auth-web/src/components/auth/account-settings/transaction/TransactionsDataTable.vue
auth-web/src/composables/transactions-factory.ts

*Issue #:*
https://github.com/bcgov/entity/issues/23620 
Add in yearly filter for transactions, should smooth out the load on pay-api for the large transaction screen as well as the smaller client ones.

23620 - Add in year filter

---

auth-api/src/auth_api/services/affiliation_invitation.py

*Issue #:*
https://github.com/bcgov/entity/issues/24363
Magic link now uses query params. The new format is more standard and easier to parse since all variables are consistently passed as query parameters rather than being embedded in the URL path.

24363 - New magic link formatting based if FF is on

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/components/pay/eft/ShortNameFinancialDialog.vue
auth-web/src/components/pay/eft/ShortNameRefund.vue
auth-web/src/models/pay/short-name.ts
auth-web/src/models/refund.ts
auth-web/src/views/pay/eft/ShortNameDetailsView.vue
auth-web/src/views/pay/eft/ShortNameRefundView.vue
auth-web/tests/unit/components/ShortNameRefund.spec.ts
auth-web/tests/unit/views/ShortNameRefundView.spec.ts

*Issue #:*
https://github.com/bcgov/entity/issues/24695

24695  - EFT Warranty - Add in Supplier Site (location in AP) EFT refund screen

---

auth-api/src/auth_api/models/dataclass.py
auth-api/src/auth_api/models/org.py
auth-api/src/auth_api/resources/v1/org.py
auth-api/src/auth_api/services/org.py
auth-api/tests/unit/api/test_org.py

*Issue #:*
https://github.com/bcgov/entity/issues/21429
- search_orgs by member name or username support and members payload

21429 - staff account search for members

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/components/auth/account-settings/transaction/Transactions.vue
auth-web/src/components/auth/account-settings/transaction/TransactionsDataTable.vue
auth-web/src/components/datatable/BaseVDataTable.vue
auth-web/src/components/pay/eft/ShortNameRefund.vue
auth-web/src/composables/transactions-factory.ts
auth-web/src/models/transaction.ts
auth-web/src/services/payment.services.ts
auth-web/src/views/pay/eft/ShortNameRefundView.vue
auth-web/tests/unit/components/TransactionsDataTable.spec.ts

*Issue #:*
https://github.com/bcgov/entity/issues/24811

24811 - Remove transaction counts from transaction table

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/components/pay/eft/ShortNameRefund.vue
auth-web/src/routes/index.ts
auth-web/src/util/navigation.ts
auth-web/src/views/pay/eft/ShortNameRefundView.vue

*Issue #:*
https://github.com/bcgov/entity/issues/24226
Here's why I needed to add this:
`https://dev.account.bcregistry.gov.bc.ca/login?redirect=http%3A%2F%2Flocalhost%3A3000%2Fen-CA%2FmagicLink%3FnrId%3DNR%2B0521856%26phone%3D1112223333`
is being redirected to which is wrong:
`https://dev.account.bcregistry.gov.bc.ca/http://localhost:3000/magicLink?nrId=NR+0521856&phone=1112223333`
The idea is, I want to go back to the new BRD after login. I have a PR upcoming in the new BRD.
This is the finished product where I have both dashboards running locally (you can play it at 2x speed):
https://github.com/user-attachments/assets/8feb1836-900f-4f33-9a62-2249d9c2e084
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …

24226 - Redirect external links

---

auth-api/src/auth_api/resources/v1/activity_log.py
auth-api/src/auth_api/resources/v1/org.py
auth-api/src/auth_api/resources/v1/task.py
auth-api/src/auth_api/services/authorization.py
auth-api/src/auth_api/services/org.py
auth-api/src/auth_api/utils/roles.py
auth-api/src/auth_api/utils/user_context.py

*Issue #:*
https://github.com/bcgov/entity/issues/24651
- updates to support new keycloak group contact_centre_staff

24651 - updates for contact_centre_staff KC group

---

auth-api/src/auth_api/models/user.py
auth-api/src/auth_api/resources/v1/user.py
auth-api/src/auth_api/services/keycloak.py

Move staff check above GOV ACCOUNT USER

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/services/business.services.ts
auth-web/src/stores/business.ts
auth-web/src/util/constants.ts
auth-web/src/views/auth/staff/IncorporationSearchResultView.vue
auth-web/src/views/auth/staff/StaffDashboardView.vue
auth-web/tests/unit/views/StaffDashboard/SearchBusinessView.spec.ts

*Issue:*https://github.com/bcgov/entity/issues/24658 
- Added new filings search API call to fetch filing
- Extend search functionality to accept and handle filingID
- As per Sev, the code to handle auto-expanding the file does not exist yet in the new Business Dashboard but it will expect the filingID which we are passing as a param in the URL

24658 Implement Staff Search by Filing ID

---

auth-web/.eslintrc.js
auth-web/package-lock.json
auth-web/package.json
auth-web/src/components/auth/common/Product.vue
auth-web/src/components/auth/create-account/SelectProductService.vue
auth-web/src/resources/display-mappers/payment-type-display.ts
auth-web/src/services/codes.service.ts
auth-web/src/stores/org.ts
auth-web/src/views/auth/create-account/AccountSetupView.vue
auth-web/src/views/auth/create-account/non-bcsc/NonBcscAccountSetupView.vue

*Issue #:*
https://github.com/bcgov/entity/issues/24936

24936 - Product and Services tab update

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/components/auth/common/Product.vue
auth-web/tests/unit/components/Product.spec.ts

*Issue #:*
https://github.com/bcgov/entity/issues/21131

21131 - Update product description

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/routes/router.ts

*Issue #:*
https://github.com/bcgov/entity/issues/25147
[screen-capture.webm](https://github.com/user-attachments/assets/e0e61b06-3d59-4f63-903e-d6c1a40f81fb)
Will open the PR in business-ui shortly.

25147 - Changed the redirection link of the new BRD

---

auth-api/src/auth_api/exceptions/errors.py
auth-api/src/auth_api/models/product_subscription.py
auth-api/src/auth_api/models/task.py
auth-api/src/auth_api/resources/v1/org_products.py
auth-api/src/auth_api/services/products.py
auth-api/tests/unit/api/test_cors_preflight.py
auth-api/tests/unit/api/test_org_products.py
queue_services/account-mailer/poetry.lock
queue_services/auth-queue/poetry.lock

*Issue #:*
https://github.com/bcgov/entity/issues/25143
- Add ability to remove a product and clean up any pending tasks
- Re-adding a product previously approved will auto approve (no new task is created, will just activate product)
- New tests to for product removal and re-adding product from various states
- clean up on orgId format validation on org_products route (moved to function)

25143 - remove product / add previously approved product support

---

auth-web/.env.example

*Issue #:*
https://github.com/bcgov/entity/issues/25281
Sev @severinbeauvais, can you change the following please:
VUE_APP_BUSINESS_REGISTRY_URL="op://web-url/$APP_ENV/business-registry-ui/BUSINESS_REGISTRY_URL"
The values are now:
https://dev.business-registry-dashboard.bcregistry.gov.bc.ca/
https://test.business-registry-dashboard.bcregistry.gov.bc.ca/
https://www.business-registry-dashboard.bcregistry.gov.bc.ca/

25281 - Updated .env.example to use new BRD domain

---

auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
auth-web/src/components/auth/account-settings/team-management/InvitationsDataTable.vue
auth-web/src/components/auth/account-settings/team-management/MemberDataTable.vue
auth-web/src/components/auth/account-settings/team-management/PendingMemberDataTable.vue
auth-web/src/components/auth/account-settings/team-management/UserManagement.vue
auth-web/src/components/auth/common/ProductTOS.vue
auth-web/src/components/auth/common/StaffAccountsTable.vue
auth-web/src/components/auth/staff/account-management/StaffAccountManagement.vue
auth-web/src/components/auth/staff/account-management/StaffPendingAccountInvitationsTable.vue
auth-web/src/components/auth/staff/review-task/DownloadAffidavit.vue
auth-web/src/components/datatable/resources/index.ts
auth-web/src/routes/index.ts
auth-web/src/routes/router.ts
auth-web/src/stores/org.ts
auth-web/src/util/common-util.ts
auth-web/src/util/constants.ts
auth-web/src/views/auth/AccountSettings.vue
auth-web/src/views/auth/staff/ReviewAccountView.vue
auth-web/src/views/auth/staff/StaffDashboardView.vue

Removing this for now, so we can push out a build for monday.
Revert "24648- Enable new role support for contact_centre_staff (#3198)"
This reverts commit b673f895f487733ebc6fcdc2677f694305480434.

Revert contact staff changes for now

---

auth-web/package.json
auth-web/src/components/auth/common/ProductTOS.vue
auth-web/src/components/auth/staff/review-task/AccountInformation.vue
auth-web/src/views/auth/staff/StaffDashboardView.vue

*Issue #:*
https://github.com/bcgov/entity/issues/24648
Fixes for contact_centre_staff role:
Hiding business registry tile
Hiding staff personal property registry tile
Hiding Safe Email List Tile
Displaying Transaction records
Access type now can't be edited

24648 - contact_centre_staff role fixes

---

auth-api/migrations/README
auth-api/migrations/versions/2025_02_11_1893ddb6d071_.py

So it's consistent with DEV/TEST/PROD.

Add in migration for edit user

---

auth-web/src/components/auth/staff/continuation-application/HomeJurisdictionInformation.vue
auth-web/src/services/business.services.ts
auth-web/src/util/constants.ts
auth-web/tests/unit/components/HomeJurisdictionInformation.spec.ts

*Issue #:*
https://github.com/bcgov/entity/issues/24640
My name is Brandon Galli from Assets team.
- Updated download document component to support both Minio and Document Record Service.

Document Record Service - Cont. In Integration

---

auth-api/src/auth_api/services/keycloak.py
auth-api/src/auth_api/services/membership.py

Small bug fixes

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/views/auth/home/DecideBusinessView.vue
auth-web/tests/unit/views/DecideBusinessView.spec.ts

*Issue #:*
https://github.com/bcgov/entity/issues/25229
- Remove Learn More button in Business Registry Marketing page

25229 - Remove Learn More button in Business Registry Marketing page

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/components/auth/home/BcscPanel.vue

*Issue #:*
https://github.com/bcgov/entity/issues/26537
- update the link of Learn More button
- update the link of set up a mobile card
currently go to an 'Information moved' page.
We should update these links to go to [www.id.gov.bc.ca](http://www.id.gov.bc.ca/)

26537 - Update button links at the bottom of the marketing page

---

docs/docs/api_contract/auth-api-1.0.0.yaml

*Issue #:*
https://github.com/bcgov/entity/issues/26558

26558 - Expose affiliationInvitation routes in AUTH-API specification

---

auth-web/package-lock.json
auth-web/package.json
auth-web/src/components/auth/account-settings/team-management/InviteUsersForm.vue

*Issue #:*
https://github.com/bcgov/entity/issues/27336

27336 - Allow bcol admin invite other admins to a customer's account

---

auth-api/src/auth_api/services/affiliation_invitation.py
queue_services/account-mailer/src/account_mailer/email_templates/affiliation_invitation_email.html

*Issue #:*
https://github.com/bcgov/entity/issues/26898 
For Firms we now populate business_name from alternateNames, as legalName is often populated with org name for firms.

26898 - Update to how business name is obtained for firms

---

auth-api/src/auth_api/services/membership.py
auth-api/tests/unit/services/test_membership.py

*Issue #:*
https://github.com/bcgov/entity/issues/27075
- update PATCH to deactivate member to send auth event message

27075 - add auth even for PATCH that doesn't use deactivate member

---

auth-api/src/auth_api/services/affiliation_invitation.py
auth-api/tests/unit/services/test_affiliation_invitation.py

*Issue #:*
https://github.com/bcgov/entity/issues/28438
Modified the `enrich_affiliation_invitations_dict_list_with_business_data` method in `auth-api/src/auth_api/services/affiliation_invitation.py`.
When processing business details for an affiliation invitation, if the entity's `legalType` is "SP" or "GP", the code now calls `get_business_name_from_alternative_name`. This ensures that an `alternateName` (operating name), if available, is prioritized over the `legalName` for display.
**Updated the `get_business_name_from_alternative_name` method:**
- It now correctly handles different structures of the input `business_data`
- It can accept either the full business details object from the Legal API (which has a nested `business` key) or just the nested business information directly
- This …

28438 - Update Affiliation to display proper title
