bcgov/sbc-auth

- auth-web/src/components/auth/staff/account-management/StaffAccountManagement.vue
- auth-web/src/util/constants.ts
- auth-web/src/views/auth/staff/StaffDashboardView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/7596
- Changes for showing pending invitations for create_accounts role
- View and manage distribution codes for manage_gl_codes role.
> Changes for showing pending invitations for create_accounts role, and gl for manage_gl_codes role.

- auth-web/src/store/modules/user.ts
- auth-web/src/views/auth/create-account/DuplicateAccountWarningView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/6921
- Duplicate account warning view would display existing accounts in ascending order
- Update sbc header on switching account
> user settings sorting and updating header

- queue_services/account-mailer/src/account_mailer/email_templates/govm_approved_notification.html
- queue_services/account-mailer/src/account_mailer/email_templates/govm_rejected_notification.html
- queue_services/account-mailer/src/account_mailer/email_templates/nonbcsc_org_rejected_notification_email.html
*Issue #:*
https://github.com/bcgov/entity/issues/7582
- Remove gmail auto-link feature 
> fix for link

- auth-web/src/components/auth/common/Product.vue
- auth-web/src/components/auth/create-account/AccountTypeSelector.vue
- auth-web/src/components/auth/create-account/SelectProductService.vue
- auth-web/src/store/modules/org.ts
- auth-web/src/views/auth/create-account/non-bcsc/NonBcscAccountSetupView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/7533
* collapse on uncheck of product
* Reset account type on change of product
> Action Based Account setup changes#7533 product link

- auth-api/migrations/versions/e7f46c30d356_restricted_ppr.py
- auth-api/src/auth_api/utils/constants.py
*Issue #:*
https://github.com/bcgov/entity/issues/6848
RPRR product added
> RPRR product added

- auth-api/migrations/versions/a0198b1e2c51_ppr_default.py
- auth-api/migrations/versions/e7f46c30d356_restricted_ppr.py
> Migration issue fix

- auth-web/src/views/auth/home/DecideBusinessView.vue
*Issue #:*
bcgov/entity#6504
* Added some top margin to the Learn More Btn as per ux review.
> Added btn top margin

- auth-api/migrations/versions/08e1d49dfa1a_business_type_and_size.py
> Removing duplicate

- auth-api/migrations/versions/3818a89ddedf_add_tos_version_5.py
- auth-api/tests/unit/api/test_documents.py
- auth-api/tests/unit/models/test_documents.py
- auth-api/tests/unit/services/test_documents.py
- auth-api/tests/unit/services/test_user.py
- auth-api/tests/utilities/factory_utils.py
*Issue #:*
https://github.com/bcgov/entity/issues/7587
- Add version 5 Tos update
> 7587- Version 5 TOS content

- auth-web/src/components/auth/common/GLPaymentForm.vue
*Issue #:*
https://github.com/bcgov/entity/issues/7686
> Changing GL code validation to alphanumeric.

- auth-api/src/auth_api/services/affiliation.py
> Changes to support CC and ULC in affiliation

- auth-web/src/components/auth/common/AccountBusinessType.vue
*Issue #:*
https://github.com/bcgov/entity/issues/7782
> style for radio button

- auth-web/src/components/auth/manage-business/EntityManagement.vue
*Issue #:*
bcgov/entity#7540
* Added Name Request btn to Dashboard.
* Open NR App in a new tab.
> 7540 NameRequest Dashboard Btn

- auth-web/src/components/auth/common/AccountBusinessType.vue
- auth-web/tests/unit/components/AccountBusinessType.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/7782
- Reset org name while switching business type
> 7782 - Reset org name on business type change

- auth-api/src/auth_api/exceptions/errors.py
- auth-api/src/auth_api/resources/org.py
- auth-api/src/auth_api/utils/role_validator.py
- auth-api/tests/unit/api/test_org.py
- auth-api/tests/utilities/factory_scenarios.py
*Issue #:*
https://github.com/bcgov/entity/issues/7936
Added a new decorator so that not allowed access is supported.
> Added a new decorator for role validation

- auth-web/src/assets/scss/base.scss
- auth-web/src/components/auth/common/AccountBusinessType.vue
*Issue #:*
https://github.com/bcgov/entity/issues/7782
> loading stepper css fix

- auth-api/src/auth_api/schemas/contact.py
- auth-api/src/auth_api/schemas/org.py
- auth-api/src/auth_api/schemas/schemas/contact_response.json
- docs/docs/api_contract/auth-api-1.0.0.yaml
*Issue #:*
https://github.com/bcgov/entity/issues/7773
> Changes to include mailing address information for org

- auth-api/src/auth_api/config.py
- auth-api/src/auth_api/services/affiliation.py
*Issue #:*
https://github.com/bcgov/entity/issues/7981
> 7981 - Changing the supported NR types to config.

- auth-web/src/assets/scss/base.scss
- auth-web/src/components/auth/common/AccountBusinessType.vue
> Release to main merge

- auth-api/tests/unit/utils/test_role_validator.py
> A few tests added

- auth-web/src/routes/index.ts
- auth-web/src/store/modules/codes.ts
- auth-web/src/util/constants.ts
and code table name
*Issue #:*
https://github.com/bcgov/entity/issues/7781
code table name corrected
added redirection logic
> Fixed redirection and code table name

- auth-api/src/auth_api/config.py
- auth-api/src/auth_api/models/task.py
- auth-api/src/auth_api/resources/task.py
- auth-api/src/auth_api/services/org.py
- auth-api/src/auth_api/services/task.py
- auth-api/tests/unit/api/test_task.py
- auth-api/tests/unit/models/test_task.py
- auth-api/tests/unit/services/test_task.py
- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/staff/account-management/StaffPendingAccountsTable.vue
- auth-web/src/components/auth/staff/account-management/StaffRejectedAccountsTable.vue
- auth-web/src/models/Task.ts
- auth-web/src/services/task.services.ts
- auth-web/src/store/modules/task.ts
- auth-web/src/util/constants.ts
- auth-web/src/views/auth/staff/ReviewAccountView.vue
> few fixes on task related screens

- auth-web/src/views/auth/staff/ReviewAccountView.vue
> small fix for disabled buttons

- auth-web/src/components/auth/common/AccountBusinessType.vue
> Remove symbol from AccoutBusinessType component

- auth-web/src/components/auth/staff/account-management/StaffPendingAccountsTable.vue
- auth-web/src/components/auth/staff/review-task/AccessRequestModal.vue
- auth-web/src/views/auth/staff/ReviewAccountView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/7780
>  BCeID Affidavit: Staff Review Changes

- auth-web/src/components/auth/common/AccountBusinessType.vue
- Remove hide-details to fix spacing issue
> remove hide-details from select account type

- auth-api/src/auth_api/schemas/schemas/mailing_address.json
- auth-web/src/store/modules/org.ts
*Issue #:*
https://github.com/bcgov/entity/issues/7737
- Capture and display delivery instructions
> bug fix for delivery instructions

- auth-api/migrations/versions/5397c5a5b0ca_staff_pending_status_permissions.py
*Issue #:*
https://github.com/bcgov/entity/issues/7781
- Added migration script to add pending staff review action in permissions table
> 7781 - pending staff review migration

- auth-api/src/auth_api/services/task.py
> fix for on hold reason

- auth-api/src/auth_api/services/org.py
*Issue #:*
https://github.com/bcgov/entity/issues/6270
> delete endpoint pass service token to pay-api

- auth-api/src/auth_api/services/org.py
> Fix issue with deactivate

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/assets/scss/theme.scss
- auth-web/src/components/auth/manage-business/AffiliatedEntityTable.vue
- auth-web/src/components/auth/manage-business/EntityManagement.vue
- auth-web/src/store/modules/org.ts
- auth-web/src/util/constants.ts
*Issue #:* bcgov/entity#7740
* Implemented the Framework component for a new affiliation table.
* Added Dynamic columns/headers selector.
* Feature flagged (although manually disabled for precaution) section to handle new table in dashboard view.
* Minor Style updates.
> Business Table Framework

- auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
*Issue #:*
https://github.com/bcgov/entity/issues/6270
Fix dissolve buttons 
> Fix dissolve buttons not shown to staff

- auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
> Fix dissolve buttons not shown to staff (#1721)

- auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
*Issue #:*
Put org returns invalid input issue 
- Remove name from request json object
> fix put org issue

- auth-api/src/auth_api/services/org.py
- auth-api/tests/unit/api/test_bulk_user.py
- auth-api/tests/unit/api/test_org.py
- Added branch name update code
- Fixed an old broken test
The lint errors are fixed in another PR.
> added branch name duplicate check

- auth-web/src/routes/index.ts
*Issue #:*
https://github.com/bcgov/entity/issues/7783
instead of accessing getter , i was accessing the state.Fixed it
> Fix for accessing getter

- auth-web/src/routes/index.ts
- auth-web/src/routes/router.ts
- auth-web/src/views/auth/TermsOfServiceView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/8001
1) Added a new redirect URI as a param to TOS flow.
2) Added redirection if its one of the redirectable uris [making it global will require lot of testing.]
> Added redirect URI to TOS flow to support reupload affidavit flow

- auth-web/src/locales/en.json
- auth-web/src/util/constants.ts
- auth-web/src/views/auth/AccountDeactivate.vue
*Issue #:*
https://github.com/bcgov/entity/issues/8218
https://github.com/bcgov/entity/issues/6914
- Adding correct error message for deactivate account based on error code
> 8218: Deactivate account error messages

- auth-web/src/components/auth/staff/account-management/StaffActiveAccountsTable.vue
*Issue #:*
https://github.com/bcgov/entity/issues/8354
>  Staff Dashboard: Pagination issue#8354

- auth-web/src/store/modules/org.ts
*Issue #:*
govm create issue
- No need to pass org name and branch while updting org during govm creation flow
> bug fix for govm create

- auth-api/src/auth_api/resources/org.py
- auth-api/src/auth_api/services/affidavit.py
- auth-api/src/auth_api/services/org.py
*Issue #:*
https://github.com/bcgov/entity/issues/8302
> Fixed bceid email names and some refactoring

- auth-web/src/routes/index.ts
*Issue #:*
https://github.com/bcgov/entity/issues/8001
> 8001-fix redirect issue.

- auth-web/src/components/auth/account-settings/statement/StatementsSettings.vue
- auth-web/src/components/auth/account-settings/transaction/Transactions.vue
- auth-web/src/models/Organization.ts
- auth-web/src/models/statement.ts
*Issue #:*
https://github.com/bcgov/entity/issues/8266
> 8266: Changes to match with schema changes (authAccountId -> accountId)

- queue_services/business-events-listener/src/business_events_listener/config.py
- queue_services/business-events-listener/src/business_events_listener/worker.py
- queue_services/business-events-listener/tests/integration/test_worker_queue.py
*Issue #:*
https://github.com/bcgov/entity/issues/8266
- Changes to support NR purchased with no accounts
> Changes to support NR purchased with no accounts

- queue_services/account-mailer/src/account_mailer/email_templates/resubmit_bceid_org.html
*Issue #:*
https://github.com/bcgov/entity/issues/8543
corrected the email id  as in the ticket.
> changed email id

- auth-api/src/auth_api/services/user_settings.py
- auth-api/tests/unit/api/test_user_settings.py
*Issue #:*
https://github.com/bcgov/entity/issues/7608
fixing to make it work with the web url
> Fix for wrong url

- queue_services/account-mailer/src/account_mailer/email_templates/resubmit_bceid_org.html
*Issue #:*
https://github.com/bcgov/entity/issues/8543
> improved the wordings

- auth-api/src/auth_api/schemas/account_payment_settings.py
- auth-api/src/auth_api/schemas/activity_log.py
- auth-api/src/auth_api/schemas/affidavit.py
- auth-api/src/auth_api/schemas/affiliation.py
- auth-api/src/auth_api/schemas/authorization.py
- auth-api/src/auth_api/schemas/base_schema.py
- auth-api/src/auth_api/schemas/contact.py
- auth-api/src/auth_api/schemas/contact_link.py
- auth-api/src/auth_api/schemas/documents.py
- auth-api/src/auth_api/schemas/entity.py
- auth-api/src/auth_api/schemas/invitation.py
- auth-api/src/auth_api/schemas/invitation_membership.py
- auth-api/src/auth_api/schemas/membership.py
- auth-api/src/auth_api/schemas/org.py
- auth-api/src/auth_api/schemas/product_subscription.py
- auth-api/src/auth_api/schemas/task.py
- auth-api/src/auth_api/schemas/user.py
- auth-api/src/auth_api/schemas/utils.py
- auth-api/src/auth_api/services/keycloak_user.py
- auth-api/tests/unit/api/test_user.py
- auth-web/src/components/auth/account-settings/team-management/InvitationsDataTable.vue
- auth-web/src/components/auth/account-settings/team-management/MemberDataTable.vue
- auth-web/src/components/auth/account-settings/transaction/TransactionsDataTable.vue
- auth-web/src/components/auth/common/DateRangeFilter.vue
- auth-web/src/util/common-util.ts
- auth-web/tests/unit/components/DateRangeFilter.spec.ts
- auth-web/tests/unit/util/common-util.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/8280
- Web changes for consistent date format
- API changes to return timezone string in response
> Changes for consistent date format in UI and backend response.

- auth-api/src/auth_api/services/affiliation.py
- auth-api/tests/unit/services/test_affiliation.py
> 8748 Removing the checks and filter we have now for manual affiliation of NR

- auth-web/Dockerfile
- auth-web/tests/unit/components/Transactions.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/8610
- Updated local Node to 14.17.6 and tested functionalities. 
- Updated Dockerfile and setup locally to test
- Fixed a unit test
> 8610 - Dockerfile Node upgrade

- auth-web/public/config/configuration.json
- auth-web/src/assets/scss/theme.scss
- auth-web/src/components/auth/manage-business/AffiliatedEntityTable.vue
- auth-web/src/components/auth/manage-business/EntityManagement.vue
- auth-web/src/components/auth/mixins/DateMixin.vue
- auth-web/src/models/business.ts
- auth-web/src/plugins/vuetify.ts
- auth-web/src/store/modules/business.ts
- auth-web/src/util/config-helper.ts
- auth-web/src/util/constants.ts
*Issue #:*
https://github.com/bcgov/entity/issues/8570
* Applied NR Target value to use in determine redirects and routing for supported and unsupported nrs.
* Updated Configuration for onestop and corporate online urls.
- This will require config map additions in Dev/Test/Prod for both onestop and corp online urls.** THIS WAS DONE BY RICHARD
- Includes the following UX updates from the document below.
https://docs.google.com/document/d/1CHcdQej6JofFdazuyIIGpMSfBq9BrfjpsgSCA2wGorA/edit?usp=sharing
> Applied target values for Unsupported NR Routing

- docs/docs/api_contract/auth-api-1.0.0.yaml
> Updating API Spec to resolve the client library issue

- auth-web/src/components/auth/manage-business/AffiliatedEntityTable.vue
- auth-web/src/components/auth/manage-business/EntityManagement.vue
- auth-web/src/util/constants.ts
*Issue #:*
https://github.com/bcgov/entity/issues/7985
* Implemented custom sorting for affiliation table values on each column.
* Some minor style adjustments.
> Custom Sorting for Affiliations Table

- docs/docs/api_contract/auth-api-1.0.0.yaml
> Cleaning up API Spec to work for partners

- auth-web/src/store/modules/business.ts
*Issue #:*
https://github.com/bcgov/entity/issues/8570
* Just added safety check to ensure only IA supported NR's are used to create Benefit Company IA's
> Implement safety check on supported ia's

- auth-api/src/auth_api/services/task.py
- auth-web/src/assets/scss/theme.scss
- auth-web/src/components/auth/staff/review-task/AccessRequestModal.vue
- auth-web/src/components/auth/staff/review-task/AccountStatus.vue
- auth-web/src/locales/en.json
- auth-web/src/services/task.services.ts
- auth-web/src/store/modules/codes.ts
- auth-web/src/store/modules/staff.ts
- auth-web/src/util/common-util.ts
- auth-web/src/util/constants.ts
- auth-web/src/views/auth/staff/ReviewAccountView.vue
- auth-web/tests/unit/components/AccessRequestModal.spec.ts
- auth-web/tests/unit/components/AccountStatus.spec.ts
- queue_services/account-mailer/src/account_mailer/email_processors/common_mailer.py
- queue_services/account-mailer/src/account_mailer/email_templates/resubmit_bceid_org.html
- queue_services/account-mailer/src/account_mailer/worker.py
*Issue #:*
https://github.com/bcgov/entity/issues/8664
1. UI changes
2. Account mailer changes
3. Updating test cases
> 8664 UI & Account mailer changes

- auth-api/migrations/versions/385a6a9ae5a8_rpt.py
- auth-api/src/auth_api/utils/constants.py
*Issue #:*
https://github.com/bcgov/entity/issues/8782
> Changes for Rural Property Tax.

- auth-web/src/components/auth/staff/review-task/AccessRequestModal.vue
- queue_services/account-mailer/src/account_mailer/auth_utils.py
- queue_services/account-mailer/src/account_mailer/config.py
- queue_services/account-mailer/src/account_mailer/email_processors/__init__.py
- queue_services/account-mailer/src/account_mailer/email_templates/reset_passcode.html
- queue_services/account-mailer/src/account_mailer/email_templates/resubmit_bceid_org.html
*Issue #:*
https://github.com/bcgov/entity/issues/8664
https://github.com/bcgov/entity/issues/8753
* 8664 UX feedback changes
* 8753 email update
> UX fix - 8664 and 9753 mail change

- auth-api/src/auth_api/__init__.py
- auth-api/src/auth_api/config.py
- auth-api/src/auth_api/models/entity.py
- auth-api/src/auth_api/models/org.py
- auth-api/src/auth_api/models/user.py
- auth-api/src/auth_api/resources/entity.py
- auth-api/src/auth_api/resources/user.py
- auth-api/src/auth_api/schemas/base_schema.py
- auth-api/src/auth_api/services/affiliation.py
- auth-api/src/auth_api/services/authorization.py
- auth-api/src/auth_api/services/entity.py
- auth-api/src/auth_api/services/invitation.py
- auth-api/src/auth_api/services/keycloak.py
- auth-api/src/auth_api/services/membership.py
- auth-api/src/auth_api/services/org.py
- auth-api/src/auth_api/services/rest_service.py
- auth-api/src/auth_api/services/user.py
- auth-api/src/auth_api/utils/user_context.py
- auth-api/src/auth_api/utils/util_logging.py
> Fixing lint issues

- auth-web/src/components/auth/staff/review-task/AccessRequestModal.vue
*Issue #:*
https://github.com/bcgov/entity/issues/8664
UI fixes for the modal
> UI fixes for the modal

- auth-web/src/components/auth/manage-business/AffiliatedEntityTable.vue
*Issue #:*
https://github.com/bcgov/entity/issues/9170
* Added entity type mappings for Type display.
> Entity Type Mapping for Table Display

- auth-web/package-lock.json
> updated package.json

- auth-api/migrations/versions/37dc988611c6_cso.py
- auth-api/src/auth_api/config.py
- auth-api/src/auth_api/services/invitation.py
*Issue #:*
https://github.com/bcgov/entity/issues/9206
- CSO codes
> 9206 : CSO codes

- queue_services/account-mailer/src/account_mailer/email_templates/govm_member_invitation_email.html
*Issue #:*
https://github.com/bcgov/entity/issues/8412
- Fixing the account name in email body
> 8412 : Fixing the account name in email body

- auth-web/src/components/auth/mixins/PaginationMixin.vue
- auth-web/src/util/constants.ts
- auth-web/src/views/auth/staff/StaffDashboardView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/8605
- Feature flag implementation
- Add config in 1password
**TASK**
1. Add **enable-fas-dashboard** feature flag in LD
2. Add "FAS_WEB_URL": "https://fas-dev.apps.silver.devops.gov.bc.ca/" in sbc-auth config
3. Add  "AUTH_WEB_URL": "https://dev.bcregistry.ca/business/auth/",
"FAS_WEB_URL": "https://fas-dev.apps.silver.devops.gov.bc.ca/" in FAS config settings
> 8605 - feature flag implementation

- auth-web/devops/vaults.json
> Update vaults.json to include fas url

- auth-web/src/util/constants.ts
- auth-web/src/views/auth/staff/StaffDashboardView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/8605
- Added Fas-search role in order to view fas search in staff dashboard
> 8605 - Added permissions to view FAS Search in Sbc-Auth

- auth-web/src/views/auth/staff/StaffDashboardView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/9124
- FAS accordion icon size change
> 9124 - FAS accordion ui updates

- auth-api/src/auth_api/services/api_gateway.py
*Issue #:*
https://github.com/bcgov/entity/issues/7071
> Corrected the action for revoking api key

- auth-api/migrations/versions/d00101759be4_view_dev_permissions.py
*Issue #:*
bcgov/entity#7071
new permission
> Added new permission

- auth-api/src/auth_api/services/org.py
- auth-api/tests/unit/api/test_org.py
- auth-api/tests/unit/services/test_org.py
> name change allowed

- auth-api/src/auth_api/config.py
- auth-api/src/auth_api/services/api_gateway.py
- auth-api/tests/unit/api/test_org_api_keys.py
*Issue #:*
https://github.com/bcgov/entity/issues/9800
- Create a sandbox payment account if URL is provided when sandbox key is generated first time for the account
> Changes to create a sandbox pay account when API key is generated first time for sandbox

- auth-web/src/assets/scss/overrides.scss
- auth-web/src/components/auth/account-settings/account-info/AccountDetails.vue
- auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
- auth-web/src/components/auth/account-settings/account-info/AccountMailingAddress.vue
*Issue #:*
https://github.com/bcgov/entity/issues/9561
> BC Registry: Change of Account Name#9561

- auth-web/src/components/auth/account-settings/advance-settings/DeveloperAccess.vue
> removed  create button

- auth-api/src/auth_api/services/authorization.py
*Issue #:*
https://github.com/bcgov/entity/issues/9801
> Changes to authorization for api gw key authorization.

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/assets/scss/base.scss
- auth-web/src/components/auth/account-settings/account-info/AccountDetails.vue
- auth-web/src/components/auth/account-settings/advance-settings/ExistingAPIKeys.vue
- auth-web/src/components/auth/common/AccountBusinessType.vue
- auth-web/src/components/auth/common/AccountLoginOptionPicker.vue
- auth-web/src/views/auth/AccountSettings.vue
*Issue #:*
https://github.com/bcgov/entity/issues/9561
https://github.com/bcgov/entity/issues/7071
> UX for 9561 and 7071 | reverted mdi icon version

- .github/workflows/account-mailer-cd.yml
- .github/workflows/account-mailer-ci.yml
- .github/workflows/activity-log-listener-cd.yml
- .github/workflows/activity-log-listener-ci.yml
- .github/workflows/business-events-listener-cd.yml
- .github/workflows/business-events-listener-ci.yml
- .github/workflows/events-listener-cd.yml
- .github/workflows/events-listener-ci.yml
- queue_services/events-listener/q_cli.py
- queue_services/events-listener/src/events_listener/config.py
*Issue #:*
- Fixing message in q_cli for lockAccount message.
- Adding CI, CD trigger for auth api models to q services
> Fixing message in q_cli for lockAccount message.

- auth-web/src/components/auth/account-settings/account-info/AccountDetails.vue
- auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
- auth-web/src/components/auth/account-settings/account-info/AccountMailingAddress.vue
- auth-web/src/components/auth/common/AccountBusinessType.vue
- auth-web/tests/unit/components/AccountDetails.spec.ts
- auth-web/tests/unit/components/AccountMailingAddress.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/9561
> Unit test  9561

- auth-web/src/store/modules/org.ts
default payment method changed to direct pay
*Issue #:*
> cc should be sent as direct pay 

- auth-web/src/store/modules/org.ts
> handled CC to direct pay in org update flow

- auth-web/src/components/auth/BceidInviteLanding.vue
- auth-web/src/components/auth/account-settings/team-management/InviteUsersForm.vue
- auth-web/src/components/auth/create-account/non-bcsc/AffidavitDownload.vue
- auth-web/src/components/auth/mixins/NextPageMixin.vue
- auth-web/src/util/constants.ts
- auth-web/src/views/auth/AcceptInviteLandingView.vue
- auth-web/src/views/auth/AcceptInviteView.vue
- auth-web/src/views/auth/TermsOfServiceView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/9326
* User accept invite
* page redirections
> Accept Invite and Upload Affidavit for new Admin#9326

- auth-api/migrations/env.py
- auth-api/migrations/versions/09dd4ea64775_verified_user.py
- auth-api/src/auth_api/models/membership.py
- auth-api/src/auth_api/models/user.py
- auth-api/src/auth_api/services/invitation.py
- auth-api/src/auth_api/services/task.py
- auth-api/src/auth_api/utils/enums.py
- auth-api/tests/unit/api/test_invitation.py
- auth-api/tests/utilities/factory_scenarios.py
- queue_services/account-mailer/src/account_mailer/email_templates/business_invitation_email_for_bceid.html
- queue_services/activity-log-listener/src/activity_log_listener/config.py
*Issue #:*
https://github.com/bcgov/entity/issues/9325
- Changes to invite BCeID admin
> Changes to invite BCeID admin

- auth-api/migrations/versions/09dd4ea64775_verified_user.py
> Fixing migration

- auth-web/devops/vaults.json
Signed-off-by: Kial Jinnah <kialj876@gmail.com>
*Issue #:*
https://github.com/bcgov/entity/issues/10040
- added to web url vault
> added ppr-ui url to auth web config

- auth-api/src/auth_api/utils/roles.py
*Issue #:*
https://github.com/bcgov/entity/issues/9326
- Adding pending staff review to settings
> Changes to support pending staff review for memberships

- auth-api/src/auth_api/config.py
- auth-api/src/auth_api/services/api_gateway.py
*Issue #:*
- Point to Sandbox and Prod gateway URL based on the environment
> Changes to key generation to point to different endpoint based on key environment

- queue_services/account-mailer/src/account_mailer/email_templates/business_invitation_email_for_bceid.html
> Admin invite email content fix

- auth-web/package-lock.json
- auth-web/package.json
*Issue #:*
https://github.com/bcgov/entity/issues/9290
> 9290-Mobile device warning

- auth-web/src/views/auth/TermsOfServiceView.vue
*Issue #:*
* removed multiple token from URL
> redirect URL token fix

- auth-api/src/auth_api/services/authorization.py
> Adding new product code check for super admin service accounts

- auth-api/src/auth_api/schemas/task.py
- auth-api/src/auth_api/services/api_gateway.py
- auth-api/src/auth_api/services/task.py
*Issue #:*
- Adding user to get tasks/id
> Adding user to get tasks/id

- auth-web/src/components/auth/common/PaymentMethods.vue
- auth-web/src/components/auth/create-account/AccountTypeSelector.vue
- auth-web/src/store/modules/org.ts
- auth-web/src/util/constants.ts
- auth-web/src/views/auth/ChooseAuthMethodView.vue
- auth-web/src/views/auth/create-account/AccountSetupView.vue
- auth-web/src/views/auth/create-account/non-bcsc/NonBcscAccountSetupView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/9332
* setting value to the session on click of check box for GOVN account 
* hiding DROWDWON for GVN account
* submission is pending in this PR
> Non-Ministry User Account creation#9332

- auth-api/src/auth_api/services/invitation.py
- auth-web/src/models/Task.ts
- auth-web/src/store/modules/staff.ts
- auth-web/src/util/constants.ts
- auth-web/src/views/auth/staff/ReviewAccountView.vue
- auth-web/tests/unit/services/task.service.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/9333
https://github.com/bcgov/entity/issues/10260
- Update staff review screen to handle the new task types - BCeID admin and GOVN types
- Update model service and store with the new changes
- Tests cases in next PR
> 9327 9333 - Staff Review screen UI WIP changes

- auth-web/src/components/auth/staff/review-task/AccessRequestModal.vue
- auth-web/src/plugins/vuetify.ts
- auth-web/src/util/constants.ts
- auth-web/src/views/auth/ChooseAuthMethodView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/9333
> Non-Ministry Account - BC Services Card Staff Review#9333

- auth-api/src/auth_api/config.py
- auth-api/src/auth_api/models/task.py
- auth-api/src/auth_api/services/affidavit.py
- auth-api/src/auth_api/services/task.py
- auth-api/tests/unit/models/test_task.py
- queue_services/account-mailer/src/account_mailer/email_templates/resubmit_bceid_admin.html
- queue_services/account-mailer/src/account_mailer/enums.py
- queue_services/account-mailer/src/account_mailer/worker.py
*Issue #:*
- Added update task logic for bceid admin
- Added on hold mail template in account-mailer
- Updated create-affidavit logic for reuploading bceid admin affidavit
> 9327 - backend changes

- auth-web/src/store/modules/org.ts
*Issue #:*
* added payment type for GOVM account ad ejv
> EJV payment method for GOVM account

- auth-api/src/auth_api/config.py
- auth-api/src/auth_api/services/org.py
- auth-web/src/routes/router.ts
> 9327 - change GOVM task action

- auth-api/src/auth_api/models/affidavit.py
- auth-api/src/auth_api/resources/user.py
- auth-api/src/auth_api/services/affidavit.py
- auth-api/tests/unit/api/test_user.py
*Issue #:*
https://github.com/bcgov/entity/issues/9333
> Adding GET affidavit by user endpoint

- auth-web/src/services/org.services.ts
- auth-web/src/services/user.services.ts
- auth-web/src/store/modules/staff.ts
>  Staff approves/reject the new admin#9327

- auth-api/src/auth_api/services/affidavit.py
*Issue #:*
https://github.com/bcgov/entity/issues/9333
> Fixing account_id on task clone

- auth-web/src/views/auth/create-account/non-bcsc/NonBcscAdminInviteSetupView.vue
- auth-web/tests/unit/views/NonBcscAdminInviteSetupView.spec.ts
>  Staff approves/reject the new admin#9327 | redirect after re-upload

- auth-web/src/views/auth/staff/ReviewAccountView.vue
> notary data was not reloading while account change

- docs/docs/api_contract/notify-api-1.0.0.yaml
*Issue #:*
https://github.com/bcgov/entity/issues/9936
- Fixing notify spec to make it up-to-date
> Notify API spec update

- auth-web/src/components/auth/account-settings/advance-settings/ExistingAPIKeys.vue
*Issue #:*
https://github.com/bcgov/entity/issues/10401
> API Key added to the developer settings view

- auth-web/src/components/auth/account-settings/team-management/InviteUsersForm.vue
- auth-web/src/components/auth/staff/SetupGovmAccountForm.vue
- auth-web/src/util/common-util.ts
- auth-web/tests/unit/components/InviteUsersForm.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/10254
> removed idir validation and replaced with email validation

- auth-api/src/auth_api/services/invitation.py
*Issue #:*
https://github.com/bcgov/entity/issues/9936
> Fixing affidavit flag on re-send invitation

- auth-web/src/components/auth/mixins/AccountMixin.vue
- auth-web/src/views/auth/AccountSettings.vue
> Authentication menu for govn uer

- auth-api/src/auth_api/models/org.py
- auth-api/src/auth_api/resources/org.py
- auth-api/src/auth_api/services/org.py
- auth-api/src/auth_api/services/validators/duplicate_org_name.py
- auth-api/tests/unit/models/test_org.py
- auth-api/tests/unit/services/test_org.py
- auth-web/src/components/auth/create-account/AccountCreateBasic.vue
- auth-web/src/components/auth/create-account/AccountCreatePremium.vue
- auth-web/src/services/org.services.ts
- auth-web/src/store/modules/org.ts
*Issue #:*
https://github.com/bcgov/entity/issues/10418
> changes for branch name in the duplicate call

- auth-api/src/auth_api/models/affidavit.py
- auth-api/src/auth_api/resources/user.py
- auth-api/src/auth_api/services/affidavit.py
- auth-api/src/auth_api/services/task.py
- auth-api/tests/unit/api/test_user.py
- auth-api/tests/utilities/factory_scenarios.py
- auth-web/src/services/user.services.ts
- auth-web/src/store/modules/staff.ts
- auth-web/src/util/constants.ts
- auth-web/src/views/auth/staff/ReviewAccountView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/9326
- Refactoring AffidavitService - retrieve affidavit based on user and task status
- Reject bceid admin task makes user as inactive
- UI updates 
> 9326 - Refactoring AffidavitService - retrieve affidavit based on user and task status

- auth-api/src/auth_api/models/org.py
- auth-api/tests/unit/api/test_org.py
*Issue #:*
bcgov/entity#10418
Because some branch is null and some branch is empty string , went for coalesce
> Branch name duplicate check made working

- auth-web/src/components/auth/account-settings/account-info/AccountAccessType.vue
- auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
- auth-web/src/locales/en.json
- auth-web/src/models/Organization.ts
- auth-web/src/services/org.services.ts
- auth-web/src/store/modules/org.ts
- auth-web/src/util/constants.ts
- auth-web/tests/unit/components/AccountAccessType.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/10255
- Added child component access type that handles access type switch feature
- Refactor org service to add org patch endpoint
- test cases
> 10255 - Add premium account to non ministry feature UI changes

- auth-web/src/components/auth/account-settings/account-info/AccountAccessType.vue
> access type pad  error message UX alignment

- auth-api/src/auth_api/services/invitation.py
- auth-api/src/auth_api/services/user.py
*Issue #:*
https://github.com/bcgov/entity/issues/10135
> Change to send user for account admin approval for verified BCeID users

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/models/user.ts
- auth-web/src/routes/router.ts
- auth-web/src/views/auth/create-account/AccountSetupLanding.vue
- auth-web/src/views/auth/create-account/AccountSetupView.vue
- auth-web/src/views/auth/create-account/non-bcsc/NonBcscAccountSetupView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/10135
* updated dynamic view for create account based on user role
* show/hide upload affidavit based on verification flag
>  Ability for Multiple Accounts for BCeID#10135

- auth-web/src/views/auth/AcceptInviteView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/10135
>  Ability for Multiple Accounts for BCeID#10135 | admin invite

- auth-web/src/components/auth/create-account/AccountCreateBasic.vue
- auth-web/src/views/auth/AcceptInviteView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/10554
- Update current account session variable to handle multiple accounts
> 10554 - handle multiple account for single idir

- auth-web/devops/vaults.json
- auth-web/package-lock.json
- auth-web/package.json
- auth-web/public/config/configuration.json
- auth-web/src/App.vue
- auth-web/src/resources/BreadcrumbResources.ts
- auth-web/src/routes/router.ts
- auth-web/src/util/config-helper.ts
- auth-web/src/views/auth/AccountSettings.vue
- auth-web/src/views/auth/UserProfileView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/10747
* Added configuration for BCROS Home Url
* Updated Home Crumb for non-staff
*NOTE:* - The updated routes require additional in configuration in DEV, TEST, PROD ENV's to add the following:
Dev = https://yfthig-dev.web.app/
Test = https://www.bcregistry.daxiom.ca/
Prod = https://www.bcregistry.gov.bc.ca/
> Updated Breadcrumbs and redirects

- auth-api/src/auth_api/services/products.py
> Adding get product for USER role as well

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/create-account/UserProfileForm.vue
- auth-web/src/routes/router.ts
*Issue #:*
https://github.com/bcgov/entity/issues/10751
* Updated redirect on 'Cancel' action from 'Edit Profile' page
* Updated home route when on the MyBusinessRegistry table to be dynamic based on role
> Updated Navigations for Edit Profile and staff

- queue_services/account-mailer/src/account_mailer/email_templates/bcol_refund_request_email.html
*Issue #:*
https://github.com/bcgov/entity/issues/10851
> 10851: Fixing key in refund email to transaction id

- auth-api/migrations/versions/8770c44d3d66_rtmp_corp_type.py
- queue_services/account-mailer/requirements.txt
- queue_services/activity-log-listener/requirements.txt
- queue_services/business-events-listener/requirements.txt
- queue_services/events-listener/requirements.txt
*Issue #:*
https://github.com/bcgov/entity/issues/10737
> 10737 : Adding new corp type to support Registrations.

- status-api/src/status_api/resources/whatsnew.py
*Issue #:*
https://github.com/bcgov/entity/issues/9811
1. The whatsnew endpoint should output json object.
> Fixed load json value issue.

- auth-web/src/components/auth/account-settings/transaction/Transactions.vue
*Issue #:*
https://github.com/bcgov/entity/issues/10867
> added isLoading for the button to avoid double clicks

- auth-web/src/components/auth/account-settings/payment/AccountPaymentMethods.vue
- auth-web/src/components/auth/common/PaymentMethods.vue
Refactor to accomodate BCOL payment to GovN
> Refactor to accomodate BCOL payment to GovN

- auth-api/src/auth_api/models/user_settings.py
- auth-api/src/auth_api/schemas/schemas/user_settings_response.json
- auth-api/src/auth_api/schemas/user_settings.py
- auth-api/src/auth_api/services/user_settings.py
- auth-api/tests/unit/api/test_user_settings.py
- auth-api/tests/unit/services/test_user_settings.py
- docs/docs/api_contract/auth-api-1.0.0.yaml
*Issue #:*
https://github.com/bcgov/entity/issues/10476
> branch name added to user settings

- auth-web/package-lock.json
- auth-web/package.json
*Issue #:*
https://github.com/bcgov/entity/issues/10476
* sbc-common-component version update 
> Expand account info drop down to include branch name#10476

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/manage-business/AffiliatedEntityTable.vue
- auth-web/src/models/business.ts
*Issue #:*
https://github.com/bcgov/entity/issues/11134
> 11134 moving business object into registration schema

- auth-web/package-lock.json
- auth-web/src/store/modules/staff.ts
- auth-web/src/views/auth/staff/ReviewAccountView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/11098
- Modify reviewAccount component to approve/reject onhold affidavit tasks
> 11098 - UI changes for allowing reject/approve onhold tasks

- auth-web/src/locales/en.json
- auth-web/src/views/auth/ChooseAuthMethodView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/10651
> 10651 - Add Govn confirmation dialog feature

- auth-api/src/auth_api/utils/account_mailer.py
- auth-api/tests/docker/docker-compose.yml
- queue_services/account-mailer/requirements.txt
- queue_services/account-mailer/requirements/prod.txt
- queue_services/account-mailer/tests/docker/docker-compose.yml
> fixed CI issue - keycloak sticky version

- auth-api/requirements/prod.txt
- auth-api/src/auth_api/schemas/schemas/org.json
- auth-api/tests/docker/docker-compose.yml
- auth-api/tests/unit/api/test_org.py
- auth-web/package-lock.json
- auth-web/src/components/auth/account-settings/payment/AccountPaymentMethods.vue
- auth-web/src/components/auth/common/LinkedBCOLBanner.vue
- auth-web/src/components/auth/common/PaymentMethods.vue
- auth-web/src/components/auth/create-account/BcolLogin.vue
*Issue #:*
https://github.com/bcgov/entity/issues/11277
> Bcol Edit feature

- auth-api/src/auth_api/services/org.py
> fix name getting updated on bcol updates

- auth-web/src/components/auth/common/SearchFilterInput.vue
> date format issue in statement

- auth-web/nginx.conf
*Issue #11488
https://github.com/bcgov/entity/issues/11488
updated nginx.conf  content security policy to in include  *.googleapis.com
> 11488_updated_nginx_csp

- auth-web/package-lock.json
- auth-web/package.json
*Issue #:* https://github.com/bcgov/entity/issues/10940
Update the phone number and email on the system error page.
> Update common components version to 2.4.43.

- auth-web/src/components/auth/create-account/SelectProductService.vue
*Issue #:*
https://github.com/bcgov/entity/issues/11778
* type fix
>  BUG Typo on live site - Step 1 original Account Set up screen

- auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
*Issue #:*
https://github.com/bcgov/entity/issues/11027
Watch not being triggered in child component, after a prop has been updated. 
> 11027 - Account Name is not Changing on UI

- auth-web/package-lock.json
- auth-web/package.json
> fas library version updated

- auth-web/package-lock.json
- auth-web/package.json
*Issue #:*
https://github.com/bcgov/entity/issues/11966
Adding text to footer
> 11966 - Add text to footer

- auth-web/package-lock.json
- auth-web/package.json
*Issue #:*
* FAS library updated
> FAS library update to latest

- auth-api/requirements.txt
- queue_services/account-mailer/requirements.txt
- queue_services/account-mailer/requirements/prod.txt
- queue_services/activity-log-listener/requirements.txt
- queue_services/activity-log-listener/requirements/prod.txt
- queue_services/business-events-listener/requirements.txt
- queue_services/business-events-listener/requirements/prod.txt
- queue_services/events-listener/requirements.txt
- queue_services/events-listener/requirements/prod.txt
*Issue #:*
https://github.com/bcgov/entity/issues/9990
9990 - Dependency fixes.
This is to fix the CD deployment of these services.
> 9990 - Dependency fixes 

- auth-web/src/components/auth/account-settings/transaction/TransactionsDataTable.vue
*Issue #:*
https://github.com/bcgov/entity/issues/12222
Add time to transactions table
> 12222 - PAD Transactions UI Enhancement - Add Time to Transactions table.

- auth-web/src/components/auth/account-settings/payment/AccountPaymentMethods.vue
*Issue #:*
https://github.com/bcgov/entity/issues/11741
Missing else in if condition.
> 11741 - Transition from BCOL to PAD 

- auth-web/src/components/auth/common/AccountBusinessType.vue
*Issue #:*
https://github.com/bcgov/entity/issues/11900
By pass the radio group, if we're a government account.
> 11900 - Minor check for govm Account for radio group.

- auth-api/migrations/versions/211deb552319_.py
- auth-api/requirements.txt
- auth-api/requirements/prod.txt
- auth-api/src/auth_api/utils/enums.py
> added business search product

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/common/Product.vue
- auth-web/src/util/constants.ts
*Issue #:*
https://github.com/bcgov/entity/issues/12492
> added ux for account selection

- auth-web/src/components/auth/mixins/NextPageMixin.vue
- auth-web/src/views/auth/SignoutView.vue
- auth-web/tests/unit/views/SignoutView.spec.ts
>  User Navigation after logging in#12301

- auth-web/src/components/auth/common/PaymentMethods.vue
- auth-web/src/components/auth/create-account/PaymentMethodSelector.vue
- auth-web/src/util/config-helper.ts
*Issue #:*
https://github.com/bcgov/entity/issues/12610
Allow BCOL for PREMIUM_UNLINKED accounts.
> 12610 - Allow BCOL for PREMIUM_UNLINKED accounts.

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/assets/scss/theme.scss
- auth-web/src/components/auth/common/ModalDialog.vue
- auth-web/src/components/auth/manage-business/AddBusinessForm.vue
- auth-web/src/components/auth/manage-business/AddNameRequestForm.vue
- auth-web/src/components/auth/manage-business/Certify.vue
- auth-web/src/components/auth/manage-business/EntityManagement.vue
- auth-web/src/util/common-util.ts
- auth-web/src/views/auth/staff/StaffDashboardView.vue
- auth-web/tests/unit/components/AddBusinessForm.spec.ts
- auth-web/tests/unit/components/Certify.spec.ts
- auth-web/tests/unit/views/SearchBusinessView.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/12172
- updated "add business" blurb
- deleted input white background override
- updated "add business" form
- updated "add name request" form
- added Certify component
- added a common util method
- updated and cleaned up staff dashboard view
- changed some "data-test" props to classnames or ids
- added unit tests for AddBusinessForm scenarios
- added unit test for Certify
- fixed other unit tests
- app version = 1.0.6
**See ticket for sample screenshots.**
> 12172 Updated Add Business component, etc for firms

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/public/config/configuration.json
- auth-web/src/util/config-helper.ts
- auth-web/src/util/constants.ts
*Issue #:*
https://github.com/bcgov/entity/issues/12565
Update package.json and package-lock.json to use new sbc-common-components.
> 12565 - Logout not clearing Siteminder cookies

- auth-web/devops/vaults.json
- auth-web/src/util/config-helper.ts
*Issue #:*
https://github.com/bcgov/entity/issues/12565
Add in Vault environment variable
+ Conditionally add SiteminderLogoutUrl.
> 12565 - Add in missing Vault environment variable

- auth-api/devops/vaults.json
- auth-api/src/auth_api/config.py
- auth-api/src/auth_api/resources/org.py
- auth-api/src/auth_api/services/affiliation.py
- auth-api/tests/unit/services/test_affiliation.py
- auth-api/tests/utilities/factory_scenarios.py
- auth-api/tests/utilities/factory_utils.py
*Issue #12303
https://github.com/bcgov/entity/issues/12303
Added the party validation for firms (SP/GP)
Updated tests
> Affiliate SP/GP

- auth-api/devops/vaults.json
> Moved legal api to API vault

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/manage-business/EntityManagement.vue
*Issue #:* /bcgov/entity#12706
- UXA background color opacity fix as requested in 12706 to match tooltip background color opacity in namex
- App version  = 1.0.11
> 12706 Change tool tip opacity

- auth-web/src/registerServiceWorker.ts
- auth-web/vue.config.js
*Issue #:*
https://github.com/bcgov/entity/issues/12821
Different way of solving https://github.com/bcgov/sbc-auth/pull/2010
> 12821 - Tweak service worker - Add in cache.keys() delete.

- queue_services/account-mailer/requirements.txt
- queue_services/account-mailer/src/account_mailer/email_processors/common_mailer.py
- queue_services/account-mailer/src/account_mailer/email_templates/pad_invoice_email.html
- queue_services/account-mailer/src/account_mailer/worker.py
- queue_services/account-mailer/tests/integration/test_worker_queue.py
*Issue #:*
https://github.com/bcgov/entity/issues/11777
11777 - Fixes for invoice date being incorrect when queue is backed up 
> 11777 - Fixes for invoice date being incorrect when queue is backed up 

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/create-account/UserProfileForm.vue
*Issue #:*
https://github.com/bcgov/entity/issues/12929
* redirect fix
> Page not found after updating Profile#12929

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/public/config/configuration.json
- auth-web/src/models/request-tracker.ts
- auth-web/src/routes/router.ts
- auth-web/src/services/business.services.ts
- auth-web/src/store/modules/business.ts
- auth-web/src/util/config-helper.ts
- auth-web/src/util/constants.ts
- auth-web/src/views/auth/staff/AdminDashboardView.vue
- auth-web/tests/unit/views/AdminDashboardView.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/12786
- Staff with admin edit permission can access this url and request for a new business number
> 12786 Administrative BN

- auth-api/src/auth_api/services/activity_log.py
- auth-web/src/services/payment.services.ts
- auth-web/src/store/modules/org.ts
- auth-web/src/views/pay/PaymentView.vue
> Fixes for payment, and activity log.

- auth-api/src/auth_api/services/activity_log.py
- auth-web/src/components/pay/PayWithCreditCard.vue
- auth-web/src/services/payment.services.ts
- auth-web/src/store/modules/org.ts
- auth-web/src/views/pay/PaymentView.vue
> Activity log fixes v2

- auth-api/src/auth_api/services/activity_log.py
- auth-api/src/auth_api/services/affiliation.py
- auth-api/src/auth_api/utils/enums.py
- auth-api/tests/unit/api/test_activity_log.py
*Issue #:*
https://github.com/bcgov/entity/issues/10683
> 10683 - More activity log fixes

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/manage-business/EntityManagement.vue
*Issue #:* /bcgov/entity#13132
- updated "add an existing business" dialog text
- app version = 1.0.18
> 13132 Updated "add an existing business" dialog text

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/common/ModalDialog.vue
- auth-web/src/components/auth/manage-business/AddBusinessDialog.vue
- auth-web/src/components/auth/manage-business/EntityManagement.vue
- auth-web/tests/unit/components/AddBusinessDialog.spec.ts
*Issue #:* /bcgov/entity#12983
- fixed ESC key in ModalDialog
- changed AddBusinessForm to AddBusinessDialog
- updated Add Business Dialog to have v-card-actions and be scrollable
- renamed unit test
- app version = 1.0.19
> 12983 Improved Add Business Dialog scrolling

- auth-web/devops/vaults.json
- auth-web/public/config/configuration.json
- auth-web/src/util/config-helper.ts
- auth-web/src/views/auth/staff/StaffDashboardView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/13296
> added reg serch link to staff dashboard

- auth-web/package-lock.json
- auth-web/package.json
*Issue #:* bcgov/entity#13154
- updated sbc-common-components import to 3.0.1
- app version = 1.1.0
> 13154 Updated sbc-common-components import

- auth-web/src/components/auth/common/LearnMoreButton.vue
- auth-web/src/components/auth/home/BcscPanel.vue
- auth-web/src/components/auth/home/InfoStepper.vue
- auth-web/src/components/auth/home/NameRequestButton.vue
- auth-web/src/components/auth/manage-business/EntityManagement.vue
- auth-web/src/views/auth/home/HomeView.vue
- auth-web/src/views/auth/home/IncorpOrRegisterView.vue
- auth-web/src/views/auth/home/MaintainBusinessView.vue
- auth-web/src/views/auth/home/RequestNameView.vue
- auth-web/tests/unit/views/HomeView.spec.ts
- auth-web/tests/unit/views/IncorpOrRegisterView.spec.ts
- auth-web/tests/unit/views/MaintainBusinessView.spec.ts
*Issue #:*
https://github.com/bcgov/entity/13253
- update auth web buttons according to the [new design UI](https://projects.invisionapp.com/share/5C12X9U7RUJT#/screens/468822174)
> 13253 Auth Web - Update Marketing Page Buttons

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/home/BcscPanel.vue
- auth-web/src/views/auth/home/HomeView.vue
- auth-web/src/views/auth/home/IncorpOrRegisterView.vue
- auth-web/src/views/auth/home/RequestNameView.vue
- auth-web/tests/unit/views/IncorpOrRegisterView.spec.ts
- auth-web/tests/unit/views/RequestNameView.spec.ts
*Issue #:* https://github.com/bcgov/entity/issues/13152
- added new look to "Register or Incorporate" component 
- added unit tests
- fixed typo
- design UI link: [here](https://projects.invisionapp.com/share/5C12X9U7RUJT#/screens/468822175) and [here](https://projects.invisionapp.com/share/5C12X9U7RUJT#/screens/468822176)
> 13152 Auth Web - Marketing Page Updates

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/views/auth/home/IncorpOrRegisterView.vue
- auth-web/src/views/auth/home/MaintainBusinessView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/13152
- updated a few text tweaks as request
> 13152 Auth Web - Marketing Page Updates & Tweaks

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/views/auth/home/IncorpOrRegisterView.vue
- auth-web/src/views/auth/home/MaintainBusinessView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/13152
- more text tweaks 
> 13152 Auth Web - Marketing Page Updates (More Tweaks)

- auth-web/src/util/constants.ts
- auth-web/src/views/auth/staff/StaffDashboardView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/13296
> added feature flag for bus search link

- queue_services/account-mailer/src/account_mailer/email_templates/business_invitation_email.html
- queue_services/account-mailer/src/account_mailer/email_templates/business_invitation_email_for_bceid.html
- queue_services/account-mailer/src/account_mailer/email_templates/dirsearch_business_invitation_email.html
- queue_services/account-mailer/src/account_mailer/email_templates/govm_business_invitation_email.html
- queue_services/account-mailer/src/account_mailer/email_templates/govm_member_invitation_email.html
*Issue #:*
https://github.com/bcgov/entity/issues/13501
- added note about browser support to invitation email templates 
- corrected formatting in govm_business_invitation_email template
> Invitation emails - add warning about which browsers are supported #13501

- auth-api/migrations/versions/e7c262b6f986_add_staff_org_types.py
> Add in org types.

- queue_services/account-mailer/src/account_mailer/email_templates/business_invitation_email.html
- queue_services/account-mailer/src/account_mailer/email_templates/business_invitation_email_for_bceid.html
- queue_services/account-mailer/src/account_mailer/email_templates/dirsearch_business_invitation_email.html
- queue_services/account-mailer/src/account_mailer/email_templates/govm_business_invitation_email.html
- queue_services/account-mailer/src/account_mailer/email_templates/govm_member_invitation_email.html
*Issue #: 13501*
https://github.com/bcgov/entity/issues/13501
- changed message from "Note: All browsers will work, except for Internet Explorer." to "Note: Internet Explorer cannot be 
used with our application. We recommend using the latest version of Microsoft Edge, Google Chrome, Mozilla Firefox or 
Apple Safari as your browser."
- added 25px of margin above and below note
> #13501 Invitation emails - add warning about which browsers are supported

- auth-web/.eslintrc.js
- auth-web/src/components/auth/CreateUserProfileForm.vue
- auth-web/src/components/auth/create-account/AccountCreatePremium.vue
- auth-web/src/components/auth/create-account/BcolLogin.vue
- auth-web/src/store/modules/org.ts
-Fix for the grant not showing the correct username
-Fix for the grant box not working first try
-Console error fix
> 13205 - Minor Fixes - Part 1

- auth-web/package.json
- auth-web/src/components/auth/staff/review-task/ProductFee.vue
*Issue #:*
https://github.com/bcgov/entity/issues/13622
> 13622 - Update package version, update product fee review.

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/manage-business/AddBusinessDialog.vue
- auth-web/tests/unit/components/AddBusinessDialog.spec.ts
*Issue #:* bcgov/entity#13810
- added proprietor/partner name example
> 13810 Added proprietor/partner name example

- auth-api/src/auth_api/models/org.py
- auth-api/src/auth_api/services/org.py
- auth-api/src/auth_api/services/products.py
- auth-api/src/auth_api/services/validators/payment_type.py
- auth-api/src/auth_api/utils/roles.py
- auth-api/tests/unit/services/test_org.py
- auth-api/tests/utilities/sqlalchemy.py
- auth-web/src/components/auth/account-settings/statement/Statements.vue
- auth-web/src/components/auth/account-settings/transaction/Transactions.vue
- Revert service level blocking
- Implement model level blocking (thanks Kial)
- Allow Staff and SBC Staff to add products
- Transaction and Statements needed a touchup in Auth-web
- Payment type check fix
*Issue #:*
https://github.com/bcgov/entity/issues/13248
> 13248 - Auth ORG changes

- auth-api/src/auth_api/version.py
- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/App.vue
*Issue #:*
https://github.com/bcgov/entity/issues/13861
Update sbc-common-components
> 13861 - Update SBC-Auth to SBC-common-components 3.0.3 to support BC Reg Staff.

- auth-api/src/auth_api/services/affiliation.py
*Issue #:*
https://github.com/bcgov/entity/issues/13245
Minor tweak
> 13245 - Allow staff to create a new business affiliation - Part 2.

- auth-web/src/components/auth/manage-business/EntityManagement.vue
- auth-web/src/components/auth/staff/PPRLauncher.vue
- auth-web/src/resources/BreadcrumbResources.ts
- auth-web/src/routes/router.ts
- auth-web/src/views/auth/staff/StaffDashboardView.vue
- auth-web/tests/unit/components/PPRLauncher.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/13246
> 13246 staff bus reg ux

- auth-api/src/auth_api/models/membership.py
- auth-api/src/auth_api/models/org.py
- auth-api/src/auth_api/resources/user.py
- auth-api/src/auth_api/services/membership.py
- auth-api/src/auth_api/services/user.py
- auth-api/tests/unit/api/test_user.py
*Issue #:*
https://github.com/bcgov/entity/issues/13662
Add/remove staff users to staff org on login
> 13662 - AUTH-API - Mechanism to add STAFF to new org type 

- auth-api/src/auth_api/models/affiliation.py
- auth-api/src/auth_api/resources/entity.py
- auth-api/src/auth_api/services/affiliation.py
- auth-api/tests/unit/services/test_affiliation.py
*Issue #:*
https://github.com/bcgov/entity/issues/13269
Relies on: https://github.com/lekshmimallika-aot/lear/tree/affiliations-fix
> 13269 - Changes to correct stale entities.

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/manage-business/AffiliatedEntityTable.vue
- auth-web/src/components/pay/PayWithCreditCard.vue
- auth-web/src/components/pay/PayWithOnlineBanking.vue
- auth-web/src/components/pay/PaymentCard.vue
*Issue #:* bcgov/entity#13487
- app version = 1.1.11
- changed a multi-line span to a div
- changed entity table height to CSS calculation to fit more height
- changed #fff to white
> 13487 Size the entity table according to window height

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/manage-business/AffiliatedEntityTable.vue
*Issue #:* bcgov/entity#13487
- revert dynamic table height (UI team has additional requirements - will implement in future)
- app version = 1.1.13
> 13487 Revert dynamic table height

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/manage-business/AffiliatedEntityTable.vue
- auth-web/tests/unit/components/AffiliatedEntityTable.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/13904
> added filtering to bus dashboard

- auth-web/src/components/auth/manage-business/AffiliatedEntityTable.vue
- auth-web/src/util/constants.ts
*Issue #:*
https://github.com/bcgov/entity/issues/13904
> fixed status issue

- auth-web/src/routes/router.ts
*Description of changes:* As described by Thor
> Fix for routing for staff.

- auth-web/src/assets/scss/layout.scss
- auth-web/src/views/auth/ChooseAuthMethodView.vue
> Create Account Page Updates

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/manage-business/AddNameRequestForm.vue
- auth-web/src/util/common-util.ts
- auth-web/tests/unit/util/common-util.spec.ts
*Issue #:* bcgov/entity#4622
- updated NR number v-text-field
- updated formatNrNumber()
- updated formatIncorporationNumber()
- updated validateNameRequestNumber()
- added/updated unit tests
- app version = 1.1.16
> 4622 Update NR input/validation

- auth-web/src/views/auth/ChooseAuthMethodView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/10673
> Text Updates - Create Account Page

- auth-api/src/auth_api/utils/api_gateway.py
*Issue #:*
https://github.com/bcgov/entity/issues/na
> added bus search mapper to api-key service accounts

- auth-api/src/auth_api/models/views/authorization.py
- auth-api/src/auth_api/services/authorization.py
- auth-api/tests/unit/services/test_authorization.py
Part of:
*Issue #:* https://github.com/bcgov/entity/issues/13962
- allow api-gw access to resources from the account level
> 13962 - manage if an api-gw account is accessing a resource

- auth-web/public/config/configuration.json
- queue_services/account-mailer/src/account_mailer/email_templates/business_invitation_email.html
> Small fix for email invitation

- auth-api/src/auth_api/models/dataclass.py
- auth-api/src/auth_api/models/task.py
- auth-api/src/auth_api/resources/task.py
- auth-api/tests/unit/api/test_task.py
- auth-api/tests/utilities/factory_utils.py
> 10728 - Add modified_by search for tasks

- auth-api/src/auth_api/services/entity.py
- auth-api/tests/unit/api/test_entity.py
- auth-api/tests/utilities/factory_utils.py
> Logging update

- auth-web/src/components/auth/common/DatePicker.vue
- auth-web/src/components/auth/staff/account-management/StaffPendingAccountsTable.vue
- auth-web/src/models/Task.ts
- auth-web/src/services/task.services.ts
- auth-web/src/util/constants.ts
> Staff dashboard - Filter for Pending Accounts 

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/staff/admin/BNRequestManager.vue
- auth-web/src/components/auth/staff/admin/ResubmitRequestDialog.vue
- auth-web/src/models/request-tracker.ts
- auth-web/src/routes/router.ts
- auth-web/src/util/constants.ts
- auth-web/src/views/auth/staff/AdminDashboardView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/14004
> 14004 BN Administrative - Improvement

- auth-web/src/components/auth/staff/account-management/StaffActiveAccountsTable.vue
- auth-web/src/components/auth/staff/account-management/StaffPendingAccountsTable.vue
*Issue #:*
Minor visual tweaks
> 10728 - Staff dashboard tweaks

- auth-web/src/assets/scss/layout.scss
- auth-web/src/views/auth/ChooseAuthMethodView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/10673
> 10673 - Account Creation Updates

- auth-api/src/auth_api/models/user.py
- auth-api/src/auth_api/services/user.py
- auth-api/tests/docker/docker-compose.yml
- auth-api/tests/unit/api/test_task.py
- auth-api/tests/unit/api/test_user.py
- auth-api/tests/unit/api/test_user_settings.py
- auth-api/tests/unit/services/test_affidavit.py
- auth-api/tests/unit/services/test_invitation.py
- auth-api/tests/unit/services/test_membership.py
- auth-api/tests/unit/services/test_org.py
- auth-api/tests/unit/services/test_product.py
- auth-api/tests/unit/services/test_reset.py
- auth-api/tests/unit/services/test_task.py
- auth-api/tests/unit/services/test_user.py
- auth-api/tests/unit/services/test_user_settings.py
- auth-api/tests/utilities/factory_scenarios.py
- auth-api/tests/utilities/factory_utils.py
> Fix duplicate user issue / users being deleted from keycloak and not being able to login

- auth-web/src/components/auth/staff/account-management/StaffRejectedAccountsTable.vue
- auth-web/src/models/Task.ts
- auth-web/src/services/task.services.ts
- auth-web/src/store/modules/task.ts
- auth-web/src/util/constants.ts
> Filters for rejected accounts tab in staff dashboard

- auth-web/src/components/auth/staff/account-management/StaffPendingAccountsTable.vue
- auth-web/src/components/auth/staff/account-management/StaffRejectedAccountsTable.vue
> Fix - Clear filter not clearing the date selection in the date picker

- auth-web/src/components/auth/staff/account-management/StaffPendingAccountsTable.vue
- auth-web/src/components/auth/staff/account-management/StaffRejectedAccountsTable.vue
> Fix - Incorrect Pagination data in the pending and rejected tasks table

- auth-api/src/auth_api/services/affiliation.py
*Issue #:*
https://github.com/bcgov/entity/issues/13333
> 13333 - Allow multiple NR Affiliations

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/assets/scss/base.scss
- auth-web/src/components/auth/account-settings/product/ProductPackage.vue
- auth-web/src/components/auth/common/Product.vue
- auth-web/src/components/auth/common/ProductTOS.vue
- auth-web/src/components/auth/manage-business/AffiliatedEntityTable.vue
- auth-web/src/components/auth/manage-business/EntityManagement.vue
- auth-web/src/components/auth/staff/review-task/ProductFee.vue
- auth-web/src/models/business.ts
- auth-web/src/store/modules/business.ts
- auth-web/src/store/modules/org.ts
- auth-web/src/util/constants.ts
- auth-web/src/views/auth/home/HomeView.vue
- auth-web/src/views/auth/home/IncorpOrRegisterView.vue
- auth-web/src/views/auth/staff/StaffDashboardView.vue
- auth-web/tests/unit/components/EntityManagement.spec.ts
- auth-web/tests/unit/components/Product.spec.ts
*Issue #:* bcgov/entity#14113
First commit:
- renamed enum productStatus -> ProductStatus
- fixed lint issues
Second commit:
- updated browserslist
Third commit:
- deleted obsolete LegalTypes enum
- used CorpTypes enum instead
- added enum values
- renamed some enum values
- renamed isTemporaryBusinessRegistration -> isTemporaryBusiness
- updated createNumberedBusiness to support different legal types
- deleted enable-sp-gp-dba FF
- added enable-bc-company FF
- added numbered IA names
- simplified some switch/if-else statements
- cleaned up some types
- moved filing body from Vue component to business module
- cleaned up createNamedBusiness()
- cleaned up createNumberedBusiness()
- misc cleanup
- app version = 1.1.19
Fourth commit:
- simplified isXXX() (various) …
> 14113 Updates for BC/CC/ULC IAs

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/pay/PaymentCard.vue
Display wasn't showing correctly
> Online banking fix

- auth-api/src/auth_api/models/dataclass.py
- auth-api/src/auth_api/models/task.py
- auth-api/src/auth_api/resources/task.py
- auth-api/tests/unit/api/test_task.py
- auth-api/tests/utilities/factory_utils.py
*Issue #: 10728*
- fixed end date filtering bug where invites with submitted dates equal to end date weren't in the query
- added sorting to date filtering 
> 10728 - fixed end date filtering bug

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/assets/scss/layout.scss
- auth-web/src/views/auth/ChooseAuthMethodView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/10673
Removing this until we get the go ahead to publish from John. 
> Remove account creation updates

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/mixins/PaginationMixin.vue
- auth-web/src/components/auth/staff/account-management/StaffPendingAccountsTable.vue
- auth-web/src/components/auth/staff/account-management/StaffRejectedAccountsTable.vue
- auth-web/src/store/modules/task.ts
> Small fix for pagination changing after search.

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/assets/scss/layout.scss
- auth-web/src/views/auth/ChooseAuthMethodView.vue
> Create Account Updates - DO NOT MERGE

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/manage-business/AffiliatedEntityTable.vue
- auth-web/src/models/business.ts
- auth-web/src/store/modules/business.ts
- auth-web/tests/unit/components/AffiliatedEntityTable.spec.ts
- auth-web/tests/unit/components/EntityManagement.spec.ts
*Issue #:* bcgov/entity#14213
- updated name(), type() and typeDescription()
- updated Business and CorpType interfaces to match API response
- deleted obsolete CCC->CC code
- updated unit tests
- app version = 1.1.22
> 14213 Removed workaround + used new corpSubType (IA/reg legal type)

- auth-api/Makefile
- auth-api/src/auth_api/services/membership.py
- auth-api/src/auth_api/services/org.py
- auth-api/src/auth_api/services/products.py
- auth-api/src/auth_api/services/task.py
- auth-api/src/auth_api/services/user.py
- auth-api/tests/unit/services/test_product.py
- auth-api/tests/unit/services/test_task.py
*Issue #:*
https://github.com/bcgov/entity/issues/14239
> 14239 - Update for 0 admin contacts

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/manage-business/EntityManagement.vue
- auth-web/tests/unit/components/EntityManagement.spec.ts
*Issue #14115
https://github.com/bcgov/entity/issues/14115
- implement dropdown on Incorporate Numbered Company
- Numbered Benefit Company
- Numbered Limited Company (feature flagged)
- Numbered Unlimited Liability Company (feature flagged)
- Numbered Community Contribution Company (feature flagged)
- add tooltips on each item, tooltips contents taken from namex
- add unit tests checking for new btns
> 14115 Numbered company drop-down

- auth-web/package-lock.json
- auth-web/package.json
*Issue #:* bcgov/entity#14331
- imported latest corp type module
- app version = 1.1.24
> 14331 Updated import

- auth-api/src/auth_api/exceptions/errors.py
- auth-api/src/auth_api/services/affiliation.py
- auth-api/tests/unit/api/test_org.py
*Issue #:*
https://github.com/bcgov/entity/issues/14317
> Affiliate Draft(Paid) NRs

- auth-web/src/components/auth/common/LinkedBCOLBanner.vue
- auth-web/src/components/auth/create-account/BcolLogin.vue
- auth-web/tests/unit/components/StaffRejectedAccountsTable.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/13205
Changes based on feedback
> 13205 - Minor fixes based on Ashna's feedback.

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/store/modules/business.ts
*Issue #:* bcgov/entity#14491
- fixed isConditionallyApproved()
- fixed enableIncorporation logic
- app version = 1.1.25
> 14491 Fixed conditionally approved bugs

- .github/workflows/account-mailer-cd.yml
- .github/workflows/account-mailer-ci.yml
- .github/workflows/activity-log-listener-cd.yml
- .github/workflows/activity-log-listener-ci.yml
- .github/workflows/auth-api-cd.yml
- .github/workflows/auth-api-ci.yml
- .github/workflows/auth-web-cd.yml
- .github/workflows/auth-web-ci.yml
- .github/workflows/business-events-listener-cd.yml
- .github/workflows/business-events-listener-ci.yml
- .github/workflows/events-listener-cd.yml
- .github/workflows/events-listener-ci.yml
- .github/workflows/pr-label-check.yml
- .github/workflows/restart_mailhog.yml
- .github/workflows/status-api-cd.yml
- .github/workflows/status-api-ci.yml
*Issue #:*
https://github.com/bcgov/entity/issues/14257
> 14257 - Update CI, so it wont fail on codecov issues.

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/staff/review-task/AccountInformation.vue
- auth-web/src/components/auth/staff/review-task/index.ts
- auth-web/src/main.ts
- auth-web/src/store/modules/org.ts
- auth-web/src/views/auth/staff/ReviewAccountView.vue
- auth-web/tests/unit/components/AccountInformation.spec.ts
- auth-web/tests/unit/test-utils/index.ts
- auth-web/tests/unit/test-utils/test-data/address.ts
- auth-web/tests/unit/test-utils/test-data/index.ts
- auth-web/tests/unit/test-utils/test-data/organization.ts
- auth-web/tsconfig.json
- auth-web/vue.config.js
*Issue #:*
https://github.com/bcgov/entity/issues/14337
> 14337 change govn access type

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/store/modules/org.ts
- auth-web/src/views/auth/staff/ReviewAccountView.vue
> 14337 small fix

- auth-web/src/views/auth/staff/ReviewAccountView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/14337
> access type change ignore previous selected fees

- docs/docs/database/bca_users_accounts.sql
Should allow anyone to run the report for BCA. 
> Add query for BCA.

- auth-web/src/components/auth/create-account/AccountTypeSelector.vue
*Issue #:*
https://github.com/bcgov/entity/issues/14753
> account create bceid govn bug fix

- auth-web/src/components/auth/common/NumberedCompanyTooltip.vue
- auth-web/src/views/auth/home/IncorpOrRegisterView.vue
- auth-web/src/views/auth/home/MaintainBusinessView.vue
- auth-web/tests/unit/views/IncorpOrRegisterView.spec.ts
- auth-web/tests/unit/views/MaintainBusinessView.spec.ts
- auth-web/tests/unit/views/RequestNameView.spec.ts
Reverts bcgov/sbc-auth#2183
So we can push the build out. Ketaki is on vacation.
> Revert "14172 - Update "How does it work?""

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/public/config/kc/keycloak.json
- auth-web/src/components/auth/manage-business/AddBusinessDialog.vue
- auth-web/src/components/auth/manage-business/AddNameRequestForm.vue
- auth-web/src/components/auth/manage-business/Certify.vue
- auth-web/tests/unit/components/AddBusinessDialog.spec.ts
- auth-web/tests/unit/components/Certify.spec.ts
*Issue #:* https://github.com/bcgov/entity/issues/14066
- added Authorization header
- renamed certifiedByNameXXX -> authorizationXXX
- updated layout/styles
- removed certify clause
- renamed currentUserName -> certifiedBy
- deleted obsolete UserModule code
- trimmed Certify By string
- updated unit tests
- updated keycloak json
- app version = 1.1.30
> 14066 Finished/cleaned up Authorization input

- auth-api/src/auth_api/schemas/schemas/business.json
- auth-api/src/auth_api/services/affiliation.py
- auth-api/src/auth_api/version.py
*Issue #:*
https://github.com/bcgov/entity/issues/14066
https://github.com/bcgov/entity/issues/14562
Minor tweaks to add more fields to affiliations. Also allow anyone to use the certified by name field.
> 14066/14562 - Minor tweaks for certified_by_name.

- auth-web/package-lock.json
- auth-web/package.json
https://github.com/bcgov/entity/issues/14796
> 14796 - Fix reference to fas-ui.

- auth-api/src/auth_api/resources/org.py
- auth-api/src/auth_api/services/affiliation.py
> Add certified by name to second affiliation call.

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/assets/scss/theme.scss
- auth-web/src/components/auth/common/NumberedCompanyTooltip.vue
- auth-web/src/views/auth/home/IncorpOrRegisterView.vue
- auth-web/src/views/auth/home/MaintainBusinessView.vue
- auth-web/tests/unit/views/IncorpOrRegisterView.spec.ts
- auth-web/tests/unit/views/MaintainBusinessView.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/14172
Update views based on UXpin attached. Also a tooltip for "BC based Company" expansion panel.  I had to separate the expansion panels as only one has tooltip.
> 14172-Update "How does it work?"

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/main.ts
- auth-web/src/routes/index.ts
- auth-web/src/routes/router.ts
*Issue #:*
https://github.com/bcgov/entity/issues/14309
Fix routing, so it works correctly
> 14309 - Fix routing navigation issues (EX double back button to navigate)

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/App.vue
- auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
*Issue #:*
https://github.com/bcgov/entity/issues/12753
Revert changes, they didn't pass QA.
> Revert - 12753 - AccountId in URL not working correctly 

- auth-web/tests/unit/components/FasSearchComponent.spec.ts
Small unit test to ensure the plugin is working correctly.
> Unit test to ensure FAS Search component gets rendered correctly.

- auth-api/src/auth_api/models/org.py
- auth-api/src/auth_api/models/task.py
- auth-api/src/auth_api/version.py
- auth-api/tests/unit/api/test_bcol_profiles.py
- auth-api/tests/unit/api/test_org.py
- auth-api/tests/unit/api/test_task.py
- auth-api/tests/unit/services/test_org.py
*Issue #:*
https://github.com/bcgov/entity/issues/11327
> remove rejected accounts from duplicate name search

- auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
> Fix update your account error message.

- auth-web/src/components/auth/common/PADInfoForm.vue
- auth-web/tests/unit/components/PADInfoForm.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/12322
> payment info qa/ux update

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/account-deactivate/DeactivateCard.vue
- auth-web/src/main.ts
- auth-web/src/plugins/i18n.ts
- auth-web/tests/unit/components/DeactivateCard.spec.ts
- auth-web/tests/unit/test-utils/test-data/MockI18n.ts
- auth-web/tests/unit/views/AccountDeactivate.spec.ts
*Issue #: 14886*
https://github.com/bcgov/entity/issues/14886
- Converted deactivateCard.vue into composition-api
- Updated VueI18n plugin to work with composition-api
- Updated deactivateCard tests with VueI18n plugin
> 14886 - converted deactivateCard.vue to composition-api

- auth-web/devops/vaults.json
*Issue #:* bcgov/entity#14429
- added hotjar vault to config
> 14429 Added hotjar vault

- auth-web/package-lock.json
- auth-web/package.json
*Issue #:*
https://github.com/bcgov/entity/issues/14099
Update sbc-common-components to work with NSF. 
> 14099 - Update sbc-common-components.

- auth-api/src/auth_api/models/user.py
- auth-api/src/auth_api/services/user.py
> To help troubleshoot keycloak guid login issue.

- auth-api/migrations/versions/3f79f6dcc58d_add_site_registry.py
- auth-api/src/auth_api/services/api_gateway.py
- auth-api/src/auth_api/services/authorization.py
- auth-api/src/auth_api/services/entity.py
- auth-api/src/auth_api/services/invitation.py
- auth-api/src/auth_api/services/membership.py
- auth-api/src/auth_api/services/products.py
- auth-api/src/auth_api/tracer.py
> Include hidden products for staff and SBC_STAFF.

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/account-settings/transaction/Transactions.vue
- auth-web/src/components/auth/account-settings/transaction/TransactionsDataTable.vue
- auth-web/src/resources/table-headers/transactions-table/headers.ts
- auth-web/tests/unit/components/InvitationsDataTable.spec.ts
- auth-web/tests/unit/components/PendingMemberDataTable.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/14376
> transaction table ux update

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/common/Product.vue
> Hide hidden products in account-info product page.

- auth-web/src/components/IconTooltip.vue
- auth-web/src/components/auth/account-settings/transaction/TransactionsDataTable.vue
> fixes for bottom variant

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/account-settings/transaction/Transactions.vue
- auth-web/src/components/auth/account-settings/transaction/TransactionsDataTable.vue
- auth-web/src/components/datatable/BaseVDataTable.vue
- auth-web/src/composables/transactions-factory.ts
- auth-web/src/views/auth/staff/StaffDashboardView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/15290
> transaction updates

- auth-web/src/components/auth/account-settings/transaction/TransactionsDataTable.vue
*Issue #:*
https://github.com/bcgov/entity/issues/15290
> fix icon click in transaction table

- auth-web/src/resources/table-headers/transactions-table/headers.ts
> added ejv to trxn drp down

- auth-api/src/auth_api/resources/org.py
- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/account-settings/account-info/AccountDetails.vue
- auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
*Issue #:*
https://github.com/bcgov/entity/issues/10628
> updated permissions for account editing

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/account-settings/account-info/AccountDetails.vue
- auth-web/src/components/auth/account-settings/account-info/AccountMailingAddress.vue
*Issue #:*
https://github.com/bcgov/entity/issues/10628
> 10628 qa 1

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/models/invoice.ts
*Issue #:*
https://github.com/bcgov/entity/issues/15387
> 15387 - add payment/refund date to invoice model

- queue_services/account-mailer/src/account_mailer/utils.py
- queue_services/account-mailer/src/account_mailer/worker.py
- queue_services/account-mailer/tests/docker/docker-compose.yml
- queue_services/account-mailer/tests/integration/test_worker_queue.py
*Issue #:*
https://github.com/bcgov/entity/issues/13879
Format currency to two decimal places.
> 13879 - Format currency to two decimal places.

- auth-api/src/auth_api/services/rest_service.py
Update rest_service.py - so it includes the endpoint in the error message
> Update rest_service.py - so it includes the endpoint in the error message

- auth-api/devops/vaults.json
- auth-api/requirements.txt
- auth-api/requirements/prod.txt
- auth-api/src/auth_api/config.py
- auth-api/src/auth_api/exceptions/__init__.py
- auth-api/src/auth_api/exceptions/errors.py
- auth-api/src/auth_api/models/affiliation.py
- auth-api/src/auth_api/resources/org.py
- auth-api/src/auth_api/services/affiliation.py
- auth-api/src/auth_api/services/rest_service.py
- auth-api/src/auth_api/utils/enums.py
- auth-api/src/auth_api/utils/roles.py
- auth-api/tests/unit/api/test_org.py
*Issue #:*
https://github.com/bcgov/entity/issues/15273
> 15273 - Get Affiliation Data from LEAR+NAMEX

- auth-api/src/auth_api/resources/org.py
- auth-api/src/auth_api/services/affiliation.py
- auth-api/src/auth_api/services/api_gateway.py
- auth-api/src/auth_api/services/rest_service.py
- auth-web/src/components/auth/manage-business/AddNameRequestForm.vue
https://github.com/bcgov/entity/issues/15593
> 15593 - Add in validation for name request number 

- auth-api/devops/vaults.json
*Issue #:*
https://github.com/bcgov/entity/issues/15273
> add needed vault item

- auth-api/devops/vaults.json
- auth-api/src/auth_api/config.py
*Issue #:*
https://github.com/bcgov/entity/issues/15273
> update config due to 1pass duplicate value across vaults

- queue_services/account-mailer/src/account_mailer/worker.py
*Issue #:*
https://github.com/bcgov/entity/issues/13879
https://github.com/bcgov/entity/issues/15609
Add format currency for NSF fee.
> 13879/15609 - Update worker.py to use format_currency for NSF.

- queue_services/account-mailer/src/account_mailer/email_templates/account_conf_over_email.html
*Issue #:*
https://github.com/bcgov/entity/issues/15609
Changes from feedback
> 15609 - Update account_conf_over_email.html

- auth-web/src/components/auth/staff/review-task/ProductFee.vue
*Issue #:*
https://github.com/bcgov/entity/issues/15293
Found while testing
> 15293 - Change dispatch -> commit.

- auth-web/src/components/auth/create-account/non-bcsc/AffidavitDownload.vue
Fixing a typo.
https://github.com/bcgov/entity/issues/15637
> 15637 - Update AffidavitDownload.vue

- auth-api/src/auth_api/services/affiliation.py
*Issue #:*
https://github.com/bcgov/entity/issues/15273
example:
```
{
"entities": [
{
"draftType": "TMP",
"identifier": "Tb4x1IydqO",
"legalType": "BC",
"nameRequest": {
"actions": [
{
"URL": null,
"entitiesFilingName": null,
"filingName": "Incorporation",
"learTemplate": null
},
{
"URL": null,
"entitiesFilingName": null,
"filingName": "Amalgamation",
"learTemplate": null
}
],
"applicants": [
{
"emailAddress": "1@1.com",
"phoneNumber": "1234567890"
}
],
"entityTypeCd": "CR",
"id": 2265604,
"legalType": "BC",
"names": [
{
"name": "KIALS TEST NAMESSS CORP.",
"state": "NE"
}
],
"natureBusinessInfo": "test",
"nrNum": "NR 2090111",
"requestTypeCd": "CR",
"stateCd": "APPROVED",
"target": "lear"
},
"nrNumber": "NR 2090111"
}
]
}
```
By submitting this pull request, I …
> updated tmp affiliation nr response structure

- .github/workflows/auth-web-cd-firebase.yml
- .github/workflows/auth-web-cd.yml
- auth-web/README.md
> Fixed CD issues.

- .github/workflows/auth-web-cd-firebase.yml
- .github/workflows/auth-web-cd.yml
- auth-web/Makefile
> Fixed the build issue of OCP

- auth-web/Makefile
- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/common/ProductFeeViewEdit.vue
- auth-web/src/components/auth/staff/review-task/ProductFee.vue
- auth-web/src/util/config-helper.ts
Small fix for fees for ESRA / other corp types.
Fix CI.
> Small fix for session storage for FAS.

- auth-api/requirements/dev.txt
- auth-api/src/auth_api/services/keycloak.py
- auth-api/src/auth_api/services/products.py
- auth-api/tests/conftest.py
- auth-api/tests/unit/services/test_keycloak.py
> Fix remove keycloak group code.

- auth-api/src/auth_api/services/keycloak.py
- auth-api/src/auth_api/services/products.py
- auth-api/tests/unit/services/test_keycloak.py
> Fix get group id.

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/App.vue
- auth-web/vue.config.js
*Issue #:*
https://github.com/bcgov/entity/issues/14375
> 14375 - Fix for footer to show application versions.

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/util/config-helper.ts
- auth-web/src/util/constants.ts
- auth-web/tests/unit/components/FasSearchComponent.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/15498
> 15498 - Update fas-UI version - update config helper

- auth-api/src/auth_api/services/keycloak.py
> Minor tweak to asyncio, cap to 40 (down from 100).

- auth-web/src/util/config-helper.ts
> Fix environment variable

- auth-web/src/components/auth/staff/review-task/AccessRequestModal.vue
- auth-web/src/util/config-helper.ts
- auth-web/src/views/auth/staff/ReviewAccountView.vue
> Hotfixes from PROD

- auth-web/src/components/auth/manage-business/AffiliatedEntityTable.vue
*Issue #:*
https://github.com/bcgov/entity/issues/15179
> fix remove business button issue

- auth-web/src/store/modules/business.ts
*Issue #:*
https://github.com/bcgov/entity/issues/15179
> fix remove business when identifier undefined

- db/backup/backup.yaml
> add pager duty alert key

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/common/PaymentMethods.vue
*Issue #:*
https://github.com/bcgov/entity/issues/15456
Changed wording when client (with BASIC) with online banking payment method.
> Changed wording for online banking payment method

- auth-api/requirements.txt
- queue_services/account-mailer/requirements.txt
- queue_services/activity-log-listener/requirements.txt
- queue_services/events-listener/requirements.txt
- queue_services/names-events-listener/requirements.txt
- status-api/requirements.txt
*Issue #: [15861](https://github.com/bcgov/entity/issues/15861)
> bump sentry sdk version

- auth-api/src/auth_api/models/affiliation.py
- auth-api/src/auth_api/resources/org.py
- auth-api/src/auth_api/services/affiliation.py
- auth-api/tests/unit/api/test_org.py
- auth-api/tests/unit/models/test_affiliation.py
- auth-api/tests/unit/services/test_affiliation.py
*Issue #:*
[16003](https://github.com/bcgov/entity/issues/16003)
1. add find affiliation by org id and business identifier function.
2. add service and endpoint.
3. add authorized check.
> Add a find affiliation endpoint.

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/main.ts
*Issue #: [15861](https://github.com/bcgov/entity/issues/15861)
> update sentry vue sdk version

- auth-web/src/store/modules/business.ts
*Issue #:*
https://github.com/bcgov/entity/issues/16086
> 16086 - fix a small type error

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/manage-business/AddNameRequestForm.vue
- auth-web/src/util/common-util.ts
- auth-web/tests/unit/components/AddNameRequestForm.spec.ts
- auth-web/tests/unit/util/common-util.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/14438
Re-write the NR number validation to make it consistent with other apps, such as business-edit-ui
> 14438 update validation on NR number

- auth-api/src/auth_api/services/affiliation.py
- auth-api/tests/unit/api/test_org.py
> Remove draft, if namerequest for it is consumed.

- auth-api/src/auth_api/services/affiliation.py
> Dashboard changes.

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/services/business.services.ts
- auth-web/tests/unit/components/DuplicateAccountWarningView.spec.ts
- auth-web/tests/unit/util/config-helper.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/16611
move to business v2 end point
> auth-web: move to business v2 end point

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/account-settings/team-management/MemberDataTable.vue
- auth-web/tests/unit/components/DuplicateAccountWarningView.spec.ts
- auth-web/tests/unit/util/config-helper.spec.ts
https://github.com/bcgov-registries/ops-support/issues/2719
Allow coordinators to remove other coordinators
> Allow coordinators to remove other coordinators

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/manage-business/BusinessLookup.vue
*Issue #:* https://github.com/bcgov/entity/issues/16621
- app version = 2.2.1
- appended spinner during searching
> 16621 implemented spinner during search

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/manage-business/BusinessLookup.vue
*Issue #:* https://github.com/bcgov/entity/issues/16227
- removed search list header (changed requirements)
- updated browerserslist
- app version = 2.2.2
> 16227 Removed business search list header

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/services/business-lookup.services.ts
- auth-web/tests/unit/services/business-lookup.service.spec.ts
*Issue #:* https://github.com/bcgov/entity/issues/16621
- app version = 2.2.3
- added entity type "SP"
- sorted the list
- updated unit tests
> 16621 Added "SP" to legal types to search for

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/services/business-lookup.services.ts
- auth-web/tests/unit/services/business-lookup.service.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/16621
> 16621 - Added SP to legal types to search for

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/assets/scss/theme.scss
- auth-web/src/components/auth/manage-business/AddNameRequestForm.vue
- auth-web/src/components/auth/manage-business/AffiliatedEntityTable.vue
- auth-web/src/components/auth/manage-business/EntityManagement.vue
- auth-web/src/components/datatable/BaseVDataTable.vue
- auth-web/src/store/modules/business.ts
- auth-web/tests/unit/components/EntityManagement.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/16723
- Show green background in table for 4 seconds if NR was successfully affiliated
- Show toast message for 4 seconds if NR was successfully affiliated
- Show error dialog if NR couldn't be added
- Update unit tests
> 16723 Update NR affiliation/error notifications

- auth-web/src/components/auth/manage-business/EntityManagement.vue
*Issue #:*
https://github.com/bcgov/entity/issues/16723
- a follow-up for PR #2381 
> Add missing type of nrNumber

- queue_services/account-mailer/src/account_mailer/email_templates/pad_invoice_email.html
*Issue #:*
https://github.com/bcgov/entity/issues/17106
> 17106 - Update pad_invoice_email.html

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/manage-business/AddBusinessDialog.vue
*Issue #:*
https://github.com/bcgov/entity/issues/17209
> 17209 - Staff fix business dashboard affiliations

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/manage-business/AddNameRequestForm.vue
- auth-web/src/components/auth/manage-business/EntityManagement.vue
- auth-web/src/components/auth/manage-business/SearchBusinessNameRequest.vue
- auth-web/tests/unit/components/AddNameRequestForm.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/15772
> 15772 - Name Request : Affiliation process using application information - no magic link

- auth-api/migrations/versions/2023_08_03_746771099983_add_nds_product_code.py
*Issue #:*
https://github.com/bcgov/entity/issues/17119
> 17119 - Add new Director Search product code

- queue_services/account-mailer/src/account_mailer/enums.py
*Issue #:16222 *
https://github.com/bcgov/entity/issues/16222 
- Synced enums between mailer and api
> #16222 - syncing template names between API and mailer.

- auth-api/src/auth_api/resources/org_products.py
- auth-api/src/auth_api/services/products.py
- auth-api/tests/unit/api/test_org_products.py
- auth-api/tests/utilities/factory_scenarios.py
*Issue #:*
https://github.com/bcgov/entity/issues/17119
> 17119 - Get hidden products option

- auth-api/migrations/versions/2023_08_15_98bee9969323_17243_mhr_qs_product_code_update.py
*Issue #:*
https://github.com/bcgov/entity/issues/17243
> 17243 update mhr qualified supplier product code descriptions

- auth-api/migrations/versions/2023_08_15_98bee9969323_17243_mhr_qs_product_code_update.py
- auth-api/requirements.txt
- auth-api/tests/unit/services/test_authorization.py
- queue_services/account-mailer/requirements.txt
- queue_services/activity-log-listener/requirements.txt
- queue_services/events-listener/requirements.txt
- queue_services/names-events-listener/requirements.txt
> Resync from main

- auth-web/src/store/modules/business.ts
Fix feature flax incorrectly set
> Fix feature flag incorrectly set

- auth-web/src/components/auth/manage-business/ManageBusinessDialog.vue
- auth-web/src/components/auth/manage-business/SearchBusinessNameRequest.vue
*Issue #15771
https://github.com/bcgov/entity/issues/15771
Change casing of "Passcode" to "passcode"
> 15771 - Change "Passcode" to "passcode"

- auth-web/.eslintrc.js
- auth-web/src/components/auth/manage-business/BusinessLookup.vue
- auth-web/src/components/auth/staff/account-management/StaffPendingAccountsTable.vue
- auth-web/src/components/auth/staff/account-management/StaffRejectedAccountsTable.vue
> Fix lint issues where it replaced with v-model, when it shouldn't have.

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/manage-business/AffiliatedEntityTable.vue
- auth-web/tests/unit/components/AffiliatedEntityTable.spec.ts
- auth-web/tests/unit/test-utils/test-data/affiliations.ts
*Issue #:*
https://github.com/bcgov/entity/issues/17396
- Fixed wordings for actions of cancelled NRs
- Updated unit tests
- App version = 2.3.1
> 17396 Cancelled NR have invalid actions

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/manage-business/AddNameRequestFormOld.vue
- auth-web/src/components/auth/manage-business/EntityManagement.vue
- auth-web/src/components/auth/manage-business/SearchBusinessNameRequest.vue
- auth-web/src/models/business-nr-lookup.ts
- auth-web/src/services/name-request-lookup.services.ts
- auth-web/src/store/modules/business.ts
- auth-web/tests/unit/services/name-request-lookup.service.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/16722
> 16722 - update NR affiliation modal

- auth-api/src/auth_api/services/affiliation_invitation.py
- queue_services/account-mailer/src/account_mailer/email_templates/affiliation_invitation_email.html
- queue_services/account-mailer/src/account_mailer/enums.py
> Sync with main

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/manage-business/EntityManagement.vue
- auth-web/src/routes/router.ts
*Issue #:*
https://github.com/bcgov/entity/issues/15740
> 15740 - fix atob issue

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/vite.config.js
> Put in plugin to allow for "." in url for localhost.

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/manage-business/EntityManagement.vue
*Issue #:*
https://github.com/bcgov/entity/issues/15740
> 15740 - fix bug when url not magic link

- auth-api/src/auth_api/services/affiliation_invitation.py
- auth-api/tests/unit/services/test_affiliation_invitation.py
*Issue #:*
https://github.com/bcgov/entity/issues/1579
- fix double slashes in url
- handling for context path is if it not present
> 15769 - affiliation invitation - fix email accept token url

- auth-web/src/components/auth/manage-business/EntityManagement.vue
- auth-web/src/routes/router.ts
*Issue #:*
https://github.com/bcgov/entity/issues/15740
> 15740 - Fix for url decode #2

- auth-web/src/components/auth/manage-business/AddNameRequestForm.vue
*Issue #:*
https://github.com/bcgov/entity/issues/15772
> 15772_fix - NR text change

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/main.ts
- auth-web/src/views/auth/home/HomeView.vue
(cherry picked from commit 630b9b55ac362a36c170e0ba38969376b5c0a3ee)
Fix, see comment in code - regarding composition-api toRefs returning .value instead of expanding .value.
> Fix intermittent pinia/composition-api issues.

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/manage-business/StartNewBusinessHelp.vue
*Issue #:*
https://github.com/bcgov/entity/issues/17029
Fix based on Yui's observations.
Before:
After fix:
> 17029 - update sub-header text color

- auth-web/src/components/auth/manage-business/AffiliatedEntityTable.vue
- auth-web/src/models/affiliation.ts
- auth-web/src/stores/business.ts
- auth-web/tests/unit/components/AffiliatedEntityTable.spec.ts
> AUTH-WEB - Remove affiliation invitation from main branch.

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/manage-business/StartNewBusinessHelp.vue
*Issue #:*
Based on Janis's recent comment, open link to the Business Structures Wizard open in a new tab
> 17029 - Open link to the Business Structures Wizard open in a new tab

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/services/business.services.ts
*Issue #:*
https://github.com/bcgov/entity/issues/16611
> Auth-web: Update business v2 endpoints

- auth-api/src/auth_api/services/affiliation.py
*Issue #:*
https://github.com/bcgov/entity/issues/17515
Delete associated affiliation invites when an affiliation is removed.
> 17515 - Small fix for removing affiliation invitations on affiliation delete.

- auth-web/src/components/auth/manage-business/AffiliatedEntityTable.vue
- auth-web/src/components/auth/manage-business/AffiliationAction.vue
- auth-web/src/components/auth/manage-business/EntityManagement.vue
*Issue #:17134
https://github.com/bcgov/entity/issues/17134
adding trigger on a button for opening modal when "open new request" is clicked on affiliation.
> 17134 - open modal on action button.

- auth-web/.eslintrc.js
- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/BceidInviteLanding.vue
- auth-web/src/components/auth/account-deactivate/DeactivateCard.vue
- auth-web/src/components/auth/account-settings/team-management/AddUsersSuccess.vue
- auth-web/src/components/auth/create-account/non-bcsc/AccountInstructions.vue
- auth-web/src/components/auth/home/BcscPanel.vue
- auth-web/src/components/auth/manage-business/AffiliatedEntityTable.vue
- auth-web/src/components/datatable/BaseVDataTable.vue
- auth-web/src/components/datatable/components/HeaderFilter.vue
- auth-web/src/views/auth/AccountLoginOptionsInfo.vue
- auth-web/src/views/auth/home/MaintainBusinessView.vue
- auth-web/src/views/auth/staff/ReviewAccountView.vue
- auth-web/tests/unit/services/codes.service.spec.ts
- auth-web/tests/unit/services/task.service.spec.ts
> Filters are unsupported in Vue3 & Lint warning fixes & Unit test fixes.

- auth-web/src/components/auth/manage-business/AffiliatedEntityTable.vue
- auth-web/src/components/auth/manage-business/AffiliationAction.vue
- auth-web/src/components/auth/manage-business/EntityManagement.vue
- auth-web/src/components/auth/manage-business/manage-business-dialog/ManageBusinessDialog.vue
- auth-web/src/models/business.ts
- auth-web/src/stores/business.ts
1. Contact error fix
2. Bad standing fix.
3. Other various fixes.
4. Fix corp type not showing up.
> AUTH-WEB - Affiliation Invitation - Fixes from feedback from UX.

- auth-api/src/auth_api/schemas/schemas/affiliation_invitation.json
- auth-api/src/auth_api/services/affiliation_invitation.py
- auth-api/src/auth_api/version.py
- auth-api/tests/unit/services/test_affiliation_invitation.py
- auth-api/tests/utilities/factory_utils.py
Adding same ability as on branch to be able to create affiliation invitation using toOrgUuid.
> Adding same ability as on branch to be able to create affiliation invitation using toOrgUuid.

- auth-api/src/auth_api/services/affiliation_invitation.py
- auth-web/src/components/auth/manage-business/AffiliationAction.vue
- auth-web/src/components/auth/manage-business/EntityManagement.vue
- auth-web/src/components/auth/manage-business/manage-business-dialog/AccountAuthorizationRequest.vue
- auth-web/src/components/auth/manage-business/manage-business-dialog/ManageBusinessDialog.vue
- auth-web/src/services/org.services.ts
Fix Affiliation Invitation main and 2ndary actions.
> Fix Affiliation Invitation main and 2ndary actions.

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/manage-business/AffiliationAction.vue
- auth-web/src/composables/affiliations-factory.ts
*Issue #:*
https://github.com/bcgov/entity/issues/17384
- Fix action button menu state issue
- App version=2.4.5
> 17384 Auth Web - Action menu button state issue

- auth-web/src/components/auth/manage-business/AffiliatedEntityTable.vue
- auth-web/src/util/common-util.ts
- auth-web/tests/unit/components/AffiliatedEntityTable.spec.ts
> Fix Sonar code issues.

- auth-api/src/auth_api/resources/v1/entity.py
> get_entity_authentication - Use False instead of 'f'

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/manage-business/AffiliationAction.vue
- auth-web/src/components/auth/manage-business/EntityManagement.vue
- auth-web/src/components/auth/staff/review-task/AccountStatus.vue
> Magic link fixes 

- auth-api/src/auth_api/services/affiliation.py
- auth-api/src/auth_api/utils/enums.py
Allow INPROGRESS to add a valid affiliation.
> Add in status INPROGRESS for a valid status to add an affiliation for a NR

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/staff/review-task/AccessRequestModal.vue
- auth-web/src/components/auth/staff/review-task/AccountStatus.vue
- auth-web/src/components/auth/staff/review-task/QsApplication.vue
*Issue #:*
https://github.com/bcgov/entity/issues/17242
* Misc UXA updates as described in ticket ( Text Colour updates, text alignments, bit of formatting)
* Updates AccountStatus component to composition api
> Staff Task UXA + AccountStatus -> Comp Api

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/manage-business/AffiliationAction.vue
- auth-web/src/composables/affiliations-factory.ts
- auth-web/src/util/constants.ts
*Issue #:*
https://github.com/bcgov/entity/issues/17687
- changed displayed status for NR which is in progress to `Draft` (discussed with Mihai)
- corrected corresponding action buttons
- app version = 2.4.13
> 17687 Change displayed status of in progress NR at MBR

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/common/ModalDialog.vue
- auth-web/src/components/auth/manage-business/AffiliatedEntityTable.vue
- auth-web/src/components/auth/manage-business/AffiliationAction.vue
- auth-web/src/components/auth/manage-business/EntityManagement.vue
- auth-web/src/components/auth/manage-business/SearchBusinessNameRequest.vue
- auth-web/src/components/auth/manage-business/manage-business-dialog/ManageBusinessDialog.vue
- auth-web/src/models/affiliation.ts
- auth-web/src/util/constants.ts
- auth-web/tests/unit/components/AffiliatedEntityTable.spec.ts
- auth-web/tests/unit/components/ManageBusinessDialog.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/17764
> 17764 - Feedback from testing - Tweak Password Option

- queue_services/account-mailer/src/account_mailer/auth_utils.py
- queue_services/account-mailer/src/account_mailer/config.py
- queue_services/account-mailer/src/account_mailer/email_processors/common_mailer.py
- queue_services/account-mailer/src/account_mailer/email_templates/product_approved_notification_detailed.html
- queue_services/account-mailer/src/account_mailer/email_templates/product_confirmation_notification.html
- queue_services/account-mailer/src/account_mailer/email_templates/product_rejected_notification_detailed.html
*Issue #:*
https://github.com/bcgov/entity/issues/17523
- add dashboard_url configuration
- update product email templates to use dashboard_url
- template typo / formatting fixes
> 17523 - Qualified Supplier Email Fixes - dashboard_url, template fixes

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/manage-business/AffiliationAction.vue
*Issue #:*
https://github.com/bcgov/entity/issues/17804
Fix actions.
> 17804 - Fix redirect for actions.

- auth-api/tests/docker/docker-compose.yml
Minor tweak to pay spec location
> Update spec to point at correct file.

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/manage-business/EntityManagement.vue
*Issue #:*
https://github.com/bcgov/entity/issues/17750
Updated page title and breadcrumbs for SBC Staff view of My Business Registry page 
> 17750 - SBC Staff Page View Title and Breadcrumb Update

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/composables/affiliations-factory.ts
- auth-web/src/stores/business.ts
https://github.com/bcgov/entity/issues/17879
> 17879 - Fix isBusinessAffiliated check and missing corpNum

- auth-web/src/components/auth/manage-business/EntityManagement.vue
- auth-web/tests/unit/components/EntityManagement.spec.ts
this.showInvalidCodeModal('hey')
this.showEntityNotFoundModal()
this.showBusinessAlreadyAdded({ name: 'hey', identifier: 911 })
this.showNRNotFoundModal()
this.showNRErrorModal()
this.showLinkExpiredModal('hey')
this.showAuthorizationErrorModal()
this.showCreateAffiliationInvitationErrorDialog()
this.showMagicLinkErrorModal()
this.showPasscodeClaimedModal()
this.showUnknownErrorModal('nr')
this.showUnknownErrorModal('business')
this.showUnknownErrorModal('zz')
> Fix dialog title + max-width to 720.

- auth-web/src/components/auth/manage-business/manage-business-dialog/ManageBusinessDialog.vue
*Issue #:17998
https://github.com/bcgov/entity/issues/17998
Add a key on a Manage Business dialog component to to clear it on reset. 
> 17998 - Add key to clear the form after reset (on hiting cancel button).

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/account-settings/transaction/TransactionsDataTable.vue
- auth-web/src/resources/display-mappers/invoice-status-display.ts
- auth-web/src/resources/table-headers/transactions-table/headers.ts
- auth-web/src/util/constants.ts
*Issue #:*
https://github.com/bcgov/entity/issues/17327
https://github.com/bcgov/entity/issues/17856
> 17327 & 17856 - Add in overdue to the transactions table & fix status for Online Banking

- status-api/config.py
- status-api/src/status_api/resources/whatsnew.py
> Change status api fix.

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/account-settings/statement/Statements.vue
*Issue #:17708*
https://github.com/bcgov/entity/issues/17708
> 17708 - Try catch for summary and removing unwanted values in Statements

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/account-settings/statement/Statements.vue
*Issue #:17708 *
https://github.com/bcgov/entity/issues/17708
*Description of changes:17708 *
> 17708 - Statement EFT instructions updated feedback

- auth-web/.env.example
- auth-web/devops/vaults.env
- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/manage-business/AffiliationAction.vue
- auth-web/src/util/config-helper.ts
- auth-web/src/util/navigation.ts
- auth-web/tests/unit/components/AffiliatedEntityTable.spec.ts
- auth-web/tests/unit/test-utils/test-data/affiliations.ts
*Issue #:*
https://github.com/bcgov/entity/issues/17992
NR (LLP, LP, XLP) will link to paper form
> 17992 - NR(LLP, LP, XLP) link to paper form

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/manage-business/manage-business-dialog/ManageBusinessDialog.vue
*Issue #:18086 *
https://github.com/bcgov/entity/issues/18086
Removing 'Request authorization or get help from the Business Registry' option from affiliation modal.
> 18086 - Removing last option from affiliation modal.

- auth-api/src/auth_api/services/affiliation.py
*Issue #:*
https://github.com/bcgov/entity/issues/18050
> 18050 - Strip characters from phone number comparison

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/manage-business/AffiliationAction.vue
*Issue #:*
https://github.com/bcgov/entity/issues/18125
> 18125 - Add in isModernizedEntity check for change of name NR.

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/manage-business/manage-business-dialog/ManageBusinessDialog.vue
> Add in text when there is no affiliation options present.

- auth-web/src/components/auth/manage-business/manage-business-dialog/ManageBusinessDialog.vue
> Remove single line.

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/pay/PayWithOnlineBanking.vue
*Issue #:*
https://github.com/bcgov/entity/issues/17869
Created a new branch. Added CFS account number to auth-web payment page.
> 17869 - AUTH-WEB - Added CFS Account Number

- queue_services/account-mailer/src/account_mailer/email_templates/paymanet_pending.html
*Issue #:*
https://github.com/bcgov/entity/issues/17869
- Added CFS Account Number to Account Mailer - paymanet_pending.html
> 17869 - Account-Mailer CFS update

- auth-web/src/components/auth/common/PaymentMethods.vue
> bug fix for EFT

- auth-api/src/auth_api/services/flags.py
- auth-api/src/auth_api/services/validators/payment_type.py
- auth-api/src/auth_api/utils/enums.py
- auth-api/src/auth_api/version.py
> Add EFT to payment type.

- auth-web/src/components/auth/common/PaymentMethods.vue
> Add missing emit is-pad-valid

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/pay/PayWithOnlineBanking.vue
*Issue #:*
https://github.com/bcgov/entity/issues/18423
- Updated auth-web based on the newly defined requirement for cfs account number description 
> 18423 - AUTH-WEB CFS New Requirement Update

- queue_services/account-mailer/src/account_mailer/email_templates/paymanet_pending.html
*Issue #:*
https://github.com/bcgov/entity/issues/18423
- Updated Account-Mailer CFS Account Number Info 
> 18423 - ACCOUNT-MAILER CFS New Requirement Update

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/services/business.services.ts
This came out of this PR: https://github.com/bcgov/lear/pull/2307
Main ticket: /bcgov/entity#18557
> Remove getNrData

- auth-api/src/auth_api/resources/v1/org.py
- auth-api/src/auth_api/services/affiliation.py
- auth-api/tests/conftest.py
- queue_services/names-events-listener/Makefile
- queue_services/names-events-listener/requirements.txt
- queue_services/names-events-listener/src/names_events_listener/worker.py
- queue_services/names-events-listener/tests/integration/test_worker_queue.py
Untested
https://github.com/bcgov/entity/issues/18627
> 18627 - Use namex-api instead of lear-api for NR details.

- auth-api/src/auth_api/services/affiliation_invitation.py
- auth-api/tests/unit/services/test_affiliation_invitation.py
- queue_services/account-mailer/src/account_mailer/email_templates/affiliation_invitation_request.html
- queue_services/account-mailer/src/account_mailer/email_templates/affiliation_invitation_request_authorization.html
- queue_services/account-mailer/src/account_mailer/worker.py
*Issue #:18380*
https://github.com/bcgov/entity/issues/18380
- updated content of the emails sent when requesting/authorizing affiliation requests
> 18380 - Affiliation Request, Email content update.

- auth-web/package-lock.json
- auth-web/package.json
*Issue #:*
https://github.com/bcgov/entity/issues/18319
- Updated corp-type-module version 
> 18319 - AUTH-WEB Updated corp-type-module version

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/manage-business/AffiliationAction.vue
- auth-web/src/composables/affiliations-factory.ts
- auth-web/src/models/business.ts
- auth-web/src/stores/business.ts
- auth-web/src/util/constants.ts
- auth-web/tests/unit/components/AffiliatedEntityTable.spec.ts
- auth-web/tests/unit/test-utils/test-data/affiliations.ts
*Issue #:*
https://github.com/bcgov/entity/issues/18533
- Implemented amalgamate now button based on FF
- Go to Colin if FF is disabled for entity
- Create draft + redirect if enabled
- Implemented all accompanying features
> 18533 - Amalgamate now button

- auth-api/src/auth_api/models/dataclass.py
- auth-api/src/auth_api/models/org.py
- auth-api/src/auth_api/resources/v1/org.py
- auth-api/src/auth_api/services/org.py
- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/manage-business/manage-business-dialog/AccountAuthorizationRequest.vue
- auth-web/src/components/auth/manage-business/manage-business-dialog/ManageBusinessDialog.vue
- queue_services/account-mailer/src/account_mailer/email_templates/affiliation_invitation_request.html
- queue_services/account-mailer/src/account_mailer/email_templates/affiliation_invitation_request_authorization.html
*Issue #:18653*
https://github.com/bcgov/entity/issues/18653
*Issue #:18380*
https://github.com/bcgov/entity/issues/18380
- update email templates
- wording of some labels changed
- removed pagination from the API call (its not being used anywhere)
> 18653, 18380 - Affiliation REQUEST - additional updates

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/models/business.ts
- auth-web/src/stores/business.ts
*Issue #:*
https://github.com/bcgov/entity/issues/18533
- Small change for the Amalgamation Schema (Changed `amalgamationType` to `type`.
> 18533 - Updated Amalgamation Schema

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/locales/en.json
> Fix the email - showing up incorrectly

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/manage-business/EntityManagement.vue
- auth-web/src/components/auth/manage-business/manage-business-dialog/ManageBusinessDialog.vue
- auth-web/vite.config.ts
*Issue #:*
https://github.com/bcgov/entity/issues/18760
> 18760 - Fix contact phone numbers.

- auth-api/src/auth_api/services/affiliation_invitation.py
Adding guardrail in prerequisites during affiliation request checks.
> Adding guardrail in prerequisites during affiliation request checks.

- queue_services/activity-log-listener/requirements.txt
- queue_services/events-listener/requirements.txt
- queue_services/names-events-listener/requirements.txt
> Update package versions.

- auth-api/src/auth_api/resources/v1/org.py
- auth-api/src/auth_api/version.py
*Issue #:*
https://github.com/bcgov/entity/issues/18763
- fix org members filter used for retrieving ADMIN emails from pay
> 18763 - org members filter fix for roles

- auth-api/src/auth_api/services/affiliation.py
- auth-api/src/auth_api/utils/enums.py
- auth-api/src/auth_api/version.py
- auth-api/tests/unit/api/test_org.py
*Issue #:*
https://github.com/bcgov/entity/issues/18940
> 18940 Add new draft type for amalgamation

- auth-api/src/auth_api/services/api_gateway.py
> change the order, strip, then truncate

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/views/auth/ChooseAuthMethodView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/18670
> 18670 - Update BC Registry Create Acct page ( 2 links)

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/manage-business/AffiliationAction.vue
- auth-web/src/composables/affiliations-factory.ts
- auth-web/src/models/business.ts
- auth-web/src/stores/business.ts
- auth-web/src/util/constants.ts
- auth-web/tests/unit/test-utils/test-data/affiliations.ts
*Issue #:*
https://github.com/bcgov/entity/issues/18952
> 18952 - Change amalgamation to amalgamationApplication

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/account-settings/statement/Statements.vue
- auth-web/src/models/statement.ts
*Issue #:*
https://github.com/bcgov/entity/issues/18493
- add payment methods to EFT statement dashboard layout
- add feature flag logic to drive display logic for frequency and payment methods
> 18493 eft statement updates

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/create-account/non-bcsc/NotaryContactForm.vue
- auth-web/src/locales/en.json
*Issue #:*
https://github.com/bcgov/entity/issues/19146
> 19146 - Fix for Notary email not required, when it should be

- auth-web/src/components/auth/account-settings/product/ProductPackage.vue
*Issue #:*
https://github.com/bcgov/entity/issues/17572
* Minor update to rejection message content
> 17572: Product Rejection Message UXA

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/manage-business/AffiliationAction.vue
- auth-web/src/models/business.ts
- auth-web/src/stores/business.ts
- auth-web/src/util/constants.ts
*Issue #:*
https://github.com/bcgov/entity/issues/19257
> 19257 - Implement Continue In Now button

- auth-api/requirements.txt
- auth-api/requirements/prod.txt
- auth-api/setup.cfg
- auth-api/src/auth_api/models/dataclass.py
- auth-api/src/auth_api/models/db.py
- auth-api/src/auth_api/resources/v1/__init__.py
- auth-api/src/auth_api/resources/v1/simple_org.py
- auth-api/src/auth_api/schemas/simple_org.py
- auth-api/src/auth_api/services/__init__.py
- auth-api/src/auth_api/services/simple_org.py
- auth-api/src/auth_api/utils/converter.py
- auth-api/src/auth_api/utils/custom_query.py
- auth-api/src/auth_api/version.py
- auth-api/tests/docker/docker-compose.yml
- auth-api/tests/unit/api/test_cors_preflight.py
- auth-api/tests/unit/api/test_simple_org.py
*Issue #:*
https://github.com/bcgov/entity/issues/19334
- implement endpoint to return a simplified data set of org
> 19334-Simple org search

- auth-web/src/assets/scss/ShortnameTables.scss
- auth-web/src/components/datatable/BaseVDataTable.vue
- auth-web/src/components/pay/LinkedShortNameTable.vue
- auth-web/src/components/pay/UnlinkedShortNameTable.vue
- auth-web/src/models/pay/short-name.ts
- auth-web/src/views/pay/ShortNameMappingView.vue
- auth-web/tests/unit/components/LinkedShortNameTable.spec.ts
- auth-web/tests/unit/components/UnlinkedShortNameTable.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/19330
UX tweaks
> 19330 - Small UX tweaks

- .sonarcloud.properties
> Add in coverage exclusions

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/pay/eft/ShortNameAccountLink.vue
- auth-web/src/components/pay/eft/ShortNameTransactions.vue
- auth-web/src/views/pay/eft/ShortNameDetailsView.vue
- auth-web/tests/unit/components/ShortNameTransactions.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/19333
- styling updates after UXA
> 19333 - UX tweaks

- auth-api/src/auth_api/services/affiliation.py
> Minor changes for activity log

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/resources/BreadcrumbResources.ts
- auth-web/src/routes/router.ts
- auth-web/src/views/auth/staff/StaffDashboardView.vue
- auth-web/tests/unit/views/StaffDashboard/StaffDashboardView.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/19699
> 19699 - Add in tile to staff page and breadcrumb

- auth-web/src/views/auth/staff/StaffDashboardView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/19699
> 19699_2 - update EFT tile words

- auth-api/src/auth_api/models/dataclass.py
- auth-api/src/auth_api/resources/v1/org.py
- auth-api/src/auth_api/schemas/simple_org.py
- auth-api/src/auth_api/services/simple_org.py
- auth-api/tests/unit/api/test_simple_org.py
*Issue #:*
https://github.com/bcgov/entity/issues/19803
> 19803 - Tweaks for simple org for EFT

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/pay/ShortNameLookup.vue
- auth-web/src/models/pay/accounts.ts
- auth-web/src/services/payment.services.ts
*Issue #: 19332 *
https://github.com/bcgov/entity/issues/19332 
Hooking up endpoint to get accounts with EFT payment enabled
> 19332 - EFT payment endpoint implementation

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/common/Product.vue
> Minor tweak for code cov

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/create-account/AccountTypeSelector.vue
- auth-web/src/util/config-helper.ts
- auth-web/src/util/constants.ts
https://github.com/bcgov/entity/issues/19881
> 19881 - Enable credit card for premium via feature flag

- auth-web/src/components/pay/LinkedShortNameTable.vue
- auth-web/src/components/pay/ShortNameLookup.vue
- auth-web/src/components/pay/UnlinkedShortNameTable.vue
- auth-web/src/composables/short-name-table-factory.ts
- auth-web/src/models/pay/short-name.ts
- auth-web/src/util/constants.ts
- auth-web/src/views/pay/ShortNameMappingView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/19727
> 19727 - Query persistence for short names

- jobs/notebook-report/devops/vaults.json
*Issue #:*
https://github.com/bcgov/entity/issues/3596
Amend weekly Auth Stats reports to include new accounts setup - counting accounts using BCeID or BCSC
> New accountsetup to count BCeID or BCSC#3596(ops ticket)

- auth-web/src/components/auth/manage-business/EntityManagement.vue
- auth-web/src/components/pay/LinkedShortNameTable.vue
- auth-web/src/components/pay/UnlinkedShortNameTable.vue
- auth-web/src/views/pay/ShortNameMappingView.vue
*Issue #: 19727 *
https://github.com/bcgov/entity/issues/19727 
> 19727 - Short names: highlight fix when linking

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/pay/UnlinkedShortNameTable.vue
- auth-web/src/components/pay/eft/ShortNameAccountLink.vue
- auth-web/src/components/pay/eft/ShortNameLinkingDialog.vue
*Issue #:*
https://github.com/bcgov/entity/issues/20015
Updated the way we watch to open dialog
> 20015  - Fixing modal not opening in details

- auth-web/src/components/auth/common/Product.vue
- auth-web/src/views/pay/RefundView.vue
Adding BASE_FEES, FUTURE_EFFECTIVE_FEES, PRIORITY_FEES
Removing OTHER_FEES
*Issue #:*
https://github.com/bcgov/entity/issues/19912
> 19912- Updating refund type types

- queue_services/account-mailer/src/account_mailer/email_processors/account_unlock.py
- queue_services/account-mailer/src/account_mailer/worker.py
- queue_services/account-mailer/tests/integration/test_worker_queue.py
*Issue #:*
https://github.com/bcgov/entity/issues/20037
> 20037 - Fix NSF unlock receipt

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/views/pay/RefundView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/19912
Now removing alphabet characters from invoice number before posting.
> 19912 - Bugfix: Matching invoiceId for API call

- queue_services/account-mailer/src/account_mailer/email_processors/account_unlock.py
- queue_services/account-mailer/src/account_mailer/worker.py
*Issue #:*
https://github.com/bcgov/entity/issues/20037
> 20037 - Small tweak for account name, not showing up in email

- auth-web/src/views/auth/ChooseAuthMethodView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/20118
> 20118_2 - Registration page changes - word fix

- auth-web/src/views/auth/ChooseAuthMethodView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/20118
> 20118 - BCSC Create Page - UX Changes

- auth-web/package-lock.json
- auth-web/package.json
https://github.com/bcgov/entity/issues/19686
> 19686 - Update sbc-common-components to include release notes

- auth-api/src/auth_api/config.py
- auth-api/src/auth_api/services/affiliation.py
> Remove temporary url for altnerative names.

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/pay/eft/ShortNameAccountLink.vue
- auth-web/src/resources/BreadcrumbResources.ts
- auth-web/src/routes/router.ts
- auth-web/src/util/constants.ts
- auth-web/src/views/auth/ChooseAuthMethodView.vue
- auth-web/src/views/auth/staff/InvoluntaryDissolution.vue
- auth-web/src/views/auth/staff/StaffDashboardView.vue
- auth-web/tests/unit/views/InvoluntaryDissolution.spec.ts
- auth-web/tests/unit/views/StaffDashboard/StaffDashboardView.spec.ts
*Issue #: https://github.com/bcgov/entity/issues/19023
- Implemented involuntary Dissolution to staff dashboard
- Implemented feature flag
- Created skeleton for the involuntary dissolution screen
- Navigate with breadcrumbs
- Unit tests
> 19023 Implemented Involuntary Dissolution Tile

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/pay/ShortNameSummaryTable.vue
- auth-web/src/composables/short-name-table-factory.ts
- auth-web/src/models/pay/short-name.ts
- auth-web/src/services/payment.services.ts
- auth-web/src/util/constants.ts
- auth-web/src/views/pay/ShortNameMappingView.vue
- auth-web/tests/unit/components/ShortNameSummaryTable.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/20414
- Update EFT manage short names screen unlinked table to "All Short Names" summary view
> 20414-EFT Short name summary search

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/views/auth/staff/StaffDashboardView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/19023
- Added the shadow from the involuntary dissolution tile
Before:
After:
> 19023 Added shadow from involuntary dissolution tile

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/datatable/BaseVDataTable.vue
- auth-web/src/components/pay/LinkedShortNameTable.vue
- auth-web/src/components/pay/ShortNameSummaryTable.vue
- auth-web/src/views/pay/ShortNameMappingView.vue
- auth-web/tests/unit/components/LinkedShortNameTable.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/20420
- update linked eft accounts table with new columns / styling
> 20420 - EFT Enabled Accounts Table

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/datatable/BaseVDataTable.vue
- auth-web/src/components/pay/LinkedShortNameTable.vue
*Issue #:*
https://github.com/bcgov/entity/issues/20420
- Remove shadow below "Actions" label
- action button styling tweaks (padding and vertical alignment)
> 20420-UXA Fixes

- .github/workflows/account-mailer-ci.yml
- .github/workflows/activity-log-listener-ci.yml
- .github/workflows/auth-api-ci.yml
- .github/workflows/auth-web-ci.yml
- .github/workflows/events-listener-ci.yml
- .github/workflows/status-api-ci.yml
> Disable codecov failure

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/CardHeader.vue
- auth-web/src/components/auth/staff/DissolutionSchedule.vue
*Issue #:*
https://github.com/bcgov/entity/issues/20929
- Before working on the buttons, I wanted to move to use composition api as per the request from relationships team
> 20929 - Changed Involuntary Dissolution files to use composition api

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/staff/DissolutionSchedule.vue
*Issue #:*
https://github.com/bcgov/entity/issues/19024
Andy's comment: https://github.com/bcgov/entity/issues/19024#issuecomment-2101223793
Fixed Invol Dissolution screens in response to UXA comments
> 19024 Fixed Invol Dissolution screens in response to UXA comments

- auth-api/src/auth_api/services/org.py
https://github.com/bcgov-registries/ops-support/issues/3865
https://github.com/bcgov-registries/ops-support/issues/3804
> OPS 3865 & 3804 - Add in small condition that will pass pay-api validation

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/staff/DissolutionSchedule.vue
- auth-web/src/views/auth/staff/InvoluntaryDissolution.vue
*Issue #:*
https://github.com/bcgov/entity/issues/19024
Designs have changed due to requirements changing. This change is in response to that.
> 19024 - More fixes for Involuntary dissolution in response to UXA comments

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/staff/DissolutionSchedule.vue
*Issue #:*
https://github.com/bcgov/entity/issues/19024
- More UXA fixes
> 19024 - Fixed involuntary dissolution text field value

- queue_services/account-mailer/Dockerfile
> Change docker for account mailer

- queue_services/account-mailer/src/account_mailer/__init__.py
- queue_services/auth-queue/Dockerfile
- queue_services/auth-queue/src/auth_queue/__init__.py
> Missing caches

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/models/Staff.ts
- auth-web/src/services/staff.services.ts
- auth-web/src/views/auth/staff/SafeEmailView.vue
- auth-web/src/views/auth/staff/StaffDashboardView.vue
*Description of changes:* Added a form to add email to safe list and a delete button to remove it [against each email in list].
> 20463 - Feat: Support Safe List Addition and Removal

- queue_services/account-mailer/requirements.txt
- queue_services/account-mailer/requirements/repo-libraries.txt
- queue_services/auth-queue/requirements.txt
- queue_services/auth-queue/requirements/repo-libraries.txt
> Fix deps to point at bcgov

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/assets/scss/theme.scss
- auth-web/src/components/datatable/BaseVDataTable.vue
- auth-web/src/components/pay/eft/ShortNameAccountLink.vue
- auth-web/src/services/payment.services.ts
- auth-web/src/util/constants.ts
*Issue #:*
https://github.com/bcgov/entity/issues/20419
- extend BaseVDataTable to support expanded rows for additional information
- update ShortNameAccountLink component to make use of expanded rows to display additional information
- Add Unlink for pending links
> 20419 - EFT Short name link additional info

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/account-settings/account-info/AccountDetails.vue
- auth-web/src/components/auth/common/AccountBusinessType.vue
- auth-web/src/stores/org.ts
- auth-web/tests/unit/components/AccountDetails.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/15959
> 15959 - Auth-web - Tweaks for govn type dropdown

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/views/auth/staff/SafeEmailView.vue
- auth-web/src/views/auth/staff/StaffDashboardView.vue
Re-render safe email list on add and delete button click
> 20463 - Update Safe Email List on Button Click

- auth-api/src/auth_api/version.py
> 21471 - updating version for release to 2.10.0

- auth-api/migrations/versions/2024_05_30_39b4f331c003_admin_view_address_permission.py
- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
*Issue #:*
https://github.com/bcgov/entity/issues/20159
> 20159 - Add view_address permission to admin account

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/staff/DissolutionSchedule.vue
- auth-web/tests/unit/components/CardHeader.spec.ts
- auth-web/tests/unit/components/DissolutionSchedule.spec.ts
- auth-web/tests/unit/views/InvoluntaryDissolution.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/21154
- Created/Updated the units tests for everything involuntary dissolution related
> 21154 - Unit tests for all involuntary dissolution views/components

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/services/staff.services.ts
- auth-web/src/views/auth/staff/SafeEmailView.vue
- auth-web/src/views/auth/staff/StaffDashboardView.vue
Changes based upon QA feedback. Includes alerts when changes are made to the safe list and code cleanup.
> 20463 - Fix: Safe List Alerts and Refactor

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/views/auth/staff/SafeEmailView.vue
- auth-web/src/views/auth/staff/StaffDashboardView.vue
Clear email text field after clicking add email button as suggested during QA. Includes some refactoring as suggested by @seeker25 previously.
> 20463 - Fix: Clear Email Text Field after Btn Click and Refactor

- auth-api/src/auth_api/models/org.py
- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/common/TermsOfUseDialog.vue
- auth-web/src/components/auth/staff/account-management/StaffActiveAccountsTable.vue
- auth-web/src/components/datatable/resources/index.ts
- auth-web/src/models/Organization.ts
- auth-web/tests/unit/components/StaffActiveAccountsTable.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/19556
1. Add Account Search for BCOL Account # in BCROS
2. Update StaffActiveAccountsTable.vue to composition-api
> 19556 - Account Search for BCOL Account # in BCROS

- auth-api/src/auth_api/utils/account_mailer.py
- auth-api/src/auth_api/utils/enums.py
- queue_services/account-mailer/requirements.txt
- queue_services/account-mailer/src/account_mailer/email_processors/common_mailer.py
- queue_services/account-mailer/src/account_mailer/email_templates/account_suspended_email.html
- queue_services/account-mailer/src/account_mailer/email_templates/account_unlocked_email.html
- queue_services/account-mailer/src/account_mailer/resources/worker.py
- queue_services/auth-queue/requirements.txt
- queue_services/auth-queue/src/auth_queue/resources/worker.py
> 20087 - Mailer changes for suspension

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/manage-business/BusinessLookup.vue
- auth-web/src/services/business-lookup.services.ts
- auth-web/tests/unit/services/business-lookup.service.spec.ts
*Issue #:* bcgov/entity#21134
- app version = 2.6.25
- added safe fallback in case FF is not returned / null in Business Lookup component
- removed legalType fallback in Business Lookup Service
- updated unit test
> 21134 - Updated business lookup

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
*Issue #:*
Fix show address at Account Info
> Fix show address at Account Info

- auth-api/migrations/versions/2024_06_05_7bf8428e568e_.py
- auth-api/migrations/versions/2024_06_05_7bf8428e568e_remove_govm_business_type_codes.py
- auth-api/src/auth_api/services/org.py
- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/account-settings/account-info/AccountDetails.vue
- auth-web/src/components/auth/common/AccountBusinessType.vue
- auth-web/src/components/auth/common/stepper/Stepper.vue
- auth-web/src/stores/org.ts
- auth-web/src/views/auth/ChooseAuthMethodView.vue
- auth-web/tests/unit/components/AccountBusinessType.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/15959
> 15959 - UXA fix - Relocate click box and Add Account Creation Process for GOVN

- auth-api/src/auth_api/services/org.py
*Issue #:*
https://github.com/bcgov/entity/issues/15959
> 15959_2 - Fix for is_staff_review_needed logic

- auth-api/tests/docker/docker-cmpose-mac.yml
> Create a docker-compose file for Mac testing

- queue_services/auth-queue/src/auth_queue/resources/worker.py
> Small tweak to fix unlock messages

- auth-web/src/components/datatable/BaseVDataTable.vue
*Issue #:*
https://github.com/bcgov/entity/issues/20420
- remove z-index from fixed column styling (position: sticky handles this)
> 20420-QA-Fix

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/common/BaseAddressForm.vue
*Issue #:*
https://github.com/bcgov/entity/issues/21878
> 21878 - fix - infinite loop while used by AccountCreateBasic.vue

- auth-api/src/auth_api/config.py
- auth-api/src/auth_api/services/affiliation_invitation.py
- auth-api/src/auth_api/services/invitation.py
- auth-api/src/auth_api/services/membership.py
- auth-api/src/auth_api/services/org.py
- auth-api/src/auth_api/services/user.py
- auth-api/tests/unit/services/test_affiliation_invitation.py
- queue_services/account-mailer/src/account_mailer/config.py
https://github.com/bcgov/entity/issues/21898
We saw an issue where =null was being put into this environment variable and would break the code in the PR.
> 21898 - Remove AUTH_WEB_TOKEN_CONFIRM_PATH

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/common/AccountBusinessType.vue
*Issue #:*
https://github.com/bcgov/entity/issues/20159
> 20159 - Fix - Incorrect Default Form Display When Editing Account Type

- auth-api/migrations/versions/2024_05_23_1e4b6359f470_add_flag_business_type_codes.py
> bug fix - a missing comma at migration

- queue_services/account-mailer/src/account_mailer/email_templates/account_conf_over_email.html
- queue_services/account-mailer/src/account_mailer/email_templates/account_suspended_email.html
- queue_services/account-mailer/src/account_mailer/email_templates/account_unlocked_email.html
- queue_services/account-mailer/src/account_mailer/email_templates/admin_notification_email.html
- queue_services/account-mailer/src/account_mailer/email_templates/admin_removed_email.html
- queue_services/account-mailer/src/account_mailer/email_templates/affiliation_invitation_email.html
- queue_services/account-mailer/src/account_mailer/email_templates/business_invitation_email.html
- queue_services/account-mailer/src/account_mailer/email_templates/business_invitation_email_for_bceid.html
- queue_services/account-mailer/src/account_mailer/email_templates/dirsearch_business_invitation_email.html
- queue_services/account-mailer/src/account_mailer/email_templates/govm_approved_notification.html
- queue_services/account-mailer/src/account_mailer/email_templates/govm_business_invitation_email.html
- queue_services/account-mailer/src/account_mailer/email_templates/govm_member_invitation_email.html
- queue_services/account-mailer/src/account_mailer/email_templates/govm_rejected_notification.html
- queue_services/account-mailer/src/account_mailer/email_templates/membership_approved_notification_email.html
- queue_services/account-mailer/src/account_mailer/email_templates/membership_approved_notification_email_for_bceid.html
- queue_services/account-mailer/src/account_mailer/email_templates/nonbcsc_org_approved_notification_email.html
- queue_services/account-mailer/src/account_mailer/email_templates/nonbcsc_org_rejected_notification_email.html
- queue_services/account-mailer/src/account_mailer/email_templates/pad_invoice_email.html
- queue_services/account-mailer/src/account_mailer/email_templates/paymanet_pending.html
- queue_services/account-mailer/src/account_mailer/email_templates/role_changed_notification_email.html
- queue_services/account-mailer/src/account_mailer/email_templates/statement_notification.html
- queue_services/account-mailer/src/account_mailer/email_templates/team_modified_email.html
*Issue #:*
https://github.com/bcgov/entity/issues/18181
*Description of changes:* Account-Mailer - New Account notification includes acct number
> 18181 - Account-Mailer - New Account notification includes acct number

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/common/AccountBusinessType.vue
- auth-web/tests/unit/components/AccountBusinessType.spec.ts
…form
*Issue #:*
https://github.com/bcgov/entity/issues/20159
> 20159_fix - Account Details Edit - The default value is not loaded into the form

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/common/BaseAddressForm.vue
- auth-web/src/components/auth/common/GLPaymentForm.vue
- auth-web/src/components/auth/common/StaffAccountsTable.vue
- auth-web/src/components/auth/manage-business/AffiliatedEntityTable.vue
- auth-web/src/components/auth/staff/account-management/StaffActiveAccountsTable.vue
- auth-web/src/components/auth/staff/account-management/StaffInactiveAccountsTable.vue
- auth-web/src/views/auth/staff/GLCodesListView.vue
*Issue #:* https://github.com/bcgov/entity/issues/21866
- Removed the isIA condition in AffiliatedEntityTable.vue to allow all application types show Flag NR expried
- Run lint so some formatting updated
> 21866 - Flag-Expired-NR

- auth-api/migrations/versions/2024_06_26_af98933abe93_.py
- auth-api/migrations/versions/2024_06_26_af98933abe93_add_partner_codes.py
- auth-api/requirements/dev.txt
*Issue #:*
https://github.com/bcgov/entity/issues/21865
> 21865 - Add in migration for new products

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
- auth-web/src/components/auth/common/BaseAddressForm.vue
- auth-web/tests/unit/components/AccountInfo.spec.ts
…l to business
*Issue #:*
https://github.com/bcgov/entity/issues/22041
> 22041 - Auth-Web - Fix request when user update org from individual to business type

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/stores/business.ts
- auth-web/src/views/auth/staff/StaffDashboardView.vue
> Small fix for searching business identifiers

- auth-api/src/auth_api/version.py
> creating a new release branch

- auth-web/package-lock.json
- auth-web/package.json
*Issue #:*
https://github.com/bcgov/entity/issues/21096
*Description of changes:* Update FAS-UI
> 21096 - Update FAS-UI

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/common/PaymentMethods.vue
- auth-web/src/components/pay/CompletePaymentDetails.vue
- auth-web/src/components/pay/OutstandingBalances.vue
*Issue #:*
https://github.com/bcgov/entity/issues/20907
- UXA Feedback updates
> 20907 - UXA Feedback

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/pay/OutstandingBalances.vue
- auth-web/src/views/pay/PayOutstandingBalanceView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/20907
- add loaders / hiding logic
- error handling
> 20907 - Error handling updates / loaders

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/pay/OutstandingBalances.vue
- auth-web/src/components/pay/eft/ShortNameAccountLink.vue
- auth-web/src/services/payment.services.ts
- auth-web/src/util/constants.ts
- auth-web/src/views/pay/eft/ShortNameDetailsView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/21527
- Cancel Pending Payment
- Apply Payment
- Unlink Account
> 21527 - Cancel / Apply Payment and Unlink Account

- auth-web/src/views/pay/eft/ShortNameDetailsView.vue
> clean up debug

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/pay/ShortNameSummaryTable.vue
- auth-web/src/components/pay/eft/ShortNameAccountLink.vue
*Issue #:*
https://github.com/bcgov/entity/issues/21527
- UXA Feedback
> 21527 - UXA Feedback

- auth-api/Makefile
> fix makefile for auth-api

- auth-api/poetry.lock
- auth-api/pyproject.toml
Reverts bcgov/sbc-auth#2921
No luck with CD
> Revert "Bump flask-cors from 3.0.10 to 4.0.1 in /auth-api"

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
*Issue #:*
https://github.com/bcgov/entity/issues/20046
*Description of changes:* Account Details missing
> 20046 - Account Details missing

- auth-api/src/auth_api/version.py
*Issue #:*
updating release version to 2.10.2
> update auth release to 2.10.2

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/views/pay/eft/ShortNameRefundView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/21535
> 21535 - Add hint text to eft refund form

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/services/payment.services.ts
*Issue #:*
https://github.com/bcgov/entity/issues/21535
> 21535 - Shortname refund api url updates

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/common/AccountBusinessType.vue
*Issue #:*
https://github.com/bcgov/entity/issues/21965
> 21965 - Align Business Type and Business Size while creating account

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/staff/continuation-application/HomeJurisdictionInformation.vue
- auth-web/tests/unit/components/HomeJurisdictionInformation.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/22420
- Removed the director's affidavit document from review page
> 22420 - Removed Director's Affidavit from Review Page

- auth-web/package-lock.json
- auth-web/package.json
*Issue #:*
https://github.com/bcgov/entity/issues/21096
*Description of changes:* Updated FAS-UI version
> 21096 - Updated FAS-UI version

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/pay/eft/ShortNameRefund.vue
- auth-web/src/routes/router.ts
*Issue #:*
https://github.com/bcgov/entity/issues/21535
> 21535 - Pass shortname info as props to ShortnameRefund

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/views/pay/eft/ShortNameRefundView.vue
- auth-web/tests/unit/views/ShortNameRefundView.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/21535
> 21535 - Disable form when processing EFT refund

- auth-api/src/auth_api/version.py
Updating release number in version.py
> update version.py to 2.10.3

- auth-api/src/auth_api/services/affiliation.py
- auth-api/tests/unit/api/test_org.py
*Issue #:*
https://github.com/bcgov/entity/issues/22222
> 22222 all affiliation information from legal-api for draft

- queue_services/account-mailer/src/account_mailer/resources/worker.py
- queue_services/auth-queue/src/auth_queue/resources/worker.py
*Issue #:*
https://github.com/bcgov/entity/issues/20087
for: https://github.com/bcgov/sbc-pay/pull/1654
> 20087 - Put in additional emails for locking

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/views/auth/account-freeze/AccountFreezeUnlockView.vue
> Small tweak for EFT unlocking

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/views/pay/eft/ShortNameDetailsView.vue
- auth-web/src/views/pay/eft/ShortNameRefundView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/22552
> 22552 - Eft refund enhancement

- auth-web/src/components/pay/eft/ShortNamePaymentHistory.vue
*Issue #:*
https://github.com/bcgov/entity/issues/21522
- correct transaction type to show negative amount
> 21522 - EFT Short name amount fix

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/account-settings/payment/AccountPaymentMethods.vue
- auth-web/src/components/auth/common/PaymentMethods.vue
*Issue #:*
https://github.com/bcgov/entity/issues/22605
> 22605 - Removing Terms and Conditions Step from EFT Account Workflow

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/account-settings/statement/Statements.vue
> Fix new tag for statements

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/pay/eft/ShortNamePaymentHistory.vue
- auth-web/src/util/constants.ts
- auth-web/tests/unit/components/ShortNamePaymentHistory.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/21597
> EFT Short name invoice refund history

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/account-settings/statement/Statements.vue
- auth-web/src/components/auth/account-settings/statement/StatementsSettings.vue
*Issue #:*
https://github.com/bcgov/entity/issues/22678
> 22678 - Add in error check, await calls so we don't have race condition

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/common/PaymentMethods.vue
- auth-web/src/util/constants.ts
*Issue #:*
https://github.com/bcgov/entity/issues/20721 
> 20721 - Add feature flag - enable-payment-change-from-eft

- queue_services/account-mailer/src/account_mailer/email_templates/payment_due_notification.html
- queue_services/account-mailer/src/account_mailer/email_templates/payment_reminder_notification.html
*Issue #:*
https://github.com/bcgov/entity/issues/22725
> 22725 - Add in account_number and account_name_with_branch

- jobs/gcp-db-data-masking/run.sh
> rename sandbox db

- queue_services/account-mailer/src/account_mailer/email_templates/creditcard_refund_request_email.html
- queue_services/account-mailer/src/account_mailer/email_templates/eft_available_notification.html
- queue_services/account-mailer/src/account_mailer/email_templates/payment_due_notification.html
- queue_services/account-mailer/src/account_mailer/email_templates/payment_reminder_notification.html
- queue_services/account-mailer/src/account_mailer/email_templates/statement_notification.html
*Issue #:*
https://github.com/bcgov/entity/issues/22725
> 22725 - Update phone numbers for financial emails

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/account-settings/payment/AccountPaymentMethods.vue
- auth-web/src/components/auth/common/PaymentMethods.vue
*Issue #:*
https://github.com/bcgov/entity/issues/22841
> 22841 - EFT pay model UXA tweak

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/common/AccountBusinessType.vue
*Issue #:*
https://github.com/bcgov/entity/issues/21963
> 21963 - Allow Fresh BC Service User and BCeId User to create GovN Account

- auth-web/src/components/pay/eft/ShortNameAccountLink.vue
- auth-web/src/components/pay/eft/ShortNamePaymentHistory.vue
*Issue #:*
https://github.com/bcgov/entity/issues/22766
- Fix previous PR Feedback - update import
> 22766 - missed pr feedback

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/views/pay/eft/ShortNameDetailsView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/21562
- eligible refund caution text update
> 21562-Short name details warning update

- auth-api/src/auth_api/version.py
> update version number for release 2.10.5

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/account-settings/statement/Statements.vue
*Issue #:*
https://github.com/bcgov/entity/issues/22391
- EFT Statement caution text for multi linked accounts
> 22391 - Statement-Caution-Text

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/account-freeze/MakePayment.vue
- auth-web/src/components/auth/account-settings/statement/Statements.vue
- auth-web/src/components/datatable/BaseVDataTable.vue
- auth-web/src/views/auth/account-freeze/AccountFreezeUnlockView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/23112
> 23112 - Add in nextStatementDate when there is no outstanding balance

- auth-api/poetry.lock
- queue_services/auth-queue/poetry.lock
> update poetry lock after repointing to feature branch

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/datatable/BaseVDataTable.vue
> Small warning fix

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/account-freeze/AccountOverview.vue
- auth-web/src/components/auth/account-freeze/MakePayment.vue
- auth-web/src/components/auth/account-settings/statement/Statements.vue
- auth-web/src/components/auth/common/PaymentMethods.vue
- auth-web/src/components/pay/OutstandingBalances.vue
- auth-web/src/composables/downloader.ts
- auth-web/src/util/constants.ts
- auth-web/src/views/auth/AccountLoginOptionsChooser.vue
- auth-web/src/views/auth/account-freeze/AccountFreezeUnlockView.vue
- auth-web/src/views/auth/account-freeze/AccountHoldView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/23072
> 23072 - EFT - Consolidated invoices / unlock - frontend changes

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/account-settings/statement/Statements.vue
*Issue #:*
https://github.com/bcgov/entity/issues/22391
- implement multi short name link under payment flag for caution text
> 22391 - EFT Multi Account Under Payment Caution

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/pay/ShortNameSummaryTable.vue
- auth-web/src/util/constants.ts
*Issue #:*
https://github.com/bcgov/entity/issues/21594
> 21594 - Refund requested badge on short name management list

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/account-freeze/MakePayment.vue
*Issue #:*
https://github.com/bcgov/entity/issues/23072
> Fix double checked

- .github/workflows/auth-queue-ci.yml
- queue_services/auth-queue/tests/conftest.py
> Fix unit tests for auth-queue

- .github/workflows/account-mailer-cd.yml
> fix maile cd flow

- auth-api/poetry.lock
- queue_services/account-mailer/poetry.lock
- queue_services/auth-queue/poetry.lock
> udpate dependency

- auth-api/poetry.lock
- auth-api/pyproject.toml
- auth-api/src/auth_api/config.py
> Switch back to psycopg2 from pg8000.

- auth-api/poetry.lock
- auth-api/pyproject.toml
> Add psycopg2 library.

- .github/workflows/account-mailer-cd.yml
- .github/workflows/auth-api-cd.yml
- .github/workflows/auth-queue-cd.yml
- .github/workflows/auth-web-cd.yml
- auth-api/poetry.lock
- auth-api/pyproject.toml
- auth-api/src/auth_api/config.py
- auth-api/src/auth_api/models/account_login_options.py
- auth-api/src/auth_api/models/affiliation.py
- auth-api/src/auth_api/models/affiliation_invitation.py
- auth-api/src/auth_api/models/contact_link.py
- auth-api/src/auth_api/models/entity.py
- auth-api/src/auth_api/models/invitation.py
- auth-api/src/auth_api/models/membership.py
- auth-api/src/auth_api/models/org.py
- auth-api/src/auth_api/models/org_settings.py
- auth-api/src/auth_api/models/product_subscription.py
- auth-api/src/auth_api/models/task.py
- auth-api/src/auth_api/models/user.py
> Back to pg8000 and add type of id to the model functions.

- auth-api/src/auth_api/models/affiliation_invitation.py
> Force convert string to int

- auth-api/src/auth_api/models/affiliation_invitation.py
- auth-api/src/auth_api/models/invitation.py
> Force conver string to int part 2.

- auth-api/src/auth_api/resources/v1/affiliation_invitation.py
- auth-api/src/auth_api/resources/v1/entity.py
- auth-api/src/auth_api/resources/v1/invitation.py
- auth-api/src/auth_api/resources/v1/org.py
- auth-api/src/auth_api/resources/v1/org_api_keys.py
- auth-api/tests/unit/api/test_org.py
> fix data: null response when {} is returned

- auth-api/src/auth_api/models/org.py
> another type error

- auth-api/Dockerfile
- auth-api/poetry.lock
- queue_services/account-mailer/poetry.lock
> Fix poetry locks

- auth-api/src/auth_api/resources/v1/__init__.py
- auth-api/src/auth_api/resources/v1/keycloak.py
- auth-api/src/auth_api/services/keycloak.py
> Fix circular dependency error from last merge

- auth-api/src/auth_api/exceptions/exception_handler.py
> add stack trace to db error / path to http error logs

- auth-web/src/components/pay/ShortNameSummaryTable.vue
*Issue #:*
https://github.com/bcgov/entity/issues/23102
- fix minWidth on table columns when shrinking window size
> 23102 - UXA Feedback

- auth-api/src/auth_api/exceptions/exception_handler.py
- auth-api/src/auth_api/models/membership.py
> pg8000 type error / add stacktrace for std handler

- auth-api/src/auth_api/exceptions/exception_handler.py
> add more details for http exception logging

- auth-api/src/auth_api/models/activity_log.py
- auth-api/src/auth_api/models/affiliation_invitation.py
- auth-api/src/auth_api/models/invitation.py
- auth-api/src/auth_api/models/product_subscription.py
- auth-api/src/auth_api/models/task.py
- auth-api/src/auth_api/services/affiliation.py
- auth-api/src/auth_api/services/user.py
> Fixed pg8000 integer issue.

- auth-api/src/auth_api/resources/v1/org_products.py
- auth-api/tests/unit/api/test_org_products.py
> Fixed get products issue.

- .github/workflows/auth-queue-cd.yml
> fix pipe name

- auth-api/migrations/versions/2024_09_20_aa74003de9d8_.py
> Removed id foreign keys in history tables.

- auth-api/devops/gcp/clouddeploy.yaml
- auth-api/src/auth_api/exceptions/exception_handler.py
> add resource params

- build-deps/poetry.lock
- build-deps/pyproject.toml
> test custom camel case function

- auth-api/poetry.lock
- auth-api/src/auth_api/resources/v1/affiliation_invitation.py
- auth-api/src/auth_api/resources/v1/entity.py
- auth-api/src/auth_api/resources/v1/invitation.py
- auth-api/src/auth_api/resources/v1/org.py
- auth-api/src/auth_api/resources/v1/org_api_keys.py
> use modified camelcase function

- auth-api/migrations/versions/2024_09_20_aa74003de9d8_.py
- auth-api/src/auth_api/exceptions/exception_handler.py
- auth-api/src/auth_api/schemas/org.py
*Issue #:*
https://github.com/bcgov/entity/issues/23606
1. Fixed org schema mailing address issue
2. Switch to warning message of auth error logging
> Fixed org schema mailing address issue and auth error logging.

- queue_services/account-mailer/poetry.lock
- queue_services/account-mailer/src/account_mailer/__init__.py
- queue_services/auth-queue/poetry.lock
- queue_services/auth-queue/src/auth_queue/__init__.py
> add better logging to services

- auth-api/src/auth_api/__init__.py
- auth-api/src/auth_api/exceptions/exception_handler.py
- auth-api/src/auth_api/resources/v1/affiliation_invitation.py
- auth-api/src/auth_api/resources/v1/invitation.py
- auth-api/src/auth_api/resources/v1/org_api_keys.py
- auth-api/src/auth_api/services/authorization.py
- auth-api/src/auth_api/utils/error.py
- auth-api/update_db.sh
> Remove migration out of app start and fix linting.

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/views/pay/eft/ShortNameDetailsView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/21570
Adding a little bit of spacing to the bottom of the short name details header.
> 21570 - Adding more whitespace to header

- auth-api/poetry.lock
- auth-api/pyproject.toml
- auth-api/src/auth_api/__init__.py
- auth-api/src/auth_api/config.py
- auth-api/update_db.sh
> Fxied migration script issue.

- queue_services/account-mailer/src/account_mailer/config.py
> fix report url

- auth-api/src/auth_api/resources/v1/org_products.py
- auth-api/src/auth_api/services/products.py
- auth-api/tests/unit/api/test_org_products.py
*Issue #:*
https://github.com/bcgov/entity/issues/23667
> 23667 - Help MHR with an endpoint they can hit with SYSTEM

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/staff/continuation-application/ContinuationApplicationTable.vue
*Issue #:*
https://github.com/bcgov/entity/issues/23519
- Update the column header to Contact Email
> Fix 23519 - update Contact Email header

- queue_services/account-mailer/src/account_mailer/resources/worker.py
> fix stacktrace logging

- build-deps/poetry.lock
- build-deps/pyproject.toml
> the other branch was merged to main

- auth-api/src/auth_api/models/affidavit.py
- auth-api/src/auth_api/models/user.py
> few more type casts

- auth-web/src/services/payment.services.ts
- auth-web/src/views/pay/PaymentView.vue
> Revert "23942 - If transaction is already completed jump directly to redirect url"

- auth-api/poetry.lock
- auth-api/pyproject.toml
> udpate auth-api deps

- queue_services/account-mailer/poetry.lock
- queue_services/account-mailer/pyproject.toml
- queue_services/auth-queue/poetry.lock
- queue_services/auth-queue/pyproject.toml
> update service deps

- queue_services/account-mailer/tests/conftest.py
> remove depreacted functionality from test mocks

- auth-web/src/services/payment.services.ts
- auth-web/src/views/pay/PaymentView.vue
> Revert "Revert "23942 - If transaction is already completed jump directly to redirect url""

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/staff/continuation-application/AuthorizationContactInformation.vue
*Issue #:*
https://github.com/bcgov/entity/issues/23647
- Show (Not entered) for phone when it's not known
> Fix-23647-Update Phone Unknown Display

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/common/PaymentMethods.vue
*Issue #:*
https://github.com/bcgov/entity/issues/24004
> 24004 - Add pad info touched

- auth-api/src/auth_api/services/products.py
- auth-api/src/auth_api/services/validators/payment_type.py
https://github.com/bcgov/sbc-pay/pull/1799
> Add in feature flag remove-premium-restrictions

- auth-api/devops/vaults.gcp.env
- queue_services/account-mailer/devops/vaults.gcp.env
- queue_services/auth-queue/devops/vaults.gcp.env
> point to correct ld key value

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/account-settings/payment/AccountPaymentMethods.vue
- auth-web/src/components/auth/create-account/BcolLogin.vue
- auth-web/src/components/auth/create-account/PaymentMethodSelector.vue
*Issue #:*
https://github.com/bcgov/entity/issues/24004 
> 24004 - update paymentMethodChanged when settings bcolInfo, fix error handling

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/staff/continuation-application/ContinuationApplicationTable.vue
- auth-web/src/models/continuation-review.ts
*Issue #:*
https://github.com/bcgov/entity/issues/23821
- Updated the Continuation Review Table Email property: from officeEmail to contactEmail
> 23821 - Update Continuation Table Contact Email Property

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/views/pay/RefundView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/23152
- update partial refund credit card error to specify DIRECT_PAY
- update read only dollar amounts to be 2 decimal places
- update validation for negative amounts
- update UI to handle invoices that already have a refund amount
> 23152-Partial Refunds - QA Feedback

- auth-web/package-lock.json
- auth-web/package.json
> Fas version update

- auth-web/package-lock.json
- auth-web/package.json
*Issue #:*
https://github.com/bcgov/entity/issues/21909 
> 21909 - Fas version update

- auth-api/src/auth_api/services/affiliation.py
- auth-api/src/auth_api/utils/roles.py
*Issue #:*
https://github.com/bcgov/entity/issues/24455
> 24455 - Add in role to bypass auth check for creating an affiliation (passcode) - Business-AR

- auth-api/src/auth_api/resources/v1/org.py
- auth-api/src/auth_api/services/affiliation.py
*Issue #:*
https://github.com/bcgov/entity/issues/24455
> 24455 - Changes to skip membership check

- auth-api/src/auth_api/__init__.py
- queue_services/auth-queue/src/auth_queue/resources/worker.py
> more logging fixes

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/views/pay/eft/ShortNameDetailsView.vue
> Change how show eft refund works

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/models/pay/short-name.ts
- auth-web/src/views/pay/eft/ShortNameDetailsView.vue
> Change display refund mechanics

- queue_services/account-mailer/src/account_mailer/email_templates/paymanet_pending.html
> Remove html tags from online banking

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/account-settings/transaction/TransactionsDataTable.vue
- auth-web/src/composables/transactions-factory.ts
- auth-web/src/models/transaction.ts
*Issue #:*
https://github.com/bcgov/entity/issues/23620 
> 23620 - Small fixes

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/common/StaffAccountsTable.vue
*Issue #:*
https://github.com/bcgov/entity/issues/21430
- small fix for when search filter state is loaded from local store and new search param members does not exist yet
> 21430 - org search filter check fix

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/common/StaffAccountsTable.vue
*Issue #:*
https://github.com/bcgov/entity/issues/21430
- fix member display string whitespace
- fix column to show padding
- fix display issue with "View more" when there are no users associated to an account
> 21430-UXA Feedback

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/views/pay/eft/ShortNameDetailsView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/24695
> 24695 - Add in Supplier Site UXA tweaks

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/account-settings/statement/Statements.vue
Parallelize statement and statement summary call
> Statement Owing: Set default amount owing to -1, then render when it's 0 or above.

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/common/StaffAccountsTable.vue
- auth-web/src/components/pay/eft/ShortNameRefund.vue
- auth-web/src/views/pay/eft/ShortNameRefundView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/24335
- UXA fixes for dashboard account search
- EFT Refund pre-population fix
- EFT Refund approval disable for same user as initiator
> 24334-EFT refund fixes

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/composables/downloader.ts
- auth-web/src/services/document.services.ts
- auth-web/src/services/payment.services.ts
- auth-web/src/util/constants.ts
*Issue #:*
https://github.com/bcgov/entity/issues/24491
- update EFT Instructions download to new pay document route
> 24491 - EFT Instructions download update

- auth-web/src/routes/index.ts
- auth-web/src/util/navigation.ts
Reverts bcgov/sbc-auth#3179
Doesn't work, causes infinite redirect
> Revert "24226 - Redirect external links"

- .github/workflows/account-mailer-cd.yml
- .github/workflows/auth-api-cd.yml
- .github/workflows/auth-queue-cd.yml
- .github/workflows/auth-web-cd.yml
*Issue #:*
1. Add redeploy option;
2. Add release branch support;
> Add redeploy option and release branch to CD flow.

- auth-api/src/auth_api/resources/v1/user.py
> rename .name -> .value

- auth-api/src/auth_api/utils/util.py
*Issue #:*
https://github.com/bcgov/entity/issues/25019
> 25019 - Update GET/POST affiliation endpoints to support sandbox env

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/assets/scss/base.scss
- auth-web/src/locales/en.json
*Issue #:*
https://github.com/bcgov/entity/issues/21131
removing:
make it consistent with other tiles
> remove strr fee code from account create tile

- auth-web/package.json
- auth-web/src/components/auth/account-settings/statement/StatementsSettings.vue
*Issue #:*
https://github.com/bcgov/entity/issues/23513
Fixing function not being invoked properly when checking for isEFT
> 23513 - Statement setting not reflecting correct option when open

- auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
- auth-web/src/components/auth/account-settings/team-management/InvitationsDataTable.vue
- auth-web/src/components/auth/account-settings/team-management/MemberDataTable.vue
- auth-web/src/components/auth/account-settings/team-management/PendingMemberDataTable.vue
- auth-web/src/components/auth/account-settings/team-management/UserManagement.vue
- auth-web/src/components/auth/common/ProductTOS.vue
- auth-web/src/components/auth/common/StaffAccountsTable.vue
- auth-web/src/components/auth/staff/account-management/StaffAccountManagement.vue
- auth-web/src/components/auth/staff/account-management/StaffPendingAccountInvitationsTable.vue
- auth-web/src/components/auth/staff/review-task/DownloadAffidavit.vue
- auth-web/src/components/datatable/resources/index.ts
- auth-web/src/routes/index.ts
- auth-web/src/routes/router.ts
- auth-web/src/stores/org.ts
- auth-web/src/util/common-util.ts
- auth-web/src/util/constants.ts
- auth-web/src/views/auth/AccountSettings.vue
- auth-web/src/views/auth/staff/ReviewAccountView.vue
- auth-web/src/views/auth/staff/StaffDashboardView.vue
> Put contact staff changes back

- auth-web/src/components/auth/account-settings/product/ProductPayment.vue
- auth-web/src/components/auth/common/Product.vue
- auth-web/src/components/auth/common/TermsOfUseDialog.vue
*Issue #:*
https://github.com/bcgov/entity/issues/24918
> 24918 - Products and Payments UX

- auth-web/src/components/auth/account-settings/product/ProductPayment.vue
- auth-web/src/components/auth/common/Product.vue
- auth-web/src/components/auth/common/TermsOfUseDialog.vue
> Revert "24918 - Products and Payments UX"

- auth-web/src/components/auth/account-settings/product/ProductPayment.vue
- auth-web/src/components/auth/common/Product.vue
- auth-web/src/components/auth/common/TermsOfUseDialog.vue
*Issue #:*
https://github.com/bcgov/entity/issues/24918
> 24918 - PAD TOS logic fix and Products checkbox alignment

- auth-web/src/components/auth/account-settings/payment/AccountPaymentMethods.vue
- auth-web/src/components/auth/account-settings/product/ProductPayment.vue
- auth-web/src/components/auth/common/PaymentMethods.vue
- auth-web/src/stores/user.ts
*Issue #:*
https://github.com/bcgov/entity/issues/24918
> Dialog for unsaved changes

- auth-web/src/components/auth/account-settings/payment/AccountPaymentMethods.vue
- auth-web/src/components/pay/CompletePaymentDetails.vue
- auth-web/src/stores/user.ts
*Issue #:*
https://github.com/bcgov/entity/issues/25449
> 25449 - Add unsaved change warning dialog when user leave the page

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/pay/OutstandingBalances.vue
- auth-web/src/services/payment.services.ts
- auth-web/src/stores/org.ts
- auth-web/src/views/auth/account-freeze/AccountFreezeUnlockView.vue
> EFT - NSF / Outstanding balance flow fixes

- auth-api/flags.json
- auth-api/src/auth_api/services/org.py
- auth-api/tests/unit/services/test_flags.py
*Issue #:*
https://github.com/bcgov/entity/issues/25377
> 25377 - Overrides existing BASIC account creation into PREMIUM

- auth-web/src/components/auth/account-settings/payment/AccountPaymentMethods.vue
*Issue #:*
https://github.com/bcgov/entity/issues/25449
> 25449 bug fix - exit dialog leave without change

- auth-web/src/components/auth/account-settings/payment/AccountPaymentMethods.vue
*Issue #:*
https://github.com/bcgov/entity/issues/25449
> 25449 - Remove guard when user switch accounts

- auth-web/src/components/auth/account-settings/payment/AccountPaymentMethods.vue
*Issue #:*
https://github.com/bcgov/entity/issues/25595
> Add BCOL error message title

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/account-settings/product/ProductPayment.vue
*Issue #:*
https://github.com/bcgov/entity/issues/25746
> Revert Promise.resolve

- auth-web/src/components/auth/account-settings/team-management/InvitationsDataTable.vue
- auth-web/src/components/auth/account-settings/team-management/MemberDataTable.vue
- auth-web/src/components/auth/account-settings/team-management/PendingMemberDataTable.vue
Fixes for coordinators unable to manage members in members, invitations, and pending tab
> Hotfix coordinator fix

- auth-api/migrations/versions/2025_02_10_7425171449c9_remove_products_coodinator.py
- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/views/auth/AccountSettings.vue
> Fix product for admin only

- auth-web/package-lock.json
- auth-web/package.json
*Issue #25522:*
https://github.com/bcgov/entity/issues/25522
> 25522 update_shared_components

- auth-api/migrations/versions/2025_02_12_63cfd9b160d7_basic_to_premium.py
> Update orgs to premium from basic

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/account-settings/payment/AccountPaymentMethods.vue
- auth-web/src/composables/account-create-factory.ts
> Change error text to create/update

- auth-api/src/auth_api/resources/v1/org.py
- auth-api/src/auth_api/services/org.py
- auth-web/src/components/auth/account-settings/payment/AccountPaymentMethods.vue
- auth-web/src/util/common-util.ts
*Issue #:*
https://github.com/bcgov/entity/issues/25595
> 25595 - Add More Payment Error Handling to Create/Update Org

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/create-account/SelectProductPayment.vue
> Current org missing

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/common/PaymentMethods.vue
> Create account fix

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/create-account/SelectProductPayment.vue
- auth-web/src/stores/org.ts
- auth-web/tests/unit/components/PaymentMethods.spec.ts
- auth-web/tests/unit/components/SelectProductPayment.spec.ts
> Product payment unit tests

- auth-api/migrations/versions/2025_02_19_7f48833011c3_add_org_types.py
- auth-api/src/auth_api/exceptions/errors.py
- auth-api/src/auth_api/models/org.py
- auth-api/src/auth_api/utils/enums.py
- auth-api/src/auth_api/utils/roles.py
- auth-api/tests/unit/models/test_org.py
- auth-api/tests/unit/services/test_org.py
*Issue #:*
https://github.com/bcgov/entity/issues/25704
> 25704 - Add org types for readonly staff

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/util/config-helper.ts
> Add in saveConfigToSessionStorage

- auth-web/.env.test.example
> Add in env example for test

- .github/workflows/account-mailer-cd.yml
- .github/workflows/auth-api-cd.yml
- .github/workflows/auth-queue-cd.yml
> CD updates

- auth-api/flags.json
- auth-api/migrations/versions/2025_03_03_0ac9ab145061_set_default_org_type_premium.py
- auth-api/src/auth_api/services/org.py
- auth-api/src/auth_api/services/products.py
- auth-api/src/auth_api/services/validators/payment_type.py
- auth-api/tests/unit/api/test_org.py
- auth-api/tests/unit/api/test_org_authorisations.py
- auth-api/tests/unit/api/test_user_settings.py
- auth-api/tests/unit/services/test_flags.py
- auth-api/tests/unit/services/test_org.py
> Migration for org default

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/composables/product-payment-factory.ts
> Hotfix 2.12.0a

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/common/PaymentMethods.vue
> Missing isCreateAccount for PAD

- auth-web/.env.example
- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/stores/business.ts
- auth-web/src/stores/codes.ts
- auth-web/src/util/http-util.ts
- auth-web/tests/unit/components/ProductPayment.spec.ts
- auth-web/vite.config.ts
> Add in App-Name to headers

- auth-web/vite.config.ts
> bug fix - /gcbrun error

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/vite.config.ts
*Issue #:*
https://github.com/bcgov/entity/issues/26030
> fix sbc-common-components not found error

- auth-api/migrations/versions/2025_03_13_2b69b3c83578_26014_permissions_updates_2.py
*Issue #:*
https://github.com/bcgov/entity/issues/26014
- add missing permissions for COORDINATOR
> 26014 - permissions update

- auth-api/migrations/versions/2025_03_14_0879befaf0b6_26014_permissions_updates_3.py
- auth-api/src/auth_api/resources/v1/user.py
- auth-api/src/auth_api/services/user.py
- auth-api/src/auth_api/utils/roles.py
*Issue #:*
https://github.com/bcgov/entity/issues/26014
- Contact Centre permissions updates
- reset_otp role updates
> 26014 - permission fixes

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/views/auth/staff/StaffDashboardView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/15568
> 15568  - StaffDashboardView load page without permission

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/mixins/NextPageMixin.vue
*Issue #:*
https://github.com/bcgov/entity/issues/26014
- fix staff sync account switching bug
> 26014 - staff permissions account switch bug

- .github/workflows/account-mailer-ci.yml
> test changes to account-mailer-ci.yml

- .github/workflows/account-mailer-ci.yml
> test account-mailer-ci.yml

- auth-web/package-lock.json
- auth-web/package.json
> Solve conflict on package version

- queue_services/account-mailer/src/account_mailer/email_templates/pad_invoice_email.html
- queue_services/account-mailer/src/account_mailer/resources/worker.py
*Issue #:*
https://github.com/bcgov/entity/issues/15674
small fix for: 
> 15674 - PAD Confirmation Email Wording Tweaks

- queue_services/account-mailer/src/account_mailer/email_processors/ejv_failures.py
> add comment about future upgrade

- auth-web/.env.example
- auth-web/devops/vaults.env
- auth-web/index.html
- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/main.ts
- auth-web/tests/unit/services/task.service.spec.ts
- auth-web/tests/unit/views/AccountSuspendedView.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/25609
> 25609 - Get google analytics rolling

- auth-api/src/auth_api/services/google_store.py
- auth-api/tests/unit/services/test_google_store.py
> experiment with compute engine credentials

- auth-api/src/auth_api/services/google_store.py
- auth-api/tests/conftest.py
- auth-api/tests/unit/services/test_google_store.py
> 26547 feature remove minio from auth api

- auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
> 26272 - lint fix

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/tests/unit/setup.ts
> upgrade sbc-common-components version

- queue_services/account-mailer/src/account_mailer/email_templates/pad_invoice_email.html
*Issue #:*
https://github.com/bcgov/entity/issues/15674
> Fix extra blank line in transaction email template

- queue_services/account-mailer/src/account_mailer/email_templates/pad_invoice_email.html
… charged'
*Issue #:*
https://github.com/bcgov/entity/issues/15674
fix for:
> Fix missing line break on pad confirmation email

- auth-api/src/auth_api/resources/v1/affiliation_invitation.py
> Small fix for auth check

- auth-api/src/auth_api/config.py
- auth-api/src/auth_api/services/invitation.py
- auth-api/src/auth_api/services/org.py
*Issue #:*
https://github.com/bcgov/entity/issues/27041
> Auto approval for SANDBOX so BCEID don't need staff approval

- auth-api/src/auth_api/config.py
- auth-api/src/auth_api/resources/v1/affiliation_invitation.py
- auth-api/src/auth_api/schemas/schemas/user_settings_response.json
*Issue #:*
https://github.com/bcgov/entity/issues/27099
When you don't include the origin header you get:
> 27099 - Fix HTTP_ORIGIN issue for API users

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/views/auth/BusinessProfileView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/25528
> 25528 fix_typo_edit_business_profile

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/mixins/NextPageMixin.vue
*Issue #:*
https://github.com/bcgov/entity/issues/27100
- add missing redirect flow for external staff when accepting invitation
> 27100 - external staff invite accept redirect fix

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/mixins/NextPageMixin.vue
*Issue #:*
https://github.com/bcgov/entity/issues/27100
- fix GOVM invite redirect ordering
> 27100-govm invite fix

- auth-api/pyproject.toml
> auth-api - CI fix, pin marshmallow

- auth-api/pyproject.toml
- auth-api/src/auth_api/services/membership.py
- auth-api/src/auth_api/utils/enums.py
- auth-api/src/auth_api/utils/roles.py
- auth-api/tests/unit/models/test_org.py
- queue_services/account-mailer/tests/unit/test_worker_queue.py
*Issue #:*
https://github.com/bcgov/entity/issues/27100
- error in _create_payment_for_org() referencing OrgType[org.type_code]
> 27100 - fix enum referencing error

- auth-api/src/auth_api/resources/v1/entity.py
- auth-api/src/auth_api/services/authorization.py
- auth-api/src/auth_api/utils/enums.py
- auth-api/tests/unit/api/test_entity.py
- auth-api/tests/unit/services/test_authorization.py
- auth-api/tests/utilities/factory_scenarios.py
*Issue #22217:*
https://github.com/bcgov/entity/issues/22217 
- adding verification in the auth_check to see if the user is competent authority
> 22217 - feat: verify user is competent authority

- auth-web/.env.example
- auth-web/.env.test.example
- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/mixins/NextPageMixin.vue
- auth-web/src/util/constants.ts
- auth-web/src/views/auth/AcceptInviteView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/27100
- Updated to check against invitation organization type and status specific to external staff
> 27100 - external staff accept invite change to check invitation instead

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/tests/unit/components/InviteUsersForm.spec.ts
…ount"
*Issue #:*
https://github.com/bcgov/entity/issues/27336
> 27336 - Add unit test for "bcol admin invite other admins to a customer's acc

- auth-api/src/auth_api/resources/v1/org.py
- auth-api/tests/unit/api/test_affiliation_invitation.py
- auth-api/tests/unit/api/test_org.py
> Revert "Remove depreciated (#3375)"

- auth-api/src/auth_api/services/affiliation_invitation.py
- auth-api/tests/unit/services/test_affiliation_invitation.py
- queue_services/account-mailer/src/account_mailer/email_processors/common_mailer.py
- queue_services/account-mailer/src/account_mailer/email_templates/affiliation_invitation_email.html
- queue_services/account-mailer/src/account_mailer/resources/worker.py
- queue_services/account-mailer/src/account_mailer/version.py
*Issue #:*
https://github.com/bcgov/entity/issues/26898
Two parts
1) Update to the affiliations email template
2) Adding business identifier
> 26898 - Update to affiliation template.

- queue_services/account-mailer/src/account_mailer/email_templates/affiliation_invitation_email.html
*Issue #:*
https://github.com/bcgov/entity/issues/26898
A few tweaks and additions to account mailer email template
> 26898 - couple of quick template updates

- queue_services/auth-queue/poetry.lock
- queue_services/auth-queue/src/auth_queue/resources/worker.py
- queue_services/auth-queue/tests/unit/test_names_worker_queue.py
> Auth queue ci

- auth-web/package-lock.json
- auth-web/package.json
*Issue #:*
https://github.com/bcgov/entity/issues/27546
> 27546 - Upgraded the footer version

- auth-api/flags.json
- auth-api/src/auth_api/models/entity.py
- auth-api/src/auth_api/services/affiliation.py
- auth-api/src/auth_api/services/affiliation_invitation.py
- auth-api/src/auth_api/services/membership.py
- auth-api/src/auth_api/utils/auth_event_publisher.py
- auth-api/src/auth_api/utils/converter.py
- auth-api/src/auth_api/utils/serializable.py
- auth-api/tests/unit/services/test_affiliation.py
- auth-api/tests/unit/services/test_affiliation_invitation.py
- auth-api/tests/unit/services/test_membership.py
- auth-api/tests/unit/services/test_org.py
*Issue #:*
https://github.com/bcgov/entity/issues/27075
- auth events for business affiliated, business unaffiliated, team member removal
> 27075 - affiliation / team member moved events

- auth-api/src/auth_api/resources/v1/affiliation_invitation.py
- auth-api/src/auth_api/services/user.py
Reverts bcgov/sbc-auth#3377
This allows USERS to work under delegation AND magic link, it isn't clear what the requirement is here.
I'll put in a change that just does USERS for Magic link for now
> Revert "27068 - updated affiliation_invitation_verification"

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/util/constants.ts
> Conditionally show/hide price list

- queue_services/account-mailer/src/account_mailer/email_templates/affiliation_invitation_email.html
*Issue #:*
https://github.com/bcgov/entity/issues/26898
Update to wording/layout of affiliation template.
> 26898 Update to template layout/wording

- queue_services/account-mailer/src/account_mailer/email_templates/affiliation_invitation_email.html
> Revert "26898 Update to template layout/wording"

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/create-account/AccountCreate.vue
- auth-web/src/components/auth/create-account/SelectProductPayment.vue
- auth-web/src/components/auth/create-account/non-bcsc/NotaryContactForm.vue
- auth-web/src/routes/router.ts
- auth-web/src/views/auth/AcceptInviteView.vue
- auth-web/src/views/auth/create-account/NonBcscAccountSetupView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/28396
link still same. auth-web has some bugs.
fix:
http://localhost:8080/setup-non-bcsc-account/3920:
submit:
> 28396 - Pending application notification link page issue

- auth-api/src/auth_api/exceptions/errors.py
- auth-api/src/auth_api/services/membership.py
- auth-api/src/auth_api/services/org.py
- auth-api/tests/conftest.py
- auth-api/tests/unit/api/test_org.py
- auth-api/tests/unit/services/test_membership.py
- auth-api/tests/utilities/factory_utils.py
*Issue #:*
https://github.com/bcgov/entity/issues/27431
> 27431 - add block nsf client from creating new account

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/account-settings/team-management/MemberDataTable.vue
*Issue #:*
https://github.com/bcgov/entity/issues/28452
> 28452 - Add in fix to remove accounts

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
- auth-web/tests/unit/components/AccountInfo.spec.ts
> Fix for suspend dialog text

- auth-api/src/auth_api/schemas/schemas/api_key.json
- auth-api/tests/unit/api/test_org_api_keys.py
> Remove environment from api key generation

- auth-web/src/components/pay/PayWithOnlineBanking.vue
- auth-web/src/util/config-helper.ts
- queue_services/account-mailer/src/account_mailer/email_templates/paymanet_pending.html
*Issue #:*
https://github.com/bcgov/entity/issues/27618
- online banking payment pending email updates (payee / payment identifier)
> 27618 - payment pending updates

- queue_services/account-mailer/Dockerfile
> Add in docker buildkit

- queue_services/account-mailer/Dockerfile
> Revert "Add in docker buildkit"

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/create-account/SelectProductPayment.vue
- queue_services/account-mailer/src/account_mailer/email_templates/resubmit_bceid_org.html
*Issue #:*
https://github.com/bcgov/entity/issues/28396
> 28396 - Update email instructions for on hold account and Enable submit button on create account

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/BusinessContactForm.vue
- auth-web/src/views/auth/BusinessProfileView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/27295
- Fix the issue by adding current account id to url
> 27295 - Fix Return From Business Profile Error

- auth-web/src/composables/product-payment-factory.ts
*Issue #:*
https://github.com/bcgov/entity/issues/25936
> 25936 - Change the payee name to avoid client confusion - description update

- auth-api/src/auth_api/services/entity_mapping.py
- auth-api/tests/unit/services/test_entity_mapping.py
> Fix performance issues

- auth-api/src/auth_api/config.py
- auth-api/src/auth_api/resources/v1/org.py
- auth-api/src/auth_api/services/affiliation.py
- auth-api/src/auth_api/services/entity_mapping.py
- auth-api/tests/unit/api/test_org.py
- auth-api/tests/unit/services/test_entity_mapping.py
> Business Dashboard fixes

- auth-api/src/auth_api/services/affiliation.py
- auth-api/src/auth_api/services/entity_mapping.py
- auth-api/tests/unit/services/test_entity_mapping.py
> Business Dashboard changes continued

- auth-api/src/auth_api/resources/v1/org.py
- auth-api/src/auth_api/services/entity_mapping.py
- auth-api/tests/unit/services/test_entity_mapping.py
*Issue #:*
https://github.com/bcgov/entity/issues/28977
> 28977 - Add in hasMore, more unit tests

- .github/workflows/notebook-report-cd.yml
*Issue #:*
Change the name for the job
> 25816-Jupyter Notebook Error Notification from sbc-auth for processing (need to move job to GCP)

- auth-api/src/auth_api/resources/v1/org.py
- auth-api/src/auth_api/services/affiliation.py
- auth-api/src/auth_api/services/entity_mapping.py
- auth-api/tests/unit/api/test_org.py
*Issue #:* 
https://github.com/bcgov/entity/issues/28974
- Added Pagination flag update after pulling details from lear and names.
*Dependencies*
- https://github.com/bcgov/namex/pull/1855
- https://github.com/bcgov/lear/pull/3606
> 28974 - Search pagination

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/views/pay/RefundView.vue
> Add in loader for refund button

- auth-api/src/auth_api/services/affiliation.py
*Issue #:*
https://github.com/bcgov/entity/issues/28974
- Handle previous response for fetch name requests for affiliations.
> 28974 -  Namex Requests Response Handling

- auth-web/package-lock.json
- auth-web/package.json
- auth-web/src/components/auth/common/StaffAccountsTable.vue
- auth-web/src/models/Organization.ts
> Update staff account search account type filter

- queue_services/auth-queue/poetry.lock
- queue_services/auth-queue/pyproject.toml
> fix jinja2 security

- auth-api/migrations/versions/2025_09_05_57e4f388c6ed_add_version_table_users.py
- auth-api/src/auth_api/models/user.py
- queue_services/account-mailer/poetry.lock
- queue_services/account-mailer/pyproject.toml
- queue_services/auth-queue/poetry.lock
- queue_services/auth-queue/pyproject.toml
https://github.com/bcgov/entity/issues/30577
> 30557 - Fix for versioning table for users

- auth-api/src/auth_api/resources/v1/org.py
*Issue #:*
https://github.com/bcgov/entity/issues/30421
Fix Mailing address errors
> 30421 - mailing address fix

- auth-api/src/auth_api/services/activity_log.py
- auth-api/tests/unit/api/test_activity_log.py
*Issue #:*
https://github.com/bcgov/entity/issues/30308
> 30308 - Activity Log - Statement Interval 
