auth-web/package.json, auth-web/src/assets/styl/base.styl, auth-web/src/assets/styl/layout.styl, auth-web/src/components/Aside.vue, auth-web/src/components/Footer.vue, auth-web/src/components/Header.vue, auth-web/src/components/PasscodeForm.vue, auth-web/src/components/SupportInfoCard.vue, auth-web/src/views/Home.vue, package-lock.json
Initial Layout/Markup for Passcode Interface / Sign-in page
=> Initial Layout / Markup for the Passcode Interface

auth-api/.idea/workspace.xml, auth-api/requirements.txt, auth-api/requirements/prod.txt
Signed-off-by: PWEI <patrick.wei@gov.bc.ca>
=> apply lear api project structure; add trace and userinfo endpoint

auth-web/src/assets/styl/base.styl, auth-web/src/assets/styl/layout.styl, auth-web/src/assets/styl/overrides.styl, auth-web/src/assets/styl/theme.styl, auth-web/src/components/Aside.vue, auth-web/src/components/PasscodeForm.vue, auth-web/src/components/SupportInfoCard.vue, auth-web/src/locales/en.json, auth-web/src/views/Home.vue
Finalized the design and content for the Passcode interface. Some additional changes as follows:
- Updating and cleaning up some redundant styling in the global stylus files
- Change / updated some components to reference REM and EM units for sizing (more flexibility with sizing components)
- Moved the button-specific loading indicator selector to the 'overrides' stylus document (we might want to consider renaming this eventually)
- Added a few global variables to the theme stylus document
=> [entity-403] Finalizing UX & Content for Passcode UI

auth-api/Jenkinsfile, auth-api/openshift/templates/auth-api-deploy.json
Signed-off-by: PWEI <patrick.wei@gov.bc.ca>
=> update build configuration

auth-api/Jenkinsfile
Signed-off-by: PWEI <patrick.wei@gov.bc.ca>
=> update pipeline scripts

auth-web/vue.config.js
*Issue #:*
- #### Common
- #### REST 
=> trying to handle 404 page

auth-api/src/auth_api/__init__.py, auth-api/src/auth_api/resources/__init__.py, auth-api/src/auth_api/resources/token.py, auth-api/tests/postman/auth-api.postman_environment.json, auth-api/tests/unit/services/test_keycloak.py
*Issue #:*
- #### Common
- #### REST 
=> Fix code to according to pylint and flake8 standard.

auth-api/migrations/versions/8d3f85a7dfb3_.py, auth-api/src/auth_api/models/action.py, auth-api/src/auth_api/models/action_log.py, auth-api/src/auth_api/models/affiliation.py, auth-api/src/auth_api/models/affiliation_business.py, auth-api/src/auth_api/models/affiliation_status.py, auth-api/src/auth_api/models/user_type.py, auth-api/src/auth_api/models/users.py, auth-api/src/auth_api/resources/admin/users.py, auth-api/src/auth_api/resources/token.py, auth-api/src/auth_api/schemas/add_user.json, auth-api/src/auth_api/status.py
*Issue #:*
- #### Common
- #### REST 
=> Add data migration file and data models for auth tables.

auth-web/.env.development, auth-web/.env.local, auth-web/package.json, auth-web/src/components/auth/PasscodeForm.vue, auth-web/src/components/pay/PaymentForm.vue, auth-web/src/components/pay/PaymentReturnForm.vue, auth-web/src/locales/en.json, auth-web/src/main.ts, auth-web/src/router.ts, auth-web/src/services/login.services.ts, auth-web/src/services/payment.services.ts, auth-web/src/util/interceptors.ts, auth-web/src/views/Home.vue, auth-web/tests/unit/PaymentReturnForm.spec.ts, auth-web/tests/unit/passcodeForm.spec.ts, auth-web/tests/unit/payment.services.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/600
- Handled redirection from coops [any client who is using the pay system]  to paybc and vice versa
=> Redirects from coops to paybc and back.   bcgov/entity#600

auth-web/src/App.vue, auth-web/src/components/auth/PasscodeForm.vue, auth-web/src/components/pay/PaymentForm.vue, auth-web/src/services/payment.services.ts, auth-web/tests/unit/passcodeForm.spec.ts
*Issue #:*
Fixed linting errors
Uncommented routing
=> Fixed Linting , Uncommented rodirect

auth-api/src/auth_api/resources/logout.py
*Issue #:*
- #### Common
- #### REST 
=> fix tracer

auth-web/src/services/payment.services.ts, auth-web/tests/unit/payment.services.spec.ts
Changed receipt to URL Param.iudpated tests
=> Receipt number fix

auth-api/src/auth_api/__init__.py, auth-api/src/auth_api/exceptions/__init__.py, auth-api/src/auth_api/models/__init__.py, auth-api/src/auth_api/models/user.py, auth-api/src/auth_api/models/users.py, auth-api/src/auth_api/resources/__init__.py, auth-api/src/auth_api/resources/logout.py, auth-api/src/auth_api/resources/token.py, auth-api/src/auth_api/services/keycloak.py, auth-api/src/auth_api/services/user.py, auth-web/.env.local, auth-web/.env.test, auth-web/.gitignore, auth-web/src/components/auth/PasscodeForm.vue, auth-web/src/services/iframe.services.ts, auth-web/src/util/interceptors.ts, auth-web/tests/unit/passcodeForm.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/651
- #### Common
- #### REST 
=> Add item to session storage for logout and tracking. #651

auth-web/.browserslistrc, auth-web/babel.config.js, auth-web/src/main.ts
*Issue #:* https://github.com/bcgov/entity/issues/819
*Description of changes:* Added babel-polyfill to ensure that the app works in IE11
- #### Common
- #### REST 
=> Add babel-polyfill to support IE11

auth-web/openshift/Caddyfile, auth-web/public/static/config/configuration.json, auth-web/src/services/login.services.ts, auth-web/src/services/payment.services.ts, auth-web/tests/unit/confighelper.spec.ts, auth-web/tests/unit/payment.services.spec.ts, auth-web/vue.config.js
*Issue #:*
- Changed put to patch
- used full url's in axios calls
- fixed failing tests
- removed caddy config which is irrelevant now 
- #### Common
- #### REST 
=> patch call , changed urls to absolute

auth-api/jenkins/dev.groovy, auth-api/jenkins/prod.groovy, auth-api/jenkins/test.groovy, auth-api/openshift/templates/auth-api-build.json, auth-api/openshift/templates/auth-api-deploy.json, auth-api/openshift/templates/auth-api-pipeline.json, auth-api/openshift/templates/auth-api-pre-deploy.json, auth-db/openshift/templates/postgresql-deploy.json, auth-web/jenkins/dev.groovy, auth-web/jenkins/prod.groovy, auth-web/jenkins/test.groovy
*Issue #:*
- #### Common
- #### REST 
=> clean up template and pipeline.

auth-api/jenkins/prod.groovy, auth-web/jenkins/test.groovy
*Issue #:*
- #### Common
- #### REST 
=> Fixed taging issue in test and prod

auth-api/openshift/templates/auth-api-deploy.json
*Issue #:*
- #### Common
- #### REST 
=> Change env setting in deployment template

auth-web/package.json, auth-web/src/main.ts
*Issue #:* https://github.com/bcgov/entity/issues/961
- Replaced @babel/polyfill package with `core-js/stable` and `regenerator-runtime/runtime`
- This issue was first identified and fixed in the coops ui and the same fix has been applied here
- #### Common
- #### REST 
=> Replace deprecated @babel/polyfill package

auth-api/jenkins/prod.groovy, auth-web/jenkins/prod.groovy
Signed-off-by: IDIR\schen <steven.chen@gov.bc.ca>
*Issue #:*
- #### Common
- #### REST 
=> 897-Deploy-To-PROD

auth-api/jenkins/dev.groovy, auth-api/tests/unit/conf/test_version.py, docs/build-deploy.md
*Issue #:*
- #### Common
- #### REST 
=> Update pytest pipeline parameter

docs/build-deploy.md
=> corrected missing .json

auth-web/package.json, auth-web/src/components/auth/BusinessContactForm.vue, auth-web/src/components/auth/PasscodeForm.vue, auth-web/src/store/modules/business/index.ts
- Upgrade Vue version to match common
- Add missing Vuex mutation
*Issue #:*
- #### Common
- #### REST 
=> Remove iframe emit

auth-api/jenkins/dev.groovy
*Issue #:*
- #### Common
- #### REST 
=> Fixed a typo

auth-api/tests/utilities/decorators.py
*Issue #:*
- #### Common
- #### REST 
=> Fixed the pod testing parameter setting

auth-web/src/components/auth/PasscodeForm.vue
*Issue #:*
*Description of changes:* Fixes the stalled spinner on login button when login credentials are incorrect.
- #### Common
- #### REST 
=> Fix login button spinner on failed login

auth-api/Jenkinsfile-post-mvp, auth-api/jenkins/dev-post.groovy, auth-web/Jenkinsfile-post-mvp, auth-web/jenkins/dev-post.groovy, auth-web/openshift/templates/auth-web-deploy.json
*Issue #:*
- #### Common
- #### REST 
=> post-mvp related files.

auth-web/package.json, auth-web/src/App.vue, auth-web/src/components/pay/PaySystemAlert.vue, auth-web/src/models/PaySystemStatus.ts, auth-web/src/services/payment.services.ts, auth-web/src/store/index.ts, auth-web/src/store/modules/payment/index.ts, auth-web/src/views/BusinessProfile.vue, auth-web/tests/unit/Footer.spec.ts, auth-web/tests/unit/Header.spec.ts, auth-web/tests/unit/businessContactForm.spec.ts
*Issue #:*
- Changes for showing paybc downtime banner
_tests are currently broken,I will fix them in the next PR_
=> Changes for adding system alerts in case of paybc is down

auth-api/src/auth_api/models/user.py, auth-api/src/auth_api/services/user.py, auth-api/tests/unit/models/test_user.py
*Issue #:* #1020
*Description of changes:*  A small refactor to some of the service calls in the User API.  Also added some additional unit tests.
- #### Common
- #### REST 
=> User API - small refactor

auth-api/jenkins/dev-post.groovy, auth-api/openshift/templates/auth-api-deploy.e2e.json, docs/build-deploy.md
*Issue #:*
- #### Common
- #### REST 
=> Update post pipeline, add e2e deploy template and update document

auth-web/src/components/pay/PaymentForm.vue
*Issue #:*
Minor fix on makepayment error handling
Minor fix on makepayment error handling
=> Fixing payment error handling

auth-web/src/components/auth/BusinessContactForm.vue
*Issue #:* #1063
* Fix an issue where the business contact form could be saved when emails don't match.
* Disable save button until form is valid
- #### Common
- #### REST 
=> Issue #1063 - Fix missed validation on email mismatch

auth-web/src/App.vue, auth-web/src/assets/styl/layout.styl, auth-web/src/views/BusinessProfile.vue, auth-web/src/views/Home.vue, auth-web/src/views/PageNotFound.vue
*Issue #:* There isn't a corresponding ticket, but these changes were made to address some unnecessary white space and incorrect positioning in the layout. This was done in collaboration with @jeznorth.
- The layout component was causing some extra white space to appear around the main content of each page. As it would require some time to properly refactor this component, SbcLayout was removed from App.vue and the header and footer were instead placed directly in App.vue.
- Added logic to ensure that the header always remains in the correct position and scrolls down with the page
- Wrapped each page in a container to ensure that the content in positioned correctly in the center of the page
- #### Common
- #### REST 
- #### Code …
=> Fix the layout of the application

auth-api/requirements.txt, auth-api/requirements/repo-libraries.txt, auth-api/src/auth_api/__init__.py, auth-api/src/auth_api/resources/__init__.py, auth-api/src/auth_api/resources/logout.py
*Issue [#:1034](https://github.com/bcgov/entity/issues/1034)
Add global exception handling to handle common exceptions:
AuthError
HttpException
SQLAlchemyError
default_exceptions from werkzeug.exceptions library
- #### Common
- #### REST 
=> Add global exception handler.

auth-web/src/components/auth/BusinessContactForm.vue
*Issue #:* #1072
Make email entry mandatory on the business contact page by removing the skip button.
- #### Common
- #### REST 
=> Remove skip button to make email entry mandatory

auth-api/src/auth_api/models/affiliation.py, auth-api/src/auth_api/models/entity.py, auth-api/src/auth_api/resources/__init__.py, auth-api/src/auth_api/resources/affiliation.py, auth-api/src/auth_api/schemas/__init__.py, auth-api/src/auth_api/schemas/affiliation.py, auth-api/src/auth_api/schemas/schemas/affiliation.json, auth-api/src/auth_api/services/__init__.py, auth-api/src/auth_api/services/affiliation.py, auth-api/src/auth_api/services/entity.py, auth-api/tests/postman/auth-api-bcsc.postman_collection.json, auth-api/tests/postman/auth-api.postman_environment.json, auth-api/tests/unit/api/test_affiliation.py, auth-api/tests/unit/api/test_org.py, auth-api/tests/unit/models/test_affiliation.py, auth-api/tests/unit/services/test_affiliation.py
*Issue #:*
- #### Common
- #### REST 
=> 1022 create affiliation endpoints

auth-web/package.json, auth-web/src/components/auth/ManagementMenu.vue, auth-web/src/router.ts, auth-web/src/util/constants.ts, auth-web/src/views/management/EntityManagement.vue, auth-web/src/views/management/Template.vue, auth-web/src/views/management/UserManagement.vue
*Issue #:* 1024
Create a template with menu that can be used to display other components/views as they are created.  Menu choice is just a v-nagivation-drawer, and could be easily replaced with a more sophisticated menu system.
- #### Common
- #### REST 
=> Issue #1024: UI Template/Layout

auth-web/src/components/auth/BusinessContactForm.vue, auth-web/src/views/BusinessProfile.vue
*Issue #:* 1135
Added edit state to business contact info if contact info already exists.  Currently the only way to access it is through the route `/auth/businessprofile`.  
- #### Common
- #### REST 
=> Issue #1135: Edit Business Contact Info

auth-web/src/components/pay/PaymentForm.vue, auth-web/src/components/pay/PaymentReturnForm.vue
*Issue #:*
Fixing issue with camelCase response attributes
Fixing issue with camelCase response attributes
=> Fixing issue with the response attribute name

auth-web/src/App.vue, auth-web/src/assets/scss/base.scss, auth-web/src/assets/scss/layout.scss, auth-web/src/assets/scss/overrides.scss, auth-web/src/views/AuthHome.vue, auth-web/src/views/BusinessProfile.vue, auth-web/src/views/Home.vue
As the title states, fixed the missing @font-face declaration and updated the missing 'header-group' positioning from previous PR.
- Small white-space fixes (spacing)
=> [entity1294] Fix Missing Declarations and Header Position

auth-web/src/App.vue, auth-web/src/assets/scss/base.scss, auth-web/src/views/AuthHome.vue, auth-web/src/views/BusinessProfile.vue
Fixed missing @font-face declarations and previous fix for the header component positioning (missed in a merge conflict)
- Removed unused 'appBodyOffset' binding in App.vue (previously used to offset the body w/ calculated height of header component).
- Removed class 'app-container' in App.vue (Vuetify 2.0 utilizes 'v-application' select now - we are leveraging this).
- Added appropriate font stack to base.scss (removed from overrides)
- Fixed redundant markup and removed non-functional button (Learn More) from the AuthHome.vue
- Fixed lint errors in BusinessProfile.vue
=> [entity1294] Fix Font Declarations & Header Component Position

auth-api/docs/contract.yaml, auth-api/migrations/versions/615db0d23fee_update_authorization_view.py, auth-api/src/auth_api/models/views/authorization.py, auth-api/src/auth_api/schemas/authorization.py, auth-api/src/auth_api/services/authorization.py, auth-api/tests/unit/api/test_entity.py, auth-api/tests/unit/api/test_user.py, auth-api/tests/unit/models/views/test_authorization.py, auth-api/tests/unit/services/test_authorization.py
*Issue #:*
https://github.com/bcgov/entity/issues/1239
- Changing role to orgMembership
- Adding roles list which would return view and edit for now
- #### Common
- #### REST 
=> #1239 : Changes for incorporating the fine grained security

auth-api/src/auth_api/models/invitation.py, auth-api/src/auth_api/resources/invitation.py, auth-api/src/auth_api/resources/token.py, auth-api/src/auth_api/services/invitation.py, auth-api/tests/unit/api/test_invitation.py, auth-api/tests/unit/models/test_invitation.py, auth-api/tests/unit/services/test_authorization.py, auth-api/tests/unit/services/test_invitation.py
=> Flake 8 fixes - Invitation API

auth-api/src/auth_api/resources/entity.py, auth-api/src/auth_api/resources/org.py, auth-api/src/auth_api/resources/token.py, auth-api/src/auth_api/services/entity.py, auth-api/src/auth_api/services/membership.py, auth-api/src/auth_api/services/org.py, auth-api/src/auth_api/utils/roles.py, auth-api/tests/postman/auth-api-load-entities.postman_collection.json, auth-api/tests/postman/auth-api-load-entities.postman_environment.json, auth-api/tests/unit/api/test_entity.py, auth-api/tests/unit/services/test_entity.py, auth-web/src/components/auth/AddBusinessForm.vue, auth-web/src/store/modules/business/index.ts
*Issue #:*
https://github.com/bcgov/entity/issues/1379
Removes POST to /token endpoint on business affiliation.  Also added postman collection to be used by service account when loading entities into auth database.
*Checklist:*
=> Update /token endpoint

auth-api/config.py, auth-api/openshift/templates/auth-api-deploy.json, auth-api/openshift/templates/auth-api-pre-deploy.json, auth-api/requirements.txt, auth-api/requirements/prod.txt, auth-api/src/auth_api/__init__.py, auth-web/src/components/auth/SearchBusinessForm.vue
*Issue #:*
https://github.com/bcgov/entity/issues/1351
- 1351 : Setting up sentry for APIs
- Changing the search business page to remove the temporary text and adding the search as the default action
*Checklist:*
=> 1351 : Setting up sentry for APIs

auth-api/tests/postman/auth-api.postman_collection.json, auth-api/tests/postman/auth-api.postman_environment.json
=> Postman collection - Invitation API

notify-api/tests/postman/notify-api.postman_collection.json
Signed-off-by: pwei1018 <pwei@ND081076.idir.BCGOV>
*Issue #:*
*Checklist:*
=> Add postman tests for Notify Service

auth-web/public/config/configuration.json, auth-web/src/assets/scss/base.scss, auth-web/src/assets/scss/overrides.scss, auth-web/src/components/SupportInfoCard.vue, auth-web/src/components/auth/InviteUsersForm.vue, auth-web/src/components/auth/ModalDialog.vue, auth-web/src/components/auth/PasscodeForm.vue, auth-web/src/components/auth/UserProfileForm.vue, auth-web/src/views/Home.vue, auth-web/src/views/UserProfile.vue, auth-web/src/views/management/EntityManagement.vue, auth-web/src/views/management/UserManagement.vue
Clean up the front-end for various components. Details as noted below
Configuration.json
- Updated (removed post as per discussion with @sutherlanda 
base.scss
- Fixed the @font-face declaration order
- Various theme fixes / font color properties (increasing the default opacity on the default text)
- Updating the application background color to conform to government style guide
overrides.scss
- Removed font declaration (moved to base.scss)
- Removed the custom progress spinner styling (leverage the button loading property)
- Minor spacing / sizing fixes
SupportInfoCard.vue
- Refactored to leverage the 'v-card' component structure
- Updating styling to conform to new structure
InviteUserForm.vue
- Removed unused/redundant styling
- Minor spacing / sizing fixes
ModalDialog.vue
- Added …
=> UI Clean-up

auth-web/src/components/auth/BusinessContactForm.vue, auth-web/src/components/auth/UserProfileForm.vue
*Issue #:* 1447
https://github.com/bcgov/entity/issues/1447
The auth API expects lowercase emails so this change ensure any uppercase characters are converted prior to making the POST.
*Checklist:*
=> Force user and business profile emails to lowercase

auth-api/src/auth_api/services/invitation.py
*Issue #:*
https://github.com/bcgov/entity/issues/1435
set Jinja autoescape to true 
*Checklist:*
=> added autoescape true to fix Bandit vulernability

auth-web/src/components/auth/Unauthorized.vue, auth-web/src/locales/en.json, auth-web/src/models/userInfo.ts, auth-web/src/router.ts, auth-web/src/services/keycloak.services.ts, auth-web/src/store/modules/user/index.ts, auth-web/src/util/constants.ts
*Issue #:*
https://github.com/bcgov/entity/issues/1382
- Changes for unauthorized check on each routes
- Added allowedRoles and disabledRoles to route meta which will be checked against on each route change
*Checklist:*
=> 1382 : Changes for unauthorized check on routes

auth-web/src/components/pay/PaymentForm.vue
=> need not encode the url ;no more a url param

auth-web/public/config/configuration.json, auth-web/src/components/auth/UserProfileForm.vue, auth-web/src/models/userInfo.ts, auth-web/src/plugins/vuetify.ts, auth-web/src/services/keycloak.services.ts, auth-web/src/services/user.services.ts, auth-web/src/store/modules/user.ts, auth-web/src/util/constants.ts, auth-web/vue.config.js
*Issue #:* 1545
https://github.com/bcgov/entity/issues/1545
Add session storage item to support username display in header (sbc-common-components)
*Checklist:*
=> Changes to AUTH-WEB to support username display

auth-web/src/locales/en.json, auth-web/src/views/AuthHome.vue
- Updated en.json to include correct phone number
- Removed hard-coded strings and replaced with reference to json.
=> [entity1751] Fix Incorrect Contact Information

auth-web/src/components/auth/InvitationsDataTable.vue, auth-web/src/components/auth/MemberDataTable.vue, auth-web/src/components/auth/PendingMemberDataTable.vue, auth-web/src/locales/en.json
Adding consistent 'no results' labels for each of the user lists.
=> [entity1852] Create Consistent No Record Labels

auth-web/src/App.vue, auth-web/src/assets/scss/base.scss, auth-web/src/assets/scss/layout.scss, auth-web/src/assets/scss/overrides.scss, auth-web/src/components/auth/AddBusinessForm.vue, auth-web/src/components/auth/AffiliatedEntityList.vue, auth-web/src/components/auth/BusinessContactForm.vue, auth-web/src/components/auth/InvitationsDataTable.vue, auth-web/src/components/auth/ManagementMenu.vue, auth-web/src/components/auth/MemberDataTable.vue, auth-web/src/components/auth/PendingMemberDataTable.vue, auth-web/src/components/auth/UserProfileForm.vue, auth-web/src/views/BusinessProfile.vue, auth-web/src/views/UserProfile.vue, auth-web/src/views/management/Dashboard.vue, auth-web/src/views/management/EntityManagement.vue, auth-web/src/views/management/UserManagement.vue
Add recovery contact information to 'Add Business' interface
=> Entity1832

auth-web/src/App.vue, auth-web/src/assets/scss/base.scss, auth-web/src/assets/scss/layout.scss, auth-web/src/assets/scss/overrides.scss, auth-web/src/components/auth/AddBusinessForm.vue, auth-web/src/components/auth/AffiliatedEntityList.vue, auth-web/src/components/auth/BusinessContactForm.vue, auth-web/src/components/auth/InvitationsDataTable.vue, auth-web/src/components/auth/ManagementMenu.vue, auth-web/src/components/auth/MemberDataTable.vue, auth-web/src/components/auth/PendingMemberDataTable.vue, auth-web/src/components/auth/UserProfileForm.vue, auth-web/src/views/BusinessProfile.vue, auth-web/src/views/UserProfile.vue, auth-web/src/views/management/Dashboard.vue, auth-web/src/views/management/EntityManagement.vue, auth-web/src/views/management/UserManagement.vue
General UI Updates / Fixes
- Cleaned up some font-sizing issues
- Increased max container width to 1224px (accommodating vuetify grid/column layouts w/ 12px padding)
- Removed redundant selectors
- Added initial 'cancel' functionality for both the Business Profile and User Profile interfaces
=> General UI Updates / Fixes

auth-api/src/auth_api/services/membership.py
=> https://github.com/bcgov/entity/issues/1929

auth-api/src/auth_api/resources/org.py, auth-api/src/auth_api/services/affiliation.py
*Issue #:* 1930
https://github.com/bcgov/entity/issues/1930
*Checklist:*
=> Allow team member with MEMBER role to add create affiliation

auth-web/src/components/auth/AffiliatedEntityList.vue, auth-web/src/components/auth/ManagementMenu.vue, auth-web/src/views/AuthHome.vue, auth-web/src/views/management/UserManagement.vue
Adding 'Manage Businesses' button for logged in user (users now have a clear call-to-action on how to navigate to this page)
Additional Fixes / Clean-up
- Change v-cards on the home page / manage businesses / manage team pages to 'flat' t(conform with standards with the entity application aesthetic)
- Spacing clean-up on the home page
=> [entity1907] Add Manage Businesses Button for Logged In Users

auth-web/src/views/AcceptInvite.vue
*Issue #:*
https://github.com/bcgov/entity/issues/1951
*Checklist:*
=> org has to be refetched 

auth-web/src/components/auth/BusinessContactForm.vue, auth-web/src/store/modules/business.ts
*Issue #:*
https://github.com/bcgov/entity/issues/1983
*Checklist:*
=> 1983: Fix business identifier set as undefined on business contact update

auth-api/requirements.txt, auth-api/src/auth_api/schemas/schemas/org.json, auth-api/tests/unit/api/test_org.py, auth-api/tests/utilities/factory_scenarios.py, auth-web/src/components/auth/TeamForm.vue, auth-web/src/store/modules/org.ts
*Issue #:*
https://github.com/bcgov/entity/issues/1974
added regex check in the back end for spaces.
added Front end trim and caught exceptions to be shown in the UI. 
Added checks for similar named team creation.
*Checklist:*
=> Entity 1974

auth-api/email_templates/admin_notification_email.html, auth-api/email_templates/business_invitation_email.html, auth-api/email_templates/membership_approved_notification_email.html
*Issue #:*
https://github.com/bcgov/entity/issues/entity1995
Fixing email template rendering issues in gmail.
*Checklist:*
=> [entity1995] Fixing rendering issues for email template in gmail

auth-web/src/locales/en.json, auth-web/src/views/AcceptInviteLanding.vue
*Issue #:*
https://github.com/bcgov/entity/issues/entity2018
Fixing the layout for the Accept Invite Landing Page
*Checklist:*
=> [entity2018] Fix Layout for Accept Invite Landing Page

queue_services/notify-queue/src/notify_service/worker.py
=> Fix queue service db session not closing issue and disable sentry message.

auth-web/src/App.vue
*Issue #:*
Fixed an issue with the system alert message alignment.
*Checklist:*
=> [entity2030] Fix Incorrect Position for System Alert Message

auth-web/src/components/auth/AddBusinessForm.vue, auth-web/src/components/auth/AffiliatedEntityList.vue, auth-web/src/store/modules/business.ts, auth-web/src/views/management/EntityManagement.vue
*Issue #:* 2025
https://github.com/bcgov/entity/issues/2025
Added extra loading feedback and async handling with the modal flow for add business.
*Checklist:*
=> #2025 - Add better async handling for add business (IE bug)

auth-api/src/auth_api/services/invitation.py, auth-api/src/auth_api/services/membership.py, auth-api/src/auth_api/services/notification.py
=> switch back to old mail service

auth-api/src/auth_api/services/membership.py
=> fixed bug of email not being sent-wrong intendation

auth-web/src/components/auth/InviteUsersForm.vue
=> https://github.com/bcgov/entity/issues/2039

auth-web/src/components/auth/InviteUsersForm.vue
*Issue #:*
https://github.com/bcgov/entity/issues/2039
fixed the bug where the model is not bound to the selected value
*Checklist:*
=> selected role not being retained

auth-api/src/auth_api/services/invitation.py, auth-api/src/auth_api/services/membership.py, auth-api/src/auth_api/services/notification.py, auth-web/jenkins/prod.groovy, auth-web/openshift/templates/auth-web-pre-deploy.json, queue_services/notify-queue/jenkins/dev.groovy, queue_services/notify-queue/src/notify_service/worker.py
=> Fixed the FastAPI db session didn't close issue and switch back to using new email service.

auth-web/src/components/auth/InviteUsersForm.vue
*Issue #:*
https://github.com/bcgov/entity/issues/2039
*Checklist:*
=> Add button has to have selectedRole

auth-api/src/auth_api/services/codes.py
=> Fixed a testcase error issue.

auth-web/src/components/auth/AddBusinessForm.vue
*Issue #:* 1868
https://github.com/bcgov/entity/issues/1868
Trim and lower case on business identifier prior to adding affiliation
*Checklist:*
=> Trim and lower case on Add Business dialog

auth-web/openshift/templates/auth-web-deploy.json, auth-web/src/components/auth/UserProfileForm.vue
*Issue #:*
https://github.com/bcgov/entity/issues/2006
*Checklist:*
=> Bug fix #2006

auth-api/email_templates/membership_approved_notification_email.html, auth-api/email_templates/role_changed_notification_email.html, auth-api/src/auth_api/resources/org.py, auth-api/src/auth_api/services/membership.py, auth-api/src/auth_api/utils/enums.py, auth-web/src/assets/scss/overrides.scss, auth-web/src/components/auth/MemberDataTable.vue, auth-web/src/components/auth/ModalDialog.vue, auth-web/src/locales/en.json, auth-web/src/models/Organization.ts, auth-web/src/services/org.services.ts, auth-web/src/views/management/UserManagement.vue
*Issue #:*
https://github.com/bcgov/entity/issues/1928
https://github.com/bcgov/entity/issues/2095
Changes for sending email notification when somebody changes the user role
*Checklist:*
=> Role change email

auth-web/src/components/auth/MemberDataTable.vue
*Issue #:* 2163
Fixes a critical bug where removing a team member causes the owner to be removed from the team.
*Checklist:*
=> Fix bug where removing a member leaves the team

auth-web/.eslintrc.js, auth-web/package.json, auth-web/src/services/keycloak.services.ts
*Issue #:*
https://github.com/bcgov/entity/issues/2077
fix for logout not working
*Checklist:*
=> fix for logout

auth-web/.eslintrc.js, auth-web/src/App.vue, auth-web/src/components/pay/PaySystemAlert.vue
*Issue #:*
https://github.com/bcgov/entity/issues/2031
Fixing the alignment issue as described in the entity2031
Fixed an issue in the eslint.js file
*Checklist:*
=> [entity2031] Fixing Issue with Alert Banner Alignment

auth-web/src/components/auth/MemberDataTable.vue
=> Fix bug where removing a member leaves the team (#299)

auth-web/src/views/management/UserManagement.vue
=> Fixed bug of not closing the modal

auth-api/requirements.txt, auth-api/requirements/dev.txt, auth-api/requirements/prod.txt, auth-api/requirements/repo-libraries.txt, auth-web/jenkins/prod.groovy, auth-web/jenkins/staging.groovy
*Issue #:*
https://github.com/bcgov/entity/issues/2076
https://github.com/bcgov/entity/issues/2082
*Checklist:*
=> Update libraries version and fix a auth-web prod pipeline issue.

auth-web/src/util/config-helper.ts
=> removed the extra slash at the begining

auth-web/src/components/auth/MemberDataTable.vue
=> fix for https://github.com/bcgov/entity/issues/2200

auth-web/src/util/config-helper.ts
*Issue #:*
Removed the extra slash
*Checklist:*
=> removed the extra slash

auth-web/src/assets/scss/overrides.scss, auth-web/src/components/auth/SearchBusinessForm.vue, auth-web/src/locales/en.json
*Issue #:*
https://github.com/bcgov/entity/issues/2096
Fixing the page layout of the Staff Search page. 
- Updated sizing of alert to conform to REM units
- Improved validation mechanism to show failed search string/number
- Added progress indicator on loading for the search button
- Change the input example to align with real-world examples (example: CP0001234)
*Checklist:*
=> [entity20196] Page Layout Broken in Search Business Interface

auth-web/src/components/auth/InterimLanding.vue
*Issue #:*
https://github.com/bcgov/entity/issues/2217
- Fixing go to home link from interim landing component
*Checklist:*
=> 2217 - Fixing go to home link from interim landing component

auth-web/src/assets/scss/overrides.scss, auth-web/src/components/auth/MemberDataTable.vue
*Issue #:*
https://github.com/bcgov/entity/issues/entity2137
- Fixed the layout issue as observed in IE11
- Updated the active state to leverage existing patterns defined in the Vuetify framework
*Checklist:*
=> [entity2137] Fix Role Menu Layout in Manage Team List (IE11 issue)

auth-api/requirements.txt, auth-api/src/auth_api/resources/invitation.py, auth-api/src/auth_api/resources/user.py
*Issue #:*
https://github.com/bcgov/entity/issues/1494
- Changes to remove unwanted auth check in resources
*Checklist:*
=> Changes to remove unwanted auth check in resources

auth-web/src/components/auth/UserProfileForm.vue
*Issue #:*
https://github.com/bcgov/entity/issues/entity2247
Fixed an issue with the button layout in the Edit Profile interface
*Checklist:*
=> [entity2247] Fix Button Layout on Edit Profile Interface

auth-web/src/views/management/UserManagement.vue
*Issue #:*
https://github.com/bcgov/entity/issues/entity2297
- Removing the optional checkbox to notify users of a role change
- Default behavior changed to send email notification automatically on role change
*Checklist:*
=> [entity2297] Remove Checkbox from Role Change Confirmation

auth-api/email_templates/role_changed_notification_email.html
*Issue #:*
https://github.com/bcgov/entity/issues/entity2298
- Fixing the language in the Role Change Confirmation Email
- White space fixes
*Checklist:*
=> Entity2298

auth-api/tests/postman/auth-api-load-entities.postman_collection.json, auth-api/tests/postman/auth-api-load-entities.postman_environment.json
*Issue #:* 2220
https://github.com/bcgov/entity/issues/2220
Update postman loader script to compensate for data schema changes
*Checklist:*
=> #2220 - Update entity loader postman collection

auth-api/email_templates/role_changed_notification_email.html
*Issue #:*
https://github.com/bcgov/entity/issues/entity2298
Fixing layout issues with email template
*Checklist:*
=> [entity2298] Fixing Issues With Email Template

auth-api/email_templates/role_changed_notification_email.html, auth-api/migrations/versions/93ba1db65ed3_update_membership_type.py, auth-web/src/components/auth/UserProfileForm.vue, auth-web/src/views/management/UserManagement.vue
*Issue #:*
https://github.com/bcgov/entity/issues/entity2298
- Fixing language in the Role Change Notification Email
- Fixed whitespace issues
- Fixed an issue with button spacing in the Role Change Confirmation Modal
*Checklist:*
=> Entity2298 HOTFIX

docs/docs/api_contract/auth-api-1.0.0.yaml, docs/docs/api_contract/notify-api-1.0.0.yaml
Signed-off-by: pwei1018 <patrick.wei@gov.bc.ca>
*Issue #:*
https://github.com/bcgov/entity/issues/1500
Using stoplight.io to create api contracts for Auth and Notify API.
*Checklist:*
=> Add api contracts for Auth and Notify API

auth-web/src/components/auth/ManagementMenu.vue, auth-web/src/router.ts, auth-web/src/views/auth/DashboardView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/1844
*Checklist:*
=> Gave routes to business and team page

auth-api/README.md
*Issue #:*
No issue created. Spelling fix.
*Checklist:*
(N/A, documentation only)
=> Fix a misspelling in README.md

README.md
=> Update README.md to include project sonar badge

auth-web/src/components/auth/TermsOfUseDialog.vue
*Issue #:* 1851
https://github.com/bcgov/entity/issues/1851
This PR fixes the Agree to Terms button enabling before hitting the bottom of the terms view.  It also fixes an issue with the tooltip on the activator not working.
*Checklist:*
=> #1851 - Fix terms of service scrolling and tooltip

auth-api/src/auth_api/schemas/contact.py, auth-api/src/auth_api/schemas/user.py
Fix for https://github.com/bcgov/entity/issues/2353 
*Issue #:*
https://github.com/bcgov/entity/issues/2353
*Checklist:*
=> Added contact relationship back to user

auth-api/requirements.txt, auth-api/src/auth_api/exceptions/errors.py, auth-api/src/auth_api/models/views/authorization.py, auth-api/src/auth_api/services/membership.py, auth-web/src/components/auth/MemberDataTable.vue
*Issue #:*
https://github.com/bcgov/entity/issues/2319
- Fix for bug which allows owner to be removed by owner 
*Checklist:*
=> 2319: Fix for bug which allows owner to be removed by owner

auth-api/src/auth_api/services/membership.py
=> Fixing dict key lookup error

auth-web/src/components/auth/UserManagement.vue
*Issue #:*
https://github.com/bcgov/entity/issues/2365
*Checklist:*
=> Added syncing of members on mounted so that data is refreshed always

openshift/templates/api-config.json
=> Add FLASK_ENV environment variable into openshift configmap

auth-api/src/auth_api/services/org.py, auth-api/tests/unit/services/test_org.py, auth-api/tests/utilities/factory_scenarios.py
*Issue #:*
https://github.com/bcgov/entity/issues/2388
Fixed owner count function and added tests for that.
*Checklist:*
=> Owner count function fixed

auth-web/src/components/auth/BusinessContactForm.vue, auth-web/src/components/auth/UserManagement.vue
*Issue #:*
https://github.com/bcgov/entity/issues/2299
https://github.com/bcgov/entity/issues/2352
*Checklist:*
=> #2299, #2352 icon for pending approvals, fix business contacts.

.github/workflows/auth-api-pr.yml, README.md
=> GitHub actions

auth-api/email_templates/admin_notification_email.html, auth-api/email_templates/business_invitation_email.html, auth-api/email_templates/membership_approved_notification_email.html, auth-api/email_templates/role_changed_notification_email.html
…tes updated
*Issue #:*
https://github.com/bcgov/entity/issues/2402
*Checklist:*
=> changes for Email templates as a part of team to account

.github/workflows/auth-api-build.yml, .github/workflows/auth-api-pr.yml, .github/workflows/notify-api-build.yml, .github/workflows/notify-api-pr.yml, .github/workflows/status-api-build.yml, .github/workflows/status-api-pr.yml, auth-api/tests/unit/services/test_codes.py
=> Update Github actions scripts and Flake8 clean up.

auth-web/src/components/auth/AccountInfo.vue
*Issue #:*
https://github.com/bcgov/entity/issues/2497
Added condition so that only owner can change the account name
*Checklist:*
=> bugfix: Added check so that only owner can change the account name

auth-web/src/views/auth/UserProfileView.vue
*Issue #:*
fix for https://github.com/bcgov/entity/issues/2519
*Checklist:*
=> fixed alignment

auth-web/package.json
=> Update package.json to fix issue with pay status banner/service

auth-web/src/util/config-helper.ts
*Issue #:*
Pay API url is incorrect
*Checklist:*
=> correcting the payment url

auth-web/jenkins/prod.groovy
*Issue #:*
Remove duplicate get image hash function.
*Checklist:*
=> Fixed the prod jenkins script issue.

auth-web/src/registerServiceWorker.ts
*Issue #:*
https://github.com/bcgov/entity/issues/2491
*Description of changes:* 
commit for testing the new content refresh
*Checklist:*
=> commit for testing the new content refresh

auth-web/README.md, auth-web/src/registerServiceWorker.ts
*Issue #:*
updated README of auth-web
*Checklist:*
=> updated README of auth-web

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md, auth-api/README.md, auth-api/docs/dotenv_template, auth-api/src/auth_api/models/__init__.py, auth-api/src/auth_api/resources/user_settings.py, auth-api/src/auth_api/services/invitation.py, auth-api/tests/unit/services/test_entity.py, docker/docker-compose.yml, notify-api/README.md, notify-api/docs/dotenv_template, status-api/README.md, status-api/docs/dotenv_template
*Issue #:*
https://github.com/bcgov/entity/issues/1501
*Checklist:*
=> Update Readme doc and add support documents.

auth-api/README.md
*Issue #:*
added document for the resolution of python mac issue in the readme file
*Checklist:*
=> updating the auth-api/readme file

auth-web/src/components/auth/MemberDataTable.vue, notify-api/README.md
*Issue #:*
https://github.com/bcgov/entity/issues/2495
Hide the remove button in the list if the member is Admin when login as Admin.
*Checklist:*
=> Can't remove Admin member by another Admin

auth-api/src/auth_api/models/__init__.py
=> Adding missing entries in .init file

auth-web/package.json, auth-web/src/App.vue, auth-web/src/components/auth/EntityManagement.vue, package-lock.json
*Issue #:*
https://github.com/bcgov/entity/issues/entity2382
UI Clean-up for account switching
*Checklist:*
=> [entity2382] UI Clean-up

auth-web/src/router.ts
Minor fix in router.ts to correct the redirect to login if no token is present
Also add auth-check to new fallback route
=> Small fix to requiresAuth check

auth-web/src/store/modules/org.ts, auth-web/src/views/auth/DashboardView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/1917
Added maximum number of organisation reached message added
Removed the check for organsation membership
*Checklist:*
=> Bug fixes -owner count message corrected

auth-web/src/views/auth/HomeView.vue, auth-web/src/views/auth/SigninView.vue
*Issue #:* 2656
Corrects issue where 'creating an account' flow would not direct to 'create account' after login. 
*Checklist:*
=> Redirect to create account post login (#2656)

auth-web/package-lock.json, auth-web/src/router.ts, auth-web/src/views/auth/SigninView.vue
*Issue #:* 2563
https://github.com/bcgov/entity/issues/2563
These are required changes in auth-web to support the changes to common components allowing a post-login URL to be specified.
*Checklist:*
=> Add prop handling for redirect urls (#2563)

auth-api/src/auth_api/models/membership.py, auth-api/src/auth_api/services/invitation.py, auth-api/src/auth_api/services/org.py, auth-api/tests/unit/api/test_invitation.py, auth-api/tests/unit/services/test_invitation.py, auth-web/src/components/auth/AccountInfo.vue
Fixes to amend errors from last PR
=> Various testing and linting fixes

docs/sso-client-creator/Keycloak SSO Client Creation.postman_collection.json, docs/sso-client-creator/Keycloak-DEV.postman_environment.json
*Issue #:*
https://github.com/bcgov/entity/issues/2663
- Created postman collection to import keycloak client with variables
*Checklist:*
=> 2663: Created postman collection to import keycloak client with variables

auth-web/src/views/auth/SigninView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/2721
*Checklist:*
=> Fixing issue with staff redirect

auth-api/src/auth_api/models/membership.py, auth-web/src/views/auth/AcceptInviteView.vue
- Removed the double accept invitation
- Removed the status=active check since pending members needs to be retrieved
*Issue #:*
https://github.com/bcgov/entity/issues/2723
*Checklist:*
=> Fix for https://github.com/bcgov/entity/issues/2723

auth-api/setup.cfg, auth-api/src/auth_api/models/__init__.py, auth-api/src/auth_api/services/contact.py, auth-api/src/auth_api/services/reset.py
Fix an issue causing the tests for reset users to fail.
=> Fix issue with pytests for resetting

auth-web/src/models/userInfo.ts, auth-web/src/services/keycloak.services.ts
*Issue #:* 2766
https://github.com/bcgov/entity/issues/2766
=> #2766 - Change account type detection

auth-web/src/views/auth/DashboardView.vue
*Issue #:* 2483
https://github.com/bcgov/entity/issues/2483
Sync membership whenever the businesses dashboard is mounted to get most recent status.  Fixes issue where an admin approves a pending member while that member is already signed in.
*Checklist:*
=> Fix membership syncing to be aggressive (#2483)

auth-api/config.py, auth-api/requirements.txt, auth-api/requirements/dev.txt, auth-api/requirements/prod.txt, auth-api/src/auth_api/__init__.py, auth-api/src/auth_api/schemas/base_schema.py, auth-api/src/auth_api/services/keycloak.py, auth-api/src/auth_api/services/membership.py, auth-api/src/auth_api/services/org.py, auth-api/src/auth_api/services/user.py, auth-api/src/auth_api/utils/constants.py, auth-api/src/auth_api/utils/roles.py, auth-api/src/auth_api/utils/util.py, auth-api/tests/conftest.py, auth-api/tests/docker/setup/demo-realm.json, auth-api/tests/unit/api/test_account.py, auth-api/tests/unit/api/test_invitation.py, auth-api/tests/unit/api/test_org.py, auth-api/tests/unit/api/test_reset.py, auth-api/tests/unit/api/test_user.py, auth-api/tests/unit/api/test_user_settings.py, auth-api/tests/unit/models/test_org.py, auth-api/tests/unit/services/test_invitation.py, auth-api/tests/unit/services/test_keycloak.py, auth-api/tests/unit/services/test_membership.py, auth-api/tests/unit/services/test_org.py, auth-api/tests/unit/services/test_user.py, auth-api/tests/unit/services/test_user_settings.py, auth-api/tests/utilities/factory_scenarios.py
*Issue #:*
https://github.com/bcgov/entity/issues/2652
- Add role when the user creates an org
- Add role when owner/admin accepts the pending approval
- Remove role when membership status is changed to inactive
- Remove role when the org is dissolved
- Remove role when the user profile is deactivated
*Checklist:*
=> #2652 : Changes for granting new role to the user if the user has account

auth-api/config.py, auth-api/src/auth_api/services/keycloak.py, auth-api/tests/unit/services/test_keycloak.py, auth-api/tests/utilities/factory_scenarios.py
This PR makes some improvements around loading the config for pytests (also related to using the local KeyCloak instance for tests).
=> Fix pytests

.github/workflows/auth-api-dev.yml, .github/workflows/auth-api-test.yml, .github/workflows/notify-api-dev.yml, .github/workflows/notify-api-test.yml, .github/workflows/status-api-dev.yml, .github/workflows/status-api-test.yml
…kins scripts.
*Issue #:*
*Checklist:*
=> Fixed a github actions script variable name issue.

.github/workflows/auth-api-test.yml, .github/workflows/notify-api-test.yml, .github/workflows/status-api-test.yml
=> Fixed action scripts issue.

auth-web/src/App.vue, auth-web/src/assets/scss/base.scss, auth-web/src/assets/scss/layout.scss, auth-web/src/views/auth/HomeView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/entity2605
Add links to the 'Online Filing and BC Services Card' on the BC Government Website (2 links)
*Checklist:*
=> [entity2605] Links to FAQ

auth-web/public/config/configuration.json, auth-web/src/App.vue, auth-web/src/views/auth/SigninView.vue
=> Fix for sign in redirecting to user profile

auth-api/config.py, docs/docs/api_contract/auth-api-1.0.0.yaml
=> Adding missing config to support /token endpoint

auth-web/package-lock.json, auth-web/package.json, auth-web/src/store/modules/org.ts, auth-web/src/views/auth/SigninView.vue
=> Small performance tweaks pre-release

auth-api/src/auth_api/resources/org.py, auth-api/src/auth_api/utils/roles.py
*Issue #:*
- Change roles for orgs search endpoint
*Checklist:*
=> Change roles for orgs search endpoint

auth-web/src/views/auth/HomeView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/2834
*Checklist:*
=> Create account can be accessed without a account settings

.github/workflows/auth-api-dev.yml, .github/workflows/auth-api-test.yml, .github/workflows/notify-api-dev.yml, .github/workflows/notify-api-test.yml, .github/workflows/status-api-dev.yml, .github/workflows/status-api-test.yml, auth-api/src/auth_api/models/entity.py, scripts/1pass_secret.sh, scripts/install_tools.sh
=> Github Actions script update.

auth-web/package-lock.json, auth-web/package.json
=> sbc-common version upgrade

auth-web/package-lock.json, auth-web/package.json
=> Fix for staff login -increase package version

auth-api/migrations/versions/3939342073ea_create_names_request_corp.py, auth-api/src/auth_api/services/entity.py, auth-api/src/auth_api/utils/enums.py, auth-web/public/config/configuration.json, auth-web/src/components/auth/AffiliatedEntityList.vue, auth-web/src/models/business.ts, auth-web/src/util/config-helper.ts, auth-web/src/util/constants.ts
*Issue #:*
https://github.com/bcgov/entity/issues/2884
- Changes for NR affiliation
*Checklist:*
=> 2884: Changes for NR affiliation

auth-web/package-lock.json, auth-web/package.json
=> upgrade version

.github/workflows/auth-api-dev.yml, auth-api/tests/postman/auth-api.postman_environment.json, auth-api/tests/postman/get_globals.sh
*Issue #:*
https://github.com/bcgov/entity/issues/2387
*Checklist:*
=> Add Postman test into github actions CD flow.

auth-api/config.py
=> Point the pytest mock url to new server.

auth-web/src/App.vue, auth-web/src/router.ts
*Issue #:* 2947, 2480, 2942, 2836, 2844
https://github.com/bcgov/entity/issues/2947
https://github.com/bcgov/entity/issues/2480
https://github.com/bcgov/entity/issues/2942
https://github.com/bcgov/entity/issues/2836
https://github.com/bcgov/entity/issues/2844
**Please don't merge until I update the common-component version (pending PR on that repo).**
*Checklist:*
=> 2836 navbar bug

auth-api/docs/contract.yaml, docs/docs/api_contract/auth-api-1.0.0.yaml
*Issue #:*
- API Contract changes to work with prism
*Checklist:*
=> Contract Changes

auth-web/src/util/constants.ts, auth-web/src/views/auth/staff/SearchBusinessView.vue
- added staff admin role and hide director search for other users
*Checklist:*
=> added staff admin role and hide director search for other users

auth-web/src/components/auth/staff/SetupAccountForm.vue, auth-web/src/store/modules/org.ts
removed sync organization call from setup account page
*Checklist:*
=> removed sync organization call from setup account page

docs/docs/api_contract/auth-api-1.0.0.yaml
*Issue #:*
- Reverting some changes with contract
*Checklist:*
=> Reverting some changes with contract

.github/workflows/auth-api-check.yml, .github/workflows/auth-api-dev.yml, .github/workflows/auth-api-test.yml, .github/workflows/check-master.yml, .github/workflows/notify-api-check.yml, .github/workflows/notify-api-dev.yml, .github/workflows/notify-api-test.yml, .github/workflows/status-api-check.yml, .github/workflows/status-api-dev.yml, .github/workflows/status-api-test.yml, auth-api/README.md, auth-api/config.py, auth-api/requirements.txt
=> Update github actions scripts for pytest docker service.

auth-api/src/auth_api/resources/user.py, auth-web/package-lock.json, auth-web/package.json, auth-web/src/App.vue, auth-web/src/components/auth/AccountInfo.vue, auth-web/src/components/auth/AffiliatedEntityList.vue, auth-web/src/components/auth/EntityManagement.vue, auth-web/src/components/auth/InviteUsersForm.vue, auth-web/src/components/auth/MemberDataTable.vue, auth-web/src/components/auth/NextPageMixin.vue, auth-web/src/components/auth/UserManagement.vue, auth-web/src/components/auth/UserProfileForm.vue, auth-web/src/models/account-settings.ts, auth-web/src/router.ts, auth-web/src/store/index.ts, auth-web/src/store/modules/org.ts, auth-web/src/store/modules/user.ts, auth-web/src/store/types.ts, auth-web/src/views/auth/AcceptInviteView.vue, auth-web/src/views/auth/SigninView.vue, auth-web/src/views/auth/UserProfileView.vue, auth-web/tests/unit/views/DashboardView.spec.ts
*Issue #:* 2980
https://github.com/bcgov/entity/issues/2980
Refactoring of signin process to support anonymous signin for Director Search.  
WIP - needs updated common components first (pending PR review)
*Checklist:*
=> 2980 anon user signin

auth-api/migrations/versions/68e2f43b9d22_added_billable_column.py, auth-api/src/auth_api/models/org.py, auth-api/src/auth_api/resources/__init__.py, auth-api/src/auth_api/resources/user.py, auth-api/src/auth_api/schemas/schemas/anonymous_user.json, auth-api/src/auth_api/schemas/schemas/bulk_user.json, auth-api/src/auth_api/services/invitation.py, auth-api/src/auth_api/services/org.py, auth-api/src/auth_api/services/user.py
*Issue #:*
https://github.com/bcgov/entity/issues/2694
Two end points to support director search. One for the username/password owner user creation and other one for owner to submit bulk users.
I am still writing tests.Nitheesh and sumesh needs these APIs.so putting it here for review.Please have a look and review so that I can incorporate the comments.Will checkin the tests very soon.
*Checklist:*
=> User creation APIs to support director search anonymous user

auth-web/package-lock.json, auth-web/package.json
*Issue #:* 2833
https://github.com/bcgov/entity/issues/2833
*Checklist:*
=> 2833 - Fix logout bug (Update common components)

auth-api/migrations/versions/68e2f43b9d22_added_billable_column.py, auth-api/src/auth_api/models/org.py, auth-api/src/auth_api/resources/__init__.py, auth-api/src/auth_api/resources/user.py, auth-api/src/auth_api/schemas/schemas/anonymous_user.json, auth-api/src/auth_api/schemas/schemas/bulk_user.json, auth-api/src/auth_api/services/invitation.py, auth-api/src/auth_api/services/org.py, auth-api/src/auth_api/services/user.py, auth-api/tests/unit/api/test_org.py, auth-web/package-lock.json, auth-web/package.json, auth-web/src/components/auth/AccountInfo.vue, auth-web/src/components/auth/CreateAccountInfoForm.vue, auth-web/src/components/auth/LoginBCSC.vue, auth-web/src/components/auth/NextPageMixin.vue, auth-web/src/components/auth/UserProfileForm.vue, auth-web/src/router.ts, auth-web/src/views/auth/AccountSetupView.vue, auth-web/src/views/auth/HomeView.vue, auth-web/src/views/auth/SigninView.vue, auth-web/src/views/auth/UserProfileView.vue
=> Merge development to master (TEST)

auth-web/src/components/auth/NextPageMixin.vue, auth-web/src/router.ts
=> Revert account stepper

auth-api/src/auth_api/exceptions/errors.py, auth-api/src/auth_api/services/org.py, auth-api/src/auth_api/services/user.py, auth-api/tests/unit/api/test_org.py, auth-api/tests/unit/services/test_user.py, auth-api/tests/utilities/factory_scenarios.py, auth-api/tests/utilities/factory_utils.py
*Issue #:*
https://github.com/bcgov/entity/issues/2694
Added the active flag for keycloak created user
Added tests
*Checklist:*
=> Added Tests;refactored some code for https://github.com/bcgov/entity/issues/2694

auth-api/src/auth_api/utils/util.py, auth-web/src/App.vue, auth-web/src/components/auth/CreateUserProfileForm.vue, auth-web/src/components/auth/CreateUserProfileLanding.vue, auth-web/src/components/auth/staff/SetupAccountForm.vue, auth-web/src/models/user.ts, auth-web/src/router.ts, auth-web/src/services/user.services.ts, auth-web/src/util/constants.ts, auth-web/src/views/auth/AcceptInviteLandingView.vue, auth-web/src/views/auth/SigninView.vue, auth-web/src/views/auth/UnauthorizedView.vue, auth-web/src/views/auth/staff/SetupAccountSuccessView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/3059
currentUser value not setting in user module#3059
handle invitation flow for director search admin user#3022 - in-progress (won't break anything else)
*Checklist:*
=> currentUser value not setting in user module#3059 and handle invitation flow for director search admin user#3022

auth-api/src/auth_api/resources/user.py, auth-api/src/auth_api/services/keycloak.py, auth-api/src/auth_api/utils/constants.py, auth-api/tests/docker/setup/demo-realm.json, auth-api/tests/unit/services/test_keycloak.py
*Issue #:*
https://github.com/bcgov/entity/issues/3077
- Adding bcros users to anonymous users group
*Checklist:*
=> 3077: Adding bcros users to anonymous users group

auth-web/src/components/auth/AffiliatedEntityList.vue
*Issue #:* 3043
https://github.com/bcgov/entity/issues/3043
Adds a route parameter for business-id to redirect to co-ops filings ui
*Checklist:*
=> Update route to coops dashboard with route param

auth-web/package-lock.json, auth-web/package.json, auth-web/src/App.vue, auth-web/src/components/auth/mixins/NextPageMixin.vue, auth-web/src/router.ts, auth-web/src/util/constants.ts, auth-web/src/views/auth/SigninView.vue
*Issue #:* 3081
https://github.com/bcgov/entity/issues/3081
* Route IDIR/BCROS users more appropriately when going to routes not applicable for those login sources
* Update navigation guard in router
* Replace strings with enum constants where applicable
*Checklist:*
=> 3081 better handling of routing for IDIR users

auth-web/src/App.vue, auth-web/src/components/auth/EntityManagement.vue, auth-web/src/components/auth/UserManagement.vue, auth-web/src/store/modules/business.ts, auth-web/src/store/modules/org.ts, auth-web/src/views/auth/BusinessProfileView.vue, auth-web/src/views/auth/DashboardView.vue, auth-web/src/views/auth/HomeView.vue, auth-web/src/views/auth/SigninView.vue
*Issue #:* 3094
* Fixes an issue with the business profile getting out of sync with co-ops.
* Improve performance by removing unnecessary syncing/routing.
* Fix issue with Create a New Account button on Home view
*Checklist:*
=> 3094 fix business profile errors, optimize syncing

auth-api/migrations/versions/09c44f82c03c_add_folio_number_to_entity_table.py, auth-api/src/auth_api/models/entity.py, auth-api/src/auth_api/resources/entity.py, auth-api/src/auth_api/schemas/entity.py, auth-api/src/auth_api/schemas/schemas/entity.json, auth-api/src/auth_api/services/entity.py, auth-api/tests/unit/api/test_entity.py, auth-api/tests/unit/services/test_entity.py, auth-api/tests/utilities/factory_scenarios.py, auth-web/src/components/auth/AddBusinessForm.vue, auth-web/src/components/auth/BusinessContactForm.vue, auth-web/src/components/auth/EntityManagement.vue, auth-web/src/models/business.ts, auth-web/src/services/business.services.ts, auth-web/src/store/modules/business.ts, auth-web/src/views/auth/BusinessProfileView.vue, auth-web/tests/unit/components/BusinessContactForm.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/278
1. add folio number into entity table;
2. modify entity model, schema, service and endpoint;
3. change update entity endpoint from put to patch;
4. add folio number into add business and business profile forms;
*Checklist:*
=> Added folio number in api and web.

auth-api/src/auth_api/resources/entity.py, auth-web/src/components/auth/BusinessContactForm.vue, auth-web/src/views/auth/staff/SearchBusinessView.vue
*Issue #:* 3094
https://github.com/bcgov/entity/issues/3094
* Allow staff to save business contact info (they can already update)
* Fix return url back to co-ops post-save
*Checklist:*
=> 3094 business profile fix

auth-web/src/components/auth/BusinessContactForm.vue, auth-web/src/views/auth/BusinessProfileView.vue
=> Change the button name to 'Update'  and add a back button.

auth-web/package-lock.json, auth-web/package.json, auth-web/src/App.vue, auth-web/src/views/auth/SigninView.vue
Small adjustment to previous PR on same topic
=> Move signin redirect to callback

auth-web/src/assets/scss/base.scss, auth-web/src/components/auth/AddBusinessForm.vue, auth-web/src/components/auth/BusinessContactForm.vue, auth-web/src/components/auth/EntityManagement.vue, auth-web/src/views/auth/BusinessProfileView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/entity278
Front-end cleanup. Few improvements.
- Reduced some of the redundant elements
- Added fieldsets for both forms (accessibility)
*Checklist:*
=> [entity278] User Interface Clean-up

auth-web/package-lock.json, auth-web/package.json
sbc-common-components version change
*Checklist:*
=> sbc-common-components version change

keycloak/kc_realm_config.json, keycloak/kc_upstream_idp_config.json
*Issue #:*
Adding keycloak config
*Checklist:*
=> Adding keycloak config

auth-api/src/auth_api/exceptions/errors.py, auth-api/src/auth_api/resources/bulk_user.py, auth-api/src/auth_api/resources/user.py, auth-api/src/auth_api/schemas/schemas/anonymous_user_response.json, auth-api/src/auth_api/services/keycloak.py, auth-api/src/auth_api/services/user.py, auth-api/tests/unit/api/test_bulk_user.py, auth-api/tests/unit/api/test_user.py, auth-api/tests/unit/services/test_user.py
*Issue #:*
https://github.com/bcgov/entity/issues/3074
*Checklist:*
=> changes to support transactions in bulk endpoint

auth-api/src/auth_api/resources/user.py
=> Fix for wrong variable

auth-web/src/components/auth/AccountInfo.vue
*Issue #:*
https://github.com/bcgov/entity/issues/2755
Error message on Account Name does not go away after saving successfully
*Checklist:*
=> Error message on Account Name does not go away after saving successfully#2755

auth-web/src/views/auth/HomeView.vue
*Issue #:* bcgov/entity#3248
- added v-alert with specified content
- set content width same as header
*Checklist:*
=> added COVID-19 alert

.github/workflows/auth-web-check.yml, auth-web/jest.config.js
*Issue #:*
https://github.com/bcgov/entity/issues/2842
*Checklist:*
=> Github Action frontend Lint

auth-api/email_templates/dirsearch_business_invitation_email.html
*Issue #:*
https://github.com/bcgov/entity/issues/2982
*Checklist:*
=> https://github.com/bcgov/entity/issues/2982

.github/workflows/auth-web-check.yml, auth-api/email_templates/dirsearch_business_invitation_email.html, auth-web/jest.config.js
=> dev to test merge

.github/workflows/auth-api-check.yml, auth-api/config.py
=> Fixed a pytest issue.

.github/workflows/auth-web-dev-deploy.yml, auth-web/.dockerignore, auth-web/Dockerfile, auth-web/nginx.conf, auth-web/openshift/templates/auth-web-deploy.json
* dokcer and nginx conf added
* change auth-web-dev-deploy.json
* created gh actions
*Issue #:*
https://github.com/bcgov/entity/issues/2842
*Checklist:*
=> Github actions for web 

auth-web/src/components/auth/TermsOfUse.vue, auth-web/src/views/auth/TermsOfServiceView.vue, auth-web/src/views/auth/staff/SetupAccountSuccessView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/entity2693
Cleaning up the user-interface to conform to design specifications.
*Checklist:*
=> [entity2693] UI Clean-up

auth-api/migrations/versions/1786b8de5f43_added_director_search_role.py, auth-api/src/auth_api/models/product_role_code.py, auth-api/src/auth_api/services/products.py
*Issue #:*
https://github.com/bcgov/entity/issues/3309
*Checklist:*
=> added missing Role for director search

auth-web/src/components/auth/AddUsersForm.vue, auth-web/src/components/auth/CreateUserProfileForm.vue, auth-web/src/components/auth/TeamManagement.vue, auth-web/src/components/auth/UserProfileForm.vue, auth-web/src/components/auth/mixins/NextPageMixin.vue, auth-web/src/router.ts, auth-web/src/util/constants.ts, auth-web/src/views/auth/AccountSettings.vue, auth-web/src/views/auth/HomeView.vue, auth-web/src/views/auth/TermsOfServiceDeclineView.vue, auth-web/src/views/auth/TermsOfServiceView.vue, auth-web/src/views/auth/UnauthorizedView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/2628
https://github.com/bcgov/entity/issues/2694
bugfixes:
- An owner can add 0 team members which is incorrect- ideally this add button should be disabled initially if there is no member added
- Member can also see the team member screen - which is incorrect ( I changed the role of existing admin to member)
- owner can navigate to Manage businesses tab which is incorrect
- on logout - user should be redirected to the Director Search Login page
- Cancel button is not working for create user profile
- hide "Create a new BC Registries account" button in home page
*Checklist:*
By submitting this pull request, I …
=> Bugfix director search

.github/workflows/auth-web-test-deploy.yml, auth-web/src/views/auth/HomeView.vue
=> Github Actions for Test

.github/workflows/auth-web-check.yml, .github/workflows/auth-web-dev-deploy.yml, .github/workflows/auth-web-test-deploy.yml, auth-api/email_templates/dirsearch_business_invitation_email.html, auth-api/migrations/versions/1786b8de5f43_added_director_search_role.py, auth-api/src/auth_api/models/product_role_code.py, auth-api/src/auth_api/services/products.py, auth-web/.dockerignore, auth-web/Dockerfile, auth-web/jest.config.js, auth-web/nginx.conf, auth-web/openshift/templates/auth-web-deploy.json, auth-web/src/components/auth/AddUsersForm.vue, auth-web/src/components/auth/CreateUserProfileForm.vue, auth-web/src/components/auth/TeamManagement.vue, auth-web/src/components/auth/TermsOfUse.vue, auth-web/src/components/auth/UserProfileForm.vue, auth-web/src/components/auth/mixins/NextPageMixin.vue, auth-web/src/router.ts, auth-web/src/util/constants.ts, auth-web/src/views/auth/AccountSettings.vue, auth-web/src/views/auth/HomeView.vue, auth-web/src/views/auth/TermsOfServiceDeclineView.vue, auth-web/src/views/auth/TermsOfServiceView.vue, auth-web/src/views/auth/UnauthorizedView.vue, auth-web/src/views/auth/staff/SetupAccountSuccessView.vue
=> dev to master merge

auth-web/src/views/auth/staff/SetupAccountSuccessView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/3322
https://github.com/bcgov/entity/issues/3323
- Director search: If more than one account is created from same account then the email displayed in the message is wrong
- Director search: Design and spelling mismatch
*Checklist:*
=> dirsearch bugfixes #3323 and #3322 

auth-api/src/auth_api/services/invitation.py
*Issue #:*
https://github.com/bcgov/entity/issues/2982
*Checklist:*
=> changes for new email title

.github/workflows/notify-api-check.yml, .github/workflows/status-api-check.yml, .github/workflows/status-api-dev.yml, notify-api/requirements/dev.txt, notify-api/src/notify_api/core/queue_publisher.py, notify-api/tests/conftest.py, notify-api/tests/docker/docker-compose.yml, notify-api/tests/unit/api/test_notify.py, notify-api/tests/unit/core/test_queue_publisher.py, notify-api/tests/utilities/factory_scenarios.py, status-api/requirements/prod.txt, status-api/tests/unit/utils/test_util_cors.py
=> Enable python 3.8 checks in Github Actions.

.github/workflows/notify-api-dev.yml
=> Fixed a using old file name issue.

auth-api/src/auth_api/resources/org.py, auth-api/tests/unit/api/test_org.py, auth-web/src/components/auth/AccountInfo.vue
https://github.com/bcgov/entity/issues/3324
*Issue #:*
*Checklist:*
=> Director Search account name non-editable

auth-web/src/components/auth/AffiliatedEntityList.vue
*Issue #:*
https://github.com/bcgov/entity/issues/3063
- Auth Web: Manage Businesses page needs to redirect to Draft Dashboard for NRs
*Checklist:*
=> Manage Businesses page needs to redirect to Draft Dashboard for NRs #3063

.github/workflows/auth-api-test.yml, .github/workflows/notify-api-test.yml, .github/workflows/status-api-test.yml
=> Fixed test github action build's issue.

auth-web/src/assets/scss/base.scss, auth-web/src/assets/scss/theme.scss, auth-web/src/components/auth/AddUsersForm.vue, auth-web/src/components/auth/AddUsersSuccess.vue, auth-web/src/components/auth/AnonymousUserManagement.vue
*Issue #:*
https://github.com/bcgov/entity/issues/entity3074
Improvements to the Director Search Team Member invitation modals
*Checklist:*
=> [entity3074] UI Improvements

auth-web/src/App.vue
*Issue #:*
https://github.com/bcgov/entity/issues/3325
*Checklist:*
=> Added logout redirect url for bcros user

auth-web/src/App.vue, auth-web/src/util/config-helper.ts
*Issue #:*
https://github.com/bcgov/entity/issues/3325
*Checklist:*
=> fixing logout for BCROS User

auth-web/src/util/config-helper.ts, auth-web/src/views/auth/AccountSettings.vue
=> Entity3329

auth-web/src/views/pay/PaymentView.vue
*Issue #:*
bcgov/entity#2890
- Changes to match error schema with pay-api
*Checklist:*
=> Changes to match with latest pay api changes

auth-web/src/App.vue
*Issue #:* 2946
https://github.com/bcgov/entity/issues/2946
Force update of header after account switch.  Ensures notification bell is updated.
*Checklist:*
=> 2946 update notification bell on switch

auth-web/src/components/auth/CreateAccountInfoForm.vue, auth-web/src/components/auth/UserProfileForm.vue, auth-web/src/components/auth/stepper/Stepper.vue, auth-web/src/components/auth/stepper/StepperStub.vue, auth-web/src/router.ts, auth-web/src/views/auth/AccountSetupView.vue
*Issue #:* 2539
Add stepper component, and stubbed out Account Setup view that will use it.
The stepper takes a configuration with names and components/content for each step.
Each embedded component will need to define two properties (stepForward and setBack) for navigation within the stepper.  See StepperStub for an example.
*Checklist:*
=> 2539 resurrect stepper

auth-web/src/components/auth/CreateAccountInfoForm.vue
=> WIP ;create premium account screen

.github/workflows/auth-api-test.yml
=> Fixed the docker image tag issue.

auth-web/src/components/auth/AddUsersForm.vue, auth-web/src/components/auth/AddUsersSuccess.vue
member dropdown not auto select while opening second time in dir search add user popup
*Issue #:*
*Checklist:*
=> member dropdown not auto select while opening second time in dir search add user popup

auth-api/config.py, auth-api/src/auth_api/models/account_payment_settings.py, auth-api/src/auth_api/services/org.py, auth-api/tests/unit/services/test_org.py, auth-api/tests/utilities/factory_scenarios.py, auth-api/tests/utilities/factory_utils.py
*Issue #:*
https://github.com/bcgov/entity/issues/3371
*Checklist:*
=> Add bcol account existing check function.

auth-api/config.py, auth-api/migrations/versions/0ab62b841b88_add_drawdown_payment_type.py, auth-api/requirements.txt, auth-api/src/auth_api/exceptions/errors.py, auth-api/src/auth_api/models/account_payment_settings.py, auth-api/src/auth_api/models/base_model.py, auth-api/src/auth_api/resources/org.py, auth-api/src/auth_api/schemas/schemas/bconline_credential.json, auth-api/src/auth_api/schemas/schemas/org.json, auth-api/src/auth_api/services/org.py, auth-api/src/auth_api/utils/enums.py, auth-api/tests/conftest.py, auth-api/tests/docker/docker-compose.yml, auth-api/tests/docker/nginx.conf, auth-api/tests/unit/api/test_org.py, auth-api/tests/unit/services/test_org.py, auth-api/tests/utilities/factory_scenarios.py
*Issue #:*
https://github.com/bcgov/entity/issues/1311
- Changes for adding premium org details
*Checklist:*
=> Changes for adding premium org details

auth-web/src/components/auth/CreateAccount/AccountCreateBasic.vue, auth-web/src/components/auth/CreateAccount/AccountCreatePremium.vue, auth-web/src/components/auth/CreateAccount/AccountTypeSelector.vue, auth-web/src/components/auth/stepper/Stepper.vue
=> title and stepper counter to stepper component, UI corrections

auth-web/src/assets/scss/base.scss, auth-web/src/assets/scss/layout.scss, auth-web/src/components/auth/BaseAddress.vue, auth-web/src/components/auth/BcolLogin.vue, auth-web/src/components/auth/CreateAccount/AccountCreateBasic.vue, auth-web/src/components/auth/CreateAccount/AccountCreatePremium.vue, auth-web/src/components/auth/CreateAccount/AccountTypeSelector.vue, auth-web/src/components/auth/CreateAccount/CreateAccountInfoForm.vue, auth-web/src/components/auth/stepper/Stepper.vue, auth-web/src/plugins/vuetify.ts, auth-web/src/views/auth/AccountSetupView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/entity515
https://github.com/bcgov/entity/issues/entity3371
https://github.com/bcgov/entity/issues/entity1311
Updates to front-end for Account Creation Interfaces
*Checklist:*
=> Account Creation Interface Clean-up

auth-web/public/config/configuration.json, auth-web/src/components/auth/UserProfileForm.vue, auth-web/src/components/auth/staff/SetupAccountForm.vue, auth-web/src/router.ts, auth-web/src/store/modules/org.ts, auth-web/src/util/config-helper.ts, auth-web/src/views/auth/AcceptInviteView.vue, auth-web/src/views/auth/TermsOfServiceView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/3496
The invitation flow was broken since we separated TOS and User Profile into two pages.
The PR fixes that.
*Checklist:*
=> Fixing invitation flow

auth-web/src/components/auth/CreateAccount/AccountCreateBasic.vue, auth-web/src/components/auth/CreateAccount/AccountCreatePremium.vue, auth-web/src/components/auth/UserProfileForm.vue, auth-web/src/components/auth/common/ConfirmCancelButton.vue, auth-web/src/components/auth/stepper/Stepper.vue, auth-web/src/views/auth/AccountSetupView.vue, auth-web/src/views/auth/UserProfileView.vue
=> Stepper ui fixes

auth-web/src/components/auth/BcolLogin.vue, auth-web/src/components/auth/CreateAccount/AccountCreateBasic.vue, auth-web/src/components/auth/CreateAccount/AccountCreatePremium.vue, auth-web/src/components/auth/CreateAccount/AccountTypeSelector.vue, auth-web/src/components/auth/UserProfileForm.vue, auth-web/src/components/auth/stepper/Stepper.vue
*Issue #:*
https://github.com/bcgov/entity/issues/entity2539
Front-end updates / clean-up
*Checklist:*
=> Account Creation UI Updates

auth-web/src/components/auth/CreateAccount/AccountCreateBasic.vue, auth-web/src/components/auth/CreateAccount/AccountCreatePremium.vue, auth-web/src/components/auth/CreateAccount/AccountTypeSelector.vue, auth-web/src/components/auth/UserProfileForm.vue, auth-web/src/components/auth/common/ConfirmCancelButton.vue, auth-web/src/store/modules/org.ts
*Issue #:*
https://github.com/bcgov/entity/issues/3535
Create Account - Cancel Confirmation Dialog Update
*Checklist:*
=> Create Account - Cancel Confirmation Dialog Update#3535

.github/workflows/notify-api&queue-test.yml, notify-api/README.md
=> Fixed test github actions script.

.github/workflows/notify-api&queue-test.yml, notify-api/tests/conftest.py
=> Fixed the github actions script and d a linting issue.

.github/workflows/notify-api&queue-test.yml, notify-api/tests/conftest.py
=> Fixed the github actions script and a linting issue.

auth-web/src/router.ts
=> If no profile exists , redirect to terms page

auth-web/src/router.ts
=> If no profile exists , redirect to terms page (#634)

auth-api/requirements.txt, auth-api/requirements/dev.txt, auth-api/requirements/prod.txt, auth-api/src/auth_api/resources/org.py, auth-api/src/auth_api/services/affiliation.py, auth-api/src/auth_api/services/entity.py
*Issue #:*
https://github.com/bcgov/entity/issues/3583
*Checklist:*
=> Changes for passing token the lear business endpoint

auth-api/requirements.txt, auth-api/requirements/dev.txt, auth-api/requirements/prod.txt, auth-api/src/auth_api/resources/org.py, auth-api/src/auth_api/services/affiliation.py, auth-api/src/auth_api/services/entity.py
=> dev to test

auth-web/src/components/auth/MemberDataTable.vue, auth-web/src/store/modules/org.ts
*Issue #:*
https://github.com/bcgov/entity/issues/3262
Admin can change the role of another admin
*Checklist:*
=> Admin can change the role of another admin

auth-web/src/components/auth/AccountInfo.vue
*Issue #:*
https://github.com/bcgov/entity/issues/2543
*Checklist:*
=> Fixing address being editable

auth-web/src/components/auth/AccountInfo.vue
=> Fixing address being editable (#650)

auth-api/migrations/versions/08063ceec05d_add_term_of_use_for_director_search.py, auth-api/src/auth_api/models/documents.py, auth-api/src/auth_api/resources/documents.py, auth-api/src/auth_api/schemas/schemas/termsofuse.json, auth-api/src/auth_api/utils/enums.py, auth-api/tests/unit/api/test_documents.py, auth-api/tests/unit/api/test_user.py, auth-api/tests/unit/models/test_documents.py, auth-api/tests/unit/models/test_user.py, auth-web/src/router.ts
*Issue #:*
https://github.com/bcgov/entity/issues/3530
*Checklist:*
=> Add director search terms of user.

auth-api/src/auth_api/exceptions/__init__.py, auth-api/src/auth_api/resources/org.py, auth-api/src/auth_api/schemas/__init__.py, auth-api/src/auth_api/schemas/account_payment_settings.py, auth-api/src/auth_api/services/org.py, auth-web/src/components/auth/AccountInfo.vue, auth-web/src/components/auth/BaseAddress.vue, auth-web/src/components/auth/UserManagement.vue, auth-web/src/components/auth/stepper/Stepper.vue, auth-web/src/models/PaymentSettings.ts, auth-web/src/models/address.ts, auth-web/src/router.ts, auth-web/src/services/org.services.ts, auth-web/src/store/modules/org.ts, auth-web/src/views/auth/AccountSettings.vue
*Issue #:*
https://github.com/bcgov/entity/issues/3594
https://github.com/bcgov/entity/issues/2543
major changes changes around layout of edit screen and API to support it.
I am missing tests for the new functionality and I will add it soon.my local tests were failing and didnt want to spend a lot of time for this.I will come back to it.
Also couple of issues I noticed during testing are noticed here..I will come back to it once the sprint priorities are over.
https://github.com/bcgov/entity/issues/3642
*Checklist:*
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the sbc-auth …
=> Payment details shown in the account info page , handled errors from BCOL

auth-web/src/components/auth/AccountInfo.vue, auth-web/src/store/modules/org.ts
=> Fixing address and payment info not being shown

auth-web/src/components/auth/AccountInfo.vue
=> Address not getting reset

auth-api/src/auth_api/exceptions/errors.py
=> message changed as per design

auth-web/src/views/auth/HomeView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/entity3542
Updating the BC Services Card link on the homepage.
*Checklist:*
=> [entity3542] Update BCSC Link on Homepage

auth-web/src/App.vue, auth-web/src/assets/scss/base.scss, auth-web/src/assets/scss/layout.scss, auth-web/src/components/auth/AccountInfo.vue, auth-web/src/components/auth/BaseAddress.vue, auth-web/src/components/auth/BcolLogin.vue, auth-web/src/components/auth/BusinessContactForm.vue, auth-web/src/components/auth/CreateAccount/AccountCreateBasic.vue, auth-web/src/components/auth/CreateAccount/AccountCreatePremium.vue, auth-web/src/components/auth/CreateAccount/AccountTypeSelector.vue, auth-web/src/components/auth/CreateAccount/CreateAccountInfoForm.vue, auth-web/src/components/auth/UserManagement.vue, auth-web/src/components/auth/UserProfileForm.vue, auth-web/src/components/auth/common/ConfirmCancelButton.vue, auth-web/src/components/auth/stepper/Stepper.vue, auth-web/src/locales/en.json, auth-web/src/plugins/vuetify.ts, auth-web/src/router.ts, auth-web/src/services/org.services.ts, auth-web/src/store/modules/org.ts, auth-web/src/util/config-helper.ts, auth-web/src/util/constants.ts, auth-web/src/views/auth/AccountChangeSuccessView.vue, auth-web/src/views/auth/AccountChangeView.vue, auth-web/src/views/auth/AccountSettings.vue, auth-web/src/views/auth/AccountSetupView.vue, auth-web/src/views/auth/CreateAccountView.vue, auth-web/src/views/auth/UserProfileView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/3604
https://github.com/bcgov/entity/issues/2462
UI changes for upgrade/downgrade and some UX improvements by @jeznorth 
*Checklist:*
=> Changes for Upgrade and Downgrade account

auth-web/src/components/auth/InvitationsDataTable.vue, auth-web/src/components/auth/Transactions.vue, auth-web/src/components/auth/TransactionsDataTable.vue, auth-web/src/locales/en.json, auth-web/src/models/transaction.ts, auth-web/src/router.ts, auth-web/src/services/payment.services.ts, auth-web/src/store/modules/org.ts, auth-web/src/util/common-util.ts, auth-web/src/util/constants.ts, auth-web/src/views/auth/AccountSettings.vue
*Issue #:*
https://github.com/bcgov/entity/issues/3194
View Account Transaction History
*Checklist:*
=> View Account Transaction History #3194

auth-api/src/auth_api/resources/org.py
=> Fix for action value

auth-web/src/components/auth/BaseAddress.vue
*Issue #:*
https://github.com/bcgov/entity/issues/entity2462
Fixing all-caps labels in the Mailing Address form.
*Checklist:*
=> [entity2462] Fixing all-caps in text inputs

auth-api/src/auth_api/services/org.py, auth-web/src/components/auth/CreateAccount/AccountCreateBasic.vue, auth-web/src/components/auth/CreateAccount/AccountCreatePremium.vue
*Issue #:*
https://github.com/bcgov/entity/issues/3604
*Checklist:*
=> misc bugs on downgrade/upgrade ;mainly for duplicate name check

auth-api/config.py
*Issue #:*
Fixing issue with bcol account link check
*Checklist:*
=> Fixing issue with bcol account link check

auth-web/src/views/auth/HomeView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/entity3663
Fixed links on Home Page
*Checklist:*
=> [entity3663] Fix Home Page Links

auth-web/src/components/auth/CreateAccount/AccountTypeSelector.vue
*Issue #:*
https://github.com/bcgov/entity/issues/entity2462
Add language for 'change' account into the account type selector.
*Checklist:*
=> [entity2462] Fixing language in Account Selector

auth-web/src/components/auth/CreateAccount/AccountCreatePremium.vue, auth-web/src/store/modules/org.ts
=> Unlink not working

auth-web/src/components/auth/UserProfileForm.vue
=> Add reset button back to screen.

auth-web/src/components/auth/BcolLogin.vue
*Issue #:*
https://github.com/bcgov/entity/issues/3656
*Checklist:*
=> reset added on successful linking

.github/workflows/auth-web-check.yml, .github/workflows/auth-web-test-deploy.yml, auth-web/src/components/auth/BcolLogin.vue
=> dev to master

auth-web/package.json, auth-web/public/config/configuration.json, auth-web/src/App.vue, auth-web/src/registerServiceWorker.ts, auth-web/src/util/constants.ts, auth-web/src/views/auth/AccountSettings.vue
*Issue #:*
https://github.com/bcgov/entity/issues/2439
Apply launch darkly for transactions page
*Checklist:*
=> Configure sbc-common-components LaunchDarkly for feature flags#2439

auth-web/package.json, auth-web/public/config/configuration.json, auth-web/src/App.vue, auth-web/src/assets/scss/base.scss, auth-web/src/components/auth/AccountInfo.vue, auth-web/src/components/auth/BcolLogin.vue, auth-web/src/components/auth/CreateAccount/AccountCreateBasic.vue, auth-web/src/components/auth/CreateAccount/AccountCreatePremium.vue, auth-web/src/registerServiceWorker.ts, auth-web/src/util/constants.ts, auth-web/src/views/auth/AccountChangeSuccessView.vue, auth-web/src/views/auth/AccountSettings.vue
=> Test Deployment

auth-web/package-lock.json, auth-web/src/components/auth/EntityManagement.vue, auth-web/src/util/constants.ts, auth-web/src/views/auth/HomeView.vue
Staff user redirect to staff dashboard.
*Issue #:*
https://github.com/bcgov/entity/issues/3709
https://github.com/bcgov/entity/issues/3705
Redirect Staff user to Staff dashboard when user click logo.
Redirect user to create account flow when user click "manage businesses" but doesn't have account.
*Checklist:*
=> Bug bix - #3709

auth-web/package-lock.json, auth-web/src/components/auth/EntityManagement.vue, auth-web/src/util/constants.ts, auth-web/src/views/auth/HomeView.vue
* Bug bix - #3709
Safff user redirect to staff dashboard.
* bug fix - #3705
Redirect user to create account when current account is null.
*Issue #:*
*Checklist:*
=> Dev to Test - Bug fix - #3709 #3705 (#699)

auth-web/src/models/business.ts, auth-web/src/store/modules/business.ts, auth-web/src/util/constants.ts
*Issue #:*
N/A
- set Legal Type (BCOMP) in initial Numbered Company draft filing
- added LegalType enum
- updated NumberedBusinessRequest model
*Checklist:*
=> set Legal Type (BCOMP) in initial Numbered Company draft filing

auth-api/migrations/versions/ef8a9847f953_merge_commits.py
=> merge alembic scripts

auth-api/migrations/versions/437ce1f93861_changing_the_roles.py
=> fixing migrations issues in dev

auth-web/src/components/auth/MemberDataTable.vue
=> getter invoked before mounted is over

auth-web/src/components/auth/InviteUsersForm.vue
=> wrong vars fixed

.github/workflows/notify-api&queue-dev.yml, .github/workflows/notify-api&queue-test.yml, notify-api/Dockerfile
=> Added missing github actions configuration changes.

auth-api/src/auth_api/models/user_settings.py, auth-api/src/auth_api/schemas/schemas/user_settings_response.json, auth-api/src/auth_api/schemas/user_settings.py, auth-api/src/auth_api/services/user_settings.py, auth-api/tests/unit/api/test_user_settings.py, auth-web/src/store/modules/org.ts
*Issue #:*
https://github.com/bcgov/entity/issues/3775
*Checklist:*
=> added org type to user settings ; Changed url of create account

auth-api/src/auth_api/services/authorization.py
=> Commenting issue with corpType for system token

auth-api/email_templates/dirsearch_business_invitation_email.html, auth-api/migrations/versions/3939342073ea_create_names_request_corp.py, auth-api/migrations/versions/437ce1f93861_changing_the_roles.py, auth-api/migrations/versions/bab2eefb9412_adding_new_business_corp_type.py, auth-api/src/auth_api/models/membership_type.py
*Issue #:*
https://github.com/bcgov/entity/issues/3461
*Checklist:*
=> Fixed up the labels and migration scripts

auth-api/migrations/versions/437ce1f93861_changing_the_roles.py, auth-api/src/auth_api/models/membership_type.py, auth-api/src/auth_api/schemas/membership_type.py, auth-api/tests/unit/services/test_authorization.py, auth-web/package-lock.json, auth-web/package.json, auth-web/src/components/auth/MemberDataTable.vue, auth-web/src/components/auth/TeamManagement.vue, auth-web/src/models/Organization.ts, auth-web/src/store/modules/user.ts, auth-web/tests/unit/components/InviteUsersForm.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/3708
packagelock updated
https://github.com/bcgov/entity/issues/3708
user was not able to see the active member list.fixed it
added a displayorder column so that list view order can be decided
*Checklist:*
=> couple of misc bug fixes related to role changes

auth-api/src/auth_api/services/authorization.py
*Issue #:*
https://github.com/bcgov/entity/issues/3781
*Checklist:*
=> Adding account type in auth response

auth-web/src/components/auth/TransactionsDataTable.vue, auth-web/src/models/transaction.ts, auth-web/src/services/payment.services.ts, auth-web/src/store/modules/org.ts, auth-web/src/util/constants.ts
*Issue #:*
https://github.com/bcgov/entity/issues/3194
Pagination, and status changes
*Checklist:*
=> 3194: Pagination, and status changes

auth-web/README.md, codecov.yaml
=> Update codecov configuration.

auth-web/src/components/auth/BcscPanel.vue, auth-web/src/views/auth/HomeViewDev.vue, auth-web/tests/unit/components/BcscPanel.spec.ts, auth-web/tests/unit/views/DecideBusinessView.spec.ts, auth-web/tests/unit/views/HomeView.spec.ts, auth-web/tests/unit/views/IncorpOrRegisterView.spec.ts, auth-web/tests/unit/views/MaintainBusinessView.spec.ts, auth-web/tests/unit/views/RequestNameView.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/2994
* Implements Unit testing for additional Views and components.
* Fixed some styling.
* Fixed some duplicate id's.
* Removed some unused imports.
*Checklist:*
=> #2994 Launch Page Unit Tests

auth-api/src/auth_api/services/affiliation.py, auth-api/src/auth_api/utils/constants.py, auth-web/src/services/business.services.ts, auth-web/src/store/modules/business.ts
*Issue #:*
https://github.com/bcgov/entity/issues/3806
- Changes for 3806 to display numbered company label and to delete the filing
*Checklist:*
=> 3806 : Numbered company and filing changes

auth-api/src/auth_api/services/affiliation.py, auth-api/src/auth_api/utils/constants.py, auth-web/src/components/auth/AffiliatedEntityList.vue
*Issue #:*
https://github.com/bcgov/entity/issues/3806
#3806: Changes for adding different labels based on incorporation
*Checklist:*
=> #3806: Changes for adding different labels based on incorporation

auth-web/src/components/auth/Transactions.vue, auth-web/src/components/auth/TransactionsDataTable.vue, auth-web/src/models/transaction.ts, auth-web/src/util/common-util.ts
*Issue #:*
https://github.com/bcgov/entity/issues/3208
https://github.com/bcgov/entity/issues/3312
Transactions - Filter Transactions by Date Range#3208
Transactions - Filter Transactions by Folio Number#3312
*Checklist:*
=> Transactions - Filter

auth-api/src/auth_api/schemas/schemas/mailing_address.json, auth-api/src/auth_api/schemas/schemas/org.json, auth-api/tests/unit/api/test_org.py, auth-api/tests/utilities/factory_scenarios.py, auth-web/src/components/auth/AccountInfo.vue, auth-web/src/components/auth/BaseAddress.vue, auth-web/src/components/auth/CreateAccount/AccountCreatePremium.vue
*Issue #:*
https://github.com/bcgov/entity/issues/3591
front end changes for mailing address mandatory
schema changes in backend.
*Checklist:*
=> mailing address made mandatory

auth-web/src/components/auth/AffiliatedEntityList.vue
*Issue #:*
Fixing issue with NR navigation, changes to not update store on navigation
*Checklist:*
=> Fixing issue with NR navigation, changes to not update store on navigation

auth-web/src/components/auth/Transactions.vue
*Issue #:*
https://github.com/bcgov/entity/issues/entity3208
Transactions Filters Clean-up
*Checklist:*
=> [entity3208] Transaction Filters UI Clean-up

auth-api/src/auth_api/services/affiliation.py, auth-api/src/auth_api/utils/enums.py
*Issue #:*
https://github.com/bcgov/entity/issues/3947
- Changes for affiliation and name for CONDITIONAL name requests
*Checklist:*
=> 3947: Changes for affiliation and name for CONDITIONAL name requests

auth-web/src/components/auth/Transactions.vue
*Issue #:*
https://github.com/bcgov/entity/issues/3208
changes to meet acceptance criteria
*Checklist:*
=> Transaction filter fixes

auth-web/src/components/auth/Transactions.vue, auth-web/src/components/auth/TransactionsDataTable.vue, auth-web/src/util/common-util.ts
UI Updates for the transaction list
*Checklist:*
=> UI updates for the transaction list

auth-web/src/components/auth/AddNameRequestForm.vue, auth-web/src/components/auth/AffiliatedEntityList.vue, auth-web/src/models/business.ts, auth-web/src/services/business.services.ts, auth-web/src/store/modules/business.ts
*Issue #:*
https://github.com/bcgov/entity/issues/3959
- merged Named and Numbered BusinessRequest models
- created sub-model NameRequest with new, required legalType property
- changed legalName property to optional (for numbered businesses)
*Checklist:*
=> added required 'legalType' property to business requests

auth-web/public/config/configuration.json, auth-web/src/components/auth/ExtraProv/AffidavitDownload.vue, auth-web/src/components/auth/ExtraProv/UploadAffidavitStep.vue, auth-web/src/components/auth/NotaryContactForm.vue, auth-web/src/components/auth/NotaryInformationForm.vue, auth-web/src/components/auth/stepper/Stepper.vue, auth-web/src/locales/en.json, auth-web/src/models/notary.ts, auth-web/src/routes/router.ts, auth-web/src/services/document.services.ts, auth-web/src/util/config-helper.ts, auth-web/src/views/auth/AccountChangeView.vue, auth-web/src/views/auth/ExtraProvincialAccountSetupView.vue
=> download fail alert

auth-api/src/auth_api/schemas/schemas/mailing_address.json
=> streetAdditional made not mandatory

auth-web/src/components/auth/Transactions.vue, auth-web/src/components/auth/TransactionsDataTable.vue, auth-web/src/views/auth/AccountSettings.vue
*Issue #:*
https://github.com/bcgov/entity/issues/entity3208
UI Updates
*Checklist:*
=> [entity3208] UI Updates / Clean-up

docs/docs/api_contract/auth-api-1.0.0.yaml
=> Adding orgType PREMIUM to example mock

auth-web/package-lock.json, auth-web/package.json, auth-web/src/components/auth/Transactions.vue, auth-web/src/router.ts, auth-web/src/views/auth/AccountSettings.vue
=> transaction role based fixes

auth-web/src/assets/scss/base.scss, auth-web/src/assets/scss/layout.scss, auth-web/src/components/auth/ExtraProv/AccountInstructions.vue, auth-web/src/components/auth/ExtraProv/AffidavitDownload.vue, auth-web/src/components/auth/LoginBCSC.vue, auth-web/src/components/auth/common/ProvinceSelectorDialog.vue
*Issue #:*
https://github.com/bcgov/entity/issues/entity3876
UI Updates / Clean-up / UX Assurance
*Checklist:*
=> [entity3876] UI Updates / Clean-up

auth-api/src/auth_api/models/membership.py, auth-api/src/auth_api/schemas/org.py, auth-api/src/auth_api/utils/roles.py, auth-web/src/components/auth/ExtraProv/UploadAffidavitStep.vue, auth-web/src/components/auth/NotaryInformationForm.vue, auth-web/src/components/auth/UserProfileForm.vue, auth-web/src/components/auth/mixins/NextPageMixin.vue, auth-web/src/locales/en.json, auth-web/src/models/Organization.ts, auth-web/src/models/notary.ts, auth-web/src/routes/router.ts, auth-web/src/services/user.services.ts, auth-web/src/store/modules/user.ts, auth-web/src/util/constants.ts, auth-web/src/views/auth/PendingAffidavitApprovalView.vue
*Issue #:*
A WIP PR. But good to get it merged.
Mainly handled the navigation for bceid and a first pass at the account creation api's
*Checklist:*
=> WIP changes for navigation for bceid and account creation

auth-api/config.py, auth-api/requirements.txt, auth-api/requirements/prod.txt, auth-api/src/auth_api/resources/documents.py, auth-api/src/auth_api/resources/org.py, auth-api/src/auth_api/services/affidavit.py, auth-api/src/auth_api/services/minio.py
*Issue #:*
https://github.com/bcgov/entity/issues/3898
- Changes for document upload
*Checklist:*
=> Adding document upload for affidavit (Pre-signed PUT URL and pre-signed GET URL)

integration-tests/tests/suites/test_basic_account.py, integration-tests/tests/suites/test_payment.py
=> Fixed get transactions 403 issue on basic account flow.

auth-api/src/auth_api/models/org.py, auth-api/src/auth_api/resources/org.py, auth-api/src/auth_api/services/org.py, auth-api/tests/unit/api/test_org.py
https://github.com/bcgov/entity/issues/3834
*Issue #:*
https://github.com/bcgov/entity/issues/3834
A bit of refactoring.
Added status to the org search endpoint
*Checklist:*
=> Added status to the search for orgs to support staff view

auth-web/src/components/auth/stepper/InfoStepper.vue, auth-web/src/views/auth/Home.vue, auth-web/src/views/auth/HomeViewDev.vue
*Issue #:*
https://github.com/bcgov/entity/issues/4039
* Cleaned up stepper code to stop duplicate route pushing, that caused Console errors.
* Added comment to placeholder Home.vue.
* Style Fix on hero image.
*Checklist:*
=> Stepper Code Improvement

auth-web/package-lock.json, auth-web/package.json, auth-web/src/components/auth/BaseAddress.vue, auth-web/src/components/auth/CreateAccount/AccountCreateBasic.vue, auth-web/src/components/auth/NotaryInformationForm.vue, auth-web/src/services/user.services.ts, auth-web/src/store/modules/org.ts, auth-web/src/store/modules/user.ts
*Issue #:*
https://github.com/bcgov/entity/issues/3876 related fixes
*Checklist:*
=> Added mailing address for extra province basic accounts ; fixed doc Id

auth-web/src/components/auth/stepper/InfoStepper.vue, auth-web/src/views/auth/HomeViewDev.vue
*Issue #:*
https://github.com/bcgov/entity/issues/4039
* Fixed router transitions.
* Fixed some styling in the routerview and step number fonts.
* Added tabbing to router steps.
*Checklist:*
=> Transitions and styling fixes

auth-web/src/assets/scss/base.scss, auth-web/src/components/auth/ExtraProv/AccountInstructions.vue, auth-web/src/components/auth/ExtraProv/AffidavitDownload.vue, auth-web/src/components/auth/common/ProvinceSelectorDialog.vue, auth-web/src/components/auth/stepper/InfoStepper.vue, auth-web/src/plugins/vuetify.ts, auth-web/src/routes/router.ts, auth-web/src/views/auth/ChooseAuthMethodView.vue, auth-web/src/views/auth/CreateAccountAuthMethods.vue, auth-web/src/views/auth/HomeView.vue, auth-web/src/views/auth/HomeViewDev.vue
*Issue #:*
https://github.com/bcgov/entity/issues/4068
Changes for new intercept page
*Checklist:*
=> Entity4068

auth-web/src/components/auth/UserProfileForm.vue, auth-web/src/locales/en.json, auth-web/src/routes/router.ts, auth-web/src/views/auth/ExtraProAccountCreationSuccessView.vue
=> got the successpage working

integration-tests/tests/pages/bcsc_invitation_login.py
=> Fixed the button not found issue.

auth-web/src/locales/en.json
=> wording change

.github/workflows/auth-api-check.yml, auth-api/config.py, auth-api/email_templates/staff_review_account_email.html, auth-api/src/auth_api/resources/org.py, auth-api/src/auth_api/services/org.py, auth-api/tests/conftest.py, auth-api/tests/unit/services/test_org.py, integration-tests/tests/utilities/settings.py
*Issue #:*
https://github.com/bcgov/entity/issues/3818
*Checklist:*
=> Send staff review reminder email.

auth-api/src/auth_api/schemas/org.py
=> corrected decisionmade varaible

auth-web/src/components/auth/staff/StaffAccountManagement.vue, auth-web/src/components/auth/staff/StaffActiveAccountsTable.vue, auth-web/src/components/auth/staff/StaffPendingAccountsTable.vue, auth-web/src/components/auth/staff/StaffRejectedAccountsTable.vue, auth-web/src/models/Organization.ts, auth-web/src/store/modules/staff.ts
=> Staff dashboard - pending, rejected counter

auth-web/src/routes/router.ts
*Issue #:*
https://github.com/bcgov/entity/issues/3879
*Checklist:*
=> requires active account added for business pages

auth-web/src/components/auth/staff/StaffAccountManagement.vue, auth-web/src/models/Organization.ts, auth-web/src/views/auth/staff/ReviewAccountView.vue
=> bcol details in review account

auth-web/src/views/auth/staff/ReviewAccountView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/entity4068
Update content for Review Account Interface
*Checklist:*
=> [entity4068] Content Updates for Review Account Interface

auth-api/src/auth_api/services/org.py
=> url fixed for mails

auth-web/src/components/auth/NonBcscAccounts/NotaryContactForm.vue, auth-web/src/components/auth/NonBcscAccounts/UploadAffidavitStep.vue, auth-web/src/components/auth/UserProfileForm.vue, auth-web/src/components/auth/common/FileUploadPreview.vue, auth-web/src/services/user.services.ts
=> Exprov stepper bugfix

auth-web/src/components/auth/UserProfileForm.vue, auth-web/src/components/auth/mixins/NextPageMixin.vue, auth-web/src/models/user.ts, auth-web/src/util/constants.ts
*Issue #:*
https://github.com/bcgov/entity/issues/4133
*Checklist:*
=> Fix for broken pending page and showed email id user profile

auth-web/package-lock.json, auth-web/package.json, auth-web/src/components/auth/CreateAccount/AccountCreatePremium.vue
removed the undefined names for bceid users [temporary fix]
updated the packages
*Issue #:*
*Checklist:*
=> updated the packages ,a temporary fix for undefined names in bcol screens

auth-web/package-lock.json, auth-web/package.json
=> upgraded version

auth-web/public/config/configuration.json, auth-web/src/components/auth/NonBcscAccounts/AffidavitDownload.vue, auth-web/src/util/config-helper.ts
=> file size changed

auth-web/src/components/auth/NonBcscAccounts/UploadAffidavitStep.vue
=> error message when file upload fails

.github/workflows/restart_mailhog.yml, auth-api/requirements.txt, auth-api/src/auth_api/models/membership.py, auth-api/src/auth_api/models/org.py, auth-api/tests/unit/api/test_documents.py, auth-api/tests/unit/models/test_documents.py, auth-api/tests/unit/services/test_documents.py, auth-api/tests/unit/services/test_user.py
=> Fixed reset issues and create a restart mailhog job.

auth-web/src/views/auth/HomeView.vue, auth-web/src/views/auth/MaintainBusinessView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/3853
* Updated Footer as per Designs.
* Updated tel links.
*Checklist:*
=> Updated Footer and Phone Links

auth-api/src/auth_api/models/org.py, integration-tests/tests/utilities/settings.py
=> Fixed reset issue during integration test.

auth-web/src/components/auth/UserProfileForm.vue, auth-web/src/components/auth/staff/StaffAccountManagement.vue, auth-web/src/views/auth/staff/SearchBusinessView.vue
=> Bceid user profile, bcol admin dashboard changes

auth-web/src/components/auth/NonBcscAccounts/AffidavitDownload.vue, auth-web/src/util/constants.ts
*Issue #:*
https://github.com/bcgov/entity/issues/4177
*Checklist:*
=> 4177 use existing bceid

auth-api/src/auth_api/models/org.py, auth-api/src/auth_api/resources/org.py, auth-api/src/auth_api/services/org.py, auth-api/tests/unit/api/test_org.py
=> Added bcolAccountId filter to the org search

auth-api/src/auth_api/exceptions/errors.py, auth-api/src/auth_api/services/affiliation.py, auth-api/src/auth_api/utils/enums.py
*Issue #:* https://github.com/bcgov/entity/issues/4160
- added new NR error code
- verify corp type when affiliating NR
- added corp type + comments
*Checklist:*
=> ensure NR being affiliated is BC or CR

auth-web/src/routes/router.ts
*Issue #:*
* added back in Feature flagging on homeview route to support Prod deployment before the actual release.
*Checklist:*
=> Added In LD Flag on HomeView for Prod Deployment

auth-web/src/components/auth/UserManagement.vue
=> BCEID users cant invite anyone

auth-web/src/views/auth/HomeViewOutdated.vue
=> Fixed account link

auth-web/src/views/auth/HomeViewOutdated.vue
=> Fixed account link (#848)

auth-web/src/components/auth/BcscPanel.vue
*Issue #:*
* Updated the Url for Bcsc help info
*Checklist:*
=> Bcsc-update

auth-web/package-lock.json, auth-web/package.json, auth-web/src/App.vue, auth-web/src/components/auth/mixins/NextPageMixin.vue, auth-web/src/main.ts, auth-web/src/util/constants.ts
*Issue #:*
https://github.com/bcgov/entity/issues/3156
https://github.com/bcgov/entity/issues/3383
- Initialize keycloak session with check-sso on load of the app
*Checklist:*
=> SSO On init of application

auth-web/src/components/auth/BcscPanel.vue
=> Master to dev merge

auth-web/src/App.vue, auth-web/src/main.ts, auth-web/src/util/common-util.ts
*Issue #:*
https://github.com/bcgov/entity/issues/3383
- Fixing issue with unwanted sync on login and logout
*Checklist:*
=> Fixing issue with session var value check

auth-web/src/App.vue
*Issue #:*
- Changes to fix issue after logout
*Checklist:*
=> Changes to fix issue after logout

auth-api/src/auth_api/models/org.py, auth-api/src/auth_api/services/org.py, auth-api/tests/unit/models/test_org.py
*Issue #:*
https://github.com/bcgov/entity/issues/4212
*Checklist:*
=> Changes to handle transaction on org creation

auth-web/src/views/auth/HomeView.vue, auth-web/tests/unit/components/BcscPanel.spec.ts, auth-web/tests/unit/components/MemberDataTable.spec.ts, auth-web/tests/unit/components/SetupAccountForm.spec.ts, auth-web/tests/unit/views/HomeView.spec.ts, auth-web/tests/unit/views/IncorpOrRegisterView.spec.ts, auth-web/tests/unit/views/MaintainBusinessView.spec.ts, auth-web/tests/unit/views/SearchBusinessView.spec.ts
=> UI Unit tests

auth-web/src/App.vue, auth-web/src/components/auth/CreateAccount/AccountCreateBasic.vue, auth-web/src/components/auth/CreateAccount/AccountCreatePremium.vue, auth-web/src/components/auth/NonBcscAccounts/AffidavitDownload.vue, auth-web/src/main.ts, auth-web/src/store/modules/user.ts, auth-web/src/util/constants.ts, auth-web/src/views/auth/PendingApprovalView.vue, auth-web/src/views/auth/SigninView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/3296
SBC_COMMON : Redirect the user to create account if the user doesn't have valid role
*Checklist:*
=> SBC_COMMON : Redirect the user to create account if the user doesn't have valid role#3296

auth-web/package-lock.json, auth-web/package.json
=> common-components version 2.2.1

auth-web/src/services/document.services.ts
=> Removing axios header from minio call

auth-api/src/auth_api/models/__init__.py, auth-api/tests/postman/auth-api.postman_collection.json, auth-api/tests/postman/auth-api.postman_environment.json
*Issue #:*
https://github.com/bcgov/entity/issues/4081
The reset function didn't fetch the affidavit model cause failure. 
Fixed postman error.
Add new postman collection test cases.
*Checklist:*
=> Fixed the import order of model class that broken reset function.

auth-web/src/services/document.services.ts
=> transformheader not working ;so creating a new header

auth-web/src/components/auth/mixins/NextPageMixin.vue, auth-web/src/util/constants.ts, auth-web/src/views/auth/ChooseAuthMethodView.vue, auth-web/src/views/auth/SigninView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/4300
*Checklist:*
=> BCSC - Frozen on one screen#4300

auth-web/package-lock.json, auth-web/package.json
=> cc version to 2.2.2

auth-web/package-lock.json, auth-web/package.json, auth-web/src/components/auth/mixins/NextPageMixin.vue, auth-web/src/util/constants.ts, auth-web/src/views/auth/ChooseAuthMethodView.vue, auth-web/src/views/auth/SigninView.vue
=> Test Deployment 

auth-web/src/components/auth/AccountLoginOptionPicker.vue, auth-web/src/views/auth/AccountLoginOptionsChooser.vue, auth-web/src/views/auth/AccountLoginOptionsInfo.vue, auth-web/src/views/auth/AccountSettings.vue, auth-web/src/views/auth/AccountSettingsLoginOption.vue
*Issue #:*
https://github.com/bcgov/entity/issues/3589
*Checklist:*
=> UI Cleanup 3589

auth-api/src/auth_api/services/invitation.py
=> fixing director search bug

auth-api/src/auth_api/services/invitation.py, auth-web/public/config/configuration.json, auth-web/src/components/auth/CreateUserProfileForm.vue
=> Fixing the broken url

auth-web/src/components/auth/UserManagement.vue
=> commenting out the obsolete requirement

auth-web/src/components/auth/OrgAdminContact.vue
=> Fixing build error

auth-web/src/views/auth/AccountSettingsLoginOption.vue
*Issue #:*
https://github.com/bcgov/entity/issues/4259
- saved button status in user authentication selector
*Checklist:*
=> saved button status in user authentication selector

auth-web/src/components/auth/UserManagement.vue
=> adding the bceid invitaiton back

auth-api/src/auth_api/schemas/org.py, auth-web/src/components/auth/AccountInfo.vue, auth-web/src/components/auth/BaseAddress.vue, auth-web/src/components/auth/UserManagement.vue, auth-web/src/views/auth/AccountSettingsLoginOption.vue
*Issue #:*
moved the logic out of address component
other change for showing bceid acceptance
*Checklist:*
=> fixing the address component

auth-web/src/components/auth/AccountInfo.vue
=> fixing the wrong variables

auth-web/src/components/auth/AccountInfo.vue, auth-web/src/components/auth/AccountLoginOptionPicker.vue, auth-web/src/components/auth/InvitationsDataTable.vue, auth-web/src/components/auth/OrgAdminContact.vue, auth-web/src/components/auth/staff/StaffAccountManagement.vue, auth-web/src/components/auth/staff/StaffActiveAccountsTable.vue, auth-web/src/components/auth/staff/StaffPendingAccountInvitationsTable.vue, auth-web/src/components/auth/staff/StaffPendingAccountsTable.vue, auth-web/src/components/auth/staff/StaffRejectedAccountsTable.vue, auth-web/src/views/auth/AccountCreationSuccessView.vue, auth-web/src/views/auth/AccountLoginOptionsChooser.vue, auth-web/src/views/auth/AccountLoginOptionsInfo.vue, auth-web/src/views/auth/AccountSettings.vue, auth-web/src/views/auth/AccountSettingsLoginOption.vue, auth-web/src/views/auth/UnauthorizedView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/entity3268
UI Updates / Clean-up
*Checklist:*
=> [entity3268] UI Updates

auth-web/src/components/auth/AccountInfo.vue, auth-web/src/components/auth/OrgAdminContact.vue, auth-web/src/components/auth/staff/StaffActiveAccountsTable.vue, auth-web/src/components/auth/staff/StaffPendingAccountInvitationsTable.vue
*Issue #:*
- Adding fix for address view and removing Type from Invitations view
*Checklist:*
=> Adding fix for address view and removing Type from Invitations view

auth-web/package-lock.json, auth-web/package.json, auth-web/src/routes/router.ts, auth-web/src/views/auth/AuthenticationOptionsView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/4220
- Authentication options for BCeID and BCSC users#4220
*Checklist:*
=> Authentication options for BCeID and BCSC users#4220

auth-api/src/auth_api/models/org.py, auth-api/src/auth_api/services/invitation.py
*Issue #:*
https://github.com/bcgov/entity/issues/3270
- Changes to fix 403 for staff delete invitation
- Changes to sort by created date by default for org search
*Checklist:*
=> Minor backend fixes

auth-api/src/auth_api/services/membership.py
=> Fixing the approval flow

auth-api/src/auth_api/schemas/membership.py, auth-web/src/components/auth/InviteUsersForm.vue, auth-web/src/components/auth/MemberDataTable.vue, auth-web/src/models/user.ts, auth-web/src/views/auth/PendingApprovalView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/4375
https://github.com/bcgov/entity/issues/4376
- Only 1 admin for OOP accounts
- BCeID delegates cannot be upgraded to admins
- minor bug fixes
*Checklist:*
=> 4376 bceid roles and 4375

auth-web/package-lock.json, auth-web/package.json, auth-web/src/components/auth/AccountLoginOptionPicker.vue, auth-web/src/views/auth/AuthenticationOptionsView.vue, auth-web/src/views/auth/ChooseAuthMethodView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/entity4220
Updates / clean-up for authentication options interfaces
*Checklist:*
=> [entity4220] UI Updates

auth-web/src/assets/scss/layout.scss, auth-web/src/components/auth/InvitationsDataTable.vue, auth-web/src/components/auth/MemberDataTable.vue, auth-web/src/components/auth/PendingMemberDataTable.vue, auth-web/src/components/auth/TransactionsDataTable.vue, auth-web/src/components/auth/UserManagement.vue, auth-web/src/views/auth/AccountSettings.vue, auth-web/src/views/auth/AccountSettingsLoginOption.vue
*Issue #:*
https://github.com/bcgov/entity/issues/entity3270
UI Updates / Cleanup
*Checklist:*
=> [entity3270] UI Updates / Cleanup

auth-web/package-lock.json, auth-web/package.json
https://github.com/bcgov/entity/issues/4386
*Issue #:*
https://github.com/bcgov/entity/issues/4386
*Checklist:*
=> updating the package-version for flickering issue problem

auth-web/package-lock.json, auth-web/package.json
https://github.com/bcgov/entity/issues/4386
*Issue #:*
*Checklist:*
=> updating the package-version for flickering issue problem (#916)

.github/workflows/main-pr-check.yml, .github/workflows/pr-label-check.yml
=> Move pr label check to development branch.

auth-web/src/components/auth/NonBcscAccounts/AffidavitDownload.vue
*Issue #:*
https://github.com/bcgov/entity/issues/4272
- Update content on affidavit instructions#4272
*Checklist:*
=> Update content on affidavit instructions#4272

auth-web/package-lock.json, auth-web/package.json, auth-web/src/components/auth/MemberDataTable.vue, auth-web/src/components/auth/TransactionsDataTable.vue, auth-web/src/views/auth/AccountSettings.vue
*Issue #:*
https://github.com/bcgov/entity/issues/entity4084
- Updating sbc-common-component packages to get the new header create account button and menu item
- Few minor UI updates
*Checklist:*
=> [entity4084] Create Account Button and Menu Item

auth-web/src/components/auth/EntityManagement.vue, auth-web/src/routes/router.ts, auth-web/src/util/config-helper.ts, auth-web/src/views/auth/AccountSettings.vue
*Issue #:*
https://github.com/bcgov/entity/issues/4481
- Remove LD flag checks and unwanted codes#4481
*Checklist:*
=> Remove LD flag checks and unwanted codes#4481

auth-web/package-lock.json
=> fixing the lock version

auth-web/package-lock.json, auth-web/package.json
*Issue #:*
https://github.com/bcgov/entity/issues/entity4048
Updating package to get latest sbc-common-components
*Checklist:*
=> [entity4048] Updating sbc-common-components package

auth-api/config.py, auth-api/migrations/versions/2e58cc00009b_add_direct_payment_to_payment_types.py, auth-api/src/auth_api/services/org.py, auth-api/src/auth_api/utils/enums.py, auth-api/tests/unit/services/test_org.py
*Issue #:*
https://github.com/bcgov/entity/issues/4511
*Checklist:*
=> change default payment method in auth

auth-web/src/components/auth/AccountInfo.vue
*Issue #:*
https://github.com/bcgov/entity/issues/4153
- fix for flickering issue in account info address page
- ul tags in account page are changed to div, which causes flickering with the v-if
*Checklist:*
=> flickering issue in account info address page

.github/workflows/pr-label-check.yml, auth-api/requirements.txt, auth-api/src/auth_api/services/keycloak.py, auth-api/src/auth_api/services/reset.py, auth-api/tests/unit/services/test_keycloak.py, auth-api/tests/unit/services/test_reset.py
=> Add reset otp function.

auth-web/package-lock.json, auth-web/package.json
*Issue #:*
- updated common-components package to 2.3.1
*Checklist:*
=> updated sbc-common-component 📦

auth-web/src/components/auth/LearnMoreBCEID.vue, auth-web/src/components/auth/LearnMoreBCSC.vue
*Issue #:*
https://github.com/bcgov/entity/issues/entity4366
Content updates for Learn More interfaces
*Checklist:*
=> [entity4366] Content Updates for Learn More Interfaces

auth-web/src/components/auth/staff/StaffAccountManagement.vue
*Issue #:*
https://github.com/bcgov/entity/issues/4542
- Pending review and Rejected tabs names mix up#4542
*Checklist:*
=> Pending review and Rejected tabs names mix up#4542

auth-web/src/components/auth/AccountLoginOptionPicker.vue, auth-web/src/util/constants.ts
*Issue #:*
https://github.com/bcgov/entity/issues/4547
- feature flag Learn more and disable it till its ready to go to users #4547
*Checklist:*
=> feature flag Learn more and disable it till its ready to go to users

auth-web/src/components/auth/AccountInfo.vue
*Issue #:*
https://github.com/bcgov/entity/issues/4153
- flickering issue in address fields in account info page - fixed
- address not hiding for non-premium accounts - fixed
*Checklist:*
=> flickering issue in address fields in account info page

auth-web/src/routes/router.ts, auth-web/src/services/payment.services.ts, auth-web/src/views/pay/PaymentReturnView.vue, auth-web/tests/unit/views/PaymentReturnView.spec.ts
*Issue #:*
- Reverting payment service changes for direct pay
*Checklist:*
=> Reverting payment service changes for direct pay

auth-web/src/routes/router.ts, auth-web/src/services/payment.services.ts, auth-web/src/views/pay/PaymentReturnView.vue, auth-web/tests/unit/views/PaymentReturnView.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/4243
- Adding direct pay changes
*Checklist:*
=> Adding direct pay changes

auth-web/src/assets/scss/overrides.scss, auth-web/src/components/auth/staff/GLCodeDetailsModal.vue, auth-web/src/components/auth/staff/GLCodesDataTable.vue, auth-web/src/views/auth/staff/GLCodesListView.vue, auth-web/src/views/auth/staff/SearchBusinessView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/entity4373
UI Updates to General Ledger Code Interfaces
*Checklist:*
=> [entity4373] UI Updates to GL Code Interfaces

auth-web/src/components/auth/TransactionsDataTable.vue, auth-web/src/store/modules/org.ts
*Issue #:*
https://github.com/bcgov/entity/issues/entity43647
Adding Incorporation Number to the transactions list interface.
*Checklist:*
=> [entity4647] Adding Incorporation Number to Transactions List

auth-web/src/components/auth/Statements.vue, auth-web/src/locales/en.json, auth-web/src/models/statement.ts, auth-web/src/routes/router.ts, auth-web/src/services/payment.services.ts, auth-web/src/store/modules/org.ts, auth-web/src/views/auth/AccountSettings.vue
*Issue #:*
https://github.com/bcgov/entity/issues/3638
- Statements - View Account Statements#3638
*Checklist:*
=> Statements - View Account Statements#3638

auth-web/src/components/auth/staff/GLCodeDetailsModal.vue, auth-web/src/components/auth/staff/GLCodesDataTable.vue
*Issue #:*
https://github.com/bcgov/entity/issues/4373
changing back date format as per the design
*Checklist:*
=> changing back date format as per the design

auth-web/src/components/auth/Statements.vue, auth-web/src/components/auth/StatementsSettings.vue, auth-web/src/models/statement.ts, auth-web/src/services/payment.services.ts, auth-web/src/store/modules/org.ts
*Issue #:*
https://github.com/bcgov/entity/issues/3637
https://github.com/bcgov/entity/issues/3310
- Statements - Set Statement Frequency
- Statements - Enable / Disable Email Notifications for Account Statements#3310 - frontend only
*Checklist:*
=> Statements - Set Statement Frequency#3637 #3310

auth-web/src/components/auth/Statements.vue, auth-web/src/components/auth/StatementsSettings.vue
*Issue #:*
https://github.com/bcgov/entity/issues/entity4647
Removing incorporation number for records that do not provide that information. 
*Checklist:*
=> [entity3637] UI Updates / Improvements - Statements Interfaces

auth-web/src/assets/scss/base.scss, auth-web/src/components/auth/Statements.vue, auth-web/src/components/auth/StatementsSettings.vue, auth-web/src/models/statement.ts, auth-web/src/services/payment.services.ts, auth-web/src/store/modules/org.ts
*Issue #:*
https://github.com/bcgov/entity/issues/3649
https://github.com/bcgov/entity/issues/3310
- Download Statements as CSV or PDF#3649
- Enable / Disable Email Notifications for Account Statements#3310
*Checklist:*
=> Download Statements #3649, Email Notifications for Statements#3310

auth-web/src/components/auth/Statements.vue, auth-web/src/services/payment.services.ts, auth-web/src/store/modules/org.ts
*Issue #:*
https://github.com/bcgov/entity/issues/3649
- fix for pdf download and get filename from backend
*Checklist:*
=> fix for pdf download and get filename from backend

auth-web/package-lock.json, auth-web/package.json, auth-web/src/components/auth/StatementsSettings.vue, auth-web/src/views/auth/AccountSettings.vue
*Issue #:*
https://github.com/bcgov/entity/issues/3638
- updated Account settings navigation side bar as per new design
- updated package.json for showing up the transaction in the account dropdown
*Checklist:*
=> Account settings ui

auth-web/package-lock.json, auth-web/package.json, auth-web/src/components/auth/StatementsSettings.vue, auth-web/src/views/auth/AccountSettings.vue
* updated Account settings navigation side bar as per new design
* updated package.json for showing up the transaction in the account dropdown
* Toast for save success in statement settings
*Issue #:*
*Checklist:*
=> Account settings ui (#978)

auth-web/src/components/auth/AccountLoginOptionPicker.vue, auth-web/src/components/auth/TransactionsDataTable.vue, auth-web/src/views/auth/AccountSettings.vue
*Issue #:*
https://github.com/bcgov/entity/issues/entity4366
- Changed the BCSC learn more dialog to open a blank window to the requested URL
- Small update to the Account Settings navigation styling
- Changed the large icon in the transactions header to small (spacing considerations with table header)
- Removed incorporation number (business identifier) from the transactions list item if it doesn't exist
*Checklist:*
=> [entity4366] Add BCSC URL to Auth Options

auth-web/src/components/auth/Statements.vue, auth-web/src/components/auth/StatementsSettings.vue, auth-web/src/views/auth/AccountSettings.vue
*Issue #:*
https://github.com/bcgov/entity/issues/entity3310
UI Updates / Fixes to the Statements Settings Interfaces
- Fixed binding issues with Account Settings Nav
*Checklist:*
=> [entity3310] Statements Settings UI Updates / Fixes

auth-web/src/components/auth/Statements.vue, auth-web/src/components/auth/StatementsSettings.vue
*Issue #:*
https://github.com/bcgov/entity/issues/4810
- account switching for statements fixed (https://github.com/bcgov/entity/issues/4810)
- removing the add button and adding recipient to the list on click
*Checklist:*
=> Statement fixes

auth-web/src/components/auth/staff/StaffActiveAccountsTable.vue
*Issue #:*
https://github.com/bcgov/entity/issues/4510
- Staff dashboard - filter by account name
*Checklist:*
=> Staff dashboard - filter by account name#4510

auth-web/src/components/auth/StatementsSettings.vue, auth-web/src/models/statement.ts, auth-web/src/services/payment.services.ts, auth-web/src/store/modules/org.ts
=> Statements message

auth-web/src/components/auth/staff/StaffActiveAccountsTable.vue
*Issue #:*
https://github.com/bcgov/entity/issues/entity4510
Minor UI polish to align with existing patterns.
*Checklist:*
=> [entity4510] Minor UI Fixes for Account Name Filter

auth-api/src/auth_api/services/org.py, auth-api/tests/unit/api/test_org.py, auth-api/tests/utilities/factory_scenarios.py
*Issue #:*
https://github.com/bcgov/entity/issues/4786
tests added
the enum variable corrected
*Checklist:*
=> Added tests , fixed the syntax

auth-api/migrations/versions/d1b167ef61da_merge_heads.py, auth-api/migrations/versions/eff007a689cb_add_reset_otp_permission.py
=> alembic heads fixed

auth-api/migrations/versions/66ae9d618842_merge_heads.py
=> fixing migration heads

.github/workflows/auth-api-cd.yml, .github/workflows/auth-web-cd.yml, .github/workflows/notify-api&queue-cd.yml, .github/workflows/status-api-cd.yml
=> Update cd action version to latest.

auth-web/src/components/auth/MemberDataTable.vue, auth-web/src/components/auth/PendingMemberDataTable.vue, auth-web/src/components/auth/UserManagement.vue
*Issue #:*
https://github.com/bcgov/entity/issues/4339
- Search by username in manage team#4339
*Checklist:*
=> Search by username in manage team#4339

scripts/1pass.sh, scripts/install_tools.sh
=> Restore scripts.

auth-web/src/components/auth/mixins/PaginationMixin.vue, auth-web/src/components/auth/staff/SetupAccountForm.vue, auth-web/src/components/auth/staff/StaffAccountManagement.vue, auth-web/src/routes/router.ts, auth-web/src/util/constants.ts, auth-web/src/views/auth/AccountSettings.vue, auth-web/src/views/auth/staff/ReviewAccountView.vue, auth-web/src/views/auth/staff/SetupAccountSuccessView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/4626
Replaced '/searchbusiness' with constants which refers to new dashboard route
*Checklist:*
=> Changes reference of staff dashboard page

auth-web/src/routes/router.ts, auth-web/src/util/constants.ts
=> adding the missed redirection (#1021)

auth-web/src/components/auth/AnonymousUserManagement.vue, auth-web/src/components/auth/UserManagement.vue, auth-web/src/components/auth/common/SearchFilterInput.vue, auth-web/src/components/auth/staff/StaffActiveAccountsTable.vue, auth-web/src/models/searchfilter.ts
*Issue #:*
https://github.com/bcgov/entity/issues/5010
- Create a Reusable component for Search Filter#5010
*Checklist:*
=> Create a Reusable component for Search Filter#5010

auth-web/src/components/auth/AnonymousUserManagement.vue, auth-web/src/components/auth/MemberDataTable.vue, auth-web/src/components/auth/UserManagement.vue, auth-web/src/components/auth/common/SearchFilterInput.vue, auth-web/src/components/auth/mixins/TeamManagementMixin.vue
*Issue #:*
https://github.com/bcgov/entity/issues/entity4339
Clean up filter component spacing issues.
- Changed 'User Name' to 'Team Member' in the filter component (Team Members interface)
- Fixed grammar issue in the 'Reset Authenticator' dialog component
- Added the team member last name to the 'Remove Team Member' confirmation dialog component
*Checklist:*
=> [entity4339] UI Clean-up

.github/workflows/auth-api-cd.yml, .github/workflows/auth-web-cd.yml, .github/workflows/notify-api&queue-cd.yml, .github/workflows/status-api-cd.yml
=> Add OPENSHIFT_REPOSITORY_DEPLOYMENT input.

auth-web/package-lock.json, auth-web/package.json, auth-web/src/store/modules/user.ts
*Issue #:*
https://github.com/bcgov/entity/issues/5051
- TOS service screen not appearing #5051
*Checklist:*
=> TOS service screen not appearing #5051

auth-api/src/auth_api/resources/user.py, auth-web/src/util/common-util.ts
=> Show Reset OTP for view staff roles

auth-web/src/components/auth/Transactions.vue, auth-web/src/components/auth/TransactionsDataTable.vue, auth-web/src/components/auth/common/DateRangeFilter.vue, auth-web/src/components/auth/common/SearchFilterInput.vue, auth-web/src/models/searchfilter.ts, auth-web/src/models/transaction.ts, auth-web/src/services/payment.services.ts, auth-web/src/store/modules/org.ts
*Issue #:*
https://github.com/bcgov/entity/issues/4341
- Added username search in transaction view
- Moved DateRange filter to a separate component and used that inside the Search Filter component.
- More flexibility in filter component
- Code clean up
*Checklist:*
=> Search by username on transaction view#4341

auth-web/package-lock.json, auth-web/package.json
*Issue #:*
https://github.com/bcgov/entity/issues/4918
- updated cc version to 2.3.7
*Checklist:*
=> Orange banner displays when an entity dashboard is restored from a bookmark#4918

auth-web/src/components/auth/AccountInfo.vue, auth-web/src/components/auth/AnonymousUserManagement.vue, auth-web/src/components/auth/MemberDataTable.vue, auth-web/src/components/auth/Statements.vue, auth-web/src/components/auth/TeamManagement.vue, auth-web/src/components/auth/Transactions.vue, auth-web/src/components/auth/TransactionsDataTable.vue, auth-web/src/components/auth/UserManagement.vue, auth-web/src/components/auth/common/DateRangeFilter.vue, auth-web/src/components/auth/common/SearchFilterInput.vue, auth-web/src/views/auth/AccountSettings.vue, auth-web/tests/unit/components/DateRangeFilter.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/entity4341
Updates / improvements to the filter control (better flexibility when viewed at smaller viewports)
A number of additional fixes as listed below:
* Spacing fix to account info top-level container (AccountInfo.vue)
* Fix spacing inconsistencies with team management interfaces (AnonymousUserManagement.vue, UserManagement.vue, TeamManagement.vue)
* Column spacing clean-up (MemberDataTable.vue)
* Fixed redundant labeling (Statements.vue)
* Fixed overflow and spacing issues with transactions interface (Transactions.vue)
* Fixed labeling / column spacing with transactions table (TransactionDataTable.vue)
* Fixed spacing / behavior of date range filter when included in the new search filter component (DateRangeFilter.vue)
* Fixed …
=> [entity4341] General UI Improvements / Clean-up

auth-api/migrations/versions/959d8ff75e82_payment_change.py
=> fix migration issue

auth-web/src/models/transaction.ts, auth-web/src/store/modules/org.ts
*Issue #:*
bcgov/entity#4733
- Changes to the model to adapt with backend response changes from pay-api
*Checklist:*
=> Changes to transactions response

auth-web/package-lock.json, auth-web/package.json
*Issue #:*
https://github.com/bcgov/entity/issues/4874
*Checklist:*
=> Updating common components version to 2.4.1

auth-api/requirements.txt, auth-api/src/auth_api/schemas/schemas/org.json, auth-api/src/auth_api/services/org.py, auth-api/src/auth_api/utils/enums.py, auth-api/tests/docker/docker-compose.yml, auth-api/tests/unit/api/test_org.py, auth-api/tests/unit/services/test_org.py, auth-api/tests/utilities/factory_scenarios.py
*Issue #:*
https://github.com/bcgov/entity/issues/4740
Changes to accept payment type from the UI
*Checklist:*
=> Changes for supporting payment_type in request

auth-api/migrations/versions/959d8ff75e82_payment_change.py
=> fixing broken commit

auth-web/src/components/auth/create-account/PaymentMethodSelector.vue, auth-web/src/views/auth/create-account/AccountSetupView.vue, auth-web/tests/unit/components/PaymentMethodSelector.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/4740
- Choose payment during basic account setup #4740 - ui
*Checklist:*
=> Choose payment during basic account setup #4740 - ui

auth-api/src/auth_api/services/org.py, auth-api/tests/unit/api/test_org.py, auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue, auth-web/src/components/auth/create-account/AccountCreateBasic.vue, auth-web/src/store/modules/org.ts, auth-web/tests/unit/components/AccountCreateBasic.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/5144
*Checklist:*
=> mailing address enabled for basic accounts as well

auth-web/src/components/auth/common/stepper/Stepper.vue, auth-web/src/components/auth/create-account/AccountCreateBasic.vue, auth-web/src/components/auth/create-account/PaymentMethodSelector.vue
*Issue #:*
https://github.com/bcgov/entity/issues/entity4740
Fixing interaction / expand animation (removed 'jumping' with top margin issue when showing/hiding element). Standardized styling and simplified the component layout for each payment selector card.
Additional  Fixes
- Minor spacing clean-up
- Changed template element to fieldset for consistency and correct form semantics - AccountCreateBasic.vue
*Checklist:*
=> [entity4740] Front-end Fixes

auth-web/src/components/auth/create-account/UserProfileForm.vue, auth-web/src/util/constants.ts, auth-web/src/views/auth/create-account/AccountSetupView.vue, auth-web/src/views/auth/create-account/non-bcsc/NonBcscAccountSetupView.vue
*Issue #:*
- Feature flag payment method step in account creation
*Checklist:*
=> Feature flag payment method step in account creation

auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue, auth-web/src/components/auth/create-account/AccountCreateBasic.vue, auth-web/tests/unit/components/AccountCreateBasic.spec.ts
*Issue #:*
https://github.com/bcgov/sbc-auth/pull/1065
*Checklist:*
=> Feature flags done for https://github.com/bcgov/entity/issues/5144

auth-web/src/views/auth/home/HomeView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/5152
* Updated the message on the HomeView banner.
*Checklist:*
~~- [ ] No test case failures and proper coverage for all modules/classes~~
~~- [ ] Updated the deployment configs for new environment variable(s)~~
~~- [ ] Updtaed the postman collection in entity repository (https://github.com/bcgov/entity/tree/master/api-e2e/postman) for e2e tests~~
=> Updated HomeView Banner Msg

auth-web/src/components/auth/common/stepper/Stepper.vue, auth-web/src/components/auth/create-account/PaymentMethodSelector.vue, auth-web/src/views/auth/create-account/AccountSetupView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/entity4740
Updates / improvements to the payment selector component
- Added iconography representation for each payment type (standardize with existing patterns)
- Broke up the selection title / content for better legibility
Additional Updates
- Added initial support for stepper themes (Error for NSF views)
- Updated the language in the account creation process (Account Info)
*Checklist:*
=> [entity4740] Payment Selector and Stepper Updates

auth-web/src/components/auth/common/PADInfoForm.vue, auth-web/src/components/auth/common/PaymentMethods.vue, auth-web/src/components/auth/common/TermsOfUseDialog.vue, auth-web/src/components/auth/create-account/PaymentMethodSelector.vue, auth-web/src/util/constants.ts, auth-web/tests/unit/components/UserProfileForm.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/4741
- Choose payment method during premium account setup - PAD UI only
*Checklist:*
=> Choose payment method during premium account setup #4741 - PAD UI only

auth-web/src/views/auth/create-account/AccountChangeView.vue, auth-web/src/views/auth/create-account/AccountSetupView.vue, auth-web/src/views/auth/create-account/non-bcsc/NonBcscAccountSetupView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/5052
- feature flagged premium account chooser
*Checklist:*
=> feature flagged premium account chooser

auth-web/src/components/auth/common/LinkedBCOLBanner.vue, auth-web/src/components/auth/common/PADInfoForm.vue, auth-web/src/components/auth/common/PaymentMethods.vue, auth-web/src/components/auth/create-account/AccountCreatePremium.vue, auth-web/src/components/auth/create-account/PaymentMethodSelector.vue, auth-web/src/util/config-helper.ts, auth-web/tests/unit/components/PaymentMethodSelector.spec.ts, auth-web/tests/unit/components/PaymentMethods.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/4741
- Choose payment method during premium account setup - BCOL UI
- payments per account moved to config helper
*Checklist:*
=> Choose payment method during premium account setup - BCOL UI

auth-web/src/main.ts
*Issue #:*
- Adding random string to keycloak json URL to force load the json
*Checklist:*
=> Adding random string to keycloak json URL to force load the json

.github/workflows/account-mailer-cd.yml, .github/workflows/account-mailer-ci.yml, .github/workflows/events-listener-cd.yml, .github/workflows/events-listener-ci.yml, codecov.yaml
*Issue #:*
https://github.com/bcgov/entity/issues/5269
Added GHA for the queues
*Checklist:*
=> GHA for queue listeners added

auth-web/src/components/auth/common/PaymentMethods.vue, auth-web/src/components/auth/create-account/AccountCreateBasic.vue, auth-web/src/components/auth/create-account/AccountTypeSelector.vue, auth-web/src/components/auth/create-account/PaymentMethodSelector.vue, auth-web/src/components/auth/create-account/PremiumChooser.vue, auth-web/src/store/modules/org.ts, auth-web/src/util/constants.ts, auth-web/tests/unit/components/PaymentMethodSelector.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/5052
*Checklist:*
=> Link premium to BC Online Account#5052

auth-api/src/auth_api/schemas/schemas/org.json
Fixed the wrong enum type in org schema
=> fixing wrong enum in org schema

auth-web/src/components/auth/create-account/PremiumChooser.vue
*Issue #:*
https://github.com/bcgov/entity/issues/5052
- Learn More Popup and content
*Checklist:*
=> Link premium to BC Online Account#5052 - Learn More Popup and content

auth-api/requirements.txt, auth-api/src/auth_api/exceptions/errors.py, auth-api/src/auth_api/schemas/schemas/org.json, auth-api/src/auth_api/schemas/schemas/payment_info.json, auth-api/src/auth_api/services/org.py, auth-api/src/auth_api/utils/enums.py, auth-api/tests/unit/api/test_org.py, auth-api/tests/unit/services/test_org.py, auth-api/tests/utilities/factory_scenarios.py
=> Adding PAD details and mailing address to pay API

auth-api/src/auth_api/resources/org.py, auth-api/src/auth_api/schemas/schemas/org.json, auth-api/src/auth_api/services/org.py, auth-api/src/auth_api/services/rest_service.py, auth-api/tests/unit/api/test_org.py, auth-api/tests/unit/services/test_org.py, auth-api/tests/utilities/factory_scenarios.py, auth-api/tests/utilities/factory_utils.py
*Issue #:*
https://github.com/bcgov/entity/issues/5053
- new endpoint for retrieving the payment method info
- made the update method working
*Checklist:*
=> Update payment method for basic org

auth-web/src/components/auth/common/LinkedBCOLBanner.vue, auth-web/src/components/auth/common/PADInfoForm.vue, auth-web/src/components/auth/common/PaymentMethods.vue, auth-web/src/components/auth/common/TermsOfUseDialog.vue, auth-web/src/components/auth/create-account/AccountCreateBasic.vue, auth-web/src/components/auth/create-account/AccountCreatePremium.vue, auth-web/src/components/auth/create-account/BcolLogin.vue, auth-web/src/components/auth/create-account/PremiumChooser.vue, auth-web/src/components/auth/create-account/UserProfileForm.vue, auth-web/src/models/Organization.ts, auth-web/src/store/modules/org.ts
*Issue #:*
https://github.com/bcgov/entity/issues/4741
https://github.com/bcgov/entity/issues/5065
- Account creation api integration
- Review payment options
*Checklist:*
=> Account creation api changes - UI integration

auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue, auth-web/src/components/auth/account-settings/payment/AccountPaymentMethods.vue, auth-web/src/components/auth/common/PaymentMethods.vue, auth-web/src/models/Organization.ts, auth-web/src/models/bcol.ts, auth-web/src/routes/router.ts, auth-web/src/services/org.services.ts, auth-web/src/store/modules/org.ts, auth-web/src/views/auth/AccountSettings.vue, auth-web/src/views/auth/create-account/AccountSetupView.vue, auth-web/src/views/auth/create-account/non-bcsc/NonBcscAccountSetupView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/5053
- Update payment method for a basic account#5053
*Checklist:*
=> Update payment method for a basic account#5053

auth-web/src/assets/scss/overrides.scss, auth-web/src/components/auth/common/LinkedBCOLBanner.vue, auth-web/src/components/auth/common/PADInfoForm.vue, auth-web/src/components/auth/common/PaymentMethods.vue, auth-web/src/components/auth/common/TermsOfUseDialog.vue, auth-web/src/components/auth/common/stepper/Stepper.vue, auth-web/src/components/auth/create-account/AccountCreateBasic.vue, auth-web/src/components/auth/create-account/AccountCreatePremium.vue, auth-web/src/components/auth/create-account/BcolLogin.vue, auth-web/src/components/auth/create-account/PaymentMethodSelector.vue, auth-web/src/components/auth/create-account/PremiumChooser.vue, auth-web/src/components/auth/create-account/UserProfileForm.vue, auth-web/src/views/auth/create-account/AccountSetupView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/entity5052
UI Clean-up / fixes. Details as follows:
**AccountCreateBasic.vue**
* Fix spacing / alignment issues
**AccountCreatePremium.vue**
* Fix spacing / alignment issues
* Removed redundant elements
**AccountSetupView.vue**
* Removed incorrect selector on the page description element
**BcolLogin.vue**
* Added input mask to password field
**PadInfoForm.vue**
* Fix spacing / alignment issues
**PaymentMethods.vue**
* Fix spacing / alignment issues
**TermsOfUseDialog.vue**
* Fixed the checkbox controls alignment and tooltip positioning & corrected theme/colors
* Fixed incorrect color on secondary button for the dialog component (see 'Close' button)
**PremiumChooser.vue**
* Fixed spacing / alignment issues
* Fixed incorrect …
=> [entity5052] UI Clean-up

README.md, auth-web/src/assets/scss/overrides.scss, auth-web/src/components/auth/common/LinkedBCOLBanner.vue, auth-web/src/components/auth/common/PADInfoForm.vue, auth-web/src/components/auth/common/PaymentMethods.vue, auth-web/src/components/auth/common/TermsOfUseDialog.vue, auth-web/src/components/auth/common/stepper/Stepper.vue, auth-web/src/components/auth/create-account/AccountCreateBasic.vue, auth-web/src/components/auth/create-account/AccountCreatePremium.vue, auth-web/src/components/auth/create-account/BcolLogin.vue, auth-web/src/components/auth/create-account/PaymentMethodSelector.vue, auth-web/src/components/auth/create-account/PremiumChooser.vue, auth-web/src/components/auth/create-account/UserProfileForm.vue, auth-web/src/views/auth/create-account/AccountSetupView.vue
=> QA Deployment

auth-web/src/components/auth/common/ModalDialog.vue, auth-web/src/components/auth/common/PADInfoForm.vue, auth-web/src/components/auth/common/stepper/Stepper.vue, auth-web/src/models/Organization.ts, auth-web/src/services/payment.services.ts, auth-web/src/store/modules/org.ts, auth-web/src/views/auth/create-account/AccountSetupView.vue, auth-web/src/views/auth/create-account/non-bcsc/NonBcscAccountSetupView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/4773
- PAD bank account validation for premium accounts#4773
*Checklist:*
=> PAD bank account validation for premium accounts#4773

auth-web/package-lock.json, auth-web/package.json, auth-web/public/config/configuration.json, auth-web/src/main.ts, auth-web/src/services/bcol.services.ts, auth-web/src/services/business.services.ts, auth-web/src/services/document.services.ts, auth-web/src/services/invitation.services.ts, auth-web/src/services/org.services.ts, auth-web/src/services/payment.services.ts, auth-web/src/services/permission.services.ts, auth-web/src/services/staff.services.ts, auth-web/src/services/user.services.ts, auth-web/src/util/http-util.ts
*Issue #:*
https://github.com/bcgov/entity/issues/4648
Added sentry logging.
Refactored axios creation to make it easier.
*Checklist:*
=> refactoring axios creation and added sentry

auth-web/src/components/auth/account-settings/payment/AccountPaymentMethods.vue, auth-web/src/components/auth/common/PADInfoForm.vue, auth-web/src/components/auth/common/PaymentMethods.vue, auth-web/src/models/Organization.ts
*Issue #:*
https://github.com/bcgov/entity/issues/5341
- PAD Payment Method - See Confirmation Period Details and Accept Confirmation Period#5341
*Checklist:*
=> PAD Payment Method - See Confirmation Period Details

queue_services/account-mailer/src/account_mailer/config.py, queue_services/events-listener/src/events_listener/config.py
=> Changing config keys

auth-web/src/components/auth/account-settings/payment/AccountPaymentMethods.vue
*Issue #:*
https://github.com/bcgov/entity/issues/5548
- redirecting user to account info, if not admin, during account switch
*Checklist:*
=> redirecting user to account info, if not admin, during account switch

auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue, auth-web/src/components/auth/common/PADInfoForm.vue, auth-web/src/components/auth/common/PaymentMethods.vue, auth-web/src/components/auth/common/SearchFilterInput.vue, auth-web/src/views/auth/AccountSettings.vue, auth-web/tests/unit/components/SearchFilterInput.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/entity5596
Adding labels to various inputs in the search component.
- Fixed an issue where the BCOL information block would show when no link has been made.
- Added fieldset and legend elements to the PAD information form. Layout fixes for smaller viewports.
- Added header element to the payment method 'cards'.
- Fixed aria implementation and added roles to navigation elements in account settings.
*Checklist:*
=> [entity5596] Fix Missing Labels for Search Component Inputs

auth-web/src/components/auth/account-settings/team-management/AddUsersSuccess.vue
*Issue #:*
https://github.com/bcgov/entity/issues/5427
- Login address needs to be updated#5427
*Checklist:*
=> Director Search : Login address needs to be updated#5427

queue_services/account-mailer/q_cli.py, queue_services/account-mailer/src/account_mailer/config.py
=> q cli cmd for refund requests

queue_services/account-mailer/src/account_mailer/email_templates/pad_confirmation_email.html
=> email alignment fix

queue_services/account-mailer/src/account_mailer/email_templates/pad_confirmation_email.html
=> email alignment fix (#1130)

auth-web/src/components/auth/account-settings/payment/AccountPaymentMethods.vue, auth-web/src/store/modules/org.ts
*Issue #:*
https://github.com/bcgov/entity/issues/5668
- Selected payment method not appearing properly#5668
*Checklist:*
=> Selected payment method not appearing properly#5668

auth-web/src/App.vue, auth-web/src/components/auth/account-freeze/AccountOverview.vue, auth-web/src/components/auth/account-freeze/PaymentReview.vue, auth-web/src/components/auth/account-freeze/ReviewBankInformation.vue, auth-web/src/components/auth/common/PADInfoForm.vue, auth-web/src/components/auth/common/stepper/Stepper.vue, auth-web/src/components/auth/mixins/NextPageMixin.vue, auth-web/src/models/Organization.ts, auth-web/src/routes/index.ts, auth-web/src/routes/router.ts, auth-web/src/util/constants.ts, auth-web/src/views/auth/account-freeze/AccountFreezeUnlockView.vue, auth-web/src/views/auth/account-freeze/AccountFreezeView.vue, auth-web/tests/unit/components/AccountOverview.spec.ts, auth-web/tests/unit/components/PaymentReview.spec.ts, auth-web/tests/unit/components/ReviewBankInformation.spec.ts, auth-web/tests/unit/components/UserProfileForm.spec.ts, auth-web/tests/unit/views/AccountFreezeUnlockView.spec.ts, auth-web/tests/unit/views/AccountFreezeView.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/4857
https://github.com/bcgov/entity/issues/5230
https://github.com/bcgov/entity/issues/4920
- UI Step 1 to unlock an account - transaction failure details#4857
- UI Step 2 to unlock account - review and update PAD bank information#5230
- Step 3 - Unlock with CC#4920
- unit tests
*Checklist:*
=> Account Freeze NSF - UI

queue_services/account-mailer/src/account_mailer/email_processors/pad_confirmation.py, queue_services/account-mailer/src/account_mailer/email_templates/pad_confirmation_email.html, queue_services/account-mailer/src/account_mailer/pdf_templates/common/style.html, queue_services/account-mailer/src/account_mailer/pdf_templates/pad_confirmation.html
*Issue #:*
https://github.com/bcgov/entity/issues/5339
*Checklist:*
=> pad confirmation pdf changes

queue_services/account-mailer/src/account_mailer/email_processors/pad_confirmation.py, queue_services/account-mailer/src/account_mailer/pdf_templates/pad_confirmation.html
=> clean up pad confirmation pdf and email

auth-api/tests/unit/api/test_bulk_user.py
*Issue #:*
https://github.com/bcgov/entity/issues/4402
update test_bulk_user.py
*Checklist:*
- [X ] No lint errors
=> #4402 update test_bulk_user.py

auth-web/src/views/auth/AccountSettings.vue
=> hide payment method in account settings w.r.t. ld flags

auth-web/src/components/auth/account-settings/team-management/AnonymousUserManagement.vue, auth-web/src/components/auth/mixins/TeamManagementMixin.vue
*Issue #:*
- Patch: Dir search user role change modal popup text fix
*Checklist:*
=> Patch: Dir search user role change modal popup text fix

queue_services/events-listener/q_cli.py, queue_services/events-listener/requirements.txt, queue_services/events-listener/requirements/repo-libraries.txt, queue_services/events-listener/src/events_listener/config.py, queue_services/events-listener/src/events_listener/worker.py
=> Cleaned up account-events

queue_services/events-listener/openshift/templates/events-listener-deploy.json, queue_services/events-listener/q_cli.py, queue_services/events-listener/requirements.txt, queue_services/events-listener/requirements/repo-libraries.txt, queue_services/events-listener/src/events_listener/config.py, queue_services/events-listener/src/events_listener/worker.py
=> Account events

auth-web/src/routes/index.ts
*Issue #:
https://github.com/bcgov/entity/issues/4831
*Checklist:*
- [X ] No lint errors
- [X ] No test case failures and proper coverage for all modules/classes
=> #4831-Account Pending Approval Message refers to wrong Approving Party

auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue, auth-web/src/views/auth/AccountSettings.vue, auth-web/src/views/pay/CcPaymentReturnView.vue, auth-web/src/views/pay/CcPaymentView.vue
*Issue #:*
- org refresh after payment by checking route param
*Checklist:*
=> org refresh after payment by checking route param

auth-web/src/services/payment.services.ts, auth-web/src/store/modules/org.ts, auth-web/src/views/auth/account-freeze/AccountFreezeUnlockView.vue
=> Fixed routes

auth-web/src/views/auth/account-freeze/AccountFreezeUnlockView.vue
=> account settings url fixed

.github/workflows/events-listener-cd.yml
*Issue #:*
Wrong url was given for GHA
*Checklist:*
=> fixed the DB connection

auth-web/src/routes/router.ts, auth-web/src/views/auth/account-freeze/AccountFreezeUnlockView.vue, auth-web/src/views/auth/account-freeze/AccountUnlockSuccessView.vue
- Success view for account unlock process
- handling org refresh inside this view
*Issue #:*
*Checklist:*
=> Success view for account unlock process

auth-web/src/components/auth/account-freeze/ReviewBankInformation.vue
=> PAD validation in Account Unlock Stepper

auth-web/src/components/auth/account-settings/transaction/TransactionsDataTable.vue, auth-web/src/util/constants.ts, auth-web/src/views/auth/account-freeze/AccountFreezeUnlockView.vue, auth-web/src/views/auth/account-freeze/AccountUnlockSuccessView.vue
- Account unlock success page UI
- temporary format fix for displaying data in transaction table
*Issue #:*
*Checklist:*
=> Account unlock success page UI

queue_services/events-listener/openshift/templates/events-listener-deploy.json, queue_services/events-listener/q_cli.py, queue_services/events-listener/requirements.txt, queue_services/events-listener/requirements/repo-libraries.txt, queue_services/events-listener/src/events_listener/config.py, queue_services/events-listener/src/events_listener/worker.py
*Issue #:*
https://github.com/bcgov/entity/issues/4854
Cleaned up account events a bit.
*Checklist:*
=> Account events changes

auth-web/src/components/auth/account-freeze/ReviewBankInformation.vue
=> patch fix for demo

auth-web/src/components/auth/account-freeze/ReviewBankInformation.vue, auth-web/src/components/auth/common/PADInfoForm.vue
=> pad verification fix in unlock stepper

queue_services/events-listener/coverage.xml, queue_services/events-listener/q_cli.py, queue_services/events-listener/src/events_listener/worker.py, queue_services/events-listener/tests/docker-compose.yml
*Issue #:*
https://github.com/bcgov/entity/issues/4920
*Checklist:*
=> Fix for flush not saving details for account events

auth-api/requirements.txt, auth-api/requirements/repo-libraries.txt
*Issue #:*
The new pip is strict about dependencies.This change is to align with that.
*Checklist:*
=> Fixed the pip issues

.github/workflows/auth-api-cd.yml, .github/workflows/auth-api-ci.yml, .github/workflows/auth-web-ci.yml, auth-api/Makefile, auth-api/setup.cfg, auth-web/.gitignore, auth-web/Dockerfile, auth-web/Makefile
*Issue #:*
1. Clean up make file and add a make file to auth-web project;
2. Switch cd flow to using new version (versioning) of bcrs_cd_action;
3. Update all latest tag to specific version of GHA, dockerfile;
*Checklist:*
=> Clean up make file. Replace latest to specific version of the image tag.

auth-web/src/components/auth/mixins/NextPageMixin.vue, auth-web/src/routes/index.ts, auth-web/src/routes/router.ts
=> Blocking other routes for Admin as well

auth-api/src/auth_api/resources/documents.py, auth-api/src/auth_api/services/org.py, auth-api/src/auth_api/utils/enums.py
*Issue #:*
https://github.com/bcgov/entity/issues/5655
1) The PAD terms of service had a todays date . Had to replace that dynamically in the HTML
2) passed the params to pay
*Checklist:*
=> PAD TOS changes

.github/PULL_REQUEST_TEMPLATE.md
=> Updating PR template as CI does the checklist tasks.

.github/workflows/account-mailer-ci.yml, .github/workflows/auth-api-ci.yml, .github/workflows/auth-web-ci.yml, .github/workflows/events-listener-ci.yml, .github/workflows/notify-api-ci.yml, .github/workflows/notify-queue-ci.yml, .github/workflows/status-api-ci.yml, auth-api/Makefile, notify-api/Makefile, queue_services/account-mailer/Makefile, queue_services/account-mailer/requirements.txt, queue_services/events-listener/Makefile, queue_services/notify-queue/Makefile, status-api/Makefile
=> Add check strictness of build in CI flow.

auth-web/src/assets/scss/overrides.scss, auth-web/src/components/auth/account-freeze/AccountOverview.vue, auth-web/src/components/auth/account-freeze/PaymentReview.vue, auth-web/src/components/auth/account-freeze/ReviewBankInformation.vue, auth-web/src/components/auth/common/stepper/Stepper.vue, auth-web/src/views/auth/account-freeze/AccountFreezeUnlockView.vue, auth-web/src/views/auth/account-freeze/AccountFreezeView.vue, auth-web/tests/unit/views/AccountFreezeUnlockView.spec.ts, auth-web/tests/unit/views/AccountFreezeView.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/entity5775
General layout / language clean-up for the NSF recovery interfaces
*Checklist:*
=> [entity5775] NSF Interface UI Clean-up

auth-api/src/auth_api/services/org.py
=> Fixed casing

auth-api/migrations/versions/316ae45f54bc_pad_tos.py
*Issue #:*
https://github.com/bcgov/entity/issues/entity4772
Content update for the PAD Terms and Conditions
=> [entity4772] Content Update for PAD Terms and Conditions

auth-api/src/auth_api/models/base_model.py, auth-api/src/auth_api/services/org.py
=> Sending auth user name to pay

auth-api/migrations/versions/316ae45f54bc_pad_tos.py
*Issue #:*
https://github.com/bcgov/entity/issues/entity4772
Fixing link
=> [entity4772] Fix Link in PAD Terms and Conditions

auth-api/migrations/versions/316ae45f54bc_pad_tos.py
=> [entity4772] Fix Link in PAD Terms and Conditions (#1195)

queue_services/account-mailer/q_cli.py, queue_services/account-mailer/src/account_mailer/config.py, queue_services/account-mailer/src/account_mailer/email_processors/account_restored.py, queue_services/account-mailer/src/account_mailer/email_processors/account_suspended.py, queue_services/account-mailer/src/account_mailer/email_templates/account_restored_email.html, queue_services/account-mailer/src/account_mailer/email_templates/account_suspended_email.html, queue_services/account-mailer/src/account_mailer/worker.py
*Issue #:*
https://github.com/bcgov/entity/issues/4855
- Email notify account admins and coordinators of freeze#4855
=> Email notify account admins and coordinators of freeze#4855

auth-api/migrations/versions/e38ad1ce6d21_added_bank_permissions.py, auth-api/requirements.txt, auth-api/src/auth_api/models/views/authorization.py, auth-api/src/auth_api/resources/__init__.py, auth-api/src/auth_api/resources/org_authorisations.py, auth-api/src/auth_api/resources/org_authorizations.py, auth-api/src/auth_api/services/authorization.py, auth-web/src/services/org.services.ts, docs/docs/api_contract/auth-api-1.0.0.yaml
* Org authorisations endpoint added
*Issue #:*
https://github.com/bcgov/entity/issues/5563
1) added org/authorisation endpoint to get the org level authorisation for a user. 
2) added two more permissions. one to view bank account number ;another one to view the page itself.
3) front end directly will hit pay api to get the bank information.
=> changes for adding org authorisaton end point

auth-web/src/store/modules/org.ts
*Issue #:*
https://github.com/bcgov/entity/issues/5879
updated cfsAccount account details after api call
=> NSF - PAD Information not pulled

auth-api/requirements.txt, queue_services/account-mailer/q_cli.py, queue_services/account-mailer/requirements.txt, queue_services/account-mailer/src/account_mailer/config.py, queue_services/account-mailer/src/account_mailer/email_processors/__init__.py, queue_services/account-mailer/src/account_mailer/email_processors/pad_confirmation.py, queue_services/account-mailer/src/account_mailer/email_processors/refund_requested.py, queue_services/account-mailer/src/account_mailer/services/notification_service.py, queue_services/account-mailer/src/account_mailer/worker.py
*Issue #:*
https://github.com/bcgov/entity/issues/5779
Add full name to email body.
Fix flake8 errors.
=> 5779 - Salutation issue in PAD sign up confirmation email

.github/workflows/account-mailer-ci.yml, queue_services/account-mailer/q_cli.py, queue_services/account-mailer/src/account_mailer/email_processors/pad_confirmation.py
*Issue #:*
https://github.com/bcgov/entity/issues/5779
Update code to accept username instead of user_id.
=> 5779 linux

auth-api/src/auth_api/resources/org.py, auth-api/src/auth_api/services/org.py, auth-api/tests/unit/services/test_org.py
*Issue #:*
https://github.com/bcgov/entity/issues/5064
Just temporary work around to make the update of the payment method work.
The code needs a rewrite.I will probably do it along the next ticket.I tried to rewrite ;but need to touch a lot of tests.So parking it for later.
This is done so that front end dev can test the ticket.
=> quick fix for the broken payment update method

auth-api/src/auth_api/resources/org.py, auth-api/src/auth_api/services/org.py, auth-api/tests/unit/services/test_org.py, auth-web/src/components/auth/account-settings/payment/AccountPaymentMethods.vue, auth-web/src/components/auth/common/PaymentMethods.vue, auth-web/tests/unit/components/AccountPaymentMethods.spec.ts
=> test merge

auth-web/src/components/auth/account-settings/payment/AccountPaymentMethods.vue, auth-web/src/components/auth/common/PADInfoForm.vue, auth-web/src/util/common-util.ts
…L to PAD #5064
*Issue #:*
https://github.com/bcgov/entity/issues/5230
=> validation error on masked bank account

auth-web/src/components/auth/account-settings/payment/AccountPaymentMethods.vue, auth-web/src/components/auth/common/PADInfoForm.vue, auth-web/src/util/common-util.ts
* validation error on masked bank account
*Issue #:*
=> validation error on masked bank account (#1216)

auth-web/src/components/auth/account-settings/payment/AccountPaymentMethods.vue, auth-web/src/components/auth/common/PaymentMethods.vue, auth-web/src/store/modules/org.ts
* Update payment method for the premium account linked to BCOL: From PAD to BCOL
*Issue #:*
=> Feature/5095 (#1219)

.github/workflows/account-mailer-cd.yml, .github/workflows/account-mailer-ci.yml, queue_services/account-mailer/app.py, queue_services/account-mailer/q_cli.py, queue_services/account-mailer/src/account_mailer/config.py, queue_services/account-mailer/src/account_mailer/email_processors/pad_confirmation.py, queue_services/account-mailer/src/account_mailer/services/minio_service.py, queue_services/account-mailer/tests/conftest.py, queue_services/account-mailer/tests/docker/docker-compose.yml
*Issue #:*
https://github.com/bcgov/entity/issues/5640
Add Minio service. Get PAD file from Minio bucket and attach to email.
Fix flake8 error and enable flake8 check.
=> 5640-Attach Copy of PAD Terms & Conditions Confirmation Letter.

auth-api/migrations/versions/aaa29018c0a1_added_namex_product.py, auth-api/src/auth_api/__init__.py, auth-api/src/auth_api/resources/org_authorizations.py, auth-api/src/auth_api/schemas/product_code.py, auth-api/src/auth_api/services/authorization.py, auth-api/src/auth_api/services/org.py, auth-api/src/auth_api/services/products.py, auth-api/src/auth_api/utils/enums.py, auth-api/tests/unit/api/test_org_authorisations.py, auth-api/tests/unit/services/test_authorization.py, auth-api/tests/unit/services/test_org.py
*Issue #:*
https://github.com/bcgov/entity/issues/5826
- Modified the code so that NRO gets org level permissions instead of product level
Will add the cachng in next PR
=> Changes to support names

auth-web/src/components/auth/account-freeze/ReviewBankInformation.vue, auth-web/src/components/auth/common/PADInfoForm.vue, auth-web/src/components/auth/common/PaymentMethods.vue
*Issue #:*
https://github.com/bcgov/entity/issues/6020
=> valiadtion for bank info

queue_services/events-listener/requirements.txt, queue_services/events-listener/requirements/repo-libraries.txt
=> correcting reqs

auth-web/src/components/auth/account-freeze/AccountOverview.vue, auth-web/src/models/invoice.ts, auth-web/src/store/modules/org.ts
*Issue #:*
https://github.com/bcgov/entity/issues/6308
- Fixing NSF partial payments
=> 6038 : Fixing NSF partial payments

auth-web/src/util/common-util.ts
=> addedd payment mehod side menu permission for staff user

queue_services/account-mailer/src/account_mailer/worker.py, queue_services/events-listener/src/events_listener/config.py
base64 printing removed
*Issue #:*
=> misc fixes

queue_services/account-mailer/src/account_mailer/worker.py, queue_services/events-listener/src/events_listener/config.py
- The logger was logging the whole dict which includes base64. removed that.
- corrected a config
=> removing base64 logging and fixed config

queue_services/account-mailer/src/account_mailer/worker.py, queue_services/events-listener/src/events_listener/config.py
* corrected config;
base64 printing removed
*Issue #:*
=> removing base64 logging and fixed config (#1237)

queue_services/account-mailer/q_cli.py, queue_services/account-mailer/src/account_mailer/email_templates/account_conf_over_email.html
*Issue #:*
CLI corrected
email contents fixed
=> Fix for NR CLI

auth-web/src/components/auth/account-freeze/ReviewBankInformation.vue
=> removed update call if there is not change in bank information

auth-api/src/auth_api/models/user_settings.py, auth-api/src/auth_api/schemas/user_settings.py, auth-api/src/auth_api/services/user_settings.py, queue_services/account-mailer/src/account_mailer/worker.py
*Issue #:*
https://github.com/bcgov/entity/issues/5229
added org status as well to the api
=> Adding account status in user_Settings api

queue_services/account-mailer/src/account_mailer/enums.py, queue_services/account-mailer/src/account_mailer/worker.py, queue_services/events-listener/src/events_listener/config.py, queue_services/events-listener/src/events_listener/worker.py
*Issue #:*
- Removed  dot from the subject lines
- added some debug logs
- added more configs
=> minor bug fixes in q

auth-web/src/components/auth/create-account/AccountTypeSelector.vue
*Issue #:*
https://github.com/bcgov/entity/issues/entity5722
Updated content for the account type selectors.
=> [entity5722] Update Account Type Information

auth-web/src/components/pay/PaymentCard.vue, auth-web/src/locales/en.json, auth-web/src/services/payment.services.ts, auth-web/src/store/modules/org.ts, auth-web/src/views/pay/PaymentView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/5799
=> Generate and Download Invoice - Online Banking

auth-web/package-lock.json, auth-web/package.json, auth-web/src/models/Organization.ts, auth-web/src/routes/index.ts, auth-web/src/store/modules/org.ts, auth-web/src/views/auth/account-freeze/AccountFreezeView.vue, auth-web/tests/unit/views/AccountFreezeView.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/5229
=> User in-app notification of suspended account

auth-web/src/routes/router.ts, auth-web/src/views/auth/PriceListView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/entity6010
Implement static content / route for initial price list (aka 'Fee Schedule')
=> [entity6010] Develop Static Price List Interface

auth-api/src/auth_api/config.py, auth-api/src/auth_api/services/invitation.py, auth-api/src/auth_api/services/membership.py, auth-api/src/auth_api/utils/account_mailer.py, auth-api/tests/conftest.py, auth-api/tests/docker/docker-compose.yml
*Issue #:*
https://github.com/bcgov/entity/issues/5894
* added event publishing in necessary places
* added nats to tests
account mailer has another PR incoming
=> Added new events to publish staff related action emails

auth-api/src/auth_api/utils/account_mailer.py, queue_services/account-mailer/q_cli.py, queue_services/account-mailer/src/account_mailer/email_templates/admin_removed_email.html, queue_services/account-mailer/src/account_mailer/email_templates/team_modified_email.html, queue_services/account-mailer/src/account_mailer/enums.py, queue_services/account-mailer/src/account_mailer/worker.py, queue_services/account-mailer/tests/integration/test_worker_queue.py
*Issue #:*
https://github.com/bcgov/entity/issues/5894
New email templates added
=> Added new email templates

.github/workflows/auth-api-cd.yml
*Issue #:*
auth-api needs the nats variables
=> adding nats 1pwd entry to auth-api

auth-api/migrations/versions/f7362101e761_add_fee_schedule_link.py, auth-api/requirements.txt
*Issue #:*
https://github.com/bcgov/entity/issues/6010
Add fee schedule link to terms and conditions.
=> 6010-Add fee schedule link to user terms and  conditions.

auth-api/migrations/versions/f7362101e761_add_fee_schedule_link.py, auth-api/requirements.txt, auth-api/src/auth_api/services/user.py, auth-api/tests/unit/services/test_user.py
*Issue #:*
https://github.com/bcgov/entity/issues/5721
Add fee schedule link to terms and conditions.
=> 5721 - Redirect existing user to accept new terms

auth-web/src/components/auth/account-freeze/ReviewBankInformation.vue, auth-web/src/components/auth/common/PADInfoForm.vue, auth-web/src/components/auth/common/PaymentMethods.vue, auth-web/src/components/auth/common/TermsOfUseDialog.vue, auth-web/tests/unit/components/PADInfoForm.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/5066
* clear all data when editing PAD info
=> Change PAD information

auth-web/src/routes/router.ts
*Issue #:*
https://github.com/bcgov/entity/issues/entity6010
Removing the entities navigation bar from the price list view.
=> [entity6010] Fixing Issue with Nav Bar showing on Price List View

.github/workflows/auth-api-cd.yml, auth-api/requirements.txt, auth-api/src/auth_api/__init__.py, auth-api/src/auth_api/config.py, auth-api/src/auth_api/services/codes.py, auth-api/src/auth_api/services/invitation.py, auth-api/src/auth_api/services/keycloak.py, auth-api/src/auth_api/services/queue_publisher.py, auth-api/src/auth_api/services/user.py, auth-api/vaults.json
*Issue #:*
https://github.com/bcgov/entity/issues/6076
=> Update config value and vaults setup.

auth-api/src/auth_api/services/affiliation.py, auth-web/src/components/auth/common/PADInfoForm.vue
*Issue #:*
https://github.com/bcgov/entity/issues/5723
- Changes to bank details hints and validation
- Allowing affiliation for staff users, as the support team would work on alterations
=> 5723: Changes to bank details hints and validation

queue_services/notify-queue/requirements.txt, queue_services/notify-queue/requirements/prod.txt
=> Update requirments to match Notify api.

auth-web/src/components/auth/common/PaymentMethods.vue
*Issue #:*
https://github.com/bcgov/entity/issues/1296
* save button enable on change of PAD info
=> Update PAD info - Multiple admins

auth-web/src/components/auth/common/PaymentMethods.vue
=> Update PAD info - Multiple admins (#1278)

auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
*Issue #:*
default was returning True .But since staff cant have access, checked permissions
=> adding disabled for basic accounts

auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue, auth-web/src/components/auth/manage-business/EntityManagement.vue, auth-web/src/main.ts, auth-web/src/routes/componentHooks.ts
*Issue #:*
https://github.com/bcgov/entity/issues/5780
- address address missing check in manage business
- added a in component guard to prevent navigation
=> Added check for incomplete profile

auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue, auth-web/src/components/auth/account-settings/payment/AccountPaymentMethods.vue, auth-web/src/components/auth/account-settings/statement/StatementsSettings.vue
*Issue #:*
https://github.com/bcgov/entity/issues/5780
=>  Account info UI for old Basic account

auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue, auth-web/src/util/constants.ts
*Issue #:*
https://github.com/bcgov/entity/issues/6123
=> added LD flags for enable upgrade downgrade

auth-web/src/components/pay/PaymentCard.vue, auth-web/src/views/pay/PaymentView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/entity5490
Cleaning up spacing / font-sizes / etc.
=> [entity5490] UI Clean-up

auth-api/migrations/versions/5f51253eeced_update_tos_version_4.py, auth-api/requirements.txt, auth-web/src/locales/en.json
*Issue #:*
https://github.com/bcgov/entity/issues/5721
Update numbering in section 13.
Add text for accept invitation button.
=> 5721-Update user terms and conditions.

auth-api/jenkins/dev.groovy, auth-api/jenkins/prod.groovy, auth-api/jenkins/test.groovy, auth-web/jenkins/dev.groovy, auth-web/jenkins/prod.groovy, auth-web/jenkins/test.groovy, notify-api/jenkins/dev.groovy, notify-api/jenkins/prod.groovy, notify-api/jenkins/test.groovy, queue_services/account-mailer/jenkins/dev.groovy, queue_services/account-mailer/jenkins/prod.groovy, queue_services/account-mailer/jenkins/test.groovy, queue_services/events-listener/jenkins/dev.groovy, queue_services/events-listener/jenkins/prod.groovy, queue_services/events-listener/jenkins/test.groovy, queue_services/notify-queue/jenkins/dev.groovy, queue_services/notify-queue/jenkins/prod.groovy, queue_services/notify-queue/jenkins/test.groovy, status-api/jenkins/dev.groovy, status-api/jenkins/prod.groovy, status-api/jenkins/test.groovy
=> Update rocket chat url.

queue_services/account-mailer/src/account_mailer/email_templates/online_banking_over_payment.html, queue_services/account-mailer/src/account_mailer/email_templates/online_banking_payment.html, queue_services/account-mailer/src/account_mailer/email_templates/online_banking_under_payment.html, queue_services/account-mailer/src/account_mailer/enums.py, queue_services/account-mailer/src/account_mailer/worker.py, queue_services/account-mailer/tests/integration/test_worker_queue.py
*Issue #:*
https://github.com/bcgov/entity/issues/4895
- Changes for sending emails for online banking payments
=> Changes for sending emails for online banking payments

queue_services/account-mailer/src/account_mailer/email_templates/online_banking_over_payment.html, queue_services/account-mailer/src/account_mailer/email_templates/online_banking_payment.html, queue_services/account-mailer/src/account_mailer/email_templates/online_banking_under_payment.html
=> Changes for sending emails for online banking payments.

auth-web/src/util/config-helper.ts
=> Commenting the cache code to initiate the value on every load.

auth-web/src/views/auth/PriceListView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/entity6010
Updating price list content.
=> [entity6010] Update Price List Content

auth-web/src/components/auth/common/PaymentMethods.vue
*Issue #:*
https://github.com/bcgov/entity/issues/entity6167
Updating online banking payment method content.
=> [entity6167] Update Online Banking Payment Method Content

auth-api/migrations/versions/a490b2db8b13_added_pad_edit_for_nsf_accounts.py
=> adding PAD_EDIT for nsf accounts

auth-api/migrations/versions/a490b2db8b13_added_pad_edit_for_nsf_accounts.py
=> adding PAD_EDIT for nsf accounts (#1305)

auth-web/src/App.vue, auth-web/src/components/auth/mixins/NextPageMixin.vue
*Issue #:*
https://github.com/bcgov/entity/issues/6180
This is a better fix for the navigation issues with invitations.
The code in nextpagemixing was the root cause .I added the if check so that the api call wont happen for pending users.
App.vue code is reverted to original
Please ignore the commits.I will squash them.
=> bug fix for invitations

auth-web/src/App.vue, auth-web/src/components/auth/mixins/NextPageMixin.vue
=> bug fix for invitations (#1308)

auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue, auth-web/src/components/auth/manage-business/EntityManagement.vue, auth-web/src/util/constants.ts
=> Fix for mandatory address flag

auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue, auth-web/src/components/auth/manage-business/EntityManagement.vue, auth-web/src/util/constants.ts
* Fix for mandatory address flag
*Issue #:*
=> Fix for mandatory address flag (#1311)

auth-api/migrations/versions/a490b2db8b13_added_pad_edit_for_nsf_accounts.py, auth-web/package-lock.json, auth-web/package.json, auth-web/src/components/auth/staff/account-management/StaffAccountManagement.vue, auth-web/src/components/auth/staff/account-management/StaffSuspendedAccountsTable.vue, auth-web/src/routes/router.ts, auth-web/src/store/modules/staff.ts, auth-web/src/util/constants.ts, auth-web/src/views/auth/AccountSettings.vue, auth-web/tests/unit/components/PADInfoForm.spec.ts, auth-web/tests/unit/components/StaffActiveAccountsTable.spec.ts, auth-web/tests/unit/components/StaffRejectedAccountsTable.spec.ts, auth-web/tests/unit/components/StaffSuspendedAccountsTable.spec.ts, auth-web/tests/unit/util/config-helper.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/4856
* new page for staff to see suspended accounts
* Added test case for new and existing page
=>  Frozen account appears in Suspended tab in Staff Account Dashboard#4856

auth-web/src/components/auth/staff/account-management/StaffSuspendedAccountsTable.vue
*Issue #:*
https://github.com/bcgov/entity/issues/4856
* pagination for suspended account data table
=> suspended account staff

auth-web/src/components/auth/staff/account-management/StaffSuspendedAccountsTable.vue
=> suspended account staff (#1316)

auth-web/src/components/auth/account-freeze/AccountOverview.vue, auth-web/src/components/auth/common/AccountSuspendAlert.vue, auth-web/src/components/auth/staff/account-management/StaffSuspendedAccountsTable.vue, auth-web/src/models/invoice.ts, auth-web/src/store/modules/org.ts, auth-web/src/views/auth/AccountSettings.vue, auth-web/tests/unit/components/AccountOverview.spec.ts, auth-web/tests/unit/components/AccountSuspendAlert.spec.ts, auth-web/tests/unit/components/StaffSuspendedAccountsTable.spec.ts, auth-web/tests/unit/views/AccountFreezeUnlockView.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/5093
=>  Staff - See NSF Banner in Account Views #5093

auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue, auth-web/src/components/auth/create-account/AccountCreatePremium.vue
*Issue #:*
https://github.com/bcgov/entity/issues/5912
1) cleared error message when they touch account name
2) PR comments addressed
3) account name shown for premium accounts as well.
=> validation corrected ; show account name for premium as well

auth-web/src/views/auth/home/DecideBusinessView.vue, auth-web/src/views/auth/home/HomeView.vue
=> Benefit Company static page url change (#1330)

queue_services/account-mailer/src/account_mailer/enums.py
*Issue #:*
https://github.com/bcgov/entity/issues/6043
=> correcting message type for the outstanding invoice type

auth-web/src/components/auth/common/PADInfoForm.vue, auth-web/src/components/auth/common/PaymentMethods.vue, auth-web/src/components/auth/common/TermsOfUseDialog.vue, auth-web/src/components/auth/common/stepper/Stepper.vue, auth-web/src/components/auth/create-account/AccountCreateBasic.vue, auth-web/src/components/auth/create-account/AccountCreatePremium.vue, auth-web/src/components/auth/create-account/AccountTypeSelector.vue, auth-web/src/components/auth/create-account/BcolLogin.vue, auth-web/src/components/auth/create-account/PaymentMethodSelector.vue, auth-web/src/components/auth/create-account/PremiumChooser.vue, auth-web/src/components/auth/create-account/UserProfileForm.vue, auth-web/src/views/auth/create-account/AccountCreationSuccessView.vue, auth-web/src/views/auth/create-account/AccountSetupView.vue, auth-web/tests/unit/components/AccountOverview.spec.ts, auth-web/tests/unit/components/AccountSuspendAlert.spec.ts, auth-web/tests/unit/components/StaffSuspendedAccountsTable.spec.ts, auth-web/tests/unit/util/config-helper.spec.ts, auth-web/tests/unit/views/AccountFreezeUnlockView.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/6275
* Added data-test for testing purpose on setup account flow 
=> Adding attribute to elements in UI #6275

auth-web/src/components/auth/common/PADInfoForm.vue, auth-web/src/components/auth/common/PaymentMethods.vue, auth-web/src/components/auth/common/TermsOfUseDialog.vue, auth-web/src/components/auth/common/stepper/Stepper.vue, auth-web/src/components/auth/create-account/AccountCreateBasic.vue, auth-web/src/components/auth/create-account/AccountCreatePremium.vue, auth-web/src/components/auth/create-account/AccountTypeSelector.vue, auth-web/src/components/auth/create-account/BcolLogin.vue, auth-web/src/components/auth/create-account/PaymentMethodSelector.vue, auth-web/src/components/auth/create-account/PremiumChooser.vue, auth-web/src/components/auth/create-account/UserProfileForm.vue, auth-web/src/views/auth/create-account/AccountCreationSuccessView.vue, auth-web/src/views/auth/create-account/AccountSetupView.vue, auth-web/tests/unit/components/AccountOverview.spec.ts, auth-web/tests/unit/components/AccountSuspendAlert.spec.ts, auth-web/tests/unit/components/StaffSuspendedAccountsTable.spec.ts, auth-web/tests/unit/util/config-helper.spec.ts, auth-web/tests/unit/views/AccountFreezeUnlockView.spec.ts
* Adding attribute to elements in UI #6275
*Issue #:*
=> Adding attribute to elements in UI #6275 (#1338)

queue_services/account-mailer/src/account_mailer/email_templates/paymanet_pending.html
*Issue #:*
https://github.com/bcgov/entity/issues/6384
=>  Amount displayed in OB pending amount email

auth-web/src/components/auth/staff/gl-code/GLCodeDetailsModal.vue, auth-web/src/components/auth/staff/gl-code/GLCodesDataTable.vue, auth-web/src/models/Staff.ts, auth-web/src/services/payment.services.ts, auth-web/src/store/modules/staff.ts
*Issue #:*
https://github.com/bcgov/entity/issues/6245
- Changes to reflect backend changes on pay to restructure GL code structure
=> Changes to reflect backend changes on pay to restructure GL code structure

auth-web/src/components/auth/account-settings/team-management/MemberDataTable.vue, auth-web/tests/unit/components/PayWithCreditCard.spec.ts, auth-web/tests/unit/components/PayWithOnlineBanking.spec.ts, auth-web/tests/unit/components/PaymentCard.spec.ts
*Issue #:*
Fix some Lint errors.
=> Fix lint errors.

auth-api/src/auth_api/services/invitation.py, auth-api/src/auth_api/services/membership.py, auth-web/src/components/auth/account-settings/team-management/MemberDataTable.vue, auth-web/src/components/auth/staff/gl-code/GLCodeDetailsModal.vue, auth-web/src/components/auth/staff/gl-code/GLCodesDataTable.vue, auth-web/src/models/Staff.ts, auth-web/src/services/payment.services.ts, auth-web/src/store/modules/staff.ts, auth-web/tests/unit/components/PayWithCreditCard.spec.ts, auth-web/tests/unit/components/PayWithOnlineBanking.spec.ts, auth-web/tests/unit/components/PaymentCard.spec.ts, queue_services/account-mailer/src/account_mailer/email_templates/paymanet_pending.html
*Issue #:
https://github.com/bcgov/entity/issues/4909
=> Dev to Test #4909

auth-web/src/components/pay/PayWithOnlineBanking.vue
*Issue #:*
https://github.com/bcgov/entity/issues/5662
=> Payment when you have a credit #5662

auth-web/src/views/auth/account-freeze/AccountFreezeUnlockView.vue, auth-web/src/views/auth/account-freeze/AccountFreezeView.vue, auth-web/src/views/auth/account-freeze/AccountSuspendedView.vue
=> account suspend header fix

auth-web/src/components/pay/PayWithOnlineBanking.vue
=>  added tofix for credit amount

auth-api/src/auth_api/models/org.py, auth-api/src/auth_api/resources/org.py, auth-api/src/auth_api/services/org.py, auth-api/tests/unit/api/test_org.py, auth-web/src/components/auth/staff/account-management/StaffActiveAccountsTable.vue, auth-web/src/components/auth/staff/account-management/StaffSuspendedAccountsTable.vue, auth-web/src/models/Organization.ts, auth-web/src/services/staff.services.ts
*Issue #:*
Suspended tab is showing basically multiple status.Made the changes to handle that.
The UI test failures will be handled in next PR by Faiz.
=> multiple status handled

auth-web/package-lock.json, auth-web/package.json
=>  Staff manually suspend account#6121 | version updated

auth-web/src/routes/index.ts
=>  Staff manually suspend account#6121

auth-web/src/components/auth/account-freeze/ReviewBankInformation.vue, auth-web/src/components/auth/common/PADInfoForm.vue, auth-web/tests/unit/components/ReviewBankInformation.spec.ts
*Issue #:*
- Fixing issues that happened in the unit test cases of ReviewBankInformation
=> ReviewBankInformation unit test fix

auth-web/src/models/business.ts, auth-web/src/services/org.services.ts, auth-web/src/store/modules/business.ts, auth-web/src/store/modules/org.ts, auth-web/src/views/auth/staff/IncorporationSearchResultView.vue, auth-web/src/views/auth/staff/StaffDashboardView.vue, auth-web/tests/unit/views/IncorporationSearchResultView.spec.ts, auth-web/tests/unit/views/SearchBusinessView.spec.ts
*Issue #:*
- Added incorporation search result view.
- Handle affiliated/non affiliated organization for businesses.
- Added API calls in org and business services.
- WIP PR
- Unit tests for the new component would be elaborated in the next PR
=> Added search result for incorporations in staff dashboard

auth-web/src/locales/en.json, auth-web/src/util/common-util.ts, auth-web/src/views/auth/staff/GeneratePasscodeView.vue, auth-web/src/views/auth/staff/IncorporationSearchResultView.vue, auth-web/src/views/auth/staff/StaffDashboardView.vue, auth-web/tests/unit/views/GeneratePasscodeView.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/6277
- Added actions for non affiliated businesses -> generate passcode
- Created GeneratePasscode component
- Added unit tests for the same 
=> Generate Passcode component

.gitignore, auth-api/src/auth_api/services/org.py, auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue, auth-web/src/components/auth/common/AccountSuspendAlert.vue, auth-web/src/views/auth/AccountSettings.vue
*Issue #:*
- Updating suspend button sizes as per UX
- Returning back suspended_on and suspended by values to UI and display in the banner.
=> QA comments fix for 6121

auth-web/tests/unit/components/AccountInfo.spec.ts, auth-web/tests/unit/views/AccountSuspendedView.spec.ts, auth-web/tests/unit/views/GeneratePasscodeView.spec.ts, auth-web/tests/unit/views/IncorporationSearchResultView.spec.ts
*Issue #:*
- Test cases for 6121 and 6277 test cases
=> Test cases for 6121 and 6277 tasks

auth-web/src/views/pay/PaymentReturnView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/6325
=>  Provide Clear Message on Result of Credit Card Payment#6325

auth-web/package-lock.json, auth-web/package.json
*Issue #:*
https://github.com/bcgov/entity/issues/6550
=> updated sbc common component version

auth-web/src/views/auth/staff/GeneratePasscodeView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/6277
- Generate Passcode UJI updates
=> GeneratePasscode UI updates

auth-web/src/components/auth/account-settings/payment/AccountPaymentMethods.vue, auth-web/tests/unit/components/AccountPaymentMethods.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/6391
- 6391 - Account payments view sub text wordings change in AccountPaymentsMethod component
- Updating test cases for the change in AccountPaymentsMethod component
=> 6391 - Wording on Account Info Screen

auth-web/src/components/auth/common/PADInfoForm.vue
*Issue #:*
https://github.com/bcgov/entity/issues/5537
=>  Add visual for PAD Payment Method (void cheque)

auth-web/src/components/auth/common/PaymentMethods.vue
*Issue #:*
https://github.com/bcgov/entity/issues/entity6167
Update supported list of banks
=> [entity6167] Update Supported Banks

auth-web/src/views/pay/PaymentReturnView.vue
=> pay loading issue

auth-web/src/views/pay/PaymentReturnView.vue
=> pay loading issue (#1384)

auth-web/src/views/pay/PaymentReturnView.vue
=> pay loading issue (#1384) (#1385)

auth-web/src/assets/scss/layout.scss, auth-web/src/views/pay/PaymentReturnView.vue, auth-web/src/views/pay/PaymentView.vue
=> progress bar style

auth-web/src/components/auth/common/PaymentMethods.vue
*Issue #:*
https://github.com/bcgov/entity/issues/entity6167
Updating list of supported banks
=> [entity6167] Updating Supported Banks

auth-web/src/views/auth/staff/IncorporationSearchResultView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/6277
- comment generate passcode event menu for 6277 Prod move
=> comment generate passcode menu for 6277 Prod move

auth-web/src/views/auth/staff/IncorporationSearchResultView.vue
=> comment generate passcodevent (#1393)

auth-web/src/components/auth/common/ModalDialog.vue, auth-web/src/components/auth/staff/SetupAccountForm.vue, auth-web/src/components/auth/staff/SetupGovnAccountForm.vue, auth-web/src/components/auth/staff/account-management/StaffAccountManagement.vue, auth-web/src/components/auth/staff/account-management/StaffCreateAccountModal.vue, auth-web/src/models/Organization.ts, auth-web/src/routes/router.ts, auth-web/src/util/common-util.ts, auth-web/src/util/constants.ts, auth-web/src/views/auth/staff/SetupGovnAccountView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/6598
* staff can send invitation for govn accounts
=>  Sending the invite to create an Ministry Account#6598

auth-api/email_templates/govm_business_invitation_email.html, auth-api/migrations/versions/d5b5eb2e8dd0_added_branch_name.py, auth-api/src/auth_api/exceptions/errors.py, auth-api/src/auth_api/models/org.py, auth-api/src/auth_api/schemas/schemas/org.json, auth-api/src/auth_api/services/invitation.py, auth-api/src/auth_api/services/org.py, auth-api/src/auth_api/utils/enums.py, auth-api/tests/unit/api/test_org.py, auth-api/tests/unit/services/test_org.py, auth-api/tests/utilities/factory_scenarios.py, auth-web/public/config/configuration.json
*Issue #:*
https://github.com/bcgov/entity/issues/6598
used the term GOVM to refer to the new type. Happy to change if theres any suggestions.
=> changes for GOVM accounts

auth-web/src/views/auth/staff/IncorporationSearchResultView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/6686
- PR for dev imitating the hotfix that was applied to PROD for 6686
=> Bug - 6686 Entity dashboard bug fix 

auth-api/migrations/versions/69a7e464fef3_product_role_changes.py, auth-api/migrations/versions/d5b5eb2e8dd0_added_branch_name.py
*Issue #:*
just removed the drop index
I ran downgrades/upgrades couple of times in Test DB.It looks fine
=> fixing the alembic scripts

auth-web/src/components/auth/account-settings/team-management/InviteUsersForm.vue, auth-web/src/components/auth/account-settings/team-management/UserManagement.vue, auth-web/src/components/auth/mixins/TeamManagementMixin.vue, auth-web/src/locales/en.json, auth-web/tests/unit/components/InviteUsersForm.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/6536
- Added email verification and text updates in invite members component
- unit test cases
=> 6536 - Added email verification in invite members component

auth-web/src/components/pay/common/PaymentErrorMessage.vue
=> payment cancel error title

auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue, auth-web/src/components/auth/staff/account-management/StaffAccountManagement.vue
*Issue #:*
https://github.com/bcgov/entity/issues/6742
- Change display in select reason from code to description
=> display issue

auth-api/email_templates/govm_business_invitation_email.html, auth-api/email_templates/govm_member_invitation_email.html, auth-api/migrations/versions/4d47b5569629_govm_org_status_added.py, auth-api/migrations/versions/d5b5eb2e8dd0_added_branch_name.py, auth-api/src/auth_api/services/invitation.py, auth-api/src/auth_api/services/org.py, auth-api/src/auth_api/utils/enums.py, auth-api/src/auth_api/utils/roles.py, auth-api/tests/unit/api/test_org.py
*Issue #:*
https://github.com/bcgov/entity/issues/6536
https://github.com/bcgov/entity/issues/6536
> new invitation templates added
> two new org status added
=> added mail templates for govm

auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue, auth-web/src/components/auth/staff/account-management/StaffAccountManagement.vue, auth-web/tests/unit/components/AccountInfo.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/6472
- Change UI behavior to show error message rather than disable button
=> Feature/6472 new UI behaviour

auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
*Issue #:*
https://github.com/bcgov/entity/issues/6746
Duplicated status is removed.
=> 6746-Two fields appearing with same information for staff

auth-web/src/components/auth/mixins/NextPageMixin.vue, auth-web/src/util/constants.ts
*Issue #:*
https://github.com/bcgov/entity/issues/6578
=> Clean Up Tasks to Support Government Ministry Accounts

auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
*Issue #:*
https://github.com/bcgov/entity/issues/6746
Adjust layout.
=> 6746-Adjust layout.

auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue, auth-web/src/components/auth/mixins/NextPageMixin.vue, auth-web/src/util/constants.ts
=> Auth dev to test

auth-api/src/auth_api/resources/user.py
*Issue #:*
https://github.com/bcgov/entity/issues/6760
I this this change got missed from the last commit.
=> Fix for bceid users missing public role

auth-api/src/auth_api/resources/user.py, auth-api/src/auth_api/services/keycloak.py
=> Fixing issue with staff users getting added to gov account group

auth-api/src/auth_api/resources/user.py, auth-api/src/auth_api/services/keycloak.py
=> Fixing issue with staff users getting added to gov account group (#1432)

auth-api/src/auth_api/services/entity.py, auth-api/src/auth_api/services/invitation.py, auth-api/src/auth_api/utils/account_mailer.py, auth-api/tests/unit/api/test_invitation.py, auth-api/tests/utilities/factory_scenarios.py
*Issue #:*
https://github.com/bcgov/entity/issues/6222
- Changes to publish event for passcode reset
=> Changes for publishing reset passcode email

auth-web/src/components/auth/staff/SetupAccountForm.vue, auth-web/src/components/auth/staff/SetupGovmAccountForm.vue, auth-web/src/routes/router.ts, auth-web/src/views/auth/staff/SetupAccountSuccessView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/6704
=> Ministry Account Email invite and IDIR login #6704

auth-web/src/components/auth/common/GLPaymentForm.vue, auth-web/src/components/auth/create-account/AccountCreateBasic.vue, auth-web/src/models/Organization.ts, auth-web/src/store/modules/org.ts, auth-web/src/views/auth/create-account/GovmAccountSetupView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/6706
=> Prime Contact create the request for Ministry Government Account #6706

auth-web/src/views/auth/AcceptInviteView.vue
=> membership

auth-api/src/auth_api/services/products.py, auth-web/src/components/auth/create-account/GovmContactInfoForm.vue, auth-web/src/components/auth/mixins/NextPageMixin.vue, auth-web/src/routes/router.ts, auth-web/src/views/auth/AcceptInviteLandingView.vue, auth-web/src/views/auth/AcceptInviteView.vue
=> invitation flow needs resync of token  (#1458)

auth-api/src/auth_api/services/invitation.py, auth-api/src/auth_api/services/user.py
*Issue #:*
IDIR users if they try again to login to GOVM account .
=> Fix for duplicate accounts for staff

auth-api/src/auth_api/services/invitation.py, auth-api/src/auth_api/services/user.py
=> Fix for duplicate accounts for staff (#1466)

auth-api/src/auth_api/models/views/authorization.py, auth-api/src/auth_api/services/affiliation.py, auth-api/src/auth_api/services/authorization.py, auth-api/src/auth_api/services/entity.py, auth-api/tests/unit/api/test_org.py, auth-api/tests/unit/services/test_affiliation.py
=> 6220-Update entity.py

auth-api/src/auth_api/services/affiliation.py, auth-api/src/auth_api/services/authorization.py, auth-api/src/auth_api/services/entity.py, auth-api/src/auth_api/services/invitation.py, auth-api/src/auth_api/services/user.py, auth-api/tests/unit/api/test_org.py, auth-api/tests/unit/services/test_affiliation.py
*Issue #:*
https://github.com/bcgov/entity/issues/6220
Update delete affiliation process, add test case.
=> Dev to Master 6220 fix.

auth-web/src/views/auth/PendingApprovalView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/6706
=> success page

auth-web/src/util/common-util.ts
*Issue #:*
https://github.com/bcgov/entity/issues/6706
=> email validation test

auth-web/src/components/auth/home/BcscPanel.vue, auth-web/src/views/auth/home/HomeView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/6903
=> Broken links on landing page#6903

auth-web/src/components/auth/staff/account-management/StaffAccountManagement.vue, auth-web/src/util/constants.ts
*Issue #:*
https://github.com/bcgov/entity/issues/6958
* added LD flag for govm account
=> LD flag for Govm account invite

auth-web/src/routes/router.ts
=> made loginsource optional (#1481)

auth-web/src/components/auth/account-settings/product/ProductPackage.vue, auth-web/src/components/auth/common/Product.vue
*Issue #:*
https://github.com/bcgov/entity/issues/6872
=> Wills Registry - Submit Request for Access#6872

.github/workflows/account-mailer-cd.yml, .github/workflows/auth-api-cd.yml, .github/workflows/auth-web-cd.yml, .github/workflows/events-listener-cd.yml, .github/workflows/notify-api&queue-cd.yml, .github/workflows/status-api-cd.yml
=> Fixed development branch issue.

auth-web/Makefile
=> Update make file with CD flow.

auth-web/vue.config.js
*Issue #:*
https://github.com/bcgov/entity/issues/7019
Adding exclusion of json files from service worker caching
=> Adding exclusion of json file from pre caching

queue_services/account-mailer/src/account_mailer/email_templates/common/style.html, queue_services/account-mailer/src/account_mailer/pdf_templates/common/fonts.html
- Minio url update for account-mailer
=> Minio url update for account-mailer

auth-api/src/auth_api/models/product_subscription.py, auth-api/src/auth_api/models/task.py, auth-api/src/auth_api/resources/task.py, auth-api/src/auth_api/services/org.py, auth-api/src/auth_api/services/products.py, auth-api/src/auth_api/services/task.py, auth-api/src/auth_api/utils/enums.py, auth-api/tests/unit/api/test_task.py, auth-api/tests/unit/models/test_task.py, auth-api/tests/unit/services/test_org.py, auth-api/tests/unit/services/test_task.py, auth-api/tests/utilities/factory_utils.py
*Issue #:*
- Update task to handle update product subscriptions
- Pagination for fetch tasks
- Test cases
=> 4118 -  update product subscription task implementation

auth-api/src/auth_api/services/invitation.py, auth-api/src/auth_api/utils/util.py, auth-api/tests/unit/utils/test_util.py, auth-web/src/components/auth/mixins/NextPageMixin.vue, auth-web/src/routes/router.ts
Fix for bae 64 encoding the org name
*Issue #:*
https://github.com/bcgov/entity/issues/7135
Added backend encoding ; same change applied to front end.
Removed some unnecessary code for the invitations
I will be deploying this branch [this is taken from master ] and will tag this branch to release. Right after that i will do development to master merge as well.
=> added base 64 encode of the org name 

auth-web/src/models/Task.ts, auth-web/src/services/task.services.ts, auth-web/src/store/index.ts, auth-web/src/store/modules/staff.ts, auth-web/src/store/modules/task.ts, auth-web/src/util/constants.ts, auth-web/src/views/auth/staff/ReviewAccountView.vue
=> Review Requests to Access Wills Search & Registration Application#4118

auth-api/src/auth_api/models/task.py, auth-api/src/auth_api/resources/task.py, auth-api/src/auth_api/services/task.py, auth-api/tests/unit/api/test_task.py, auth-api/tests/unit/services/test_task.py
*Issue #:*
- Fetch Tasks pagination fix
=> Fetch Tasks Pagination issue Fix

auth-web/src/components/auth/mixins/NextPageMixin.vue, auth-web/src/routes/index.ts, auth-web/src/routes/router.ts
*Issue #:*
https://github.com/bcgov/entity/issues/7135
=> Fix for pending approval pages 

auth-web/src/components/auth/mixins/NextPageMixin.vue, auth-web/src/routes/index.ts, auth-web/src/routes/router.ts
=> Fix for pending approval pages  (#1522)

auth-api/migrations/versions/885632ab6357_insert_tasks_table_with_pending_orgs.py, auth-api/src/auth_api/services/org.py, auth-api/src/auth_api/services/products.py, auth-api/src/auth_api/utils/enums.py, auth-api/tests/unit/api/test_task.py, auth-api/tests/unit/models/test_task.py, auth-api/tests/unit/services/test_task.py, auth-api/tests/utilities/factory_utils.py, auth-web/src/components/auth/staff/account-management/StaffAccountManagement.vue, auth-web/src/components/auth/staff/account-management/StaffPendingAccountsTable.vue, auth-web/src/models/Task.ts, auth-web/src/services/task.services.ts, auth-web/src/store/modules/staff.ts, auth-web/src/store/modules/task.ts, auth-web/src/util/constants.ts
*Issue #:*
- Fetch tasks implementation in Staff Dashboard UI
- Task Type update as per UX pin
=> 4118 - fetch tasks and task type update

auth-api/migrations/versions/885632ab6357_insert_tasks_table_with_pending_orgs.py
=> dev to master push for Test merge

auth-api/migrations/versions/885632ab6357_insert_tasks_table_with_pending_orgs.py
=> 4118: missing import

auth-api/migrations/versions/885632ab6357_insert_tasks_table_with_pending_orgs.py, auth-api/src/auth_api/services/org.py, auth-api/src/auth_api/services/task.py
*Issue #:*
- Update migration script to handle special characters.
- Update email notification for BCEID staff review
=> 4118 - Migration script and notification mail update

auth-api/migrations/versions/885632ab6357_insert_tasks_table_with_pending_orgs.py, auth-api/src/auth_api/services/org.py, auth-api/src/auth_api/services/task.py
*Issue #:*
- 4118 - migration and email notification
=> 4118 - merge master from dev 

queue_services/account-mailer/src/account_mailer/email_templates/bcol_refund_request_email.html
=> Formatting refund email

auth-web/src/views/auth/staff/StaffDashboardView.vue, auth-web/tests/unit/components/AgreementInformation.spec.ts, auth-web/tests/unit/components/Product.spec.ts, auth-web/tests/unit/components/ProductTOS.spec.ts
| other test cases
*Issue #:*
https://github.com/bcgov/entity/issues/6591
=>  Change Title from Search Cooperatives to Search Business#6591 

auth-web/src/store/modules/staff.ts, auth-web/src/views/auth/staff/ReviewAccountView.vue
=> Fix for affidavit not refreshing issue (#1553)

auth-web/src/views/auth/staff/StaffDashboardView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/6591
=>  Change Title from Search Cooperatives to Search Business#6591

auth-api/src/auth_api/services/products.py
*Issue #:*
https://github.com/bcgov/entity/issues/7155
=> add missing product codes

auth-web/src/components/auth/BceidInviteLanding.vue, auth-web/src/components/auth/create-account/non-bcsc/AccountInstructions.vue
*Issue #:*
https://github.com/bcgov/entity/issues/7314
=>  BCeID/2FA Changes to Registry App for desktop plugin#7314

auth-api/src/auth_api/services/products.py, auth-api/tests/unit/api/test_org.py
*Issue #:*
https://github.com/bcgov/entity/issues/7155
=> GOVM needs default approvals

auth-api/src/auth_api/services/org.py, auth-api/tests/unit/api/test_org.py
*Issue #:*
https://github.com/bcgov/entity/issues/7155
=> GOVM account dont need default products

auth-web/src/components/auth/account-settings/product/ProductPackage.vue, auth-web/src/components/auth/common/Product.vue, auth-web/src/views/auth/AccountSettings.vue
*Issue #:*
https://github.com/bcgov/entity/issues/6872
=>  Wills Registry - Submit Request for Access#6872 | wording changes

auth-web/src/components/auth/common/Product.vue
*Issue #:*
https://github.com/bcgov/entity/issues/6872
=>  Wills Registry - Submit Request for Access#6872 | submit button

auth-api/migrations/versions/a37f90e6802d_affidavit_inactive_status_added.py, auth-api/src/auth_api/models/affidavit.py, auth-api/src/auth_api/services/affidavit.py, auth-api/src/auth_api/utils/enums.py, auth-api/tests/unit/api/test_org.py, auth-api/tests/unit/services/test_affidavit.py, auth-api/tests/utilities/factory_scenarios.py
=> Affidavit fix (#1569)

auth-web/package-lock.json, auth-web/package.json, auth-web/src/App.vue, auth-web/src/components/auth/staff/review-task/AccessRequestModal.vue
*Issue #:*
https://github.com/bcgov/entity/issues/7369
=> Fix account name display in pending pages #7369

auth-web/package-lock.json, auth-web/package.json, auth-web/src/App.vue, auth-web/src/components/auth/staff/review-task/AccessRequestModal.vue
=> Fix account name display in pending pages #7369 (#1571)

auth-api/src/auth_api/services/org.py
*Issue #:*
https://github.com/bcgov/entity/issues/6859
- Handle update org service to approve/reject govm accounts
=> updated govm handling in update org

auth-web/src/components/auth/staff/account-management/StaffRejectedAccountsTable.vue
Issue #:
Reject tab next button disabled issue
Description of changes:
updated RejectedTab component with the fix
=> Reject tab next button disabled issue fix

auth-web/src/services/org.services.ts
*Issue #:*
https://github.com/bcgov/entity/issues/7155
=> list all product in product page

auth-web/src/services/user.services.ts
=> added encoding since idir usernames has backslashes (#1588)

auth-api/src/auth_api/services/membership.py, queue_services/account-mailer/src/account_mailer/email_templates/prod_package_rejected_notification.html, queue_services/account-mailer/src/account_mailer/enums.py, queue_services/account-mailer/src/account_mailer/worker.py
*Issue #:*
https://github.com/bcgov/entity/issues/6116
- Update subject of mail according to message type
=> subject modifications

auth-web/src/components/auth/staff/review-task/AccountAdministrator.vue, auth-web/src/components/auth/staff/review-task/ProductFee.vue, auth-web/src/store/modules/org.ts, auth-web/src/views/auth/staff/ReviewAccountView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/7426
=> GOVM review page

auth-web/src/components/auth/account-settings/product/ProductPackage.vue, auth-web/src/views/auth/create-account/GovmAccountSetupView.vue, auth-web/tests/unit/components/ProductPackage.spec.ts
=> updated wordings

auth-web/src/components/auth/common/PaymentMethods.vue, auth-web/src/util/config-helper.ts, auth-web/src/views/auth/home/HomeView.vue
*Issue #:*
https://github.com/bcgov/entity/issues/7455
=> BCOL Account - Payment Method not showing

auth-api/src/auth_api/services/org.py
*Issue #:*
https://github.com/bcgov/entity/issues/6875
- Fix for Govm approval mail
=> GovM approval mail fix

auth-api/src/auth_api/services/org.py
*Issue #:*
https://github.com/bcgov/entity/issues/6875
- Govm Approval mail issue fix
- merge to master to deploy in Test
=> GovM approval mail fix - merge to master

queue_services/account-mailer/src/account_mailer/email_templates/bcol_refund_request_email.html
*Issue #:*
https://github.com/bcgov/entity/issues/7456
- updated bcol refund template
=> 7456 - Update BCOL refund template

auth-api/src/auth_api/services/user_settings.py, auth-api/tests/unit/api/test_user_settings.py
=> Fixing product settings URL

auth-web/src/components/auth/account-settings/product/ProductPackage.vue, auth-web/src/views/auth/AccountSettings.vue, auth-web/src/views/auth/create-account/GovmAccountSetupView.vue, auth-web/tests/unit/components/ProductPackage.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/6872
=> changed wording

docs/docs/api_contract/auth-api-1.0.0.yaml
*Issue #:*
https://github.com/bcgov/entity/issues/7264
=> Adding partner on-boarding document

auth-web/src/components/auth/common/AccountLoginOptionPicker.vue, auth-web/src/locales/en.json
*Issue #:*
https://github.com/bcgov/entity/issues/7443
- 
=> 7443 name change

auth-web/src/assets/scss/overrides.scss, auth-web/src/components/auth/create-account/AccountCreateBasic.vue, auth-web/src/components/auth/create-account/AccountCreatePremium.vue, auth-web/src/views/auth/OrgNameAutoComplete.vue
*Issue #:*
https://github.com/bcgov/entity/issues/7381
=>  Account Creation Process: VON API Integration style changes

auth-web/src/services/von.services.ts, auth-web/src/views/auth/OrgNameAutoComplete.vue
*Issue #:*
https://github.com/bcgov/entity/issues/7381
- make von results distinct
=> VON api show distinct org names

auth-web/src/components/auth/account-settings/transaction/TransactionsDataTable.vue
*Issue #:*
https://github.com/bcgov/entity/issues/6715
=> right align for total amount in transaction table

auth-web/tests/unit/views/OrgNameAutoComplete.spec.ts, queue_services/account-mailer/src/account_mailer/auth_utils.py, queue_services/account-mailer/src/account_mailer/config.py
*Issue #:*
https://github.com/bcgov/entity/issues/7585
- Added env for App URI for account-mailer
=> Login url fix for account mailer

auth-web/src/components/auth/staff/review-task/AccountInformation.vue, auth-web/src/components/auth/staff/review-task/ProductFee.vue
*Issue #:*
https://github.com/bcgov/entity/issues/6895
- Product fee selected UI fix.
- display branch name for govm accounts in account info
=> 6895 UI changes

queue_services/account-mailer/requirements.txt, queue_services/account-mailer/requirements/repo-libraries.txt, queue_services/activity-log-listener/requirements.txt, queue_services/activity-log-listener/requirements/repo-libraries.txt, queue_services/events-listener/requirements.txt, queue_services/events-listener/requirements/repo-libraries.txt
=> Fixing the repo back to bcgov

auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue, auth-web/tests/unit/components/AccountInfo.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/7563
=> added account number in account info screen

auth-web/src/components/auth/account-settings/login-options/AccountSettingsLoginOption.vue
*Issue #:*
https://github.com/bcgov/entity/issues/6734
=> 6734-refactor text for authentication screen

auth-api/migrations/versions/9b04140db7d3_product_code_flags.py, auth-api/src/auth_api/models/product_code.py, auth-api/src/auth_api/services/org.py, auth-api/tests/unit/api/test_org.py, auth-api/tests/utilities/factory_scenarios.py
*Issue #:*
https://github.com/bcgov/entity/issues/7533
=> 7533 - Adding subscription as part org create payload

auth-api/src/auth_api/utils/account_mailer.py
Bug fix for mails not being sent
=> Fixed wrong subject reference

auth-web/src/components/auth/account-settings/product/ProductPackage.vue, auth-web/src/components/auth/common/Product.vue, auth-web/src/components/auth/common/ProductTOS.vue, auth-web/src/components/auth/create-account/AccountTypeSelector.vue, auth-web/src/components/auth/create-account/ProductPackages.vue, auth-web/src/components/auth/create-account/SelectProductService.vue, auth-web/src/components/auth/staff/review-task/ProductFee.vue, auth-web/src/locales/en.json, auth-web/src/models/Organization.ts, auth-web/src/store/modules/org.ts, auth-web/src/views/auth/create-account/AccountSetupView.vue, auth-web/src/views/auth/create-account/GovmAccountSetupView.vue, auth-web/tests/unit/components/AccountTypeSelector.spec.ts, auth-web/tests/unit/components/Product.spec.ts, auth-web/tests/unit/components/ProductFee.spec.ts, auth-web/tests/unit/components/SelectProductService.spec.ts
*Issue #:*
https://github.com/bcgov/entity/issues/7533
=> Action Based Account setup changes
